import Link from"next/link";
import{getCurrentAppUser}from"./auth";
import{DevPreviewBanner}from"./dev-preview-banner";
import{getPreviewRole}from"./lib/dev-preview";
import{LogoutButton}from"./logout-button";
const adminLinks=[["Overview","/admin"],["Upload","/admin/upload"],["Sources","/admin/sources"],["Activity","/admin/activity"]];
const libraryLinks=[["Library","/library"],["All Files","/library/files"],["Source Folders","/library/folders"],["Images","/library/files?type=image"],["Videos","/library/files?type=video"],["Documents","/library/files?type=document"]];
export async function ApplicationShell({panel,active,children}:{panel:"staff"|"admin";active:string;children:React.ReactNode}){const preview=await getPreviewRole(),user=await getCurrentAppUser(),isAdmin=user?.role==="ADMIN",links=panel==="admin"?adminLinks:libraryLinks;return <div className="appShell"><DevPreviewBanner/><aside className="appSidebar"><Link className="appBrand" href="/library"><span>KDI</span><div>Central Media<small>Library</small></div></Link>{isAdmin&&<div className="panelSwitch"><a className={panel==="staff"?"active":""} href="/library">Library</a><a className={panel==="admin"?"active":""} href="/admin">Admin</a></div>}<div className="panelLabel">{panel==="admin"?"ADMIN PANEL":"FRONTEND PANEL"}</div><nav aria-label={`${panel} navigation`}>{links.map(([name,href])=><a className={active===href||active===href.split("?")[0]?"active":""} href={href} key={href}>{name}</a>)}</nav><div className="sidebarFoot"><span>●</span> {preview?"DEMO DATA ONLY":"Authorized access"}</div></aside><div className="appBody"><header className="topbar"><div className="topbarTitle">{panel==="admin"?"Administration":"Media library"}</div><div className="accountArea"><div className="rolePill"><span>{user?.displayName.slice(0,2).toUpperCase()||"KD"}</span><div>{user?.displayName||"KDI user"}<small>{isAdmin?"Administrator":"Staff"}</small></div></div>{preview?<span className="previewOnlyAction">Preview mode</span>:<LogoutButton/>}</div></header><main className="appContent">{children}</main></div></div>}
export function Crumbs({items}:{items:{label:string;href?:string}[]}){return <nav className="crumbs" aria-label="Breadcrumb">{items.map((item,index)=><span key={item.label}>{index>0&&<i>/</i>}{item.href?<a href={item.href}>{item.label}</a>:<b>{item.label}</b>}</span>)}</nav>}
export function Status({value}:{value:string}){const good=/VERIFIED|ACCESSIBLE|TAKE|UPLOADED|CONNECTED/.test(value);return <span className={`status ${good?"ok":""}`}>{value.replaceAll("_"," ")}</span>}
