export const SORT_FIELDS = ["verified_at","upload_attempt_count","upload_status","verification_level"] as const;
export const FILE_SORT_FIELDS = ["file_name","size_bytes","drive_modified_at","processing_status","created_at","mime_type"] as const;
export type FileSort = typeof FILE_SORT_FIELDS[number];
export type Summary={sourceFiles:number;eligible:number;excluded:number;assets:number;verified:number;failed:number;retries:number;claims:number;leases:number;duplicateGroups:number;duplicateDestinations:number};
export function completion(s:Summary){return s.assets?Math.round(s.verified/s.assets*10000)/100:0}
export function shortId(v:string){return v.length>12?`${v.slice(0,8)}…${v.slice(-4)}`:v}
export function maskDestination(v:string|null){return v?shortId(v):"Not recorded"}
export function maskFilename(v:string){const dot=v.lastIndexOf("."),ext=dot>=0?v.slice(dot).replace(/[^.a-z0-9]/gi,"").slice(0,10):"";return `Restricted file${ext.toLowerCase()}`}
export function safePath(v:string|null){if(!v||v==="/"||!v.includes("/"))return "Source folder";const depth=v.split("/").filter(Boolean).length;return `Nested folder · ${depth} level${depth===1?"":"s"}`}
export function isUuid(v:string){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v)}
export function fileKind(mime:string|null,ext:string|null){return classifyMedia(mime,ext)}
export function formatBytes(n:number|null){if(n===null)return"—";if(n<1024)return`${n} B`;const u=["KB","MB","GB","TB"],i=Math.min(Math.floor(Math.log(n)/Math.log(1024)),4);return`${(n/1024**i).toFixed(i>1?1:0)} ${u[i-1]}`}
export function parseFileParams(input:Record<string,string|undefined>){const page=Math.max(1,Number.parseInt(input.page||"1")||1),raw=Number.parseInt(input.pageSize||"50")||50,pageSize=[25,50,100].includes(raw)?raw:50;return{page,pageSize,query:(input.query||"").trim().slice(0,80),type:["image","video","document","other"].includes(input.type||"")?input.type!:"",extension:(input.extension||"").replace(/[^a-z0-9]/gi,"").slice(0,10).toLowerCase(),decision:["TAKE","SKIP","PENDING"].includes(input.decision||"")?input.decision!:"",status:(input.status||"").replace(/[^A-Z_]/g,"").slice(0,40),migration:(input.migration||"").replace(/[^A-Z_]/g,"").slice(0,40),verified:["verified","unverified"].includes(input.verified||"")?input.verified!:"",excluded:input.excluded==="true",duplicate:["yes","no"].includes(input.duplicate||"")?input.duplicate!:"",sort:FILE_SORT_FIELDS.includes(input.sort as FileSort)?input.sort as FileSort:"drive_modified_at",direction:input.direction==="asc"?"asc":"desc" as "asc"|"desc"}}
export function duplicateTrace(rows:{assetId:string;sourceId:string;folderId:string}[]){const map=new Map<string,{sources:Set<string>;folders:Set<string>}>();for(const r of rows){const x=map.get(r.assetId)||{sources:new Set<string>(),folders:new Set<string>()};x.sources.add(r.sourceId);x.folders.add(r.folderId);map.set(r.assetId,x)}return[...map].map(([assetId,x])=>({assetId,sourceCount:x.sources.size,folderCount:x.folders.size,isDuplicate:x.sources.size>1}))}
export const FAILURES=["SOURCE_CHANGED","SOURCE_NOT_FOUND","SOURCE_ACCESS_DENIED","DESTINATION_ACCESS_DENIED","DESTINATION_CONFLICT","UPLOAD_FAILED","MANUAL_REVIEW_REQUIRED"] as const;
export function isException(status:string,failure:string|null,retry:boolean){return retry||FAILURES.includes((failure||status) as typeof FAILURES[number])}
export function parseParams(input:Record<string,string|undefined>){const page=Math.max(1,Number.parseInt(input.page||"1")||1),requested=Number.parseInt(input.pageSize||"25")||25,pageSize=Math.min(100,Math.max(10,requested)),sort=SORT_FIELDS.includes(input.sort as typeof SORT_FIELDS[number])?input.sort!:"verified_at";return{page,pageSize,sort,direction:input.direction==="asc"?"asc":"desc",search:(input.search||"").slice(0,80)}}
import{classifyMedia}from"./lib/library/classification";
