import { ApplicationShell, Crumbs, Status } from "./application-shell";
import { AssetThumbnail } from "./asset-thumbnail";
import { LibrarySearchBox } from "./library-search-box";
import { formatBytes, maskFilename } from "./lib";
import { getMediaAssets, InvalidMediaQuery, parseMediaQuery } from "./lib/media/repository";
import { hybridSearchAssets, normalizeNaturalLanguageQuery } from "./lib/media/search";
import type { MediaAsset, MediaQuery } from "./types/media";
import { DeterministicQueryInterpreter, effectiveSemanticQuery, stateFromSearchParams } from "./lib/media/conversation";

const date = (value: string | null) => value ? new Intl.DateTimeFormat("en-MY", { dateStyle: "medium", timeZone: "Asia/Singapore" }).format(new Date(value)) : "Date unavailable";
function libraryUrl(query: Record<string, string | undefined>, changes: Record<string, string | number | undefined>) { const params = new URLSearchParams(); for (const [key, value] of Object.entries({ ...query, ...changes })) if (value !== undefined && value !== "" && !(key === "page" && String(value) === "1")) params.set(key, String(value)); const result = params.toString(); return result ? `/library?${result}` : "/library"; }
function CategoryNav({ active, query }: { active: MediaQuery["category"]; query: Record<string, string | undefined> }) { const links: [string, MediaQuery["category"]][] = [["All Files", ""], ["Images", "image"], ["Videos", "video"], ["Documents", "document"]]; return <nav className="categoryNav" aria-label="Media categories">{links.map(([label, category]) => <a className={active === category ? "active" : ""} href={libraryUrl(query, { category, type: undefined, page: 1 })} key={label}>{label}</a>)}</nav>; }
function AssetCard({ asset }: { asset: MediaAsset }) { return <article className="fileCard"><a className="filePreview" href={`/library/files/${asset.id}`} aria-label={`Open ${maskFilename(asset.filename)}`}>{asset.thumbnailUrl && <AssetThumbnail key={asset.thumbnailUrl} src={asset.thumbnailUrl} alt="" />}<span className={`largeType ${asset.category}`}>{asset.category === "video" ? "▶" : asset.category === "document" ? "▤" : asset.category === "image" ? "▧" : "?"}</span><Status value={asset.migrationStatus} />{asset.matchPercent != null && <span className="matchBadge">{Math.round(asset.matchPercent)}% match</span>}</a><div className="fileInfo"><small>{asset.sourceFolder}</small><a href={`/library/files/${asset.id}`}><h3>{maskFilename(asset.filename)}</h3></a>{asset.shortCaption && <p className="shortCaption">{asset.shortCaption}</p>}<p>{asset.extension?.toUpperCase() || "FILE"} · {formatBytes(asset.sizeBytes)} · {date(asset.modifiedAt)}</p><div className="cardActions"><a href={`/library/files/${asset.id}`}>Open</a>{asset.downloadUrl && <a href={asset.downloadUrl}>Download</a>}</div></div></article>; }
function Pager({ page, pageSize, total, totalPages, query }: { page: number; pageSize: number; total: number; totalPages: number; query: Record<string, string | undefined> }) { const first = total === 0 ? 0 : (page - 1) * pageSize + 1; return <nav className="modernPager" aria-label="Library pages"><span>{first}–{Math.min(page * pageSize, total)} of {total}</span><div><a aria-disabled={page <= 1} href={page > 1 ? libraryUrl(query, { page: page - 1 }) : undefined}>Previous</a><b>{page} / {totalPages}</b><a aria-disabled={page >= totalPages} href={page < totalPages ? libraryUrl(query, { page: page + 1 }) : undefined}>Next</a></div></nav>; }

export async function MediaLibraryPage({ query }: { query: Record<string, string | undefined> }) {
  const previous = stateFromSearchParams(query);
  const refinement = normalizeNaturalLanguageQuery(query.refine);
  const conversation = refinement ? (await new DeterministicQueryInterpreter().interpret(refinement, previous)).state : previous;
  const nlq = effectiveSemanticQuery(conversation);
  const filterQuery = { ...query };
  for (const key of Object.keys(filterQuery)) if (key === "refine" || key === "nlq" || key.startsWith("cs_")) delete filterQuery[key];
  if (conversation.mediaType) filterQuery.category = conversation.mediaType;
  if (conversation.sort !== "relevance") filterQuery.sort = conversation.sort;
  let parsed: MediaQuery; try { parsed = parseMediaQuery(filterQuery); } catch { parsed = parseMediaQuery({}); }
  let result; try { result = nlq ? await hybridSearchAssets({ ...filterQuery, nlq }) : await getMediaAssets(filterQuery); } catch (error) { const invalid = error instanceof InvalidMediaQuery; return <ApplicationShell panel="staff" active="/library"><Crumbs items={[{ label: "Library" }]} /><header className="contentHead"><div><span className="kicker">CENTRAL MEDIA LIBRARY</span><h1>All files</h1></div></header><CategoryNav active={parsed.category} query={query} /><LibrarySearchBox parsed={parsed} conversation={conversation} /><div className="secureError" role="alert"><b>{invalid ? "Invalid library filters" : "Database unavailable"}</b><p>{invalid ? "Clear the filters and try again." : "The secure media database could not be reached. Please refresh to try again."}</p></div></ApplicationShell>; }
  const filtered = Boolean(nlq || parsed.search || parsed.category || parsed.extension);
  const emptyHeading = nlq ? "No matches for your search" : filtered ? "No files match your search" : "No accessible files yet";
  const emptyBody = nlq ? "Try describing the media differently, or use the filename field instead." : filtered ? "Try a different filename, category, or extension." : "Files will appear here when access has been granted.";
  return <ApplicationShell panel="staff" active="/library"><Crumbs items={[{ label: "Library" }]} /><header className="contentHead"><div><span className="kicker">CENTRAL MEDIA LIBRARY</span><h1>All files</h1><p>{result.total} accessible file{result.total === 1 ? "" : "s"}</p></div></header><CategoryNav active={parsed.category} query={query} /><LibrarySearchBox parsed={parsed} conversation={conversation} />{result.items.length === 0 ? <section className="emptyModern"><h2>{emptyHeading}</h2><p>{emptyBody}</p>{filtered && <a href="/library">Clear all filters</a>}</section> : <><section className="fileGrid" aria-label="Media assets">{result.items.map((asset) => <AssetCard asset={asset} key={asset.id} />)}</section><Pager {...result} query={query} /></>}</ApplicationShell>;
}
