import { ApplicationShell, Crumbs, Status } from "./application-shell";
import { formatBytes, maskFilename } from "./lib";
import { getMediaAssets, InvalidMediaQuery, parseMediaQuery } from "./lib/media/repository";
import type { MediaAsset, MediaQuery } from "./types/media";

const date = (value: string | null) => value ? new Intl.DateTimeFormat("en-MY", { dateStyle: "medium", timeZone: "Asia/Singapore" }).format(new Date(value)) : "Date unavailable";
function libraryUrl(query: Record<string, string | undefined>, changes: Record<string, string | number | undefined>) { const params = new URLSearchParams(); for (const [key, value] of Object.entries({ ...query, ...changes })) if (value !== undefined && value !== "" && !(key === "page" && String(value) === "1")) params.set(key, String(value)); const result = params.toString(); return result ? `/library?${result}` : "/library"; }
function CategoryNav({ active, query }: { active: MediaQuery["category"]; query: Record<string, string | undefined> }) { const links: [string, MediaQuery["category"]][] = [["All Files", ""], ["Images", "image"], ["Videos", "video"], ["Documents", "document"]]; return <nav className="categoryNav" aria-label="Media categories">{links.map(([label, category]) => <a className={active === category ? "active" : ""} href={libraryUrl(query, { category, type: undefined, page: 1 })} key={label}>{label}</a>)}</nav>; }
function Filters({ parsed }: { parsed: MediaQuery }) { return <form className="libraryFilters" action="/library" method="get">{parsed.category && <input type="hidden" name="category" value={parsed.category} />}<input name="query" defaultValue={parsed.search} placeholder="Search by filename…" aria-label="Search by filename" /><input name="extension" defaultValue={parsed.extension} placeholder="Extension" aria-label="Filter by extension" /><select name="sort" defaultValue={parsed.sort} aria-label="Sort files"><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="smallest">Smallest first</option><option value="largest">Largest first</option></select><select name="pageSize" defaultValue={parsed.pageSize} aria-label="Files per page"><option>25</option><option>50</option><option>100</option></select><button type="submit">Apply</button><a href={parsed.category ? `/library?category=${parsed.category}` : "/library"}>Reset</a></form>; }
function AssetCard({ asset }: { asset: MediaAsset }) { return <article className="fileCard"><a className="filePreview" href={`/library/files/${asset.id}`} aria-label={`Open ${maskFilename(asset.filename)}`}><span className={`largeType ${asset.category}`}>{asset.category === "video" ? "▶" : asset.category === "document" ? "▤" : asset.category === "image" ? "▧" : "?"}</span><Status value={asset.migrationStatus} /></a><div className="fileInfo"><small>{asset.sourceFolder}</small><a href={`/library/files/${asset.id}`}><h3>{maskFilename(asset.filename)}</h3></a><p>{asset.extension?.toUpperCase() || "FILE"} · {formatBytes(asset.sizeBytes)} · {date(asset.modifiedAt)}</p><div className="cardActions"><a href={`/library/files/${asset.id}`}>Open</a>{asset.downloadUrl && <a href={asset.downloadUrl}>Download</a>}</div></div></article>; }
function Pager({ page, pageSize, total, totalPages, query }: { page: number; pageSize: number; total: number; totalPages: number; query: Record<string, string | undefined> }) { const first = total === 0 ? 0 : (page - 1) * pageSize + 1; return <nav className="modernPager" aria-label="Library pages"><span>{first}–{Math.min(page * pageSize, total)} of {total}</span><div><a aria-disabled={page <= 1} href={page > 1 ? libraryUrl(query, { page: page - 1 }) : undefined}>Previous</a><b>{page} / {totalPages}</b><a aria-disabled={page >= totalPages} href={page < totalPages ? libraryUrl(query, { page: page + 1 }) : undefined}>Next</a></div></nav>; }

export async function MediaLibraryPage({ query }: { query: Record<string, string | undefined> }) {
  let parsed: MediaQuery; try { parsed = parseMediaQuery(query); } catch { parsed = parseMediaQuery({}); }
  let result; try { result = await getMediaAssets(query); } catch (error) { const invalid = error instanceof InvalidMediaQuery; return <ApplicationShell panel="staff" active="/library"><Crumbs items={[{ label: "Library" }]} /><header className="contentHead"><div><span className="kicker">CENTRAL MEDIA LIBRARY</span><h1>All files</h1></div></header><CategoryNav active={parsed.category} query={query} /><Filters parsed={parsed} /><div className="secureError" role="alert"><b>{invalid ? "Invalid library filters" : "Database unavailable"}</b><p>{invalid ? "Clear the filters and try again." : "The secure media database could not be reached. Please refresh to try again."}</p></div></ApplicationShell>; }
  const filtered = Boolean(parsed.search || parsed.category || parsed.extension);
  return <ApplicationShell panel="staff" active="/library"><Crumbs items={[{ label: "Library" }]} /><header className="contentHead"><div><span className="kicker">CENTRAL MEDIA LIBRARY</span><h1>All files</h1><p>{result.total} accessible file{result.total === 1 ? "" : "s"}</p></div></header><CategoryNav active={parsed.category} query={query} /><Filters parsed={parsed} />{result.items.length === 0 ? <section className="emptyModern"><h2>{filtered ? "No files match your search" : "No accessible files yet"}</h2><p>{filtered ? "Try a different filename, category, or extension." : "Files will appear here when access has been granted."}</p>{filtered && <a href="/library">Clear all filters</a>}</section> : <><section className="fileGrid" aria-label="Media assets">{result.items.map((asset) => <AssetCard asset={asset} key={asset.id} />)}</section><Pager {...result} query={query} /></>}</ApplicationShell>;
}
