import "server-only";
import type{Summary}from"./lib";import{isUuid,parseFileParams}from"./lib";import{requireActiveAppUser,requireAdmin}from"./auth";import{getPreviewRole}from"./lib/dev-preview";import{liveRest}from"./lib/library/live-transport";
export type Result<T>={data:T|null;error:string|null};
export type FolderSummary={id:string;name:string;account:string;googleFolderId:string;folderUrl:string|null;active:boolean;accessStatus:string;lastScan:string|null;totalFiles:number;images:number;videos:number;documents:number;other?:number;eligible:number;excluded:number;migrated:number;verified:number;failed:number;assets:number;uploaded:number};
export type FileRow={id:string;sourceFileId?:string|null;folderId:string;folderName:string;sourceFolders?:string[];name:string;mime:string|null;extension:string|null;size:number|null;created:string|null;modified:string|null;relativePath:string|null;decision:string;processing:string;skipReason:string|null;duplicateOf:string|null;assetId:string|null;assetStatus:string|null;migration:string;verification:string;destinationId:string|null;attempts:number;contentType:string|null;treatment:string|null;subject:string|null;doctorName:string|null;shortCaption:string|null;aiDescription:string|null;thumbnailUrl:string|null};
export type FileDetails=FileRow&{folderId:string;googleFileId:string;sourceUrl:string|null;assetRelationship:string|null;duplicateCount:number;destinationUrl:string|null;uploadedAt:string|null;verifiedAt:string|null;attempts:number;error:string|null};
async function rest(path:string,init:RequestInit={}){await requireActiveAppUser();if(await getPreviewRole()){const{mockDashboardResponse}=await import("./lib/mock-dashboard-data");return mockDashboardResponse(path)}return liveRest(path,init)}
async function rows<T>(path:string){return await(await rest(path)).json() as T[]}
async function count(table:string,filter=""){const r=await rest(`${table}?select=id${filter}`,{headers:{Prefer:"count=exact"}});return Number((r.headers.get("content-range")||"").split("/")[1]||0)}
function safe<T>(fn:()=>Promise<T>):Promise<Result<T>>{return fn().then(data=>({data,error:null})).catch(()=>({data:null,error:"Secure production read unavailable"}))}
const n=(v:unknown)=>Number(v||0),s=(v:unknown)=>v==null?null:String(v);
export async function getSummary(){if(!await getPreviewRole())return(await import("./lib/library/live-provider")).getSummary();return safe<Summary>(async()=>{const[sourceFiles,assets,verified,failed,retries,claims,leases,links,dests]=await Promise.all([count("source_files"),count("assets"),count("asset_destinations","&upload_status=eq.VERIFIED"),count("asset_destinations","&failure_code=not.is.null"),count("asset_destinations","&next_retry_at=not.is.null"),count("asset_destinations","&claim_owner=not.is.null"),count("asset_destinations","&claim_expires_at=gt.now()"),rows<{asset_id:string}>("asset_sources?select=asset_id"),rows<{destination_google_file_id:string|null}>("asset_destinations?select=destination_google_file_id&destination_google_file_id=not.is.null")]);const g=new Map<string,number>();for(const x of links)g.set(x.asset_id,(g.get(x.asset_id)||0)+1);const seen=new Set<string>();let duplicateDestinations=0;for(const x of dests){if(x.destination_google_file_id&&seen.has(x.destination_google_file_id))duplicateDestinations++;else if(x.destination_google_file_id)seen.add(x.destination_google_file_id)}return{sourceFiles,eligible:assets,excluded:sourceFiles-assets,assets,verified,failed,retries,claims,leases,duplicateGroups:[...g.values()].filter(x=>x>1).length,duplicateDestinations}})}
async function folderMediaCounts(id:string){const f=`&source_folder_id=eq.${id}`,[images,videos,documents]=await Promise.all([count("source_files",`${f}&mime_type=like.image/*`),count("source_files",`${f}&mime_type=like.video/*`),count("source_files",`${f}&or=(file_extension.eq.pdf,file_extension.eq.pptx)`)]);return{images,videos,documents}}
function mapFolder(x:Record<string,unknown>,media:{images:number;videos:number;documents:number}):FolderSummary{return{id:String(x.id),name:String(x.source_name),account:String(x.account_name),folderUrl:s(x.folder_url),googleFolderId:String(x.google_folder_id),active:Boolean(x.active),accessStatus:String(x.access_status),lastScan:s(x.last_scan_at),totalFiles:n(x.total_files),...media,eligible:n(x.take_files),excluded:n(x.skip_files),migrated:n(x.uploaded_files),verified:n(x.uploaded_files),failed:n(x.failed_files),assets:n(x.take_files),uploaded:n(x.uploaded_files)}}
export async function listSourceFolders(){if(!await getPreviewRole())return(await import("./lib/library/live-provider")).listSourceFolders();return safe(async()=>{const d=await rows<Record<string,unknown>>("source_folder_summary?select=id,source_name,account_name,folder_url,google_folder_id,active,access_status,last_scan_at,total_files,take_files,skip_files,uploaded_files,failed_files&order=source_name.asc");return Promise.all(d.map(async x=>mapFolder(x,await folderMediaCounts(String(x.id)))) )})}
export const getFolders=listSourceFolders;
export async function getSourceFolderById(id:string){if(!isUuid(id))return{data:null,error:null};if(!await getPreviewRole())return(await import("./lib/library/live-provider")).getSourceFolderById(id);return safe(async()=>{const x=(await rows<Record<string,unknown>>(`source_folder_summary?select=id,source_name,account_name,folder_url,google_folder_id,active,access_status,last_scan_at,total_files,take_files,skip_files,uploaded_files,failed_files&id=eq.${id}&limit=1`))[0];if(!x)return null;return mapFolder(x,await folderMediaCounts(id))})}
export const getSourceFolderSummary=getSourceFolderById;
const select="id,source_folder_id,google_file_id,file_name,mime_type,file_extension,size_bytes,drive_created_at,drive_modified_at,web_view_link,relative_path,decision,processing_status,processing_error,skip_reason,duplicate_of_source_file_id,source_folders(source_name),asset_sources(asset_id,relationship_type,assets(upload_status,asset_semantic_index(content_type,treatment,subject,doctor_name,short_caption,ai_description))),asset_destinations(id,destination_google_file_id,destination_url,destination_filename,upload_status,verification_level,upload_attempt_count,upload_completed_at,verified_at,failure_reason)";
function mapFile(x:Record<string,unknown>):FileRow{const links=(x.asset_sources as Record<string,unknown>[]||[]),asset=links[0]||{},assets=(asset.assets||{}) as Record<string,unknown>,semanticRows=(assets.asset_semantic_index as Record<string,unknown>[]||[]),semantic=semanticRows[0]||{},ds=(x.asset_destinations as Record<string,unknown>[]||[]),d=ds[0]||{},folder=(x.source_folders||{}) as Record<string,unknown>;return{id:String(x.id),folderId:String(x.source_folder_id),folderName:String(folder.source_name||"Source folder"),name:String(x.file_name),mime:s(x.mime_type),extension:s(x.file_extension),size:x.size_bytes==null?null:n(x.size_bytes),created:s(x.drive_created_at),modified:s(x.drive_modified_at),relativePath:s(x.relative_path),decision:String(x.decision),processing:String(x.processing_status),skipReason:s(x.skip_reason),duplicateOf:s(x.duplicate_of_source_file_id),assetId:s(asset.asset_id),assetStatus:s(assets.upload_status),migration:s(d.upload_status)||"NOT_STARTED",verification:s(d.verification_level)||"NONE",destinationId:s(d.destination_google_file_id),attempts:n(d.upload_attempt_count),contentType:s(semantic.content_type),treatment:s(semantic.treatment),subject:s(semantic.subject),doctorName:s(semantic.doctor_name),shortCaption:s(semantic.short_caption),aiDescription:s(semantic.ai_description),thumbnailUrl:null}}
export async function listSourceFolderFiles(folderId:string,input:Record<string,string|undefined>={}){if(!isUuid(folderId))return{data:null,error:null};if(!await getPreviewRole())return(await import("./lib/library/live-provider")).listSourceFolderFiles(folderId,input);return safe(async()=>{const p=parseFileParams(input),filters=[`source_folder_id=eq.${folderId}`];const offset=(p.page-1)*p.pageSize,r=await rest(`source_files?select=${select}&${filters.join("&")}&order=${p.sort}.${p.direction}.nullslast,id.asc&offset=${offset}&limit=${p.pageSize}`,{headers:{Prefer:"count=exact"}}),raw=await r.json() as Record<string,unknown>[];return{rows:raw.map(mapFile),total:Number((r.headers.get("content-range")||"").split("/")[1]||0),params:p}})}
export function countSourceFolderFiles(folderId:string){return isUuid(folderId)?safe(()=>count("source_files",`&source_folder_id=eq.${folderId}`)):Promise.resolve({data:null,error:null})}
export async function listFiles(input:Record<string,string|undefined>={}){if(!await getPreviewRole())return(await import("./lib/library/live-provider")).listFiles(input);const folder=input.folder;if(folder&&!isUuid(folder))return{data:null,error:null};return listFileQuery(input,folder||null)}
async function listFileQuery(input:Record<string,string|undefined>,folderId:string|null){return safe(async()=>{const p=parseFileParams(input),filters:string[]=[];if(folderId)filters.push(`source_folder_id=eq.${folderId}`);if(p.query){const q=encodeURIComponent(`*${p.query.replace(/[*,()]/g,"")}*`);filters.push(`or=(file_name.ilike.${q},relative_path.ilike.${q})`)}if(p.extension)filters.push(`file_extension=eq.${encodeURIComponent(p.extension)}`);if(p.decision)filters.push(`decision=eq.${p.decision}`);if(p.status)filters.push(`processing_status=eq.${p.status}`);if(p.type){const t:Record<string,string>={image:"mime_type=like.image/*",video:"mime_type=like.video/*",document:"or=(file_extension.in.(pdf,pptx),mime_type.ilike.*pdf*,mime_type.ilike.*presentation*)",other:"and=(mime_type=not.like.image/*,mime_type=not.like.video/*,file_extension=not.in.(pdf,pptx))"};filters.push(t[p.type])}const offset=(p.page-1)*p.pageSize,r=await rest(`source_files?select=${select}${filters.length?`&${filters.join("&")}`:""}&order=${p.sort}.${p.direction}.nullslast&offset=${offset}&limit=${p.pageSize}`,{headers:{Prefer:"count=exact"}}),raw=await r.json() as Record<string,unknown>[];return{rows:raw.map(mapFile),total:Number((r.headers.get("content-range")||"").split("/")[1]||0),params:p}})}
export async function getFileById(fileId:string){if(!isUuid(fileId))return{data:null,error:null};if(!await getPreviewRole())return(await import("./lib/library/live-provider")).getFileById(fileId);return safe(async()=>{const x=(await rows<Record<string,unknown>>(`source_files?select=${select}&id=eq.${fileId}&limit=1`))[0];return x?mapFile(x):null})}
// ---- Asset semantic detail (18-layer evidence + scene timeline) -----------
export type SemanticEvidenceItem={state:string;confidence:number|null;code:string|null;text:string|null;sceneId:string|null;searchCritical:boolean};
export type SemanticLayerGroup={layerId:string;label:string;items:SemanticEvidenceItem[]};
export type AssetSceneRow={index:number;start:number|null;end:number|null;description:string|null};
export type AssetSemanticDetail={layers:SemanticLayerGroup[];scenes:AssetSceneRow[]};
const LAYER_ORDER=["ASSET_IDENTITY_PROVENANCE","GLOBAL_ASSET_UNDERSTANDING","TEMPORAL_SCENE_STRUCTURE","PEOPLE_ROLES","PERSON_APPEARANCE","ANATOMY","TREATMENT_PROCEDURE","ACTIONS_EVENTS","RELATIONSHIPS","CLINICAL_VISUAL_OBSERVATIONS","ENVIRONMENT","CINEMATOGRAPHY","COMPOSITION","SPEECH_TRANSCRIPT_AUDIO","OCR_VISIBLE_TEXT","MARKETING_CONTENT_USAGE","SEMANTIC_NARRATIVE","SEARCH_EMBEDDINGS"];
const prettyLayer=(id:string)=>id.toLowerCase().replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase());
// Loads an asset's active assertions grouped into the canonical 18 layers, plus its scenes for the
// video timeline. Reads only AI-derived semantic fields (state/confidence/value_text/scene) - never
// source_files.relative_path (patient-name path). RLS on semantic_assertions/asset_scenes gates rows
// to what the viewer may see; the page itself is requireProtectedPage-gated.
export async function getAssetSemanticDetail(assetId:string|null):Promise<Result<AssetSemanticDetail>>{
  if(!assetId||!isUuid(assetId))return{data:{layers:[],scenes:[]},error:null};
  if(await getPreviewRole())return{data:{layers:[],scenes:[]},error:null};
  return safe(async()=>{
    const [assertions,scenes]=await Promise.all([
      rows<Record<string,unknown>>(`semantic_assertions?select=layer_id,canonical_concept_code,semantic_state,confidence,value_text,scene_id,search_critical&asset_id=eq.${assetId}&active=is.true&superseded_by=is.null&limit=2000`),
      rows<Record<string,unknown>>(`asset_scenes?select=scene_index,start_seconds,end_seconds,short_description,literal_description&asset_id=eq.${assetId}&order=scene_index.asc&limit=500`),
    ]);
    const byLayer=new Map<string,SemanticEvidenceItem[]>();
    for(const a of assertions){const layer=String(a.layer_id||"");if(!layer)continue;const code=a.canonical_concept_code==null?null:String(a.canonical_concept_code);let arr=byLayer.get(layer);if(!arr){arr=[];byLayer.set(layer,arr);}arr.push({state:String(a.semantic_state||"UNKNOWN"),confidence:a.confidence==null?null:Number(a.confidence),code:code&&code!==layer?code:null,text:a.value_text==null?null:String(a.value_text),sceneId:a.scene_id==null?null:String(a.scene_id),searchCritical:Boolean(a.search_critical)});}
    const ordered=[...LAYER_ORDER,...[...byLayer.keys()].filter(l=>!LAYER_ORDER.includes(l))];
    const layers=ordered.filter(l=>byLayer.has(l)).map(l=>({layerId:l,label:prettyLayer(l),items:byLayer.get(l)!}));
    const sceneRows=scenes.map(sc=>({index:n(sc.scene_index),start:sc.start_seconds==null?null:Number(sc.start_seconds),end:sc.end_seconds==null?null:Number(sc.end_seconds),description:s(sc.short_description)||s(sc.literal_description)}));
    return{layers,scenes:sceneRows};
  });
}

// Canonical Drive-media resolution (thumbnail/preview/download) lives in
// media-service.ts -> lib/media/resolve-location.ts, not here - it always
// resolves an asset's verified destination directly rather than by
// re-deriving it through this dashboard-facing query layer.
export async function getLibrarySummary(){if(!await getPreviewRole())return(await import("./lib/library/live-provider")).getLibrarySummary();const [summary,folders,images,videos,documents]=await Promise.all([getSummary(),listSourceFolders(),safe(()=>count("source_files","&mime_type=like.image/*")),safe(()=>count("source_files","&mime_type=like.video/*")),safe(()=>count("source_files","&or=(file_extension.eq.pdf,file_extension.eq.pptx)"))]);if(!summary.data||!folders.data)return{data:null,error:"Secure production read unavailable"};return{data:{...summary.data,folders:folders.data,images:images.data||0,videos:videos.data||0,documents:documents.data||0},error:null}}
export function getSourceFileDetails(folderId:string,fileId:string){if(!isUuid(folderId)||!isUuid(fileId))return Promise.resolve({data:null,error:null});return safe(async()=>{const x=(await rows<Record<string,unknown>>(`source_files?select=${select}&id=eq.${fileId}&source_folder_id=eq.${folderId}&limit=1`))[0];if(!x)return null;const base=mapFile(x),links=(x.asset_sources as Record<string,unknown>[]||[]),ds=(x.asset_destinations as Record<string,unknown>[]||[]),d=ds[0]||{},assetId=base.assetId,duplicateCount=assetId?await count("asset_sources",`&asset_id=eq.${assetId}`):0;return{...base,folderId:String(x.source_folder_id),googleFileId:String(x.google_file_id),sourceUrl:s(x.web_view_link),assetRelationship:s(links[0]?.relationship_type),duplicateCount,destinationUrl:s(d.destination_url),uploadedAt:s(d.upload_completed_at),verifiedAt:s(d.verified_at),attempts:n(d.upload_attempt_count),error:s(d.failure_reason)||s(x.processing_error)} as FileDetails})}
export function listSourceFolderSubfolders(folderId:string){if(!isUuid(folderId))return Promise.resolve({data:null,error:null});return safe(async()=>{const d=await rows<{relative_path:string|null}>(`source_files?select=relative_path&source_folder_id=eq.${folderId}&relative_path=not.is.null&limit=1000`);return[...new Set(d.map(x=>x.relative_path).filter(Boolean))] as string[]})}
export type MigrationRow={id:string;status:string;verification:string;attempts:number;bytes:number};
export function getMigrations(page=1,pageSize=25){return safe(async()=>{await requireAdmin();const offset=(page-1)*pageSize,r=await rest(`asset_destinations?select=id,upload_status,verification_level,upload_attempt_count,expected_bytes&order=verified_at.desc.nullslast&offset=${offset}&limit=${pageSize}`,{headers:{Prefer:"count=exact"}}),d=await r.json() as Record<string,unknown>[];return{rows:d.map(x=>({id:String(x.id),status:String(x.upload_status),verification:String(x.verification_level),attempts:n(x.upload_attempt_count),bytes:n(x.expected_bytes)})),total:Number((r.headers.get("content-range")||"").split("/")[1]||0)}})}
export function getExceptions(){return safe(async()=>{await requireAdmin();const d=await rows<Record<string,unknown>>("asset_destinations?select=id,upload_status,verification_level,upload_attempt_count,expected_bytes&or=(failure_code.not.is.null,next_retry_at.not.is.null)&limit=100");return d.map(x=>({id:String(x.id),status:String(x.upload_status),verification:String(x.verification_level),attempts:n(x.upload_attempt_count),bytes:n(x.expected_bytes)}))})}
export function getDuplicates(){return safe(async()=>{await requireAdmin();const d=await rows<{asset_id:string}>("asset_sources?select=asset_id"),m=new Map<string,number>();for(const x of d)m.set(x.asset_id,(m.get(x.asset_id)||0)+1);return[...m].filter(([,v])=>v>1).map(([assetId,sourceCount])=>({assetId,sourceCount}))})}
export const DASHBOARD_MUTATIONS:readonly never[]=[];
