import "server-only";
import{validateDashboardEnvironment,validateDashboardPublicEnvironment}from"./environment";
const PROJECT="wcqqjpndlwsvatjuqnol",SESSION_FILE=".reader-session.json",LOCK_FILE=".reader-session.json.lock",MIN_TTL=300;
type ManagedSession={access_token:string;refresh_token:string;expires_at:number;project_ref:string};
function claims(token:string){try{return JSON.parse(Buffer.from(token.split(".")[1],"base64url").toString("utf8")) as Record<string,unknown>}catch{throw new Error("Dashboard authentication requires reader bootstrap")}}
function validate(session:ManagedSession,url:string,allowExpired=false){const c=claims(session.access_token),m=(c.app_metadata||{}) as Record<string,unknown>;if(session.project_ref!==PROJECT||c.iss!==`${url}/auth/v1`||c.aud!=="authenticated"||c.email!=="kdimediaautomation@gmail.com"||m.kdi_media_reader!=="true"||m.kdi_media_access!==true||typeof c.exp!=="number"||(!allowExpired&&c.exp<=Date.now()/1000)||!session.refresh_token)throw new Error("Dashboard authentication requires reader bootstrap");return c.exp as number}
async function modules(){const[fs,path,child]=await Promise.all([import("node:fs/promises"),import("node:path"),import("node:child_process")]);return{fs,path,child}}
async function readManaged():Promise<ManagedSession|null>{const{fs,path}=await modules();try{return JSON.parse(await fs.readFile(path.join(process.cwd(),SESSION_FILE),"utf8")) as ManagedSession}catch(e){if((e as NodeJS.ErrnoException).code==="ENOENT")return null;throw new Error("Dashboard authentication requires reader bootstrap")}}
async function writeManaged(session:ManagedSession){const{fs,path,child}=await modules(),target=path.join(process.cwd(),SESSION_FILE),temp=`${target}.${process.pid}.${Date.now()}`;await fs.writeFile(temp,JSON.stringify(session),{encoding:"utf8",mode:0o600,flag:"wx"});await fs.rename(temp,target);if(process.platform==="win32")await new Promise<void>(resolve=>child.execFile("icacls",[target,"/inheritance:r","/grant:r",`${process.env.USERNAME||""}:(R,W)`],{windowsHide:true},()=>resolve()))}
async function withLock<T>(fn:()=>Promise<T>):Promise<T>{const{fs,path}=await modules(),lock=path.join(process.cwd(),LOCK_FILE);let handle;for(let attempt=0;attempt<40&&!handle;attempt++){try{handle=await fs.open(lock,"wx",0o600)}catch(e){if((e as NodeJS.ErrnoException).code!=="EEXIST")throw new Error("Dashboard authentication requires reader bootstrap");await new Promise(r=>setTimeout(r,250))}}if(!handle)throw new Error("Dashboard authentication requires reader bootstrap");try{return await fn()}finally{await handle.close();await fs.unlink(lock).catch(()=>undefined)}}
async function refresh(current:ManagedSession,url:string,key:string){return withLock(async()=>{const latest=await readManaged();if(latest&&validate(latest,url)-Date.now()/1000>MIN_TTL)return latest;let response:Response;try{response=await fetch(`${url}/auth/v1/token?grant_type=refresh_token`,{method:"POST",headers:{apikey:key,"Content-Type":"application/json"},body:JSON.stringify({refresh_token:current.refresh_token}),cache:"no-store"})}catch{throw new Error("Dashboard authentication requires reader bootstrap")}if(!response.ok)throw new Error("Dashboard authentication requires reader bootstrap");const body=await response.json() as Record<string,unknown>,next={access_token:String(body.access_token||""),refresh_token:String(body.refresh_token||""),expires_at:0,project_ref:PROJECT};next.expires_at=validate(next,url);await writeManaged(next);return next})}
export async function getReaderCredentials(){const managed=await readManaged();if(!managed)return validateDashboardEnvironment();const{url,key}=validateDashboardPublicEnvironment(),expiry=validate(managed,url,true);if(expiry-Date.now()/1000>MIN_TTL)return{url,key,token:managed.access_token};const renewed=await refresh(managed,url,key);return{url,key,token:renewed.access_token}}
