import"server-only";import{createHash,randomBytes,timingSafeEqual}from"node:crypto";import{cookies}from"next/headers";import{createServiceClient}from"../supabase/service";import{ADMIN_SESSION_COOKIE,REMEMBER_SESSION_SECONDS,SHORT_SESSION_SECONDS}from"./constants";
export type AdminIdentity={id:string;email:string;fullName:string;role:"admin";isActive:boolean;mustChangePassword:boolean};
export const tokenHash=(token:string)=>createHash("sha256").update(token).digest("hex");
export async function createAdminSession(adminId:string,remember:boolean){const token=randomBytes(32).toString("base64url"),seconds=remember?REMEMBER_SESSION_SECONDS:SHORT_SESSION_SECONDS,expires=new Date(Date.now()+seconds*1000);const{error}=await createServiceClient().from("admin_sessions").insert({admin_account_id:adminId,token_hash:tokenHash(token),expires_at:expires.toISOString(),last_used_at:new Date().toISOString()});if(error)throw new Error("Session could not be created");(await cookies()).set(ADMIN_SESSION_COOKIE,token,{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production",path:"/",...(remember?{maxAge:seconds}:{})});return expires}
export async function currentAdmin():Promise<AdminIdentity|null>{const token=(await cookies()).get(ADMIN_SESSION_COOKIE)?.value;if(!token)return null;const{data}=await createServiceClient().from("admin_sessions").select("id,expires_at,revoked_at,admin_accounts!inner(id,email,full_name,role,is_active,must_change_password)").eq("token_hash",tokenHash(token)).is("revoked_at",null).gt("expires_at",new Date().toISOString()).maybeSingle();const a=Array.isArray(data?.admin_accounts)?data.admin_accounts[0]:data?.admin_accounts;if(!data||!a||a.role!=="admin"||!a.is_active)return null;void createServiceClient().from("admin_sessions").update({last_used_at:new Date().toISOString()}).eq("id",data.id);return{id:a.id,email:a.email,fullName:a.full_name||a.email.split("@")[0],role:"admin",isActive:true,mustChangePassword:Boolean(a.must_change_password)}}
export async function revokeCurrentSession(){const store=await cookies(),token=store.get(ADMIN_SESSION_COOKIE)?.value;if(token)await createServiceClient().from("admin_sessions").update({revoked_at:new Date().toISOString()}).eq("token_hash",tokenHash(token));store.set(ADMIN_SESSION_COOKIE,"",{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production",path:"/",maxAge:0})}
export async function revokeAllSessions(adminId:string){await createServiceClient().from("admin_sessions").update({revoked_at:new Date().toISOString()}).eq("admin_account_id",adminId).is("revoked_at",null)}
export function verifyRecoveryKey(value:string){const expected=process.env.KDI_ADMIN_RECOVERY_KEY;if(!expected||!value)return false;const a=Buffer.from(createHash("sha256").update(value).digest()),b=Buffer.from(createHash("sha256").update(expected).digest());return a.length===b.length&&timingSafeEqual(a,b)}
export async function audit(event_type:string,admin_account_id:string|null,metadata:Record<string,unknown>={}){await createServiceClient().from("admin_auth_audit").insert({event_type,admin_account_id,metadata})}
