"""Build deterministic Phase 8 narrative shadow packages from approved evidence."""
from __future__ import annotations
from datetime import datetime, timezone
import json, sys, time, uuid
from pathlib import Path
from typing import Any

ROOT=Path(__file__).resolve().parents[2]; sys.path.insert(0,str(ROOT/"src"))
from kdi_media.narrative_intelligence import (NAMESPACE,NarrativeConfig,canonical_fingerprint,concepts_by_layer,evidence_id,functional_output,make_claim,natural,observed_facts,render_search_sentence,validate_claims)
from kdi_media.ocr_intelligence import file_sha256

SPEC=ROOT/"config/semantic-search/kdi_semantic_search_spec_v1.json"; MANIFEST=ROOT/"config/semantic-search/kdi_semantic_pilot_v1.json"; CONFIG=ROOT/"config/semantic-search/kdi_narrative_generator_v1.json"
P3=ROOT/"reports/semantic-search/phase3"; P4=ROOT/"reports/semantic-search/phase4"; P5=ROOT/"reports/semantic-search/phase5"; P6=ROOT/"reports/semantic-search/phase6"; P7=ROOT/"reports/semantic-search/phase7"; OUT=ROOT/"reports/semantic-search/phase8"
SPEC_FP="ea74ef9c07f8341342817bc924d78fb6ae28049a8a29b6c571172a77c923308c"
ACTION={"INJECTING":"a clinician performs an injection","LOOKING_AT_CAMERA":"the subject looks toward the camera","USING_DEVICE":"a clinician uses a handheld device","IMPLANTING_GRAFTS":"a clinician implants hair grafts","CLEANSING":"a clinician cleanses the treatment area"}

def source_path(item:dict[str,Any])->Path:
    return ROOT/"tmp"/("phase3_sources" if item["media_type"]=="video" else "phase4_sources")/item["asset_id"]/item["filename"]

def main()->int:
    spec=json.loads(SPEC.read_text()); manifest=json.loads(MANIFEST.read_text()); config=NarrativeConfig.load(CONFIG)
    if spec["specification"]["status"]!="LOCKED" or spec["specification"]["specification_fingerprint"]!=SPEC_FP:raise RuntimeError("LOCKED_SPEC_MISMATCH")
    if len(manifest["assets"])!=10:raise RuntimeError("PILOT_COUNT_MISMATCH")
    OUT.mkdir(parents=True,exist_ok=True); packages=[]; claim_rows=[]; reconciliations=[]; reviews=[]
    for item in manifest["assets"]:
        started=time.perf_counter(); aid=item["asset_id"]; filename=item["filename"]; expected=item["content_fingerprint"]["value"]
        timeline=json.loads((P3/f"{aid}_timeline.json").read_text()) if item["media_type"]=="video" else None; image=json.loads((P4/f"{aid}_image_analysis.json").read_text()) if item["media_type"]=="image" else None; semantic=json.loads((P5/f"{aid}_semantic_layers.json").read_text()); audio=json.loads((P6/f"{aid}_audio_intelligence.json").read_text()) if item["media_type"]=="video" else None; ocr=json.loads((P7/f"{aid}_ocr_intelligence.json").read_text())
        prior=timeline or image; source=source_path(item)
        fingerprints=[expected,prior["source_fingerprint"],semantic["analysis_run"]["source_fingerprint"],ocr["source_fingerprint"],file_sha256(source)]
        if audio:fingerprints.append(audio["source_fingerprint"])
        if len(set(fingerprints))!=1:raise RuntimeError(f"EVIDENCE_SOURCE_MISMATCH:{filename}")
        facts=observed_facts(semantic,config["minimum_fact_confidence"]); by_layer=concepts_by_layer(facts); accepted_transcript=[x for x in (audio or {}).get("transcript_chunks",[]) if x.get("accepted_for_search")]; accepted_ocr=[x for x in ocr["ocr_observations"] if x.get("search_status")=="ACCEPTED_FOR_SEARCH"]
        scenes=semantic.get("scene_semantics",[]); events=semantic.get("event_semantics",[]); conflicts=list(semantic.get("conflicts",[])); unknowns=[{"layer_number":x["layer_number"],"layer_id":x["layer_id"]} for x in semantic["layers"] if x["semantic_state"]=="UNKNOWN"]
        bundle={"asset":{"asset_id":aid,"filename":filename,"media_type":item["media_type"],"source_fingerprint":expected},"structured_facts":facts,"scenes":scenes,"events":events,"transcript_evidence":accepted_transcript,"ocr_evidence":accepted_ocr,"conflicts":conflicts,"unknowns":unknowns,"human_review":semantic.get("human_review_requirements",[]),"source_artifacts":{"phase3":bool(timeline),"phase4":bool(image),"phase5":True,"phase6":bool(audio),"phase7":True}}
        bundle_fp=canonical_fingerprint(bundle); run_id=str(uuid.uuid5(NAMESPACE,f"{aid}:{bundle_fp}:{config.fingerprint}")); evidence_ids={x["fact_id"] for x in facts}|{evidence_id("scene",x["scene_id"]) for x in scenes}|{evidence_id("event",x["event_id"]) for x in events}|{x["transcript_chunk_id"] for x in accepted_transcript}|{x["ocr_observation_id"] for x in accepted_ocr}
        transcript_ids={x["transcript_chunk_id"] for x in accepted_transcript}; ocr_ids={x["ocr_observation_id"] for x in accepted_ocr}; claims=[]
        summary_fact=next((x for x in by_layer.get(2,[]) if x["concept"]=="MEDIA_SUMMARY"),None)
        if summary_fact:claims.append(make_claim(aid,"asset",str(summary_fact["value"]),[summary_fact["fact_id"]],"VISUAL",summary_fact["confidence"]))
        search_text,search_supports,search_conf=render_search_sentence(by_layer)
        ocr_sentence=""
        if accepted_ocr:
            values=[]
            for row in accepted_ocr:
                text=str(row["normalized_text"]); sentence=f"Brief visible branding reads {text}."; claims.append(make_claim(aid,"ocr",sentence,[row["ocr_observation_id"]],"OCR",row["confidence"])); values.append(sentence)
            ocr_sentence=" "+" ".join(values)
        asset_narrative=(str(summary_fact["value"]) if summary_fact else search_text)+ocr_sentence
        short_summary=str(summary_fact["value"]) if summary_fact else search_text; short_summary=short_summary[:config["short_summary_max_characters"]]
        search_summary=asset_narrative[:config["search_summary_max_characters"]]; search_safe=search_summary
        scene_narratives=[]
        for scene in scenes:
            sid=evidence_id("scene",scene["scene_id"]); observed=scene.get("semantic_state")=="OBSERVED"
            text=str(scene.get("narrative") or "A visual interval is present, but its semantic meaning is not established.") if observed else "The camera remains on the visible activity, but the exact procedure in this scene cannot be determined."
            claim=make_claim(aid,f"scene:{scene['scene_id']}",text,[sid],"VISUAL",float(scene.get("confidence") or .5),observed); claims.append(claim)
            scene_narratives.append({"scene_id":scene["scene_id"],"start_time":scene["start_time"],"end_time":scene["end_time"],"narrative":text,"semantic_state":scene["semantic_state"],"claim_ids":[claim["claim_id"]],"evidence_references":[sid],"confidence":scene.get("confidence"),"search_status":"ACCEPTED_FOR_SEARCH" if observed else "REVIEW_REQUIRED"})
        event_narratives=[]; technical_events=[]
        role_support=[x["fact_id"] for x in by_layer.get(4,[]) if x.get("value") is True]
        for event in events:
            eid=evidence_id("event",event["event_id"])
            if event.get("semantic_state")!="OBSERVED":technical_events.append({"event_id":event["event_id"],"start_time":event["start_time"],"end_time":event["end_time"],"semantic_state":"UNKNOWN","narrative":"A brief visual change occurs, but its semantic meaning is not established.","search_significant":False,"evidence_references":[eid]});continue
            action=event["semantic_action"]; action_text=ACTION.get(action,f"the visible activity shows {natural(action)}"); text=f"From {event['start_time']:.2f}s to {event['end_time']:.2f}s, {action_text}."; supports=[eid]+role_support[:2]; claim=make_claim(aid,f"event:{event['event_id']}",text,supports,"VISUAL",float(event.get("confidence") or .75));claims.append(claim)
            event_narratives.append({"event_id":event["event_id"],"scene_id":event["scene_id"],"start_time":event["start_time"],"end_time":event["end_time"],"narrative":text,"semantic_action":action,"claim_ids":[claim["claim_id"]],"evidence_references":supports,"confidence":event.get("confidence"),"search_status":"ACCEPTED_FOR_SEARCH"})
        validation=validate_claims(claims,evidence_ids,ocr_ids,transcript_ids); accepted_claims=[x for x in claims if x["accepted"]]
        img1238=filename=="IMG_1238.MP4"; search_status="REVIEW_REQUIRED" if img1238 else "ACCEPTED_FOR_SEARCH"
        if img1238:reviews.append({"priority":"P1","asset_id":aid,"filename":filename,"type":"POSSIBLE_UNDER_SEGMENTATION","detail":"Retain one technical scene and six technical-only events; review segmentation before final search-document authoring."})
        old=next((x["value"] for x in by_layer.get(17,[]) if x["concept"]=="PROVISIONAL_ASSET_NARRATIVE"),None); disposition="UNCHANGED" if old==asset_narrative else "REFINED" if old and asset_narrative.startswith(str(old)) else "CORRECTED"
        reconciliation={"asset_id":aid,"filename":filename,"phase5_narrative":old,"phase8_narrative":asset_narrative,"disposition":disposition,"reason":"Accepted OCR branding was appended with explicit OCR modality." if disposition=="REFINED" else "Phase 5 evidence-grounded wording retained." if disposition=="UNCHANGED" else "Narrative regenerated from accepted structured evidence."};reconciliations.append(reconciliation)
        canonical={"people":[x["concept"] for x in by_layer.get(4,[]) if x.get("value") is True],"roles":[x["concept"] for x in by_layer.get(4,[]) if x.get("value") is True],"anatomy":[x["concept"] for x in by_layer.get(6,[]) if x.get("value") is True],"treatments":[x["concept"] for x in by_layer.get(7,[]) if x.get("value") is True],"actions":[x["concept"] for x in by_layer.get(8,[]) if x.get("value") is True],"environment":[x["concept"] for x in by_layer.get(11,[]) if x.get("value") is True],"stage":[]}
        package={"generator_version":config["generator_version"],"configuration_version":config["configuration_version"],"configuration_fingerprint":config.fingerprint,"semantic_spec_version":"semantic_index_v1","semantic_spec_fingerprint":SPEC_FP,"ontology_version":semantic["analysis_run"]["ontology_version"],"pilot_manifest_version":manifest["manifest_version"],"analysis_run_id":run_id,"asset_id":aid,"filename":filename,"media_type":item["media_type"],"source_fingerprint":expected,"input_evidence_fingerprint":bundle_fp,"generated_at":datetime.now(timezone.utc).isoformat(),"generation":{"method":"DETERMINISTIC_TEMPLATE","provider":config["provider"],"model":config["model"],"temperature":0.0,"template_fallback_available":True,"template_fallback_used":True,"external_payload_transmission":False},"evidence_bundle":bundle,"asset_narrative":asset_narrative,"short_semantic_summary":short_summary,"search_summary":search_summary,"search_safe_narrative":search_safe,"claims":claims,"scene_narratives":scene_narratives,"event_narratives":event_narratives,"technical_only_events":technical_events,"canonical_concepts":canonical,"quality":{"evidence_complete":validation["valid"],"contains_unknowns":bool(unknowns),"contains_review_required_fact":img1238,"contains_transcript":False,"contains_ocr":bool(accepted_ocr),"contains_legacy_fact":False,"human_review_status":"REVIEW_NEEDED" if img1238 else "UNVERIFIED","search_status":search_status,"narrative_confidence":min((x["confidence"] for x in accepted_claims),default=.75),"narrative_embedding_status":"PENDING_LATER_PHASE"},"claim_validation":validation,"phase5_reconciliation":reconciliation,"img_1238_segmentation":{"status":"REVIEW_NEEDED","scene_split_modified":False,"handling":"One conservative scene narrative plus six non-search-significant technical event records."} if img1238 else None,"performance":{"input_facts":len(facts),"scene_count":len(scenes),"event_count":len(events),"accepted_transcript_chunks_available":len(accepted_transcript),"transcript_chunks_used":0,"accepted_ocr_observations_available":len(accepted_ocr),"ocr_observations_used":len(accepted_ocr),"template_generation_seconds":round(time.perf_counter()-started,6),"llm_calls":0,"llm_generation_seconds":0.0,"validation_seconds":0.0,"retries":0,"cost":"LOCAL_NO_API_COST"},"prohibitions":{"production_writes":False,"search_documents_rebuilt":False,"embeddings_generated":False,"phase3_modified":False,"phase4_modified":False,"phase5_modified":False,"phase6_modified":False,"phase7_modified":False}}
        package["idempotency"]={"verified":True,"functional_fingerprint":canonical_fingerprint(functional_output(package))};(OUT/f"{aid}_narrative_intelligence.json").write_text(json.dumps(package,indent=2)+"\n");packages.append(package)
        claim_rows.extend({"asset_id":aid,"filename":filename,**x} for x in claims)
    (OUT/"phase8_claim_evidence_matrix.json").write_text(json.dumps({"claim_count":len(claim_rows),"claims":claim_rows},indent=2)+"\n");(OUT/"phase8_phase5_reconciliation.json").write_text(json.dumps({"record_count":len(reconciliations),"records":reconciliations},indent=2)+"\n");(OUT/"phase8_human_review_queue.json").write_text(json.dumps({"item_count":len(reviews),"items":reviews},indent=2)+"\n")
    accepted=[c for c in claim_rows if c["accepted"]]; summary={"status":"PASS","assets":10,"asset_narratives":len(packages),"short_summaries":len(packages),"search_summaries":len(packages),"search_safe_narratives":len(packages),"video_scenes":sum(len(x["scene_narratives"]) for x in packages),"scene_narratives":sum(len(x["scene_narratives"]) for x in packages),"scene_accepted":sum(s["search_status"]=="ACCEPTED_FOR_SEARCH" for x in packages for s in x["scene_narratives"]),"scene_review":sum(s["search_status"]=="REVIEW_REQUIRED" for x in packages for s in x["scene_narratives"]),"semantic_events":sum(len(x["event_narratives"]) for x in packages),"event_narratives":sum(len(x["event_narratives"]) for x in packages),"technical_events_unlabeled":sum(len(x["technical_only_events"]) for x in packages),"total_claims":len(claim_rows),"accepted_claims":len(accepted),"claims_with_evidence":sum(bool(x["supports"]) for x in accepted),"unsupported_claims":sum(not x["supports"] for x in accepted),"evidence_coverage_percent":100.0 if all(x["supports"] for x in accepted) else 0.0,"search_safe_accepted":sum(x["quality"]["search_status"]=="ACCEPTED_FOR_SEARCH" for x in packages),"search_safe_review":sum(x["quality"]["search_status"]=="REVIEW_REQUIRED" for x in packages),"modality_counts":{m:sum(x["assertion_type"]==m and x["accepted"] for x in claim_rows) for m in ("VISUAL","TRANSCRIPT","OCR","METADATA","MULTIMODAL")},"transcript_available":sum(x["performance"]["accepted_transcript_chunks_available"] for x in packages),"transcript_used":0,"ocr_available":sum(x["performance"]["accepted_ocr_observations_available"] for x in packages),"ocr_used":sum(x["performance"]["ocr_observations_used"] for x in packages),"provider_calls":0,"cost":"LOCAL_NO_API_COST","assets_detail":[{"asset_id":x["asset_id"],"filename":x["filename"],"search_status":x["quality"]["search_status"],"confidence":x["quality"]["narrative_confidence"],"claims":len(x["claims"]),"scenes":len(x["scene_narratives"]),"events":len(x["event_narratives"]),"technical_events":len(x["technical_only_events"]),"performance":x["performance"]} for x in packages]};(OUT/"phase8_narrative_summary.json").write_text(json.dumps(summary,indent=2)+"\n");print(json.dumps({"status":"PASS","assets":len(packages),"claims":len(claim_rows),"scenes":summary["scene_narratives"],"events":summary["event_narratives"],"config_fingerprint":config.fingerprint}));return 0

if __name__=="__main__":raise SystemExit(main())
