"""Create Phase 10 review drafts; never make human decisions or sign off assets."""
from __future__ import annotations
import json,sys,uuid
from datetime import datetime,timezone
from pathlib import Path

ROOT=Path(__file__).resolve().parents[2];sys.path.insert(0,str(ROOT/"src"))
from kdi_media.gold_standard_review import NAMESPACE,empty_decision,fingerprint

SPEC_FP="ea74ef9c07f8341342817bc924d78fb6ae28049a8a29b6c571172a77c923308c";REPORTS=ROOT/"reports/semantic-search";OUT=REPORTS/"phase10";REVIEW=OUT/"review"
def load(path):return json.loads(path.read_text())
def main():
    spec=load(ROOT/"config/semantic-search/kdi_semantic_search_spec_v1.json");manifest=load(ROOT/"config/semantic-search/kdi_semantic_pilot_v1.json");config=load(ROOT/"config/semantic-search/kdi_gold_pilot_v1.json")
    if spec["specification"]["specification_fingerprint"]!=SPEC_FP or spec["specification"]["status"]!="LOCKED":raise RuntimeError("LOCKED_SPEC_MISMATCH")
    REVIEW.mkdir(parents=True,exist_ok=True);packets=[]
    for asset in manifest["assets"]:
        aid=asset["asset_id"];video=asset["media_type"]=="video"
        p3=load(REPORTS/"phase3"/f"{aid}_timeline.json") if video else None;p4=load(REPORTS/"phase4"/f"{aid}_image_analysis.json") if not video else None;p5=load(REPORTS/"phase5"/f"{aid}_semantic_layers.json");p6=load(REPORTS/"phase6"/f"{aid}_audio_intelligence.json") if video else None;p7=load(REPORTS/"phase7"/f"{aid}_ocr_intelligence.json");p8=load(REPORTS/"phase8"/f"{aid}_narrative_intelligence.json");p9=load(REPORTS/"phase9"/f"{aid}_consistency_validation.json")
        expected=asset["content_fingerprint"]["value"];fingerprints=[expected,(p3 or p4)["source_fingerprint"],p5["analysis_run"]["source_fingerprint"],p7["source_fingerprint"],p8["source_fingerprint"],p9["source_fingerprint"]]+([p6["source_fingerprint"]] if p6 else [])
        if len(set(fingerprints))!=1:raise RuntimeError(f"EVIDENCE_SOURCE_MISMATCH:{asset['filename']}")
        packet={"review_packet_version":"kdi_human_gold_review_packet_v1","gold_standard_version":config["gold_standard_version"],"semantic_spec_version":"semantic_index_v1","semantic_spec_fingerprint":SPEC_FP,"pilot_manifest_version":manifest["manifest_version"],"asset_id":aid,"filename":asset["filename"],"media_type":asset["media_type"],"source_fingerprint":expected,"review_status":"AWAITING_HUMAN_REVIEW","reviewer_label":config["reviewer_label_default"],"explicit_signoff":False,"signed_off_at":None,"revision":0,"media":{"preview_url":f"/api/dev/library/media/{aid}/preview","duration":p3["technical_metadata"]["duration_seconds"] if video else None,"dimensions":p3["technical_metadata"].get("resolution") if video else p4.get("technical_metadata",{}).get("analysis_dimensions")},"layer_decisions":[empty_decision(aid,x) for x in p5["layers"]],"temporal_review":{"human_decision":None,"ai_scenes":p3["scene_candidates"] if video else [],"ai_events":p3["event_candidates"] if video else [],"scene_overrides":[],"event_overrides":[],"history":[]},"transcript_review":{"human_decision":None if video else "NOT_APPLICABLE","ai_audio":p6["layer_14"] if video else None,"chunks":p6["transcript_chunks"] if video else [],"overrides":[],"history":[]},"ocr_review":{"human_decision":None,"ai_layer_15":p7["layer_15"],"observations":p7["ocr_observations"],"overrides":[],"history":[]},"narrative_review":{"human_decision":None,"asset_narrative":p8["asset_narrative"],"search_summary":p8["search_summary"],"search_safe_narrative":p8["search_safe_narrative"],"scene_narratives":p8["scene_narratives"],"event_narratives":p8["event_narratives"],"overrides":[],"history":[]},"critical_issue_decisions":[{**x,"human_decision":None,"human_value":None,"reason":None,"reviewer_label":None,"reviewed_at":None,"history":[]} for x in p9["issues"] if x["priority"] in {"P0","P1"}],"phase9":{"overall_state":p9["overall_consistency_state"],"rules":p9["rule_results"],"all_issues":p9["issues"]},"review_requirements":{"layer_decisions_required":18,"p0_p1_resolution_required":True,"video_temporal_review_required":video,"transcript_review_required":video,"ocr_review_required":True,"narrative_review_required":True,"explicit_signoff_required":True},"history":[],"created_at":datetime.now(timezone.utc).isoformat(),"prohibitions":{"codex_human_approval":False,"production_writes":False,"database_migrations":False,"source_artifacts_modified":False}}
        packet["input_evidence_fingerprint"]=fingerprint({"phase5":p5,"phase6":p6,"phase7":p7,"phase8":p8,"phase9":p9});packet["review_packet_id"]=str(uuid.uuid5(NAMESPACE,f"{aid}:{packet['input_evidence_fingerprint']}"));packet["review_packet_fingerprint"]=fingerprint({k:v for k,v in packet.items() if k not in {"created_at","review_packet_fingerprint"}})
        (REVIEW/f"{aid}_review_packet.json").write_text(json.dumps(packet,indent=2)+"\n");packets.append(packet)
    summary={"phase":"PHASE_10","status":"AWAITING_HUMAN_REVIEW","gold_standard_version":config["gold_standard_version"],"assets_expected":10,"review_packets":len(packets),"human_layer_decisions_required":180,"human_layer_decisions_completed":0,"p1_issues_required":sum(len(x["critical_issue_decisions"]) for x in packets),"p1_issues_resolved":0,"assets_signed_off":0,"gold_packages_created":0,"gold_manifest_created":False,"ready_for_phase11":False,"generated_at":datetime.now(timezone.utc).isoformat()};(OUT/"phase10_review_summary.json").write_text(json.dumps(summary,indent=2)+"\n");print(json.dumps(summary));return 0
if __name__=="__main__":raise SystemExit(main())
