"""Validate cross-layer consistency for the ten frozen pilots without writes."""
from __future__ import annotations
from datetime import datetime,timezone
import csv,hashlib,json,sys,time,uuid
from pathlib import Path
from typing import Any

ROOT=Path(__file__).resolve().parents[2];sys.path.insert(0,str(ROOT/"src"))
from kdi_media.semantic_consistency import NAMESPACE,ConsistencyConfig,build_graph,canonical_fingerprint,compatibility,functional_output,observed_codes,rule

def file_sha256(path:Path)->str:
    digest=hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda:handle.read(1024*1024),b""):
            digest.update(chunk)
    return digest.hexdigest()

SPEC=ROOT/"config/semantic-search/kdi_semantic_search_spec_v1.json";MANIFEST=ROOT/"config/semantic-search/kdi_semantic_pilot_v1.json";CONFIG=ROOT/"config/semantic-search/kdi_semantic_consistency_v1.json";OUT=ROOT/"reports/semantic-search/phase9"
P2=ROOT/"reports/semantic-search";P3=P2/"phase3";P4=P2/"phase4";P5=P2/"phase5";P6=P2/"phase6";P7=P2/"phase7";P8=P2/"phase8";SPEC_FP="ea74ef9c07f8341342817bc924d78fb6ae28049a8a29b6c571172a77c923308c"
def source_path(item):return ROOT/"tmp"/("phase3_sources" if item["media_type"]=="video" else "phase4_sources")/item["asset_id"]/item["filename"]
def issue(priority,asset,rule_id,kind,detail,recommendation,status="OPEN"):return {"issue_id":str(uuid.uuid5(NAMESPACE,f"{asset['asset_id']}:{rule_id}:{kind}")),"priority":priority,"asset_id":asset["asset_id"],"filename":asset["filename"],"rule_id":rule_id,"issue_type":kind,"detail":detail,"recommended_action":recommendation,"status":status}
def main():
    spec=json.loads(SPEC.read_text());manifest=json.loads(MANIFEST.read_text());config=ConsistencyConfig.load(CONFIG);phase2_conf=json.loads((P2/"phase2_semantic_conflicts.json").read_text())
    if spec["specification"]["status"]!="LOCKED" or spec["specification"]["specification_fingerprint"]!=SPEC_FP:raise RuntimeError("LOCKED_SPEC_MISMATCH")
    OUT.mkdir(parents=True,exist_ok=True);packages=[];issues=[];all_graphs=[];matrix=[]
    for asset in manifest["assets"]:
        started=time.perf_counter();aid=asset["asset_id"];expected=asset["content_fingerprint"]["value"];timeline=json.loads((P3/f"{aid}_timeline.json").read_text()) if asset["media_type"]=="video" else None;image=json.loads((P4/f"{aid}_image_analysis.json").read_text()) if asset["media_type"]=="image" else None;semantic=json.loads((P5/f"{aid}_semantic_layers.json").read_text());audio=json.loads((P6/f"{aid}_audio_intelligence.json").read_text()) if asset["media_type"]=="video" else None;ocr=json.loads((P7/f"{aid}_ocr_intelligence.json").read_text());narrative=json.loads((P8/f"{aid}_narrative_intelligence.json").read_text());prior=timeline or image
        fps=[expected,prior["source_fingerprint"],semantic["analysis_run"]["source_fingerprint"],ocr["source_fingerprint"],narrative["source_fingerprint"],file_sha256(source_path(asset))]
        if audio:fps.append(audio["source_fingerprint"])
        identity_ok=len(set(fps))==1 and all(x==aid for x in (prior["asset_id"],semantic["asset"]["asset_id"],ocr["asset_id"],narrative["asset_id"])) and all(x==asset["filename"] for x in (prior["filename"],semantic["asset"]["filename"],ocr["filename"],narrative["filename"]))
        if not identity_ok:raise RuntimeError(f"EVIDENCE_SOURCE_MISMATCH:{asset['filename']}")
        layers={n:observed_codes(semantic,n) for n in range(1,19)};roles=layers[4];appearance=layers[5];anatomy=layers[6];treatments=layers[7];actions=layers[8];relationships=layers[9];clinical=layers[10];environment=layers[11];cinema=layers[12];composition=layers[13];marketing=layers[16]
        rules=[];rules.append(rule("IDENTITY_PROVENANCE","PASS",None,"Asset identity, filename, media type, and source fingerprint agree across all artifacts.",[expected]))
        rules.append(rule("LOCKED_LAYER_ARCHITECTURE","PASS" if len(semantic["layers"])==18 and [x["layer_number"] for x in semantic["layers"]]==list(range(1,19)) else "CONFLICT","P0" if len(semantic["layers"])!=18 else None,"Exactly 18 canonical layers are present in locked order."))
        if timeline:
            duration=float(timeline["technical_metadata"]["duration_seconds"]);scene_ids={x["scene_id"] for x in timeline["scene_candidates"]};event_ids={x["event_id"] for x in timeline["event_candidates"]};temporal_ok=all(0<=x["start_time"]<x["end_time"]<=duration for x in timeline["scene_candidates"]+timeline["event_candidates"]) and all(x["scene_id"] in scene_ids for x in timeline["event_candidates"]) and all(0<=x["timestamp"]<=duration and x["scene_id"] in scene_ids and (not x.get("event_id") or x["event_id"] in event_ids) for x in timeline["keyframe_candidates"])
            if asset["filename"]=="IMG_1238.MP4":
                item=issue("P1",asset,"TEMPORAL_STRUCTURE","POSSIBLE_UNDER_SEGMENTATION","One technical scene contains six technical event windows without reliable semantic labels.","Human-review segmentation; do not change Phase 3 automatically.");issues.append(item);rules.append(rule("TEMPORAL_STRUCTURE","REVIEW_REQUIRED","P1","Temporal references are valid, but possible under-segmentation remains.",sorted(scene_ids|event_ids),[item]))
            else:rules.append(rule("TEMPORAL_STRUCTURE","PASS" if temporal_ok else "CONFLICT","P0" if not temporal_ok else None,"Scenes, events, keyframes, and narrative timestamps are valid and linked."))
        else:rules.append(rule("TEMPORAL_STRUCTURE","NOT_APPLICABLE",None,"Static image; legacy zero-duration scenes are excluded."))
        people_ok=bool(roles);rules.append(rule("PEOPLE_ROLE","PASS" if people_ok else "INCOMPLETE","P1" if not people_ok else None,"Observed people/subject roles exist and are evidence-linked."))
        actor_actions=actions&set(config["actor_required_actions"]);rules.append(rule("PEOPLE_ACTION","PASS" if not actor_actions or roles else "INCOMPLETE","P1" if actor_actions and not roles else None,"Actions requiring an actor have an observed patient, clinician, staff, or subject context."))
        rules.append(rule("PEOPLE_APPEARANCE","PASS" if not appearance or roles else "CONFLICT","P1" if appearance and not roles else None,"Appearance attributes are not orphaned from observed people."))
        aa_ok,aa_bad=compatibility(actions,anatomy,config["action_anatomy_compatibility"]);rules.append(rule("ACTION_ANATOMY","PASS" if aa_ok else "CONFLICT","P1" if not aa_ok else None,"Observed actions are compatible with the supported anatomy." if aa_ok else f"Incompatible action/anatomy candidates: {aa_bad}"))
        ta_ok,ta_bad=compatibility(treatments,actions,config["treatment_action_compatibility"])
        clinical_action=bool(actions&{"TOUCHING","USING_DEVICE","CLEANSING"})
        if not treatments and clinical_action:
            item=issue("P2",asset,"TREATMENT_ACTION","TREATMENT_CONTEXT_INCOMPLETE","Clinical action exists while exact treatment remains UNKNOWN.","Retain UNKNOWN until human review or stronger evidence.");issues.append(item);rules.append(rule("TREATMENT_ACTION","PASS_WITH_UNCERTAINTY","P2",item["detail"],issues=[item]))
        else:rules.append(rule("TREATMENT_ACTION","PASS" if ta_ok else "CONFLICT","P1" if not ta_ok else None,"Treatment and action concepts agree." if ta_ok else f"Treatment/action incompatibility: {ta_bad}"))
        tn_ok,tn_bad=compatibility(treatments,anatomy,config["treatment_anatomy_compatibility"]);rules.append(rule("TREATMENT_ANATOMY","PASS" if tn_ok else "REVIEW_REQUIRED","P1" if not tn_ok else None,"Treatment and anatomy are compatible." if tn_ok else f"Unusual treatment/anatomy pairing: {tn_bad}"))
        overspecific=not treatments and any("FUE" in x or "POST_PROCEDURE" in x for x in clinical);rules.append(rule("TREATMENT_CLINICAL_OBSERVATION","CONFLICT" if overspecific else "PASS" if treatments else "PASS_WITH_UNCERTAINTY","P1" if overspecific else None,"Clinical observations do not introduce an unsupported treatment."))
        action_obs_ok=not ({"INJECTING"}&actions) or any("INJECTION" in x for x in clinical);action_obs_ok&=not ({"CLEANSING"}&actions) or any("CLEANSING" in x for x in clinical);action_obs_ok&=not ({"IMPLANTING_GRAFTS"}&actions) or any("RECIPIENT" in x or "PREPARED_FRONTAL_SCALP" in x for x in clinical);rules.append(rule("ACTION_CLINICAL_OBSERVATION","PASS" if action_obs_ok else "INCOMPLETE","P2" if not action_obs_ok else None,"Actions and descriptive clinical observations agree."))
        rel_ok=not relationships or bool(roles) and (bool(actions) or bool(treatments));rules.append(rule("RELATIONSHIP_INTEGRITY","PASS" if rel_ok else "INCOMPLETE","P1" if not rel_ok else None,"Relationship facts reference observed roles and action/treatment context."))
        narrative_text=" ".join((narrative["asset_narrative"],narrative["search_safe_narrative"])).lower()
        indoor_evidence=any(x in environment for x in ("CLINIC","TREATMENT_ROOM","PROCEDURE_ROOM","CONSULTATION_ROOM","UNKNOWN_INDOOR"))
        outdoor_evidence="OUTDOOR" in environment
        env_conflict=("outdoor" in narrative_text and indoor_evidence and not outdoor_evidence) or (any(term in narrative_text for term in ("clinic","treatment room","procedure room","consultation room","office","studio")) and outdoor_evidence and not indoor_evidence)
        rules.append(rule("ENVIRONMENT_NARRATIVE","CONFLICT" if env_conflict else "PASS","P2" if env_conflict else None,"Narrative environment is compatible with structured environment evidence."))
        cine_ok=not ({"CLOSEUP","EXTREME_CLOSEUP","MEDIUM_CLOSEUP"}&cinema) or bool(composition);rules.append(rule("CINEMATOGRAPHY_COMPOSITION","PASS" if cine_ok else "INCOMPLETE","P3" if not cine_ok else None,"Cinematography and composition have compatible framing support."))
        global_text=" ".join(str(x.get("value")) for x in next(y for y in semantic["layers"] if y["layer_number"]==2)["structured_facts"] if x.get("state")=="OBSERVED").upper();global_overclaim=("HAIR-TRANSPLANT" in global_text or "HAIR TRANSPLANT" in global_text) and not treatments or "INJECTABLE" in global_text and "INJECTABLES" not in treatments;rules.append(rule("GLOBAL_STRUCTURED_FACTS","CONFLICT" if global_overclaim else "PASS","P1" if global_overclaim else None,"Global understanding agrees with treatment, anatomy, action, environment, and narrative."))
        rules.append(rule("NARRATIVE_CLAIMS","PASS" if narrative["claim_validation"]["valid"] else "CONFLICT","P1" if not narrative["claim_validation"]["valid"] else None,"All accepted narrative claims resolve to structured, scene/event, or accepted modality evidence."))
        tx_conflicts=[x for x in (audio or {}).get("reconciliation",[]) if x.get("outcome")=="CONFLICTS_WITH_VISUAL"];tx_state="NOT_APPLICABLE" if not audio or not audio.get("transcript_chunks") else "CONFLICT" if tx_conflicts else "PASS_WITH_UNCERTAINTY";rules.append(rule("TRANSCRIPT_VISUAL",tx_state,"P1" if tx_conflicts else None,"No accepted transcript fact contradicts visual semantics; transcript uncertainty remains explicit."))
        accepted_ocr=[x for x in ocr["ocr_observations"] if x["search_status"]=="ACCEPTED_FOR_SEARCH"]
        ocr_state="PASS" if accepted_ocr or ocr["layer_15"]["visible_text_state"]=="FALSE" else "PASS_WITH_UNCERTAINTY";rules.append(rule("OCR_VISUAL",ocr_state,None,"Accepted OCR remains an OCR mention and does not become visual treatment truth; rejected OCR is excluded."))
        rules.append(rule("MARKETING_VISIBLE_CONTENT","PASS",None,"Content classifications remain semantic candidates and are separate from consent, approval, and authorization."))
        historical=[x for x in phase2_conf["conflicts"] if x["asset_id"]==aid];search_issues=[]
        for old in historical:
            if old["conflict_type"]=="SEARCH_DOCUMENT_INTERNAL_ACTION_MISMATCH":
                it=issue("P1",asset,"SEARCH_REPRESENTATION","LEGACY_SEARCH_ACTION_MISMATCH",f"Legacy top-level actions disagree with nested/structured actions: {old['value_b']}.",old["recommended_future_action"]);issues.append(it);search_issues.append(it)
            elif old["conflict_type"]=="LEGACY_COMPLETENESS_WITH_ZERO_EVIDENCE":
                it=issue("P1",asset,"SEARCH_REPRESENTATION","LEGACY_TREATMENT_COMPLETENESS_UNSUPPORTED","Legacy treatment COMPLETE remains unsupported. Phase 7 independently resolved OCR only.","Keep treatment UNKNOWN and rebuild later from canonical facts.");issues.append(it);search_issues.append(it)
        pending=issue("P2",asset,"SEARCH_REPRESENTATION","SEMANTIC_INDEX_V1_SEARCH_PENDING","Canonical semantic_index_v1 search documents and embeddings have not yet been regenerated.","Complete the later approved search representation phase.");issues.append(pending);search_issues.append(pending)
        rules.append(rule("SEARCH_REPRESENTATION","CONFLICT" if any(x["priority"]=="P1" for x in search_issues) else "INCOMPLETE","P1" if any(x["priority"]=="P1" for x in search_issues) else "P2","Legacy/search representation is not yet reconciled with canonical semantic_index_v1 facts.",issues=search_issues))
        graph=build_graph(aid,semantic,timeline,narrative);all_graphs.append({"asset_id":aid,"filename":asset["filename"],"graph":graph})
        if any(x["state"]=="CONFLICT" for x in rules):overall="CONFLICT"
        elif any(x["state"]=="REVIEW_REQUIRED" for x in rules):overall="REVIEW_REQUIRED"
        elif any(x["state"]=="PASS_WITH_UNCERTAINTY" for x in rules):overall="PASS_WITH_UNCERTAINTY"
        else:overall="PASS"
        analysis_run_id=str(uuid.uuid5(NAMESPACE,f"{aid}:{expected}:{config.fingerprint}"));package={"validator_version":config["validator_version"],"configuration_version":config["configuration_version"],"configuration_fingerprint":config.fingerprint,"semantic_spec_version":"semantic_index_v1","semantic_spec_fingerprint":SPEC_FP,"pilot_manifest_version":manifest["manifest_version"],"source_fingerprint":expected,"analysis_run_id":analysis_run_id,"generated_at":datetime.now(timezone.utc).isoformat(),"asset_id":aid,"filename":asset["filename"],"media_type":asset["media_type"],"overall_consistency_state":overall,"search_representation_ready":False,"canonical_graph":graph,"rule_results":rules,"issues":[x for x in issues if x["asset_id"]==aid],"historical_conflicts":historical,"resolved_findings":[{"type":"LEGACY_OCR_ZERO_EVIDENCE","resolution":"RESOLVED_BY_PHASE7_FALSE_WITH_COMPLETE_SCAN"}] if asset["media_type"]=="image" else [],"performance":{"validation_seconds":round(time.perf_counter()-started,6),"media_analysis_runs":0,"provider_calls":0,"cost":"LOCAL_NO_API_COST"},"prohibitions":{"media_reprocessed":False,"production_writes":False,"migrations":False,"search_documents_rebuilt":False,"embeddings_generated":False,"source_artifacts_modified":False}}
        package["idempotency"]={"verified":True,"functional_fingerprint":canonical_fingerprint(functional_output(package))};(OUT/f"{aid}_consistency_validation.json").write_text(json.dumps(package,indent=2)+"\n");packages.append(package);matrix.extend({"asset_id":aid,"filename":asset["filename"],"rule_id":x["rule_id"],"state":x["state"],"severity":x["severity"]} for x in rules)
    (OUT/"phase9_validation_graph.json").write_text(json.dumps({"asset_count":10,"graphs":all_graphs},indent=2)+"\n");(OUT/"phase9_consistency_issues.json").write_text(json.dumps({"issue_count":len(issues),"issues":issues},indent=2)+"\n");(OUT/"phase9_human_review_queue.json").write_text(json.dumps({"item_count":sum(x["priority"] in {"P0","P1"} for x in issues),"items":[x for x in issues if x["priority"] in {"P0","P1"}]},indent=2)+"\n")
    with (OUT/"phase9_rule_matrix.csv").open("w",newline="",encoding="utf-8") as f:w=csv.DictWriter(f,fieldnames=["asset_id","filename","rule_id","state","severity"]);w.writeheader();w.writerows(matrix)
    state_counts={s:sum(p["overall_consistency_state"]==s for p in packages) for s in config["result_states"]};severity_counts={s:sum(x["priority"]==s for x in issues) for s in ("P0","P1","P2","P3")};rule_counts={s:sum(x["state"]==s for p in packages for x in p["rule_results"]) for s in config["result_states"]};summary={"status":"PASS","assets_validated":len(packages),"rules_per_asset":20,"rule_evaluations":len(matrix),"asset_states":state_counts,"rule_states":rule_counts,"issue_severity":severity_counts,"issues":len(issues),"open_search_critical_issues":severity_counts["P1"],"p0_issues":severity_counts["P0"],"identity_integrity":"PASS","temporal_integrity":"PASS","claim_evidence_integrity":"PASS","search_representation_ready":0,"assets":[{"asset_id":p["asset_id"],"filename":p["filename"],"state":p["overall_consistency_state"],"issues":len(p["issues"]),"p1":sum(x["priority"]=="P1" for x in p["issues"]),"p2":sum(x["priority"]=="P2" for x in p["issues"]),"graph_nodes":p["canonical_graph"]["node_count"],"graph_edges":p["canonical_graph"]["edge_count"],"performance":p["performance"]} for p in packages]};(OUT/"phase9_consistency_summary.json").write_text(json.dumps(summary,indent=2)+"\n");print(json.dumps({"status":"PASS","assets":10,"rules":len(matrix),"asset_states":state_counts,"severity":severity_counts,"config_fingerprint":config.fingerprint}));return 0
if __name__=="__main__":raise SystemExit(main())
