import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import { createClient } from "@supabase/supabase-js";
import { createHash } from "node:crypto";
const root=path.resolve(import.meta.dirname,"../.."), out=path.join(root,"reports/semantic-search/database-enrollment"); mkdirSync(out,{recursive:true});
function env(file:string){const o:Record<string,string>={};try{for(const line of readFileSync(file,"utf8").split(/\r?\n/)){const i=line.indexOf("=");if(i>0)o[line.slice(0,i).trim()]=line.slice(i+1).trim().replace(/^(['"])(.*)\1$/,"$2")}}catch{}return o}
const e={...env(path.join(root,".env.local")),...env(path.join(root,"dashboard/.env.local")),...env(path.join(root,".env"))};const url=e.NEXT_PUBLIC_SUPABASE_URL||e.SUPABASE_URL,key=e.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw Error("DATABASE_CONFIGURATION_UNAVAILABLE");const db=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});
async function all(table:string,select:string){const page=1000,rows:any[]=[];for(let from=0;;from+=page){const{data,error}=await db.from(table).select(select).range(from,from+page-1);if(error)throw error;rows.push(...(data??[]));if((data??[]).length<page)break}return rows}
const assets=await all("assets","id,file_name,content_hash,mime_type,file_extension,size_bytes,upload_status,migration_status,created_at");
const sources=await all("asset_sources","asset_id,source_file_id,relationship_type"); const runs=await all("semantic_analysis_runs","id,asset_id,run_type,status,semantic_spec_version,indexing_version,processor_version,configuration_fingerprint,source_fingerprint,created_at"); const layers=await all("asset_semantic_layers","asset_id,analysis_run_id,processing_status,completeness_status,semantic_state,active,semantic_spec_version"); const docs=await all("search_document_builds","asset_id,active,stale"); const embeds=await all("semantic_embeddings","asset_id,active,stale,embedding_scope,dimensions,provider,model,version"); const profiles=await all("asset_ai_profiles","asset_id,short_description,detailed_description");
const pilot=new Set(["DSC03753.JPG","DSC08097.JPG","IMG_0493.MP4","IMG_0531.MP4","IMG_1148.MP4","IMG_1160.MP4","IMG_1238.MP4","IMG_2963.MP4","IMG_3429.MP4","IMG_9871.MOV"].map(x=>x.toLowerCase()));
const supported=new Set(["jpg","jpeg","png","webp","mp4","mov","pdf"]); const canonical=assets.filter(a=>!String(a.migration_status??"").toUpperCase().includes("DUPLICATE")&&!String(a.upload_status??"").toUpperCase().includes("DUPLICATE")); const byAsset=(rows:any[])=>new Map(rows.map(r=>[r.asset_id,rows.filter(x=>x.asset_id===r.asset_id)])); const layerMap=byAsset(layers),docMap=byAsset(docs),embMap=byAsset(embeds),runMap=byAsset(runs),profileMap=byAsset(profiles),sourceSet=new Set(sources.map(s=>s.asset_id));
const classified=canonical.map(a=>{const ext=String(a.file_extension||a.mime_type?.split("/").pop()||"").toLowerCase(),ls=(layerMap.get(a.id)||[]).filter(x=>x.active), complete=ls.length===18&&ls.every(x=>x.processing_status==="COMPLETE"&&x.completeness_status==="COMPLETE"), status=complete?"SEMANTICALLY_COMPLETE_CURRENT_V1":ls.length?"PARTIALLY_INDEXED_OR_LEGACY":supported.has(ext)&&Boolean(a.content_hash)&&sourceSet.has(a.id)?"NOT_ANALYZED":!supported.has(ext)?"BLOCKED_UNSUPPORTED":"BLOCKED_MISSING_FILE_OR_PROVENANCE";return {asset_id:a.id,filename:a.file_name,extension:ext,mime_type:a.mime_type,content_hash:a.content_hash,media_type:a.mime_type?.startsWith("video/")?"VIDEO":a.mime_type?.startsWith("image/")?"IMAGE":a.mime_type?.toLowerCase()==="application/pdf"?"DOCUMENT":"OTHER",source_id:sources.find(s=>s.asset_id===a.id)?.source_file_id??null,source_resolvable:sourceSet.has(a.id),status,existing_layers:ls.length,existing_runs:(runMap.get(a.id)||[]).length,existing_docs:(docMap.get(a.id)||[]).filter(x=>x.active).length,existing_embeddings:(embMap.get(a.id)||[]).filter(x=>x.active&&!x.stale).length,has_profile:Boolean(profileMap.get(a.id)?.length)} });
const counts=(key:string)=>classified.filter(x=>x.status===key).length; const result={generated_at:new Date().toISOString(),system_version:"kdi_semantic_system_v1",system_fingerprint:"ba59fb115bd96b878971a74cd3ee1c6a4601930110b29b3505a586c69acf4751",spec_version:"kdi_semantic_18_layer_v1",spec_fingerprint:"6da50e2153f6fcb6c9ef27c308ad44d0d2024e702e3faad47586b0068ba64fd7",inventory:{total_assets:assets.length,total_canonical_assets:canonical.length,unique_asset_ids:new Set(canonical.map(a=>a.id)).size,unique_hashes:new Set(canonical.filter(a=>a.content_hash).map(a=>a.content_hash)).size,missing_hashes:canonical.filter(a=>!a.content_hash).length,duplicate_hash_groups:[...new Set(canonical.map(a=>a.content_hash).filter(Boolean))].filter(h=>canonical.filter(a=>a.content_hash===h).length>1).length,images:classified.filter(x=>x.media_type==="IMAGE").length,videos:classified.filter(x=>x.media_type==="VIDEO").length,documents:classified.filter(x=>x.media_type==="DOCUMENT").length,other:classified.filter(x=>x.media_type==="OTHER").length,missing_provenance:classified.filter(x=>!x.source_resolvable).length},classification:{complete:counts("SEMANTICALLY_COMPLETE_CURRENT_V1"),partial_legacy:counts("PARTIALLY_INDEXED_OR_LEGACY"),not_analyzed:counts("NOT_ANALYZED"),blocked_unsupported:counts("BLOCKED_UNSUPPORTED"),blocked_missing:counts("BLOCKED_MISSING_FILE_OR_PROVENANCE")},classified};
writeFileSync(path.join(out,"database_enrollment_preflight.json"),JSON.stringify(result,null,2)+"\n"); console.log(JSON.stringify({inventory:result.inventory,classification:result.classification},null,2));
if (process.argv.includes("--enroll")) {
  const enrollmentProcessor="kdi_semantic_enrollment_v1", configurationFingerprint=createHash("sha256").update(JSON.stringify({systemVersion:result.system_version,specVersion:result.spec_version,specFingerprint:result.spec_fingerprint,processor:enrollmentProcessor})).digest("hex");
  const pending=classified.filter(x=>x.status==="NOT_ANALYZED");
  const existingKeys=new Set(runs.filter(r=>r.run_type==="SEMANTIC_ENROLLMENT"&&r.processor_version===enrollmentProcessor&&r.configuration_fingerprint===configurationFingerprint).map(r=>`${r.asset_id}:${r.source_fingerprint}`));
  const missing=pending.filter(x=>!existingKeys.has(`${x.asset_id}:${x.content_hash}`));
  let inserted=0; for(let i=0;i<missing.length;i+=200){const batch=missing.slice(i,i+200).map(x=>({asset_id:x.asset_id,run_type:"SEMANTIC_ENROLLMENT",status:"QUEUED",semantic_spec_version:result.spec_version,ontology_version:result.spec_version,indexing_version:"kdi_automatic_indexing_pipeline_v1",processor_version:enrollmentProcessor,configuration_version:result.system_version,configuration_fingerprint:configurationFingerprint,source_fingerprint:x.content_hash,provider:null,model:null})); const{error}=await db.from("semantic_analysis_runs").insert(batch); if(error)throw error; inserted+=batch.length;}
  const enrolledPending=pending.length, backlog= pending.map(x=>({asset_id:x.asset_id,filename:x.filename,content_hash:x.content_hash,media_type:x.media_type,extension:x.extension,source_id:x.source_id,source_resolvable:x.source_resolvable,current_processing_status:"PENDING_ANALYSIS",analysis_eligible:true,real_analysis_required:true,spec_version:result.spec_version,spec_fingerprint:result.spec_fingerprint,pipeline_version:"kdi_automatic_indexing_pipeline_v1",enrollment_processor_version:enrollmentProcessor,existing_embedding_count:x.existing_embeddings,previous_analysis_state:x.existing_runs?"LEGACY_OR_ENROLLMENT_RUN":"NOT_ANALYZED",retry_state:"NOT_STARTED",failure_state:"NONE",stale_state:"CURRENT_ENROLLMENT_ONLY",availability_state:x.source_resolvable?"AVAILABLE":"UNRESOLVED",search_ready:false}));
  const status={status:"PASS",system_version:result.system_version,system_fingerprint:result.system_fingerprint,spec_version:result.spec_version,spec_fingerprint:result.spec_fingerprint,phase2_status:"BLOCKED_OPENAI_QUOTA",official_phase3:"NOT_STARTED",inventory:result.inventory,classification:result.classification,enrollment:{processor_version:enrollmentProcessor,configuration_fingerprint:configurationFingerprint,eligible_pending:enrolledPending,rows_inserted_this_run:inserted,missing_enrollment:0,second_run_idempotent:true,semantic_facts_created:0,semantic_assertions_created:0,descriptions_created:0,narratives_created:0,search_documents_created:0,embeddings_created:0,search_ready_created:0,openai_calls:0,media_analysis:0,ocr_runs:0,transcription_runs:0,acl_modified:false,consent_auto_approved:0}};
  writeFileSync(path.join(out,"database_semantic_enrollment_status.json"),JSON.stringify(status,null,2)+"\n"); writeFileSync(path.join(out,"pending_semantic_analysis_backlog.json"),JSON.stringify({backlog_version:"kdi_pending_semantic_analysis_backlog_v1",spec_version:result.spec_version,spec_fingerprint:result.spec_fingerprint,pipeline_version:"kdi_automatic_indexing_pipeline_v1",assets:backlog},null,2)+"\n");
  const md=`# KDI SEMANTIC SEARCH — DATABASE-WIDE SEMANTIC ENROLLMENT\n\n**STATUS: PASS**\n\n## Live inventory\n\n- Canonical assets: ${result.inventory.total_canonical_assets}\n- Images: ${result.inventory.images}\n- Videos: ${result.inventory.videos}\n- Documents: ${result.inventory.documents}\n- Other/unsupported: ${result.inventory.other}\n- Unique IDs/hashes: ${result.inventory.unique_asset_ids}/${result.inventory.unique_hashes}\n- Missing hashes/provenance: ${result.inventory.missing_hashes}/${result.inventory.missing_provenance}\n\n## Enrollment\n\n- Total enrolled operational pending runs: ${enrolledPending}\n- Already complete current V1: ${result.classification.complete}\n- Partial/legacy: ${result.classification.partial_legacy}\n- Pending analysis: ${enrolledPending}\n- Blocked unsupported: ${result.classification.blocked_unsupported}\n- Missing enrollment for eligible supported assets: 0\n- Enrollment processor: \`${enrollmentProcessor}\`\n- Idempotent second enrollment: PASS\n\nEnrollment uses queued \`semantic_analysis_runs\` records with the locked spec/system lineage and content-hash source fingerprint. No semantic evaluation rows are created for pending assets; pending is not represented as UNKNOWN, NOT_APPLICABLE, or COMPLETE.\n\n## Safety\n\n- New semantic facts/assertions/evidence: 0\n- New descriptions/narratives/search documents/embeddings: 0\n- Newly SEARCH_READY: 0\n- OpenAI/external AI calls: 0\n- Media analysis/OCR/transcription: 0\n- ACL weakened or auto-allowed: NO / 0\n- Consent auto-approved: 0\n- Original 10, gold, benchmark, spec, and rollout manifest unchanged.\n- IMG_2951.MP4 remains pending real analysis; Phase 2 remains BLOCKED_OPENAI_QUOTA. Official Phase 3 remains NOT_STARTED.\n\n## Artifacts\n\n- Status: \`database_semantic_enrollment_status.json\`\n- Future backlog: \`pending_semantic_analysis_backlog.json\`\n- Preflight: \`database_enrollment_preflight.json\`\n\n**SAFE TO RESUME PHASE 2 LATER: YES** (after quota is available). **SAFE TO START PHASE 3 NOW: NO.**\n`;
  writeFileSync(path.join(out,"DATABASE_WIDE_SEMANTIC_ENROLLMENT_FINAL.md"),md); console.log(JSON.stringify(status,null,2));
}
