import { randomBytes } from "node:crypto";
import { readFileSync } from "node:fs";
import { createClient, type Session } from "@supabase/supabase-js";

function env(path:string){try{return Object.fromEntries(readFileSync(path,"utf8").replace(/^\uFEFF/,"").split(/\r?\n/).flatMap(line=>{const match=line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);return match?[[match[1],match[2].trim().replace(/^(['"])(.*)\1$/, "$2")]]:[]}))}catch{return{}}}
const e={...env("../.env.local"),...env(".env.local")},url=e.NEXT_PUBLIC_SUPABASE_URL,key=e.NEXT_PUBLIC_SUPABASE_ANON_KEY,serviceKey=e.SUPABASE_SERVICE_ROLE_KEY,base=(process.env.KDI_BASE_URL||"http://127.0.0.1:3001").replace(/\/$/,"");
if(!url||!key||!serviceKey)throw new Error("Acceptance configuration unavailable");
const service=createClient(url,serviceKey,{auth:{persistSession:false,autoRefreshToken:false}}),ref=new URL(url).hostname.split(".")[0],run=Date.now(),createdIds:string[]=[],createdEmails:string[]=[],result:Record<string,string>={};
function assert(value:unknown,label:string){if(!value)throw new Error(`Acceptance failed: ${label}`);result[label]="PASS"}
function alias(email:string,label:string){const at=email.lastIndexOf("@");return`${email.slice(0,at)}+kdi-${label}-${run}${email.slice(at)}`.toLowerCase()}
function cookie(session:Session){const raw=`base64-${Buffer.from(JSON.stringify(session)).toString("base64url")}`,name=`sb-${ref}-auth-token`,parts=[];for(let i=0;i<raw.length;i+=3180)parts.push(`${name}.${parts.length}=${raw.slice(i,i+3180)}`);return parts.join("; ")}
async function request(path:string,options:RequestInit={},session?:Session){return fetch(`${base}${path}`,{...options,redirect:"manual",headers:{Origin:base,...(session?{Cookie:cookie(session)}:{}),...options.headers}})}
async function magicSession(email:string){const generated=await service.auth.admin.generateLink({type:"magiclink",email}),hash=generated.data.properties?.hashed_token;if(generated.error||!hash)throw generated.error??new Error("Magic link generation failed");const auth=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}),verified=await auth.auth.verifyOtp({token_hash:hash,type:"magiclink"});if(verified.error||!verified.data.session)throw verified.error??new Error("Session verification failed");return verified.data.session}
async function setupLink(owner:Session,email:string,role:"admin"|"user"){const response=await request("/api/admin/users/setup-link",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,role})},owner),body=await response.json();assert(response.status===201&&typeof body.setupUrl==="string",`super_admin_setup_link_${role}`);const parsed=new URL(body.setupUrl);if(parsed.origin!==base||parsed.pathname!=="/auth/confirm")throw new Error(`Acceptance failed: ${role}_link_local_origin (${parsed.origin}${parsed.pathname})`);result[`${role}_link_local_origin`]="PASS";const hash=parsed.searchParams.get("token_hash");assert(hash&&!body.setupUrl.includes("service_role"),`${role}_link_provider_token`);const auth=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}),verified=await auth.auth.verifyOtp({token_hash:hash!,type:"invite"});if(verified.error||!verified.data.session)throw verified.error??new Error("Invitation token verification failed");createdIds.push(verified.data.user!.id);return{auth,session:verified.data.session,id:verified.data.user!.id}}
async function finishSetup(linked:{auth:any;session:Session},password:string){const changed=await linked.auth.auth.updateUser({password});if(changed.error)throw changed.error;const response=await request("/api/auth/accept-invitation",{method:"POST",headers:{"Content-Type":"application/json"}},linked.session);assert(response.status===200,"password_setup_and_activation");return linked.session}
async function invite(actor:Session,email:string,role:string){const response=await request("/api/admin/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,role})},actor);return{response,body:await response.json()}}

try{
  const{data:owner,error}=await service.from("app_users").select("user_id,email,management_role,is_active").eq("management_role","super_admin").single();if(error||!owner?.is_active)throw error??new Error("Owner unavailable");
  const ownerSession=await magicSession(owner.email),adminEmail=alias(owner.email,"admin-link"),userEmail=alias(owner.email,"user-link"),adminInviteEmail=alias(owner.email,"admin-user-email"),password=`Kdi!${randomBytes(15).toString("base64url")}`;createdEmails.push(adminEmail,userEmail,adminInviteEmail);
  const adminLinked=await setupLink(ownerSession,adminEmail,"admin");
  const{data:adminPending}=await service.from("app_users").select("management_role,is_active").eq("user_id",adminLinked.id).single();assert(adminPending?.management_role==="admin"&&!adminPending.is_active,"admin_role_fixed_before_setup");
  const adminSession=await finishSetup(adminLinked,password);
  const passwordLogin=await request("/api/auth/password-login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:adminEmail,password,remember:true})});assert(passwordLogin.status===200,"invited_admin_password_login");
  const{data:activeAdmin}=await service.from("app_users").select("management_role,is_active").eq("user_id",adminLinked.id).single();assert(activeAdmin?.management_role==="admin"&&activeAdmin.is_active,"invited_admin_active_role");
  assert((await request("/admin/users",{},adminSession)).status===200,"invited_admin_panel");assert((await request("/admin/upload",{},adminSession)).status===200,"invited_admin_upload");
  assert((await invite(adminSession,alias(owner.email,"forbidden-admin"),"admin")).response.status===403,"admin_invite_admin_denied");assert((await invite(adminSession,alias(owner.email,"forbidden-super"),"super_admin")).response.status===403,"admin_invite_super_admin_denied");
  assert((await request(`/api/admin/users/${owner.user_id}/status`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({active:false})},adminSession)).status===403,"admin_modify_super_admin_denied");
  const adminUserAttempt=await invite(adminSession,adminInviteEmail,"user");result.admin_to_user_email_api=adminUserAttempt.response.status===201?"PASS":`EMAIL_BLOCKED_${adminUserAttempt.response.status}`;
  if(adminUserAttempt.response.status===201){const list=await service.auth.admin.listUsers({page:1,perPage:1000}),identity=list.data.users.find(item=>item.email===adminInviteEmail);if(identity)createdIds.push(identity.id)}
  const userLinked=await setupLink(ownerSession,userEmail,"user"),userSession=await finishSetup(userLinked,`Kdi!${randomBytes(15).toString("base64url")}`);
  assert((await request("/library",{},userSession)).status===200,"user_library");assert((await request("/admin/users",{},userSession)).status===307,"user_admin_denied");assert((await request("/admin/upload",{},userSession)).status===307,"user_upload_denied");
  const{data:acceptedInvite}=await service.from("user_invitations").select("status").eq("email",adminEmail).single();assert(acceptedInvite?.status==="accepted","accepted_invitation_status");
  const forgot=await request("/api/auth/forgot-password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:adminEmail})});assert(forgot.status===200,"forgot_password_privacy_response");
  const recovery=await service.auth.admin.generateLink({type:"recovery",email:adminEmail}),recoveryHash=recovery.data.properties?.hashed_token;assert(!recovery.error&&recoveryHash,"recovery_link_generated");const recoveryAuth=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}),recovered=await recoveryAuth.auth.verifyOtp({token_hash:recoveryHash!,type:"recovery"});assert(!recovered.error&&recovered.data.session,"recovery_token_valid");const newPassword=`Kdi!${randomBytes(15).toString("base64url")}`,updated=await recoveryAuth.auth.updateUser({password:newPassword});assert(!updated.error,"password_reset");const newLogin=await request("/api/auth/password-login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:adminEmail,password:newPassword,remember:true})});assert(newLogin.status===200,"login_after_password_reset");
  const{data:ownerAfter}=await service.from("app_users").select("management_role,is_active").eq("user_id",owner.user_id).single();assert(ownerAfter?.management_role==="super_admin"&&ownerAfter.is_active,"super_admin_preserved");
  console.log(JSON.stringify(result,null,2));
}finally{
  for(const id of [...new Set(createdIds)].reverse())await service.auth.admin.deleteUser(id).catch(()=>undefined);
  if(createdEmails.length){await service.from("user_invitations").delete().in("email",createdEmails);await service.from("user_management_audit").delete().in("target_email",createdEmails)}
}
