import"server-only";
import nextEnv from"@next/env";
import{classifyMedia}from"../app/lib/library/classification";
nextEnv.loadEnvConfig(process.cwd());
const{createServiceClient}=await import("../app/lib/supabase/service");
const client=createServiceClient();
type Row=Record<string,unknown>;
async function all(table:string,select:string){const output:Row[]=[];for(let from=0;;from+=1000){const{data,error}=await client.from(table).select(select).range(from,from+999).order("id");if(error)throw new Error("library_reconciliation_unavailable");output.push(...(data as unknown as Row[]));if((data?.length??0)<1000)break}return output}
try{const[folders,files,assets,links,destinations]=await Promise.all([all("source_folders","id"),all("source_files","id,source_folder_id,mime_type,file_extension,decision"),all("assets","id,mime_type,file_extension"),all("asset_sources","asset_id,source_file_id"),all("asset_destinations","asset_id,upload_status,destination_google_file_id")]);const assetIds=new Set(assets.map(x=>String(x.id))),sourceIds=new Set(files.map(x=>String(x.id))),verified=destinations.filter(x=>x.upload_status==="VERIFIED"),linkedAssets=new Set(links.map(x=>String(x.asset_id))),linkedSources=new Set(links.map(x=>String(x.source_file_id))),categories={image:0,video:0,document:0,other:0};for(const asset of assets)categories[classifyMedia(asset.mime_type as string|null,asset.file_extension as string|null)]++;const assetById=new Map(assets.map(x=>[String(x.id),x])),sourceById=new Map(files.map(x=>[String(x.id),x])),folderIndex=new Map(folders.map((x,i)=>[String(x.id),`SOURCE_${i+1}`])),sourceCounts=new Map<string,{total:number;image:number;video:number;document:number;other:number}>();for(const link of links){const source=sourceById.get(String(link.source_file_id)),asset=assetById.get(String(link.asset_id));if(!source||!asset)continue;const label=folderIndex.get(String(source.source_folder_id))??"SOURCE_UNKNOWN",entry=sourceCounts.get(label)??{total:0,image:0,video:0,document:0,other:0},category=classifyMedia(asset.mime_type as string|null,asset.file_extension as string|null);entry.total++;entry[category]++;sourceCounts.set(label,entry)}const duplicateDestinations=verified.length-new Set(verified.map(x=>String(x.destination_google_file_id))).size;const checks={global_asset_ids_unique:assetIds.size===assets.length,all_assets_have_source:assets.every(x=>linkedAssets.has(String(x.id))),all_linked_sources_exist:[...linkedSources].every(id=>sourceIds.has(id)),verified_assets_have_destination:verified.every(x=>Boolean(x.destination_google_file_id)),duplicate_destination_identities:duplicateDestinations};console.log(`registered_source_folders=${folders.length}`);console.log(`source_files=${files.length}`);console.log(`canonical_assets=${assets.length}`);console.log(`asset_sources=${links.length}`);console.log(`verified_destinations=${verified.length}`);console.log(`excluded_records=${files.filter(x=>x.decision==="SKIP").length}`);for(const[k,v]of Object.entries(categories))console.log(`category_${k}=${v}`);for(const[label,value]of[...sourceCounts].sort())console.log(`${label}=${JSON.stringify(value)}`);for(const[k,v]of Object.entries(checks))console.log(`${k}=${v}`);if(Object.values(checks).some(v=>v===false)||duplicateDestinations!==0)throw new Error("library_reconciliation_failed");console.log("LIVE_LIBRARY_RECONCILIATION_PASSED")}catch(error){console.error(error instanceof Error&&error.message.startsWith("library_reconciliation")?error.message:"library_reconciliation_unavailable");process.exitCode=1}
