import { performance } from "node:perf_hooks";import { readFileSync } from "node:fs";import path from "node:path";
function envFile(file:string){try{return Object.fromEntries(readFileSync(file,"utf8").replace(/^\uFEFF/,"").split(/\r?\n/).flatMap(line=>{const m=line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);return m?[[m[1],m[2].trim().replace(/^(['"])(.*)\1$/,"$2")]]:[]}))}catch{return {}}}
const root=path.resolve(process.cwd(),'..'),l=envFile(path.join(process.cwd(),'.env.local')),p=envFile(path.join(root,'.env.local')),url=l.NEXT_PUBLIC_SUPABASE_URL||p.NEXT_PUBLIC_SUPABASE_URL,token=[p.SUPABASE_DASHBOARD_ACCESS_TOKEN,l.SUPABASE_DASHBOARD_ACCESS_TOKEN].find(v=>v?.startsWith('sbp_'));if(!url||!token)throw new Error('configuration unavailable');const ref=new URL(url).hostname.split('.')[0];
const query=`set statement_timeout='120s';
create temp table scale_assets(id uuid primary key,ordinal int not null);
insert into scale_assets select md5('asset-'||g)::uuid,g from generate_series(1,1000)g;
create temp table scale_layers(asset_id uuid not null,layer_id text not null,semantic_state text not null,human_review_status text not null,primary key(asset_id,layer_id));
insert into scale_layers select a.id,'L'||l,'UNKNOWN','PENDING' from scale_assets a cross join generate_series(1,18)l;
create temp table scale_assertions(id bigint generated always as identity primary key,asset_id uuid not null,layer_id text not null,canonical_concept_code text,semantic_state text not null,search_critical boolean not null,approved boolean not null default false);
insert into scale_assertions(asset_id,layer_id,canonical_concept_code,semantic_state,search_critical) select a.id,'L'||((g-1)%18+1),case when g%5=0 then 'HAIR_TRANSPLANT' else 'CONCEPT_'||(g%250) end,case when g%7=0 then 'UNKNOWN' else 'OBSERVED' end,g%3=0 from scale_assets a cross join generate_series(1,100)g;
create temp table scale_evidence(id bigint generated always as identity primary key,assertion_id bigint not null,asset_id uuid not null,evidence_type text not null);
insert into scale_evidence(assertion_id,asset_id,evidence_type) select id,asset_id,case when id%2=0 then 'KEYFRAME_LEVEL' else 'ASSET_LEVEL' end from scale_assertions;
create temp table scale_gold(asset_id uuid not null,layer_id text not null,canonical_concept_code text not null,primary key(asset_id,layer_id));
insert into scale_gold select id,'L7','HAIR_TRANSPLANT' from scale_assets where ordinal%20=0;
create index scale_assertions_asset_idx on scale_assertions(asset_id,layer_id);create index scale_assertions_concept_idx on scale_assertions(canonical_concept_code);create index scale_assertions_search_idx on scale_assertions(search_critical,semantic_state);create index scale_layers_layer_idx on scale_layers(layer_id,semantic_state);create index scale_evidence_asset_idx on scale_evidence(asset_id,assertion_id);analyze scale_assets;analyze scale_layers;analyze scale_assertions;analyze scale_evidence;analyze scale_gold;
create temp table scale_timings(test text,elapsed_ms double precision);
do $$declare i int;t timestamptz;a uuid;begin select id into a from scale_assets where ordinal=500;for i in 1..50 loop
 t:=clock_timestamp();perform count(*) from scale_assertions where asset_id=a;insert into scale_timings values('asset_semantic_lookup',extract(epoch from clock_timestamp()-t)*1000);
 t:=clock_timestamp();perform count(*) from scale_assertions where canonical_concept_code='HAIR_TRANSPLANT';insert into scale_timings values('canonical_concept_lookup',extract(epoch from clock_timestamp()-t)*1000);
 t:=clock_timestamp();perform count(*) from scale_layers where layer_id='L7' and semantic_state='UNKNOWN';insert into scale_timings values('layer_lookup',extract(epoch from clock_timestamp()-t)*1000);
 t:=clock_timestamp();perform count(*) from scale_assertions where search_critical and semantic_state='OBSERVED';insert into scale_timings values('search_critical_lookup',extract(epoch from clock_timestamp()-t)*1000);
 t:=clock_timestamp();perform distinct on(s.asset_id,s.layer_id) s.asset_id,s.layer_id,coalesce(g.canonical_concept_code,s.canonical_concept_code) from scale_assertions s left join scale_gold g using(asset_id,layer_id) where s.asset_id=a order by s.asset_id,s.layer_id,g.canonical_concept_code nulls last,s.id desc;insert into scale_timings values('effective_semantic_resolution',extract(epoch from clock_timestamp()-t)*1000);
 t:=clock_timestamp();perform coalesce(g.canonical_concept_code,s.canonical_concept_code) from scale_assertions s left join scale_gold g using(asset_id,layer_id) where s.asset_id=a and s.layer_id='L7' order by g.canonical_concept_code nulls last,s.id desc limit 1;insert into scale_timings values('human_override_resolution',extract(epoch from clock_timestamp()-t)*1000);
end loop;end$$;
select test,round(percentile_cont(.5)within group(order by elapsed_ms)::numeric,4)p50_ms,round(percentile_cont(.95)within group(order by elapsed_ms)::numeric,4)p95_ms,round(max(elapsed_ms)::numeric,4)max_ms from scale_timings group by test order by test;`;
const started=performance.now(),response=await fetch(`https://api.supabase.com/v1/projects/${ref}/database/query`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({query})});if(!response.ok)throw new Error(`scale test failed ${response.status}: ${(await response.text()).slice(0,3000)}`);const timings=await response.json();console.log(JSON.stringify({assets:1000,layer_rows:18000,assertions:100000,evidence:100000,temporary_tables:true,production_rows_persisted:0,request_elapsed_ms:Number((performance.now()-started).toFixed(2)),timings},null,2));
