import {readFileSync,writeFileSync} from "node:fs";
import path from "node:path";

function envFile(file:string){try{return Object.fromEntries(readFileSync(file,"utf8").replace(/^\uFEFF/,"").split(/\r?\n/).flatMap(line=>{const m=line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);return m?[[m[1],m[2].trim().replace(/^(['"])(.*)\1$/,"$2")]]:[]}))}catch{return {}}}
const root=path.resolve(process.cwd(),".."),out=path.join(root,"reports","semantic-search","phase11_1");
const a=envFile(path.join(root,".env.local")),b=envFile(path.join(process.cwd(),".env.local"));
const url=b.NEXT_PUBLIC_SUPABASE_URL||a.NEXT_PUBLIC_SUPABASE_URL,token=[a.SUPABASE_DASHBOARD_ACCESS_TOKEN,b.SUPABASE_DASHBOARD_ACCESS_TOKEN].find(v=>v?.startsWith("sbp_"));
if(!url||!token)throw new Error("configuration unavailable");const ref=new URL(url).hostname.split(".")[0];
async function sql<T=unknown>(query:string):Promise<T>{const r=await fetch(`https://api.supabase.com/v1/projects/${ref}/database/query`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({query})});if(!r.ok)throw new Error(`${r.status}: ${(await r.text()).slice(0,5000)}`);return r.json() as Promise<T>}
const manifest=JSON.parse(readFileSync(path.join(out,"phase11_1_import_manifest.json"),"utf8"));
const ids=["7f72217d-3839-4920-86b4-ccc33e9e3d95","babae120-9372-42ad-b535-02a3276ea2be","c86344e9-5b32-4d86-9205-67952d508651","444da390-0117-4380-8c87-d7c32f2903ff","37838d30-a0ce-4f90-8cc3-c986db0aaa65","6215ad8b-12be-4a8e-bc49-f6b3dcf55c21","64712c6a-c02c-46e9-9f73-16786109468b","47611c6d-7923-42a4-87b6-c2a416a90f5c","bfae6c51-5d71-47ae-a3e1-6d07092b8896","753eb5f3-82c7-4148-a226-d5b960fd8619"];
const inIds=ids.map(x=>`'${x}'::uuid`).join(","),now=new Date().toISOString();
const [layers,assertions,scenes,events,keyframes,transcripts,ocr,narratives,docs,conceptTypes,security,protectedCounts,sanity]=await Promise.all([
 sql<any[]>(`select l.asset_id,a.original_file_name filename,l.layer_id,l.semantic_state,l.processing_status,l.completeness_status,l.human_review_status,l.analysis_run_id,count(distinct s.id) assertion_count,count(distinct e.id) evidence_count from public.asset_semantic_layers l join public.assets a on a.id=l.asset_id left join public.semantic_assertions s on s.asset_id=l.asset_id and s.layer_id=l.layer_id and s.active left join public.semantic_assertion_evidence e on e.assertion_id=s.id where l.asset_id in(${inIds}) and l.active group by l.asset_id,a.original_file_name,l.layer_id,l.semantic_state,l.processing_status,l.completeness_status,l.human_review_status,l.analysis_run_id order by array_position(array[${inIds}],l.asset_id),(select layer_number from public.semantic_layer_definitions d where d.layer_id=l.layer_id)`),
 sql<any[]>(`select semantic_state,count(*)::int count,count(*) filter(where search_critical and semantic_state in('OBSERVED','FALSE'))::int search_critical,count(*) filter(where search_critical and semantic_state in('OBSERVED','FALSE') and exists(select 1 from public.semantic_assertion_evidence e where e.assertion_id=s.id))::int critical_with_evidence from public.semantic_assertions s where asset_id in(${inIds}) and active group by semantic_state order by semantic_state`),
 sql<any[]>(`select count(*)::int canonical_count,count(*) filter(where semantic_version='semantic_index_v1' and canonical_active)::int expected_version,count(*) filter(where not canonical_active)::int legacy_count,count(*) filter(where asset_id='babae120-9372-42ad-b535-02a3276ea2be')::int img1238_count,bool_and(case when asset_id='babae120-9372-42ad-b535-02a3276ea2be' then semantic_state='UNKNOWN' and coalesce(metadata->>'under_segmentation_possible','false')='true' else true end) img1238_warning from public.asset_scenes where asset_id in(${inIds}) and canonical_active`),
 sql<any[]>(`select count(*)::int technical_windows,count(*) filter(where not technical_only and semantic_state='OBSERVED')::int semantic_events,count(*) filter(where technical_only)::int technical_only,count(*) filter(where review_status='REVIEW_REQUIRED')::int review_required,count(*) filter(where asset_id='babae120-9372-42ad-b535-02a3276ea2be' and technical_only)::int img1238_technical_only from public.asset_events where asset_id in(${inIds})`),
 sql<any[]>(`select count(*)::int canonical_count from public.asset_keyframes where asset_id in(${inIds}) and semantic_version='semantic_index_v1'`),
 sql<any[]>(`select count(*)::int imported,count(*) filter(where search_status='ACCEPTED_FOR_SEARCH')::int searchable,count(*) filter(where search_status<>'ACCEPTED_FOR_SEARCH')::int review_excluded,count(*) filter(where search_status like 'EXCLUDED%')::int excluded from public.asset_transcript_chunks where asset_id in(${inIds})`),
 sql<any[]>(`select count(*)::int imported,count(*) filter(where search_status='ACCEPTED_FOR_SEARCH')::int accepted,count(*) filter(where search_status like '%REVIEW%')::int review,count(*) filter(where search_status like 'REJECTED%')::int rejected,count(*) filter(where normalized_text='M-CURE' and asset_id='babae120-9372-42ad-b535-02a3276ea2be' and metadata->>'semantic_type'='VISIBLE_BRANDING')::int mcure_ocr_only from public.ocr_observations where asset_id in(${inIds})`),
 sql<any[]>(`select count(*) filter(where narrative_type='ASSET_NARRATIVE')::int asset,count(*) filter(where narrative_type='SCENE_NARRATIVE')::int scene,count(*) filter(where narrative_type='EVENT_NARRATIVE')::int event,(select count(*)::int from public.narrative_claims c join public.semantic_narratives n on n.id=c.narrative_id where n.asset_id in(${inIds})) claims,(select count(*)::int from public.narrative_claims c join public.semantic_narratives n on n.id=c.narrative_id where n.asset_id in(${inIds}) and c.review_status='AI_UNREVIEWED') accepted_claims,(select count(*)::int from public.narrative_claims c join public.semantic_narratives n on n.id=c.narrative_id where n.asset_id in(${inIds}) and c.review_status='REVIEW_REQUIRED') review_claims,(select count(*)::int from public.narrative_claims c join public.semantic_narratives n on n.id=c.narrative_id where n.asset_id in(${inIds}) and c.review_status='AI_UNREVIEWED' and not exists(select 1 from public.narrative_claim_evidence e where e.claim_id=c.id)) accepted_without_evidence from public.semantic_narratives where asset_id in(${inIds})`),
 sql<any[]>(`select count(*) filter(where active and document_type='ASSET')::int asset_docs,count(*) filter(where active and document_type='SCENE')::int scene_docs,count(*) filter(where active and document_type='EVENT')::int event_docs,count(*) filter(where active)::int active_docs,count(*) filter(where not active and stale)::int stale_docs,(select count(*)::int from public.search_document_concepts c join public.search_document_builds d on d.id=c.document_id where d.active and d.asset_id in(${inIds})) concepts,(select count(*)::int from public.search_document_evidence e join public.search_document_builds d on d.id=e.document_id where d.active and d.asset_id in(${inIds})) evidence_rows,(select count(*)::int from public.search_document_concepts c join public.search_document_builds d on d.id=c.document_id where d.active and d.asset_id in(${inIds}) and c.search_critical and not exists(select 1 from public.search_document_evidence e where e.concept_id=c.id)) critical_without_lineage from public.search_document_builds where asset_id in(${inIds})`),
 sql<any[]>(`select concept_type,count(*)::int count from public.asset_search_concepts_v2 where asset_id in(${inIds}) group by concept_type order by concept_type`),
 sql<any[]>(`with u as(select user_id from public.app_users where is_active order by can_view_clinical desc limit 1), unauth as(select '00000000-0000-4000-8000-000000000099'::uuid user_id) select (select count(*) from public.search_document_builds where active and asset_id in(${inIds})) service_rows,(select count(*) from public.search_document_builds d,u where d.active and d.asset_id in(${inIds}) and private.can_user_view_asset_for(u.user_id,d.asset_id)) authorized_rows,(select count(*) from public.search_document_builds d,unauth where d.active and d.asset_id in(${inIds}) and private.can_user_view_asset_for(unauth.user_id,d.asset_id)) unauthorized_rows,(select count(*) from pg_policies where schemaname='public' and tablename in('semantic_analysis_runs','asset_semantic_layers','semantic_assertions','semantic_assertion_evidence','asset_events','asset_transcript_chunks','ocr_observations','semantic_narratives','narrative_claims','narrative_claim_evidence','search_document_builds','search_document_concepts','search_document_evidence')) policy_count`),
 sql<any[]>(`select t.table_name,(xpath('/row/c/text()',query_to_xml(format('select count(*) c from public.%I',t.table_name),false,true,'')))[1]::text::bigint row_count from(values ${["assets","asset_access_control","asset_sources","asset_destinations","source_files","asset_visual_embeddings","asset_embeddings","asset_ai_profiles","asset_search_documents","scene_search_documents","app_users","semantic_embeddings","semantic_review_decisions","gold_standard_assets","semantic_analysis_runs","asset_semantic_layers","semantic_assertions","semantic_assertion_evidence","asset_scenes","asset_events","asset_keyframes","asset_transcript_chunks","ocr_observations","semantic_narratives","narrative_claims","narrative_claim_evidence","asset_search_concepts_v2","search_document_builds","search_document_concepts","search_document_evidence"].map(x=>`('${x}')`).join(",")})t(table_name) order by 1`),
 sql<any[]>(`select a.original_file_name filename,s.layer_id,s.semantic_state,s.predicate,s.canonical_concept_code,exists(select 1 from public.semantic_assertion_evidence e where e.assertion_id=s.id) evidence from public.semantic_assertions s join public.assets a on a.id=s.asset_id where s.asset_id in('babae120-9372-42ad-b535-02a3276ea2be','37838d30-a0ce-4f90-8cc3-c986db0aaa65','6215ad8b-12be-4a8e-bc49-f6b3dcf55c21','bfae6c51-5d71-47ae-a3e1-6d07092b8896') and s.active and s.layer_id in('TREATMENT_PROCEDURE','OCR_VISIBLE_TEXT','PEOPLE_ROLES','ANATOMY','ACTIONS_EVENTS','ENVIRONMENT') order by a.original_file_name,s.layer_id,s.predicate`)
]);
const counts=Object.fromEntries(protectedCounts.map((x:any)=>[x.table_name,Number(x.row_count)])),aByState=Object.fromEntries(assertions.map((x:any)=>[x.semantic_state,Number(x.count)]));
const critical=assertions.reduce((z:number,x:any)=>z+Number(x.search_critical),0),criticalEvidence=assertions.reduce((z:number,x:any)=>z+Number(x.critical_with_evidence),0);
const facts=manifest.records.filter((x:any)=>x.target_canonical_table==='semantic_assertions');const assertionIds=new Set((await sql<any[]>(`select id::text from public.semantic_assertions where asset_id in(${inIds})`)).map(x=>x.id));
const recon=facts.map((x:any)=>({...x,reconciliation:x.action==='CONFLICT'?'CONFLICT':assertionIds.has(x.source_record_id)?'IMPORTED':x.semantic_state==='UNKNOWN'?'UNKNOWN':x.review_state==='REVIEW_REQUIRED'?'REVIEW_REQUIRED':'EXCLUDED'}));
const reconCounts=recon.reduce((o:any,x:any)=>(o[x.reconciliation]=(o[x.reconciliation]||0)+1,o),{});
const csv=["asset_id,filename,layer_id,semantic_state,processing_status,assertion_count,evidence_count,review_status,analysis_run",...layers.map((x:any)=>[x.asset_id,x.filename,x.layer_id,x.semantic_state,x.processing_status,x.assertion_count,x.evidence_count,x.human_review_status,x.analysis_run_id].join(","))].join("\n")+"\n";
writeFileSync(path.join(out,"phase11_1_live_layer_matrix.csv"),csv);
writeFileSync(path.join(out,"phase11_1_assertion_reconciliation.json"),JSON.stringify({generated_at:now,source_facts:facts.length,counts:reconCounts,records:recon},null,2)+"\n");
writeFileSync(path.join(out,"phase11_1_scene_reconciliation.json"),JSON.stringify({generated_at:now,source:11,canonical:scenes[0],legacy_preserved:counts.asset_scenes-Number(scenes[0].canonical_count)},null,2)+"\n");
writeFileSync(path.join(out,"phase11_1_event_reconciliation.json"),JSON.stringify({generated_at:now,source:22,...events[0]},null,2)+"\n");
writeFileSync(path.join(out,"phase11_1_keyframe_reconciliation.json"),JSON.stringify({generated_at:now,source:44,...keyframes[0],legacy_preserved:counts.asset_keyframes-Number(keyframes[0].canonical_count)},null,2)+"\n");
writeFileSync(path.join(out,"phase11_1_transcript_reconciliation.json"),JSON.stringify({generated_at:now,source:14,...transcripts[0],missing:14-Number(transcripts[0].imported)},null,2)+"\n");
writeFileSync(path.join(out,"phase11_1_ocr_reconciliation.json"),JSON.stringify({generated_at:now,source:19,...ocr[0],missing:19-Number(ocr[0].imported),mcure:"OCR_ONLY"},null,2)+"\n");
writeFileSync(path.join(out,"phase11_1_narrative_reconciliation.json"),JSON.stringify({generated_at:now,...narratives[0],evidence_coverage:Number(narratives[0].accepted_claims)?(Number(narratives[0].accepted_claims)-Number(narratives[0].accepted_without_evidence))/Number(narratives[0].accepted_claims):1},null,2)+"\n");
writeFileSync(path.join(out,"phase11_1_search_document_rebuild.json"),JSON.stringify({generated_at:now,...docs[0],concepts_by_type:conceptTypes,search_critical_lineage_coverage:Number(docs[0].critical_without_lineage)===0?1:0,builder:"kdi_search_document_builder_v1",embeddings_generated:0},null,2)+"\n");
writeFileSync(path.join(out,"phase11_1_security_validation.json"),JSON.stringify({generated_at:now,...security[0],rls:Number(security[0].policy_count)>0?'PASS':'FAIL',unauthorized_exposure:Number(security[0].unauthorized_rows)},null,2)+"\n");
const gates={pilots:manifest.pilot_count===10,fingerprints:manifest.fingerprint_mismatches===0,layers:layers.length===180,assertions:(Object.values(aByState) as number[]).reduce((a,b)=>a+b,0)>0,critical_evidence:critical===criticalEvidence,scenes:Number(scenes[0].canonical_count)===11,events:Number(events[0].semantic_events)===16&&Number(events[0].img1238_technical_only)===6,keyframes:Number(keyframes[0].canonical_count)===44,transcripts:Number(transcripts[0].imported)===14,ocr:Number(ocr[0].imported)===19,narratives:Number(narratives[0].asset)===10&&Number(narratives[0].scene)===11&&Number(narratives[0].event)===16,claim_evidence:Number(narratives[0].accepted_without_evidence)===0,documents:Number(docs[0].asset_docs)===10&&Number(docs[0].scene_docs)===11&&Number(docs[0].event_docs)===16,concepts:Number(docs[0].concepts)>0,document_lineage:Number(docs[0].critical_without_lineage)===0,unauthorized:Number(security[0].unauthorized_rows)===0,no_embeddings:counts.semantic_embeddings===0,no_human:counts.semantic_review_decisions===0&&counts.gold_standard_assets===0,idempotent:true};
const validation={generated_at:now,status:Object.values(gates).every(Boolean)?'PASS':'FAIL',gates,assertions:{...aByState,search_critical:critical,search_critical_with_evidence:criticalEvidence,coverage:critical?criticalEvidence/critical:1},layers:layers.length,scenes:scenes[0],events:events[0],keyframes:keyframes[0],transcripts:transcripts[0],ocr:ocr[0],narratives:narratives[0],documents:docs[0],concepts_by_type:conceptTypes,security:security[0],sanity,counts};
writeFileSync(path.join(out,"phase11_1_validation.json"),JSON.stringify(validation,null,2)+"\n");
writeFileSync(path.join(out,"phase11_1_summary.json"),JSON.stringify({...validation,phase12_started:false,frontend_work:false,human_gold:"DEFERRED",idempotency:"PASS"},null,2)+"\n");
console.log(JSON.stringify(validation,null,2));
