import {randomUUID} from "node:crypto";
import {mkdirSync,readFileSync,writeFileSync} from "node:fs";
import path from "node:path";
import {buildDocuments,BUILDER_VERSION,CONFIGURATION_FINGERPRINT,CONFIGURATION_VERSION,ONTOLOGY_VERSION,SEARCH_DOCUMENT_VERSION,SEMANTIC_SPEC_VERSION,sha256} from "../db/search-document-builder";

function envFile(file:string){try{return Object.fromEntries(readFileSync(file,"utf8").replace(/^\uFEFF/,"").split(/\r?\n/).flatMap(line=>{const m=line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);return m?[[m[1],m[2].trim().replace(/^(['"])(.*)\1$/,"$2")]]:[]}))}catch{return {}}}
const root=path.resolve(process.cwd(),".."),a=envFile(path.join(root,".env.local")),b=envFile(path.join(process.cwd(),".env.local"));
const url=b.NEXT_PUBLIC_SUPABASE_URL||a.NEXT_PUBLIC_SUPABASE_URL,token=[a.SUPABASE_DASHBOARD_ACCESS_TOKEN,b.SUPABASE_DASHBOARD_ACCESS_TOKEN].find(v=>v?.startsWith("sbp_"));
if(!url||!token)throw new Error("configuration unavailable");const ref=new URL(url).hostname.split(".")[0];
async function sql<T=unknown>(query:string):Promise<T>{const r=await fetch(`https://api.supabase.com/v1/projects/${ref}/database/query`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({query})});if(!r.ok)throw new Error(`${r.status}: ${(await r.text()).slice(0,5000)}`);return r.json() as Promise<T>}
const q=(v:any)=>v==null?"null":`'${String(v).replaceAll("'","''")}'`,u=(v:any)=>v?`${q(v)}::uuid`:"null",n=(v:any)=>v==null?"null":String(v),j=(v:any)=>`${q(JSON.stringify(v))}::jsonb`;
const du=(seed:string)=>{const h=sha256(seed);return`${h.slice(0,8)}-${h.slice(8,12)}-5${h.slice(13,16)}-a${h.slice(17,20)}-${h.slice(20,32)}`};
const audit=JSON.parse(readFileSync(path.join(root,"reports","semantic-search","phase11","phase11_existing_search_document_audit.json"),"utf8"));
const built=audit.assets.map((x:any)=>({input:x,result:buildDocuments({asset_id:x.asset_id,filename:x.filename,mime_type:x.mime_type,source_fingerprint:x.source_fingerprint,scenes:x.scenes,events:x.events,assertions:x.effective_assertions,narratives:x.semantic_narratives,transcripts:x.transcripts,ocr:x.ocr})}));
if(built.length!==10)throw new Error("pilot count gate");const docs=built.flatMap((x:any)=>[x.result.asset,...x.result.scenes,...x.result.events]),runId=randomUUID();
const pilotIds=audit.assets.map((x:any)=>u(x.asset_id)).join(",");
const stmts=["begin",`update public.search_document_builds set active=false,stale=true,status='STALE' where asset_id in(${pilotIds}) and active`,`insert into public.search_document_build_runs(id,status,search_document_version,builder_version,configuration_version,configuration_fingerprint,semantic_spec_version,ontology_version,source_semantic_version,asset_count,asset_document_count,scene_document_count,event_document_count) values(${u(runId)},'RUNNING',${q(SEARCH_DOCUMENT_VERSION)},${q(BUILDER_VERSION)},${q(CONFIGURATION_VERSION)},${q(CONFIGURATION_FINGERPRINT)},${q(SEMANTIC_SPEC_VERSION)},${q(ONTOLOGY_VERSION)},${q(SEMANTIC_SPEC_VERSION)},10,10,${built.reduce((z:number,x:any)=>z+x.result.scenes.length,0)},${built.reduce((z:number,x:any)=>z+x.result.events.length,0)})`];
const identity=(alias:string,d:any)=>`${alias}.asset_id=${u(d.asset_id)} and ${alias}.document_type=${q(d.document_type)} and ${alias}.scene_id is not distinct from ${u(d.scene_id)} and ${alias}.event_id is not distinct from ${u(d.event_id)} and ${alias}.search_document_version=${q(SEARCH_DOCUMENT_VERSION)}`;
for(const d of docs){
 const docId=du(`document:${d.document_fingerprint}`),plain=identity("sd",d);
 stmts.push(`update public.search_document_builds sd set active=false,stale=true,status='STALE' where ${plain} and sd.active and sd.document_fingerprint<>${q(d.document_fingerprint)}`);
 stmts.push(`update public.search_document_builds sd set build_run_id=${u(runId)},active=true,stale=false,status='READY',generated_at=now() where ${plain} and sd.document_fingerprint=${q(d.document_fingerprint)}`);
 stmts.push(`insert into public.search_document_builds(id,build_run_id,asset_id,scene_id,event_id,document_type,filename,media_type,start_time,end_time,normalized_document,search_text,positive_concepts,negative_concepts,search_document_version,builder_version,configuration_version,configuration_fingerprint,semantic_spec_version,ontology_version,source_semantic_version,source_fingerprint,source_semantic_fingerprint,document_fingerprint,status,review_status,gold_standard_version,human_approved,review_required,active,stale,generated_at) select ${u(docId)},${u(runId)},${u(d.asset_id)},${u(d.scene_id)},${u(d.event_id)},${q(d.document_type)},${q(d.filename)},${q(d.media_type)},${n(d.start_time)},${n(d.end_time)},${j(d)},${q(d.search_text)},${j(d.positive_concepts)},${j(d.negative_concepts)},${q(SEARCH_DOCUMENT_VERSION)},${q(BUILDER_VERSION)},${q(CONFIGURATION_VERSION)},${q(CONFIGURATION_FINGERPRINT)},${q(SEMANTIC_SPEC_VERSION)},${q(ONTOLOGY_VERSION)},${q(SEMANTIC_SPEC_VERSION)},${q(d.source_semantic_fingerprint)},${q(d.source_semantic_fingerprint)},${q(d.document_fingerprint)},'READY','AI_UNREVIEWED',null,false,${d.review_required},true,false,now() where not exists(select 1 from public.search_document_builds sd where ${plain} and sd.document_fingerprint=${q(d.document_fingerprint)}) on conflict(id) do update set build_run_id=excluded.build_run_id,active=true,stale=false,status='READY',generated_at=now()`);
 for(const c of [...d.positive_concepts,...d.negative_concepts])if(c.assertion_id){
  const cid=du(`concept:${d.document_fingerprint}:${c.assertion_id}`);
  stmts.push(`insert into public.search_document_concepts(id,document_id,asset_id,scene_id,event_id,concept_type,canonical_code,display_text,semantic_state,confidence,origin,resolution_source,review_status,assertion_id,search_critical) select ${u(cid)},sd.id,${u(d.asset_id)},${u(d.scene_id)},${u(d.event_id)},${q(c.concept_type)},${q(c.canonical_code)},${q(c.display_text)},${q(c.semantic_state)},${n(c.confidence)},${q(c.origin)},${q(c.resolution_source)},'AI_UNREVIEWED',${u(c.assertion_id)},${c.search_critical} from public.search_document_builds sd where ${plain} and sd.active on conflict(id) do nothing`);
  for(const eid of c.evidence_ids){const deid=du(`document-evidence:${d.document_fingerprint}:${eid}`);stmts.push(`insert into public.search_document_evidence(id,document_id,concept_id,assertion_id,assertion_evidence_id,asset_id,scene_id,event_id,keyframe_id,transcript_chunk_id,ocr_observation_id,evidence_type) select ${u(deid)},sd.id,${u(cid)},e.assertion_id,e.id,e.asset_id,e.scene_id,e.event_id,e.keyframe_id,e.transcript_chunk_id,e.ocr_observation_id,e.evidence_type from public.search_document_builds sd join public.semantic_assertion_evidence e on e.id=${u(eid)} where ${plain} and sd.active on conflict(id) do nothing`)}
 }
}
stmts.push(`update public.search_document_builds old set superseded_by=cur.id from public.search_document_builds cur where cur.active and not old.active and old.superseded_by is null and old.asset_id=cur.asset_id and old.document_type=cur.document_type and old.scene_id is not distinct from cur.scene_id and old.event_id is not distinct from cur.event_id and old.search_document_version=cur.search_document_version`);
stmts.push(`update public.search_document_build_runs set status='COMPLETE',completed_at=now() where id=${u(runId)}`,"commit");
await sql(stmts.join(";\n")+";");
const dir=path.join(root,"reports","semantic-search","phase11"),assetDir=path.join(dir,"assets");mkdirSync(assetDir,{recursive:true});for(const x of built)writeFileSync(path.join(assetDir,`${x.input.asset_id}_search_document.json`),JSON.stringify(x.result.asset,null,2)+"\n");
const assets=built.map((x:any)=>x.result.asset),scenes=built.flatMap((x:any)=>x.result.scenes),events=built.flatMap((x:any)=>x.result.events),concepts=built.flatMap((x:any)=>x.result.concepts),base={generated_at:new Date().toISOString(),build_run_id:runId,search_document_version:SEARCH_DOCUMENT_VERSION,builder_version:BUILDER_VERSION,configuration_version:CONFIGURATION_VERSION,configuration_fingerprint:CONFIGURATION_FINGERPRINT,review_status:"AI_UNREVIEWED",human_approved:false,gold_standard_version:null};
for(const [name,value] of [["asset_documents",{...base,count:assets.length,documents:assets}],["scene_documents",{...base,count:scenes.length,documents:scenes}],["event_documents",{...base,count:events.length,technical_only_skipped:audit.assets.reduce((z:number,x:any)=>z+x.events.filter((e:any)=>e.technical_only).length,0),documents:events}],["search_concepts",{...base,count:concepts.length,concepts}]])writeFileSync(path.join(dir,`phase11_${name}.json`),JSON.stringify(value,null,2)+"\n");
console.log(JSON.stringify({run_id:runId,asset_documents:assets.length,scene_documents:scenes.length,event_documents:events.length,concepts:concepts.length,statements:stmts.length},null,2));
