import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
function env(file:string){try{return Object.fromEntries(readFileSync(file,"utf8").replace(/^\uFEFF/,"").split(/\r?\n/).flatMap(line=>{const m=line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);return m?[[m[1],m[2].trim().replace(/^(['"])(.*)\1$/,"$2")]]:[]}))}catch{return{}}}
const root=path.resolve(import.meta.dirname,"../.."),a:any=env(path.join(root,".env.local")),b:any=env(path.join(root,"dashboard",".env.local")),url=b.NEXT_PUBLIC_SUPABASE_URL||a.NEXT_PUBLIC_SUPABASE_URL,token=[a.SUPABASE_DASHBOARD_ACCESS_TOKEN,b.SUPABASE_DASHBOARD_ACCESS_TOKEN].find(x=>x?.startsWith("sbp_"));if(!url||!token)throw Error("configuration unavailable");
const ref=new URL(url).hostname.split(".")[0],query=`select jsonb_build_object(
'counts',(select jsonb_object_agg(name,n) from (select 'assets' name,count(*) n from public.assets union all select 'asset_access_control',count(*) from public.asset_access_control union all select 'semantic_embeddings',count(*) from public.semantic_embeddings union all select 'asset_search_concepts_v2',count(*) from public.asset_search_concepts_v2 union all select 'semantic_assertions',count(*) from public.semantic_assertions union all select 'semantic_assertion_evidence',count(*) from public.semantic_assertion_evidence union all select 'asset_search_documents',count(*) from public.asset_search_documents union all select 'scene_search_documents',count(*) from public.scene_search_documents union all select 'app_users',count(*) from public.app_users)t),
'pilot',(select jsonb_object_agg(w.name,exists(select 1 from public.assets a where a.file_name=w.name)) from (values('DSC03753.JPG'),('DSC08097.JPG'),('IMG_0493.MP4'),('IMG_0531.MP4'),('IMG_1148.MP4'),('IMG_1160.MP4'),('IMG_1238.MP4'),('IMG_2963.MP4'),('IMG_3429.MP4'),('IMG_9871.MOV'))w(name)),
'phase18_app_users',(select count(*) from public.app_users where email like 'phase18-%'),
'controlled_acl',(select jsonb_build_object('internal_usage_status',internal_usage_status,'is_clinical',is_clinical,'requires_clinical_permission',requires_clinical_permission,'sensitivity_level',sensitivity_level,'download_allowed',download_allowed) from public.asset_access_control where asset_id=(select id from public.assets where file_name='IMG_3429.MP4'))
) result`;
const response=await fetch(`https://api.supabase.com/v1/projects/${ref}/database/query`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({query})});if(!response.ok)throw Error(`preservation query failed ${response.status}`);const rows=await response.json() as any[],result=rows[0]?.result??rows[0]?.[0]?.result;if(!result)throw Error("preservation result unavailable");const pilotCount=Object.values(result.pilot).filter(Boolean).length,status=pilotCount===10&&result.phase18_app_users===0&&result.counts.assets===881&&result.counts.asset_access_control===881&&result.counts.app_users===2?"PASS":"FAIL",report={generated_at:new Date().toISOString(),status,pilot_count:pilotCount,...result};const out=path.join(root,"reports","semantic-search","phase18");mkdirSync(out,{recursive:true});writeFileSync(path.join(out,"final_preservation.json"),JSON.stringify(report,null,2)+"\n");console.log(JSON.stringify(report,null,2));if(status!=="PASS")process.exitCode=1;
