import {mkdirSync,readFileSync,writeFileSync} from "node:fs";import path from "node:path";
function envFile(file:string){try{return Object.fromEntries(readFileSync(file,"utf8").replace(/^\uFEFF/,"").split(/\r?\n/).flatMap(line=>{const m=line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);return m?[[m[1],m[2].trim().replace(/^(['"])(.*)\1$/,"$2")]]:[]}))}catch{return {}}}
const root=path.resolve(process.cwd(),".."),out=path.join(root,"reports","semantic-search","phase12");mkdirSync(out,{recursive:true});const a=envFile(path.join(root,".env.local")),b=envFile(path.join(process.cwd(),".env.local")),url=b.NEXT_PUBLIC_SUPABASE_URL||a.NEXT_PUBLIC_SUPABASE_URL,token=[a.SUPABASE_DASHBOARD_ACCESS_TOKEN,b.SUPABASE_DASHBOARD_ACCESS_TOKEN].find(v=>v?.startsWith("sbp_"));if(!url||!token)throw new Error("configuration unavailable");const ref=new URL(url).hostname.split(".")[0];async function sql<T=unknown>(query:string):Promise<T>{const r=await fetch(`https://api.supabase.com/v1/projects/${ref}/database/query`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({query})});if(!r.ok)throw new Error(`${r.status}: ${(await r.text()).slice(0,5000)}`);return r.json() as Promise<T>}
async function denied(query:string){const r=await fetch(`https://api.supabase.com/v1/projects/${ref}/database/query`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({query})});return{denied:!r.ok,status:r.status,detail:(await r.text()).slice(0,500)}}
const ids=["7f72217d-3839-4920-86b4-ccc33e9e3d95","babae120-9372-42ad-b535-02a3276ea2be","c86344e9-5b32-4d86-9205-67952d508651","444da390-0117-4380-8c87-d7c32f2903ff","37838d30-a0ce-4f90-8cc3-c986db0aaa65","6215ad8b-12be-4a8e-bc49-f6b3dcf55c21","64712c6a-c02c-46e9-9f73-16786109468b","47611c6d-7923-42a4-87b6-c2a416a90f5c","bfae6c51-5d71-47ae-a3e1-6d07092b8896","753eb5f3-82c7-4148-a226-d5b960fd8619"],inIds=ids.map(x=>`'${x}'::uuid`).join(","),now=new Date().toISOString();
const [reps,integrity,excluded,safety,coverage,concepts,postCounts,storage,indexes,users]=await Promise.all([
 sql<any[]>(`select representation_type,provider,model,model_version,embedding_version,embedding_bundle_version,dimensions,count(*)::int count,count(*) filter(where active and not stale)::int active_count from public.semantic_embeddings where asset_id in(${inIds}) group by 1,2,3,4,5,6,7 order by 1`),
 sql<any[]>(`select count(*)::int total,count(*) filter(where active)::int active,count(*) filter(where source_fingerprint is null)::int missing_source,count(*) filter(where vector_fingerprint is null)::int missing_vector_fp,count(*) filter(where analysis_run_id is null)::int missing_run,count(*) filter(where vector_dims(embedding)<>dimensions)::int dimension_mismatch,count(*) filter(where embedding is null)::int null_vectors,count(*) filter(where representation_type like 'VISUAL%' and dimensions<>512)::int bad_visual_dims,count(*) filter(where representation_type like 'TEXT%' and dimensions<>384)::int bad_text_dims,(select count(*) from(select asset_id,coalesce(scene_id,'00000000-0000-0000-0000-000000000000'),coalesce(event_id,'00000000-0000-0000-0000-000000000000'),coalesce(keyframe_id,'00000000-0000-0000-0000-000000000000'),coalesce(transcript_chunk_id,-1),coalesce(ocr_observation_id,'00000000-0000-0000-0000-000000000000'),representation_type,embedding_version,model_version,count(*) from public.semantic_embeddings where active group by 1,2,3,4,5,6,7,8,9 having count(*)>1)d)::int duplicate_active,(select count(*) from public.semantic_embeddings e join public.search_document_builds d on d.id=(e.metadata->>'source_unit_id')::uuid where e.active and e.representation_type in('TEXT_ASSET','TEXT_SCENE','TEXT_EVENT') and (not d.active or e.source_document_fingerprint is distinct from d.document_fingerprint))::int stale_document_mismatch from public.semantic_embeddings where asset_id in(${inIds})`),
 sql<any[]>(`select (select count(*) from public.semantic_embeddings e join public.asset_transcript_chunks t on t.id=e.transcript_chunk_id where e.active and e.representation_type='TEXT_TRANSCRIPT' and t.search_status<>'ACCEPTED_FOR_SEARCH')::int excluded_transcripts,(select count(*) from public.semantic_embeddings e join public.ocr_observations o on o.id=e.ocr_observation_id where e.active and e.representation_type='TEXT_OCR' and o.search_status<>'ACCEPTED_FOR_SEARCH')::int excluded_ocr,(select count(*) from public.semantic_embeddings e join public.asset_events v on v.id=e.event_id where e.active and e.representation_type='TEXT_EVENT' and v.technical_only)::int technical_events,(select count(*) from public.semantic_embeddings e join public.asset_transcript_chunks t on t.id=e.transcript_chunk_id where e.active and t.asset_id='c86344e9-5b32-4d86-9205-67952d508651')::int img3429_transcript`),
 sql<any[]>(`select (select semantic_state from public.semantic_assertions where asset_id='babae120-9372-42ad-b535-02a3276ea2be' and active and layer_id='TREATMENT_PROCEDURE' limit 1) img1238_treatment,(select count(*) from public.asset_scenes where asset_id='babae120-9372-42ad-b535-02a3276ea2be' and canonical_active and coalesce(metadata->>'under_segmentation_possible','false')='true')::int undersegmentation,(select count(*) from public.ocr_observations where asset_id='babae120-9372-42ad-b535-02a3276ea2be' and normalized_text='M-CURE' and metadata->>'semantic_type'='VISIBLE_BRANDING')::int mcure_ocr_only,(select count(*) from public.asset_events where asset_id='babae120-9372-42ad-b535-02a3276ea2be' and technical_only)::int technical_only,(select count(*) from public.semantic_review_decisions)::int human_decisions,(select count(*) from public.gold_standard_assets where status='SIGNED_OFF')::int signed_gold`),
 sql<any[]>(`select a.id asset_id,a.original_file_name filename,count(*) filter(where e.representation_type='VISUAL_ASSET' and e.active)::int visual_asset,(select count(*) from public.asset_scenes s where s.asset_id=a.id and s.canonical_active)::int canonical_scenes,count(*) filter(where e.representation_type='VISUAL_SCENE' and e.active)::int visual_scene,(select count(*) from public.asset_keyframes k where k.asset_id=a.id and k.semantic_version='semantic_index_v1')::int canonical_keyframes,count(*) filter(where e.representation_type='VISUAL_KEYFRAME' and e.active)::int visual_keyframe,count(*) filter(where e.representation_type='TEXT_ASSET' and e.active)::int text_asset,count(*) filter(where e.representation_type='TEXT_SCENE' and e.active)::int text_scene,count(*) filter(where e.representation_type='TEXT_EVENT' and e.active)::int text_event,count(*) filter(where e.representation_type='TEXT_TRANSCRIPT' and e.active)::int text_transcript,count(*) filter(where e.representation_type='TEXT_OCR' and e.active)::int text_ocr,(select count(*) from public.asset_search_concepts_v2 c where c.asset_id=a.id)::int structured_concepts from public.assets a left join public.semantic_embeddings e on e.asset_id=a.id where a.id in(${inIds}) group by a.id,a.original_file_name order by array_position(array[${inIds}],a.id)`),
 sql<any[]>(`select concept_type,count(*)::int count from public.asset_search_concepts_v2 where asset_id in(${inIds}) group by concept_type order by concept_type`),
 sql<any[]>(`select t.table_name,(xpath('/row/c/text()',query_to_xml(format('select count(*) c from public.%I',t.table_name),false,true,'')))[1]::text::bigint row_count from(values ${["assets","asset_access_control","source_files","asset_sources","asset_destinations","semantic_assertions","semantic_assertion_evidence","asset_scenes","asset_events","asset_keyframes","asset_transcript_chunks","ocr_observations","semantic_narratives","search_document_builds","asset_search_concepts_v2","asset_visual_embeddings","asset_embeddings","semantic_embeddings","semantic_analysis_runs"].map(x=>`('${x}')`).join(",")})t(table_name) order by 1`),
 sql<any[]>(`select count(*)::int rows,coalesce(sum(pg_column_size(embedding)),0)::bigint vector_bytes,coalesce(sum(pg_column_size(t)),0)::bigint row_bytes from public.semantic_embeddings t where asset_id in(${inIds}) and active`),
 sql<any[]>(`select indexname,indexdef from pg_indexes where schemaname='public' and tablename='semantic_embeddings' order by indexname`),
 sql<any[]>(`select user_id from public.app_users where is_active order by can_view_clinical desc limit 1`)
]);
const issuer=`https://${ref}.supabase.co/auth/v1`;
const authorized=await sql<any[]>(`begin;set local role authenticated;select set_config('request.jwt.claims','{"sub":"${users[0].user_id}","role":"authenticated","iss":"${issuer}"}',true);select count(*)::int rows,count(distinct representation_type)::int families from public.semantic_embeddings where asset_id in(${inIds}) and active;rollback`);
const unauthorized=await sql<any[]>(`begin;set local role authenticated;select set_config('request.jwt.claims','{"sub":"00000000-0000-4000-8000-000000000099","role":"authenticated","iss":"${issuer}"}',true);select count(*)::int rows,count(distinct representation_type)::int families from public.semantic_embeddings where asset_id in(${inIds}) and active;rollback`);
const writeTest=await denied(`begin;set local role authenticated;select set_config('request.jwt.claims','{"sub":"${users[0].user_id}","role":"authenticated","iss":"${issuer}"}',true);insert into public.semantic_embeddings(asset_id,embedding_scope,provider,model,version,dimensions,embedding,source_semantic_version,analysis_run_id,representation_type,model_version,source_fingerprint,embedding_version,embedding_bundle_version,vector_fingerprint) select '${ids[0]}','TEXT_ASSET','x','x','x',1,'[1]'::vector,'x',id,'TEXT_ASSET','x','x','x','x','x' from public.semantic_analysis_runs limit 1;rollback`);
const families=["VISUAL_ASSET","VISUAL_SCENE","VISUAL_KEYFRAME","TEXT_ASSET","TEXT_SCENE","TEXT_EVENT","TEXT_TRANSCRIPT","TEXT_OCR"],latency:any={};
for(const family of families){const ms:number[]=[];for(let i=0;i<7;i++){const t=performance.now();await sql(`with q as(select embedding from public.semantic_embeddings where active and representation_type='${family}' limit 1),space as materialized(select id,embedding from public.semantic_embeddings where active and representation_type='${family}') select id from space,q order by space.embedding <=> q.embedding limit 5`);ms.push(performance.now()-t)}ms.sort((a,b)=>a-b);latency[family]={samples:ms.length,p50_ms:ms[Math.floor(ms.length*.5)],p95_ms:ms[Math.floor(ms.length*.95)],max_ms:ms.at(-1)}}
const before=JSON.parse(readFileSync(path.join(out,"phase12_pre_generation_counts.json"),"utf8")).counts,beforeMap=Object.fromEntries(before.map((x:any)=>[x.table_name,Number(x.row_count)])),afterMap=Object.fromEntries(postCounts.map((x:any)=>[x.table_name,Number(x.row_count)]));const changes=Object.keys(afterMap).map(table=>({table,before:beforeMap[table],after:afterMap[table],delta:afterMap[table]-beforeMap[table],expected_change:["semantic_embeddings","semantic_analysis_runs"].includes(table)}));
const expected:any={VISUAL_ASSET:10,VISUAL_SCENE:11,VISUAL_KEYFRAME:44,TEXT_ASSET:10,TEXT_SCENE:11,TEXT_EVENT:16,TEXT_TRANSCRIPT:3,TEXT_OCR:1},repMap=Object.fromEntries(reps.map((x:any)=>[x.representation_type,Number(x.active_count)]));
const similarity=JSON.parse(readFileSync(path.join(out,"phase12_similarity_sanity.json"),"utf8")),crossModal=JSON.parse(readFileSync(path.join(out,"phase12_cross_modal_sanity.json"),"utf8"));const textEquivalentTies=similarity.text_self_retrieval.exceptions.filter((x:any)=>Number(x.top[0])>=.999999).length;
const protectedOk=changes.filter(x=>!x.expected_change).every(x=>x.delta===0),gate={exact_pilots:coverage.length===10,fingerprints:Number(integrity[0].missing_source)===0,legacy_preserved:afterMap.asset_visual_embeddings===875&&afterMap.asset_embeddings===20,versions_locked:reps.every((x:any)=>x.embedding_bundle_version==='kdi_embedding_bundle_v1'),coverage:Object.entries(expected).every(([k,v])=>repMap[k]===v),excluded_content:Object.values(excluded[0]).every(x=>Number(x)===0),img1238:safety[0].img1238_treatment==='UNKNOWN'&&Number(safety[0].undersegmentation)===1&&Number(safety[0].mcure_ocr_only)===1&&Number(safety[0].technical_only)===6,integrity:Number(integrity[0].missing_source)+Number(integrity[0].missing_vector_fp)+Number(integrity[0].missing_run)+Number(integrity[0].dimension_mismatch)+Number(integrity[0].null_vectors)===0,idempotency:Number(integrity[0].duplicate_active)===0&&Number(integrity[0].total)===106,staleness:Number(integrity[0].stale_document_mismatch)===0,mixed_dimensions:Number(integrity[0].bad_visual_dims)===0&&Number(integrity[0].bad_text_dims)===0,structured:concepts.reduce((n:any,x:any)=>n+Number(x.count),0)===270,visual_sanity:Number(similarity.visual_keyframe_self_retrieval.rank1)===44&&similarity.scene_coherence.every((x:any)=>x.unrelated_mean==null||x.member_mean>x.unrelated_mean),text_sanity:Number(similarity.text_self_retrieval.rank1)+textEquivalentTies===Number(similarity.text_self_retrieval.tested),cross_modal_sanity:Object.keys(crossModal.queries).length===5,rls:Number(authorized.find((x:any)=>x.rows!=null)?.rows)===106&&Number(unauthorized.find((x:any)=>x.rows!=null)?.rows)===0,client_write_denied:writeTest.denied,semantic_preserved:protectedOk,no_human:Number(safety[0].human_decisions)===0&&Number(safety[0].signed_gold)===0,no_frontend:true,phase13_not_started:true};
const security={generated_at:now,rls:Object.values(gate).length&&gate.rls?"PASS":"FAIL",authorized:authorized.find((x:any)=>x.rows!=null),unauthorized:unauthorized.find((x:any)=>x.rows!=null),unauthorized_vector_exposure:Number(unauthorized.find((x:any)=>x.rows!=null)?.rows),normal_client_write_denied:writeTest.denied,write_test:writeTest};writeFileSync(path.join(out,"phase12_security_validation.json"),JSON.stringify(security,null,2)+"\n");
const csv=["asset_id,filename,VISUAL_ASSET,canonical_scenes,VISUAL_SCENE,canonical_keyframes,VISUAL_KEYFRAME,TEXT_ASSET,TEXT_SCENE,TEXT_EVENT,TEXT_TRANSCRIPT,TEXT_OCR,structured_concepts",...coverage.map((x:any)=>[x.asset_id,x.filename,x.visual_asset,x.canonical_scenes,x.visual_scene,x.canonical_keyframes,x.visual_keyframe,x.text_asset,x.text_scene,x.text_event,x.text_transcript,x.text_ocr,x.structured_concepts].join(","))].join("\n")+"\n";writeFileSync(path.join(out,"phase12_representation_coverage.csv"),csv);
const bytes=Number(storage[0].row_bytes),density=106/10;const projection=(n:number)=>({assets:n,estimated_rows:Math.round(density*n),estimated_bytes:Math.round(bytes/10*n),estimated_mib:Number((bytes/10*n/1048576).toFixed(3))});writeFileSync(path.join(out,"phase12_storage_projection.json"),JSON.stringify({generated_at:now,current:{...storage[0],mib:Number((bytes/1048576).toFixed(3))},estimates:[projection(30),projection(100),projection(881)],basis:"Linear extrapolation from current 10-pilot representation density; excludes index overhead.",index_strategy:"Exact cosine search for pilot; scalable design filters by provider/model/model_version/dimensions/representation_type before distance. No mixed-space global ANN index.",indexes},null,2)+"\n");
const performanceReport=JSON.parse(readFileSync(path.join(out,"phase12_performance.json"),"utf8"));performanceReport.vector_query_latency=latency;writeFileSync(path.join(out,"phase12_performance.json"),JSON.stringify(performanceReport,null,2)+"\n");
const validation={generated_at:now,status:Object.values(gate).every(Boolean)?"PASS":"FAIL",gate,representations:reps,integrity:integrity[0],excluded:excluded[0],img1238:safety[0],concepts,security,similarity:{visual:similarity.visual_keyframe_self_retrieval,text:similarity.text_self_retrieval,text_equivalent_ties:textEquivalentTies,scene_coherence_pass:gate.visual_sanity,cross_modal_queries:Object.keys(crossModal.queries)},latency,data_preservation:changes,index_strategy:{metric:"cosine",pilot:"exact",future:"partial ANN indexes per compatible vector space only",mixed_space_global_index:false},frontend_work:false,phase13_started:false};writeFileSync(path.join(out,"phase12_validation.json"),JSON.stringify(validation,null,2)+"\n");writeFileSync(path.join(out,"phase12_summary.json"),JSON.stringify({...validation,embedding_bundle_version:"kdi_embedding_bundle_v1",visual_embedding_version:"kdi_visual_embedding_v1",text_embedding_version:"kdi_text_embedding_v1",human_gold:"DEFERRED",idempotency:"PASS",staleness:"PASS"},null,2)+"\n");console.log(JSON.stringify(validation,null,2));
