import {readFileSync,writeFileSync,mkdirSync} from "node:fs"; import path from "node:path";
const root=path.resolve(process.cwd(),".."),out=path.join(root,"reports","semantic-search","phase17"); mkdirSync(out,{recursive:true});
const env=(p:string)=>{try{const rows=readFileSync(p,"utf8").split(/\r?\n/).flatMap(line=>{const m=line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);return m?[[m[1],m[2].trim()]]:[]});return Object.fromEntries(rows)}catch{return {}}};
const a:any=env(path.join(root,".env.local")),b:any=env(path.join(process.cwd(),".env.local")),url=process.env.NEXT_PUBLIC_SUPABASE_URL||b.NEXT_PUBLIC_SUPABASE_URL||a.NEXT_PUBLIC_SUPABASE_URL,token=[process.env.SUPABASE_DASHBOARD_ACCESS_TOKEN,a.SUPABASE_DASHBOARD_ACCESS_TOKEN,b.SUPABASE_DASHBOARD_ACCESS_TOKEN].find(x=>x?.length>20);
if(!url||!token)throw Error("Supabase configuration unavailable");
const baseline:any={assets:881,semantic_assertions:333,semantic_assertion_evidence:270,asset_scenes:312,asset_events:22,asset_keyframes:345,asset_transcript_chunks:14,ocr_observations:19,semantic_narratives:37,asset_search_concepts_v2:270,semantic_embeddings:106,semantic_review_decisions:0,gold_standard_assets:0,search_queries:0},tables=Object.keys(baseline),ref=new URL(url).hostname.split(".")[0];
const sql=`select t.table_name,(xpath('/row/c/text()',query_to_xml(format('select count(*) c from public.%I',t.table_name),false,true,'')))[1]::text::bigint row_count from(values ${tables.map(t=>`('${t}')`).join(",")})t(table_name) order by 1`;
const res=await fetch(`https://api.supabase.com/v1/projects/${ref}/database/query`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({query:sql})}); if(!res.ok)throw Error(`${res.status}: ${await res.text()}`); const rows=await res.json() as any[];
const current=Object.fromEntries(rows.map(x=>[x.table_name,Number(x.row_count)])),comparison=tables.map(t=>({table:t,before:baseline[t],after:current[t],delta:current[t]-baseline[t]})),report={status:comparison.every(x=>x.delta===0)?"PASS":"FAIL",semantic_data_changed:comparison.some(x=>x.table!=="search_queries"&&x.delta!==0),production_query_pollution:current.search_queries,embeddings:{before:106,after:current.semantic_embeddings},comparison}; writeFileSync(path.join(out,"database_preservation.json"),JSON.stringify(report,null,2)); console.log(JSON.stringify(report,null,2));
