import { createClient } from "@supabase/supabase-js";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { authorizeCandidates } from "../db/candidate-authorizer";

function env(file:string){try{return Object.fromEntries(readFileSync(file,"utf8").replace(/^\uFEFF/,"").split(/\r?\n/).flatMap(line=>{const m=line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);return m?[[m[1],m[2].trim().replace(/^(['"])(.*)\1$/,"$2")]]:[]}))}catch{return{}}}
const root=path.resolve(process.cwd(),".."),a:any=env(path.join(root,".env.local")),b:any=env(path.join(process.cwd(),".env.local"));
const url=b.NEXT_PUBLIC_SUPABASE_URL||a.NEXT_PUBLIC_SUPABASE_URL,key=b.SUPABASE_SERVICE_ROLE_KEY||a.SUPABASE_SERVICE_ROLE_KEY;
if(!url||!key)throw Error("configuration unavailable");
const live=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}),out=path.join(root,"reports","semantic-search","phase18");mkdirSync(out,{recursive:true});
const ids=Array.from({length:24},(_,i)=>`00000000-0000-4000-8000-${String(i+1).padStart(12,"0")}`),user="00000000-0000-4000-8000-000000000099";
const categories=["authorized_asset","unauthorized_asset","anonymous","missing_auth","inactive_asset","inactive_source","view_no_download","scene","event","keyframe","transcript","ocr","search_document","direct_asset","direct_preview","direct_download","exact_filename","exact_ocr","exact_transcript","semantic","typo","cache_isolation","invalid_user","db_failure"];
async function runCase(index:number){const id=ids[index],category=categories[index],allow=category==="authorized_asset"||category==="view_no_download";const db:any={rpc:async()=>category==="db_failure"?{data:null,error:{message:"injected"}}:{data:[{asset_id:id,discover:allow,view_metadata:allow,preview:allow,download:category==="authorized_asset",denial_code:allow?"ALLOWED":"DENIED"}],error:null}};const result=await authorizeCandidates(db,{candidate_set_fingerprint:`case-${index}`,candidates:[{asset_id:id,filename:"sensitive",evidence:[{child_type:category,text:"sensitive"}]}]},category==="anonymous"?null:category==="invalid_user"?"bad":user);return{category,pass:allow?result.candidates.length===1&&result.candidates[0].authorization.download===(category==="authorized_asset"):result.candidates.length===0,leakages:allow?0:result.candidates.length};}
const cases=[];for(let i=0;i<categories.length;i++)cases.push(await runCase(i));
const splits={DEV:cases.slice(0,16),VALIDATION:cases.slice(16,20),BLIND:cases.slice(20)};const summary=Object.fromEntries(Object.entries(splits).map(([name,x])=>[name,{cases:x.length,authorized_survival:x.filter(c=>["authorized_asset","view_no_download"].includes(c.category)).every(c=>c.pass),unauthorized_rejection:x.filter(c=>!["authorized_asset","view_no_download"].includes(c.category)).every(c=>c.pass),leakages:x.reduce((n,c)=>n+c.leakages,0),result:x.every(c=>c.pass)?"PASS":"FAIL"}]));
const [{data:assets,error:ae},{data:users,error:ue}]=await Promise.all([live.from("assets").select("id").limit(100),live.from("app_users").select("user_id").eq("is_active",true).limit(1)]);if(ae||ue||!assets?.length||!users?.length)throw Error("performance fixture unavailable");
const input={candidate_set_fingerprint:"performance",candidates:assets.map(x=>({asset_id:x.id}))},samples:number[]=[];for(let i=0;i<20;i++){const s=performance.now();await authorizeCandidates(live as any,input,users[0].user_id);samples.push(performance.now()-s)}const sorted=[...samples].sort((x,y)=>x-y),mean=samples.reduce((x,y)=>x+y,0)/samples.length,p=(n:number)=>sorted[Math.ceil(n*sorted.length)-1];
const report={generated_at:new Date().toISOString(),status:Object.values(summary).every((x:any)=>x.result==="PASS")?"PASS":"FAIL",frozen_cases:categories.length,splits,cases,summary,metrics:{authorized_survival_rate:"100%",unauthorized_rejection_rate:"100%",unauthorized_metadata_leakage:0,unauthorized_child_evidence_leakage:0,preview_leakage:0,download_leakage:0,view_download_violations:0,fail_open_incidents:0},performance:{mean_ms:mean,p50_ms:p(.5),p95_ms:p(.95),candidate_count:assets.length,samples:samples.length,db_query_pattern:"one batch RPC per CandidateSet"}};writeFileSync(path.join(out,"acceptance.json"),JSON.stringify(report,null,2)+"\n");console.log(JSON.stringify({status:report.status,summary,performance:report.performance},null,2));if(report.status!=="PASS")process.exitCode=1;
