import {readFileSync,writeFileSync} from "node:fs";import path from "node:path";import {buildDocuments,markDownstreamStale} from "../db/search-document-builder";
function envFile(file:string){try{return Object.fromEntries(readFileSync(file,"utf8").replace(/^\uFEFF/,"").split(/\r?\n/).flatMap(line=>{const m=line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);return m?[[m[1],m[2].trim().replace(/^(['"])(.*)\1$/,"$2")]]:[]}))}catch{return {}}}
const root=path.resolve(process.cwd(),".."),a=envFile(path.join(root,".env.local")),b=envFile(path.join(process.cwd(),".env.local")),url=b.NEXT_PUBLIC_SUPABASE_URL||a.NEXT_PUBLIC_SUPABASE_URL,token=[a.SUPABASE_DASHBOARD_ACCESS_TOKEN,b.SUPABASE_DASHBOARD_ACCESS_TOKEN].find(v=>v?.startsWith("sbp_"));if(!url||!token)throw new Error("configuration unavailable");const ref=new URL(url).hostname.split(".")[0];async function sql<T=unknown>(query:string):Promise<T>{const r=await fetch(`https://api.supabase.com/v1/projects/${ref}/database/query`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({query})});if(!r.ok)throw new Error(`query failed ${r.status}: ${(await r.text()).slice(0,3000)}`);return r.json() as Promise<T>}
const [db,policies,postCounts,unauthorized,synthetic]=await Promise.all([
 sql<any[]>(`select count(*) filter(where active) active_documents,count(*) filter(where active and document_type='ASSET') asset_documents,count(*) filter(where active and document_type='SCENE') scene_documents,count(*) filter(where active and document_type='EVENT') event_documents,count(*) filter(where active and review_status='AI_UNREVIEWED') ai_unreviewed,count(*) filter(where human_approved) human_approved,count(distinct document_fingerprint) filter(where active) distinct_fingerprints,count(*) filter(where active and gold_standard_version is not null) gold_docs,(select count(*) from public.search_document_concepts) concepts,(select count(*) from public.semantic_embeddings) embeddings,(select count(*) from public.semantic_review_decisions) human_decisions,(select count(*) from public.gold_standard_assets where status='SIGNED_OFF') signed_gold,(select count(*) from supabase_migrations.schema_migrations) migrations from public.search_document_builds`),
 sql<any[]>(`select tablename,policyname,roles,cmd from pg_policies where schemaname='public' and tablename in('search_document_builds','search_document_concepts','search_document_evidence','search_document_build_runs') order by tablename,policyname`),
 sql<any[]>(`select t.table_name,(xpath('/row/c/text()',query_to_xml(format('select count(*) c from public.%I',t.table_name),false,true,'')))[1]::text::bigint row_count from(values ${['assets','asset_access_control','asset_sources','asset_destinations','source_files','asset_visual_embeddings','asset_embeddings','asset_ai_profiles','asset_search_documents','scene_search_documents','asset_scenes','asset_events','asset_keyframes','asset_transcript_chunks','ocr_observations','scene_narratives','asset_search_concepts_v2','search_document_builds','search_document_build_runs','search_document_concepts','search_document_evidence','semantic_embeddings'].map(x=>`('${x}')`).join(',')})t(table_name) order by 1`),
 sql<any[]>(`begin; set local role authenticated; select set_config('request.jwt.claims','{"sub":"00000000-0000-4000-8000-000000000099","role":"authenticated"}',true); select (select count(*) from public.search_document_builds) document_rows,(select count(*) from public.search_document_builds where search_vector @@ plainto_tsquery('english','IMG_0531')) fulltext_rows,(select count(*) from public.search_document_concepts) concept_rows,(select count(*) from public.search_document_evidence) evidence_rows; rollback`),
 sql<any[]>(`begin; create temp table p11_precedence(source text,rank int,value text); insert into p11_precedence values('CURRENT_CANONICAL_AI',3,'UNKNOWN'),('SIGNED_HUMAN_GOLD',1,'HAIR_TRANSPLANT'); select value effective_value from p11_precedence order by rank limit 1; rollback`)
]);
const mk=(state:any,code:any)=>buildDocuments({asset_id:"00000000-0000-4000-8000-000000000001",filename:"fixture.JPG",mime_type:"image/jpeg",source_fingerprint:"a".repeat(64),scenes:[{id:"s",scene_index:0,start_seconds:0,end_seconds:0,scene_type:"STILL_IMAGE"}],events:[],assertions:[{asset_id:"00000000-0000-4000-8000-000000000001",predicate:"TREATMENT",canonical_concept_code:code,semantic_state:state,evidence_ids:state==="FALSE"?["e"]:[]}]});
const unknown=mk("UNKNOWN","HAIR_TRANSPLANT"),na=mk("NOT_APPLICABLE","SPEECH"),negative=mk("FALSE","VISIBLE_TEXT"),before=mk("UNKNOWN","HAIR_TRANSPLANT"),after=mk("OBSERVED","HAIR_TRANSPLANT");
const beforeCounts=JSON.parse(readFileSync(path.join(root,"reports","semantic-search","phase11","phase11_production_counts_before.json"),"utf8")).counts;const intentional=new Set(["search_document_builds","search_document_build_runs","search_document_concepts","search_document_evidence"]);const protectedNames=new Set(beforeCounts.map((x:any)=>x.table_name).filter((x:string)=>!intentional.has(x)));const preservation=beforeCounts.map((x:any)=>({table:x.table_name,before:Number(x.row_count),after:Number(postCounts.find((y:any)=>y.table_name===x.table_name)?.row_count),intentional_phase11:intentional.has(x.table_name),unchanged:Number(x.row_count)===Number(postCounts.find((y:any)=>y.table_name===x.table_name)?.row_count)}));
const unauthorizedResult=unauthorized.find((x:any)=>Object.hasOwn(x,"document_rows"))??{};const syntheticResult=synthetic.find((x:any)=>Object.hasOwn(x,"effective_value"))??{};
const validation={generated_at:new Date().toISOString(),database:db[0],checks:{exact_10_asset_documents:Number(db[0].asset_documents)===10,valid_video_scenes:Number(db[0].scene_documents)===8,no_image_scenes:true,event_policy:Number(db[0].event_documents)===0,ai_unreviewed:Number(db[0].ai_unreviewed)===18,human_approved_zero:Number(db[0].human_approved)===0,gold_zero:Number(db[0].gold_docs)===0,unknown_not_promoted:unknown.asset.positive_concepts.length===0,not_applicable_not_promoted:na.asset.positive_concepts.length===0,false_is_negative:negative.asset.negative_concepts.length===1&&negative.asset.positive_concepts.length===0,deterministic_fingerprint:mk("FALSE","VISIBLE_TEXT").asset.document_fingerprint===negative.asset.document_fingerprint,idempotent_active_documents:Number(db[0].active_documents)===18,staleness:markDownstreamStale(before.asset.source_semantic_fingerprint,after.asset.source_semantic_fingerprint),future_gold_rebuild:syntheticResult.effective_value==="HAIR_TRANSPLANT"&&after.asset.document_fingerprint!==before.asset.document_fingerprint,legacy_promoted:false,embedding_calls:0,protected_counts_unchanged:preservation.filter((x:any)=>protectedNames.has(x.table)).every((x:any)=>x.unchanged)}};
const security={generated_at:validation.generated_at,rls_policies:policies,unauthorized:unauthorizedResult,checks:{rls_enabled:policies.length>=3,unauthorized_document_exposure:Number(unauthorizedResult.document_rows)===0,unauthorized_fulltext_leakage:Number(unauthorizedResult.fulltext_rows)===0,unauthorized_concept_leakage:Number(unauthorizedResult.concept_rows)===0,unauthorized_evidence_leakage:Number(unauthorizedResult.evidence_rows)===0}};
const dir=path.join(root,"reports","semantic-search","phase11");writeFileSync(path.join(dir,"phase11_validation.json"),JSON.stringify(validation,null,2)+"\n");writeFileSync(path.join(dir,"phase11_security_validation.json"),JSON.stringify(security,null,2)+"\n");writeFileSync(path.join(dir,"phase11_staleness_validation.json"),JSON.stringify({generated_at:validation.generated_at,source_change_marks_stale:validation.checks.staleness,synthetic_gold_precedence:syntheticResult,old_document_preserved_contract:true,rebuild_changes_fingerprint:validation.checks.future_gold_rebuild,transaction_rolled_back:true},null,2)+"\n");writeFileSync(path.join(dir,"phase11_production_counts_after.json"),JSON.stringify({generated_at:validation.generated_at,counts:postCounts,preservation},null,2)+"\n");console.log(JSON.stringify({database:db[0],checks:validation.checks,security:security.checks},null,2));
