import { createHash } from "node:crypto";import { mkdirSync,readFileSync,writeFileSync } from "node:fs";import path from "node:path";
function envFile(file:string){try{return Object.fromEntries(readFileSync(file,"utf8").replace(/^\uFEFF/,"").split(/\r?\n/).flatMap(line=>{const m=line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);return m?[[m[1],m[2].trim().replace(/^(['"])(.*)\1$/,"$2")]]:[]}))}catch{return {}}}
const root=path.resolve(process.cwd(),'..'),l=envFile(path.join(process.cwd(),'.env.local')),p=envFile(path.join(root,'.env.local')),url=l.NEXT_PUBLIC_SUPABASE_URL||p.NEXT_PUBLIC_SUPABASE_URL,token=[p.SUPABASE_DASHBOARD_ACCESS_TOKEN,l.SUPABASE_DASHBOARD_ACCESS_TOKEN].find(v=>v?.startsWith('sbp_'));if(!url||!token)throw new Error('configuration unavailable');const ref=new URL(url).hostname.split('.')[0];
async function sql<T=unknown>(query:string):Promise<T>{const r=await fetch(`https://api.supabase.com/v1/projects/${ref}/database/query`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({query})});if(!r.ok)throw new Error(`query failed ${r.status}: ${(await r.text()).slice(0,2000)}`);return r.json() as Promise<T>}
const pilots=[['IMG_0531.MP4','7f72217d-3839-4920-86b4-ccc33e9e3d95'],['IMG_1238.MP4','babae120-9372-42ad-b535-02a3276ea2be'],['IMG_3429.MP4','c86344e9-5b32-4d86-9205-67952d508651'],['IMG_9871.MOV','444da390-0117-4380-8c87-d7c32f2903ff'],['DSC03753.JPG','37838d30-a0ce-4f90-8cc3-c986db0aaa65'],['DSC08097.JPG','6215ad8b-12be-4a8e-bc49-f6b3dcf55c21'],['IMG_0493.MP4','64712c6a-c02c-46e9-9f73-16786109468b'],['IMG_1148.MP4','47611c6d-7923-42a4-87b6-c2a416a90f5c'],['IMG_2963.MP4','bfae6c51-5d71-47ae-a3e1-6d07092b8896'],['IMG_1160.MP4','753eb5f3-82c7-4148-a226-d5b960fd8619']];
const ids=pilots.map(x=>`'${x[1]}'::uuid`).join(',');
const [rows,counts,migrations]=await Promise.all([
 sql<any[]>(`select a.id asset_id,a.original_file_name filename,a.mime_type,a.checksum_sha256,a.content_hash,
  (select to_jsonb(d) from public.asset_search_documents d where d.asset_id=a.id) legacy_asset_document,
  (select to_jsonb(p) from public.asset_ai_profiles p where p.asset_id=a.id) ai_profile_comparison,
  coalesce((select jsonb_agg(to_jsonb(s) order by s.scene_index) from public.asset_scenes s where s.asset_id=a.id and s.canonical_active),'[]') scenes,
  coalesce((select jsonb_agg(to_jsonb(e) order by e.start_time) from public.asset_events e where e.asset_id=a.id),'[]') events,
  coalesce((select jsonb_agg(to_jsonb(x)) from public.effective_semantic_assertions x where x.asset_id=a.id),'[]') effective_assertions,
  coalesce((select jsonb_agg(to_jsonb(n)) from public.semantic_narratives n where n.asset_id=a.id),'[]') semantic_narratives,
  coalesce((select jsonb_agg(to_jsonb(n)) from public.scene_narratives n where n.asset_id=a.id),'[]') legacy_scene_narratives,
  coalesce((select jsonb_agg(to_jsonb(t)) from public.asset_transcript_chunks t where t.asset_id=a.id),'[]') transcripts,
  coalesce((select jsonb_agg(to_jsonb(o)) from public.ocr_observations o where o.asset_id=a.id),'[]') ocr,
  coalesce((select jsonb_agg(to_jsonb(c)) from public.asset_search_concepts_v2 c where c.asset_id=a.id),'[]') canonical_concepts
 from public.assets a where a.id in(${ids}) order by array_position(array[${ids}],a.id)`),
 sql(`select t.table_name,(xpath('/row/c/text()',query_to_xml(format('select count(*) c from public.%I',t.table_name),false,true,'')))[1]::text::bigint row_count from(values ${['assets','asset_access_control','asset_sources','asset_destinations','source_files','asset_visual_embeddings','asset_embeddings','asset_ai_profiles','asset_search_documents','scene_search_documents','asset_scenes','asset_events','asset_keyframes','asset_transcript_chunks','ocr_observations','scene_narratives','search_document_builds','asset_search_concepts_v2','semantic_embeddings'].map(x=>`('${x}')`).join(',')})t(table_name) order by 1`),
 sql<any[]>(`select version,name from supabase_migrations.schema_migrations order by version`)
]);
const byId=new Map(rows.map((r:any)=>[r.asset_id,r]));const assets=pilots.map(([filename,id])=>{const r=byId.get(id);if(!r)return{filename,asset_id:id,status:'MISSING'};const legacy=Boolean(r.legacy_asset_document),assertions=r.effective_assertions.length,transcripts=r.transcripts.length,ocr=r.ocr.length;return{...r,expected_filename:filename,filename_match:r.filename===filename,status:'FOUND',source_fingerprint:r.checksum_sha256||r.content_hash,classification:{legacy_document:legacy?'LEGACY':'MISSING',canonical_semantics:assertions?'CANONICAL_COMPATIBLE':'MISSING_FACTS',transcript:transcripts?'CANONICAL_COMPATIBLE':'MISSING_FACTS',ocr:ocr?'CANONICAL_COMPATIBLE':'MISSING_FACTS',unsupported_facts:legacy&&assertions===0?'LEGACY_NOT_AUTHORITY':null}}});
const out=path.join(root,'reports','semantic-search','phase11');mkdirSync(out,{recursive:true});const payload={generated_at:new Date().toISOString(),specification:'semantic_index_v1',ontology:'KDI_SEMANTIC_V2',pilot_expected:10,pilot_found:assets.filter((x:any)=>x.status==='FOUND').length,assets,protected_counts:counts,migrations:migrations.length,snapshot_fingerprint:createHash('sha256').update(JSON.stringify({assets,counts})).digest('hex')};writeFileSync(path.join(out,'phase11_existing_search_document_audit.json'),JSON.stringify(payload,null,2)+'\n');writeFileSync(path.join(out,'phase11_production_counts_before.json'),JSON.stringify({generated_at:payload.generated_at,counts},null,2)+'\n');console.log(JSON.stringify({pilot_found:payload.pilot_found,migrations:payload.migrations,summary:assets.map((x:any)=>({asset_id:x.asset_id,filename:x.filename,scenes:x.scenes?.length,events:x.events?.length,assertions:x.effective_assertions?.length,transcripts:x.transcripts?.length,ocr:x.ocr?.length,legacy:Boolean(x.legacy_asset_document)}))},null,2));
