import { createClient } from "@supabase/supabase-js";
import { readFileSync,writeFileSync,mkdirSync } from "node:fs";
import path from "node:path";
import { interpretQuery } from "../db/query-interpreter";
import { classifyRequirements } from "../db/requirement-classifier";
import { expandQuery } from "../db/query-expander";
import { retrieveCandidates } from "../db/candidate-retriever";
import { authorizeCandidates } from "../db/candidate-authorizer";
import { loadRerankingEvidence,rerankAuthorizedCandidates } from "../db/deterministic-reranker";
import { encodePhase17Queries } from "../db/phase17-query-encoder";
function env(file:string){try{return Object.fromEntries(readFileSync(file,"utf8").replace(/^\uFEFF/,"").split(/\r?\n/).flatMap(line=>{const m=line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);return m?[[m[1],m[2].trim().replace(/^(['"])(.*)\1$/,"$2")]]:[]}))}catch{return{}}}
const root=path.resolve(import.meta.dirname,"../.."),a:any=env(path.join(root,".env.local")),b:any=env(path.join(root,"dashboard",".env.local")),url=b.NEXT_PUBLIC_SUPABASE_URL||a.NEXT_PUBLIC_SUPABASE_URL,key=b.SUPABASE_SERVICE_ROLE_KEY||a.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw Error("configuration unavailable");const db=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}),names=["DSC03753.JPG","DSC08097.JPG","IMG_0493.MP4","IMG_0531.MP4","IMG_1148.MP4","IMG_1160.MP4","IMG_1238.MP4","IMG_2963.MP4","IMG_3429.MP4","IMG_9871.MOV"],selected=await db.from("assets").select("id,file_name").in("file_name",names);if(selected.error||selected.data?.length!==10)throw selected.error??Error("pilot unavailable");const ids=selected.data.map(x=>x.id),byName=new Map(selected.data.map(x=>[x.file_name,x.id])),snapshot=await db.from("asset_access_control").select("*").in("asset_id",ids);if(snapshot.error||snapshot.data?.length!==10)throw snapshot.error??Error("ACL snapshot unavailable");const user=await db.from("app_users").select("user_id").eq("is_active",true).limit(1).single();if(user.error)throw user.error;
const expectations=[{query:"neck injection",allowed:["IMG_3429.MP4"]},{query:"nek injecton",allowed:["IMG_3429.MP4"]},{query:"doctor injecting neck",allowed:["IMG_3429.MP4"]},{query:"lower face injection",allowed:["IMG_0531.MP4"]},{query:"doctor working on scalp",allowed:["IMG_1148.MP4","IMG_1238.MP4","IMG_2963.MP4"]},{query:"clinician treating scalp",allowed:["IMG_1148.MP4","IMG_1238.MP4","IMG_2963.MP4"]},{query:"frontal scalp procedure",allowed:["IMG_2963.MP4","IMG_1148.MP4","IMG_1238.MP4"]},{query:"front-facing portrait",allowed:["DSC03753.JPG","DSC08097.JPG","IMG_9871.MOV"]},{query:"scalp treatment",allowed:["IMG_1148.MP4","IMG_1238.MP4","IMG_2963.MP4"]},{query:"clinician cleansing cheek",allowed:["IMG_1160.MP4"]}],noMatch=["airplane cockpit","wedding ceremony","football stadium","underwater coral reef"],allTests=[...expectations,...noMatch.map(query=>({query,allowed:[]}))],vectors=await encodePhase17Queries(allTests.map(x=>x.query)),rows:any[]=[];let restored=false;
try{const updated=await db.from("asset_access_control").update({internal_usage_status:"ALLOWED",is_clinical:false,requires_clinical_permission:false,sensitivity_level:"GENERAL",download_allowed:false}).in("asset_id",ids);if(updated.error)throw updated.error;
 for(const [index,test] of allTests.entries()){const parsed=await interpretQuery(test.query),requirements=classifyRequirements(parsed),expanded=expandQuery(parsed,requirements),retrieved=await retrieveCandidates(db as any,{queryPlan:parsed,requirementPlan:requirements,expandedQueryPlan:expanded,queryVectors:vectors[index],requestedCount:10}),pilotCandidates={...retrieved,candidates:retrieved.candidates.filter((x:any)=>ids.includes(x.asset_id))},authorized=await authorizeCandidates(db as any,pilotCandidates,user.data.user_id),evidence=await loadRerankingEvidence(db as any,authorized as any),ranked=rerankAuthorizedCandidates(authorized as any,requirements,expanded,evidence,parsed.result_request.effective_count),ordered=ranked.candidates.filter((x:any)=>x.phase19.eligible).map((x:any)=>x.filename),top=ordered[0]??null,pass=test.allowed.length?test.allowed.includes(top):ordered.length===0;rows.push({query:test.query,expected:test.allowed,top,ordered,pass,ranking_fingerprint:ranked.ranking_fingerprint,authorization_boundary:ranked.diagnostics.authorization_boundary_valid,database_query_count:evidence.databaseQueryCount,top_explanation:ranked.candidates[0]?{coverage:ranked.candidates[0].phase19.strongRequirementCoverage,exact:ranked.candidates[0].phase19.exactCanonicalMatches,coherent:ranked.candidates[0].phase19.coherentRequirementGroups,contributions:ranked.candidates[0].phase19.evidenceContributions.map((x:any)=>({class:x.requirementClass,concept:x.matchedConcept,type:x.matchType,state:x.state,contribution:x.finalContribution}))}:null})}
}finally{for(const row of snapshot.data){const{asset_id,created_at,updated_at,...restore}=row;const result=await db.from("asset_access_control").update(restore).eq("asset_id",asset_id);if(result.error)throw result.error}const check=await db.from("asset_access_control").select("*").in("asset_id",ids);const keys=["internal_usage_status","is_clinical","requires_clinical_permission","sensitivity_level","download_allowed","classification_status","review_status","consent_status","marketing_usage_status","external_ai_status"];restored=!check.error&&snapshot.data.every(before=>{const after=check.data?.find(x=>x.asset_id===before.asset_id);return after&&keys.every(k=>after[k]===before[k])})}
const neck=rows.find(x=>x.query==="neck injection"),lower=rows.find(x=>x.query==="lower face injection"),report={generated_at:new Date().toISOString(),status:rows.every(x=>x.pass)&&restored?"PASS":"FAIL",cases:rows.length,passed:rows.filter(x=>x.pass).length,failed:rows.filter(x=>!x.pass).length,acl_restored:restored,pilot_count:ids.length,rows,key_pairwise:{neck_injection:neck?.ordered.indexOf("IMG_3429.MP4")<neck?.ordered.indexOf("IMG_0531.MP4"),lower_face_injection:lower?.ordered.indexOf("IMG_0531.MP4")<lower?.ordered.indexOf("IMG_3429.MP4")}};const out=path.join(root,"reports","semantic-search","phase19");mkdirSync(out,{recursive:true});writeFileSync(path.join(out,"live_pilot.json"),JSON.stringify(report,null,2)+"\n");console.log(JSON.stringify({status:report.status,cases:report.cases,passed:report.passed,failed:report.failed,acl_restored:restored,key_pairwise:report.key_pairwise,rows:rows.map(x=>({query:x.query,top:x.top,pass:x.pass,ordered:x.ordered}))},null,2));if(report.status!=="PASS")process.exitCode=1;
