import { readFileSync } from "node:fs";import path from "node:path";
function envFile(file:string){try{return Object.fromEntries(readFileSync(file,"utf8").replace(/^\uFEFF/,"").split(/\r?\n/).flatMap(line=>{const m=line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);return m?[[m[1],m[2].trim().replace(/^(['"])(.*)\1$/,"$2")]]:[]}))}catch{return {}}}
const root=path.resolve(process.cwd(),'..'),l=envFile(path.join(process.cwd(),'.env.local')),p=envFile(path.join(root,'.env.local')),url=l.NEXT_PUBLIC_SUPABASE_URL||p.NEXT_PUBLIC_SUPABASE_URL,token=[p.SUPABASE_DASHBOARD_ACCESS_TOKEN,l.SUPABASE_DASHBOARD_ACCESS_TOKEN].find(v=>v?.startsWith('sbp_'));if(!url||!token)throw new Error('configuration unavailable');const ref=new URL(url).hostname.split('.')[0];
const query=`begin;create temp table phase10_rls_context(asset_id uuid,user_id uuid) on commit drop;grant select on phase10_rls_context to authenticated;
do $$declare a uuid:=gen_random_uuid();u uuid;r uuid;s uuid;begin select user_id into u from public.app_users where is_active order by can_view_clinical desc limit 1;if u is null then raise exception 'no authorized test user';end if;insert into public.assets(id,checksum_sha256,original_file_name,file_name,mime_type,migration_status,upload_status)values(a,encode(digest(a::text,'sha256'),'hex'),'phase10-rls.jpg','phase10-rls.jpg','image/jpeg','PENDING','PENDING');insert into public.asset_access_control(asset_id,is_clinical,sensitivity_level,internal_usage_status)values(a,false,'GENERAL','ALLOWED');insert into public.semantic_analysis_runs(asset_id,run_type,status,processor_version,configuration_fingerprint,source_fingerprint)values(a,'RLS_TEST','COMPLETED','test','rls-cfg','rls-src')returning id into r;insert into public.semantic_assertions(asset_id,layer_id,subject_type,predicate,semantic_state,search_critical,analysis_run_id,origin,ontology_version,semantic_spec_version,source_fingerprint,idempotency_key)values(a,'GLOBAL_ASSET_UNDERSTANDING','ASSET','rls_test','UNKNOWN',false,r,'AI_MODEL','KDI_SEMANTIC_V2','semantic_index_v1','rls-src','rls-test');insert into phase10_rls_context values(a,u);if(select count(*) from public.semantic_assertions where asset_id=a)<>1 then raise exception 'backend/service test failed';end if;end$$;
set local role authenticated;select set_config('request.jwt.claims',jsonb_build_object('sub',(select user_id::text from phase10_rls_context),'iss','https://${ref}.supabase.co/auth/v1')::text,true);
do $$begin if(select count(*) from public.semantic_assertions where asset_id=(select asset_id from phase10_rls_context))<>1 then raise exception 'authorized assertion read failed';end if;if(select count(*) from public.effective_semantic_assertions where asset_id=(select asset_id from phase10_rls_context))<>1 then raise exception 'authorized effective view read failed';end if;begin insert into public.gold_standard_sets(code,revision,status,semantic_spec_version,source_fingerprint)values('unauthorized-write',1,'DRAFT','semantic_index_v1','x');raise exception 'unauthorized gold write permitted';exception when insufficient_privilege then null;end;begin insert into public.semantic_review_sessions(reviewer_label,semantic_spec_version)values('unauthorized','semantic_index_v1');raise exception 'unauthorized review write permitted';exception when insufficient_privilege then null;end;end$$;
select set_config('request.jwt.claims',jsonb_build_object('sub',gen_random_uuid()::text,'iss','https://${ref}.supabase.co/auth/v1')::text,true);
do $$begin if(select count(*) from public.semantic_assertions where asset_id=(select asset_id from phase10_rls_context))<>0 then raise exception 'unauthorized assertion exposure';end if;if(select count(*) from public.effective_semantic_assertions where asset_id=(select asset_id from phase10_rls_context))<>0 then raise exception 'unauthorized effective view exposure';end if;if(select count(*) from public.asset_search_concepts_v2 where asset_id=(select asset_id from phase10_rls_context))<>0 then raise exception 'unauthorized concept exposure';end if;if(select count(*) from public.gold_standard_assets where asset_id=(select asset_id from phase10_rls_context))<>0 then raise exception 'unauthorized gold exposure';end if;end$$;reset role;rollback;`;
const response=await fetch(`https://api.supabase.com/v1/projects/${ref}/database/query`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({query})});if(!response.ok)throw new Error(`RLS test failed ${response.status}: ${(await response.text()).slice(0,3000)}`);console.log(JSON.stringify({authorized_user_read:'PASS',unauthorized_assertion_exposure:0,unauthorized_effective_view_exposure:0,unauthorized_search_concept_exposure:0,unauthorized_gold_exposure:0,unauthorized_review_writes:0,unauthorized_gold_writes:0,backend_access:'PASS',rolled_back:true},null,2));
