import{createHash}from"node:crypto";import{createClient}from"@supabase/supabase-js";import{mkdirSync,readFileSync,writeFileSync}from"node:fs";import path from"node:path";
const root=path.resolve(import.meta.dirname,"../.."),dir=path.join(root,"reports","semantic-search","phase28");mkdirSync(dir,{recursive:true});
function env(file:string){try{return Object.fromEntries(readFileSync(file,"utf8").replace(/^\uFEFF/,"").split(/\r?\n/).flatMap(line=>{const m=line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);return m?[[m[1],m[2].trim().replace(/^(['"])(.*)\1$/,"$2")]]:[]}))}catch{return{}}}
const a:any=env(path.join(root,".env.local")),b:any=env(path.join(root,"dashboard",".env.local")),url=b.NEXT_PUBLIC_SUPABASE_URL||a.NEXT_PUBLIC_SUPABASE_URL,key=b.SUPABASE_SERVICE_ROLE_KEY||a.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw Error("DATABASE_CONFIGURATION_UNAVAILABLE");const db=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});
const manifest=["DSC03753.JPG","DSC08097.JPG","IMG_0493.MP4","IMG_0531.MP4","IMG_1148.MP4","IMG_1160.MP4","IMG_1238.MP4","IMG_2963.MP4","IMG_3429.MP4","IMG_9871.MOV"],expectedSpec="6da50e2153f6fcb6c9ef27c308ad44d0d2024e702e3faad47586b0068ba64fd7";
const many=async(q:any)=>{const{data,error}=await q;if(error)throw error;return data??[]},assets=await many(db.from("assets").select("*").in("file_name",manifest)),ids=assets.map((x:any)=>x.id);if(ids.length!==10)throw Error(`PILOT_MANIFEST:${ids.length}`);
const tables:any={assets,layers:await many(db.from("asset_semantic_layers").select("*").in("asset_id",ids).eq("active",true)),assertions:await many(db.from("semantic_assertions").select("*").in("asset_id",ids).eq("active",true).is("superseded_by",null)),evidence:await many(db.from("semantic_assertion_evidence").select("*").in("asset_id",ids)),profiles:await many(db.from("asset_ai_profiles").select("*").in("asset_id",ids)),scenes:await many(db.from("asset_scenes").select("*").in("asset_id",ids)),events:await many(db.from("asset_events").select("*").in("asset_id",ids)),narratives:await many(db.from("semantic_narratives").select("*").in("asset_id",ids).eq("active",true)),documents:await many(db.from("search_document_builds").select("*").in("asset_id",ids).eq("active",true).eq("stale",false)),concepts:await many(db.from("search_document_concepts").select("*").in("asset_id",ids)),document_evidence:await many(db.from("search_document_evidence").select("*").in("asset_id",ids)),embeddings:await many(db.from("semantic_embeddings").select("*").in("asset_id",ids).eq("active",true)),acl:await many(db.from("asset_access_control").select("*").in("asset_id",ids)),analysis_runs:await many(db.from("semantic_analysis_runs").select("*").in("asset_id",ids))};
const stable=(x:any):string=>Array.isArray(x)?`[${[...x].sort((u,v)=>String(u.id??u.asset_id).localeCompare(String(v.id??v.asset_id))).map(stable).join(",")}]`:x&&typeof x==="object"?`{${Object.keys(x).sort().map(k=>JSON.stringify(k)+":"+stable(x[k])).join(",")}}`:JSON.stringify(x),sha=(x:any)=>createHash("sha256").update(stable(x)).digest("hex");
const layerIds=new Set(tables.layers.map((x:any)=>`${x.asset_id}:${x.layer_id}`)),assertionIds=new Set(tables.assertions.map((x:any)=>String(x.id))),sceneIds=new Set(tables.scenes.map((x:any)=>String(x.id))),eventIds=new Set(tables.events.map((x:any)=>String(x.id))),documentIds=new Set(tables.documents.map((x:any)=>String(x.id)));
const complete=tables.layers.filter((x:any)=>x.processing_status==="COMPLETE"&&x.completeness_status==="COMPLETE").length,partial=tables.layers.filter((x:any)=>x.completeness_status==="PARTIAL").length,profiles=tables.profiles,descriptions={short:profiles.filter((x:any)=>String(x.short_description??"").trim()).length,detailed:profiles.filter((x:any)=>String(x.detailed_description??"").trim()).length,exact_duplicates:profiles.filter((x:any)=>String(x.short_description??"").trim()===String(x.detailed_description??"").trim()).length};
const evidenceIntegrity={orphan_assertions:tables.evidence.filter((x:any)=>!assertionIds.has(String(x.assertion_id))).length,wrong_asset:tables.evidence.filter((x:any)=>tables.assertions.find((a:any)=>String(a.id)===String(x.assertion_id))?.asset_id!==x.asset_id).length,missing_scenes:tables.assertions.filter((x:any)=>x.scene_id&&!sceneIds.has(String(x.scene_id))).length,missing_events:tables.assertions.filter((x:any)=>x.event_id&&!eventIds.has(String(x.event_id))).length};
const perAsset=(rows:any[])=>Object.fromEntries(manifest.map(name=>{const id=assets.find((x:any)=>x.file_name===name)?.id;return[name,rows.filter((x:any)=>x.asset_id===id).length]}));
const spec=JSON.parse(readFileSync(path.join(root,"config","semantic-search","kdi_semantic_18_layer_v1.json"),"utf8")),gold=JSON.parse(readFileSync(path.join(root,"reports","semantic-search","phase25","kdi_gold_answers_v1.certified.json"),"utf8")),lock=JSON.parse(readFileSync(path.join(root,"reports","semantic-search","phase25","gold_lock.json"),"utf8")),benchmark=JSON.parse(readFileSync(path.join(root,"config","semantic-search","kdi_semantic_benchmark_v1.json"),"utf8"));
const embeddingLineage={active:tables.embeddings.length,stale_active:tables.embeddings.filter((x:any)=>x.stale).length,bad_dimensions:tables.embeddings.filter((x:any)=>![384,512].includes(Number(x.dimensions))).length,missing_document:tables.embeddings.filter((x:any)=>x.source_document_id&&!documentIds.has(String(x.source_document_id))).length,per_asset:perAsset(tables.embeddings)};
const currentRuns=tables.analysis_runs.filter((x:any)=>x.completed_at),provenance={invalid_time:currentRuns.filter((x:any)=>new Date(x.completed_at)<new Date(x.started_at)).length,legacy_missing_model:tables.analysis_runs.filter((x:any)=>!x.model||!x.provider).length,zero_duration:currentRuns.filter((x:any)=>new Date(x.completed_at).getTime()===new Date(x.started_at).getTime()).length};
const snapshot=Object.fromEntries(Object.entries(tables).filter(([k])=>!["analysis_runs"].includes(k)).map(([k,v])=>[k,{count:(v as any[]).length,hash:sha(v)}]));
const report={generated_at:new Date().toISOString(),source:"LIVE_SUPABASE_READ_ONLY",project_ref:new URL(url).hostname.split(".")[0],manifest:{expected:manifest,actual:assets.map((x:any)=>x.file_name).sort(),pass:manifest.every(x=>assets.some((a:any)=>a.file_name===x))},spec:{version:spec.spec_version,status:spec.status,layers:spec.layers.length,populated_layers:spec.layers.filter((x:any)=>x.description&&x.applicability_rules?.length&&x.completeness_rules?.length).length,global_rules:Boolean(spec.global_rules?.future_run_contract),expected_fingerprint:expectedSpec,lineage_fingerprints:[...new Set(tables.documents.map((x:any)=>x.semantic_spec_fingerprint).filter(Boolean))]},layers:{count:tables.layers.length,complete,partial,missing:180-tables.layers.length,duplicate_active:tables.layers.length-layerIds.size,per_asset:perAsset(tables.layers),states:Object.fromEntries(["OBSERVED","FALSE","UNKNOWN","NOT_APPLICABLE"].map(s=>[s,tables.layers.filter((x:any)=>x.semantic_state===s).length]))},evidence:evidenceIntegrity,descriptions,narratives:{active:tables.narratives.length,per_asset:perAsset(tables.narratives)},search_documents:{active:tables.documents.length,asset_documents:tables.documents.filter((x:any)=>x.document_type==="ASSET").length,per_asset:perAsset(tables.documents),concept_links:tables.concepts.length,evidence_links:tables.document_evidence.length,stale:tables.documents.filter((x:any)=>x.stale).length},embeddings:embeddingLineage,provenance,gold:{version:gold.gold_version,status:gold.status,certification:gold.certification_status,lock:gold.lock_status,immutable:gold.immutable,fingerprint:gold.gold_fingerprint,lock_record:lock,cases:gold.cases.length,determinate:gold.cases.filter((x:any)=>x.determinacy==="GOLD_DETERMINATE").length},benchmark:{version:benchmark.benchmark_version,cases:benchmark.cases.length,single:benchmark.cases.filter((x:any[])=>!Array.isArray(x[2])).length,multi:benchmark.cases.filter((x:any[])=>Array.isArray(x[2])).length},snapshot};
const mode=process.argv.includes("--after")?"after":"before";writeFileSync(path.join(dir,`foundation_${mode}.json`),JSON.stringify(report,null,2)+"\n");console.log(JSON.stringify({mode,manifest:report.manifest.pass,layers:report.layers,evidence:report.evidence,descriptions:report.descriptions,narratives:report.narratives,documents:report.search_documents,embeddings:report.embeddings,provenance:report.provenance,gold:report.gold,benchmark:report.benchmark},null,2));
