import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
function env(file:string){try{return Object.fromEntries(readFileSync(file,"utf8").replace(/^\uFEFF/,"").split(/\r?\n/).flatMap(line=>{const m=line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);return m?[[m[1],m[2].trim().replace(/^(['"])(.*)\1$/,"$2")]]:[]}))}catch{return{}}}
const root=path.resolve(import.meta.dirname,"../.."),a:any=env(path.join(root,".env.local")),b:any=env(path.join(root,"dashboard",".env.local")),url=b.NEXT_PUBLIC_SUPABASE_URL||a.NEXT_PUBLIC_SUPABASE_URL,token=[a.SUPABASE_DASHBOARD_ACCESS_TOKEN,b.SUPABASE_DASHBOARD_ACCESS_TOKEN].find(x=>x?.startsWith("sbp_"));if(!url||!token)throw Error("configuration unavailable");const ref=new URL(url).hostname.split(".")[0];
async function sql(query:string){const response=await fetch(`https://api.supabase.com/v1/projects/${ref}/database/query`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({query})});if(!response.ok)throw Error(`preflight query failed ${response.status}`);return response.json()}
const counts=await sql(`select * from (values
('assets',(select count(*) from public.assets)),('asset_sources',(select count(*) from public.asset_sources)),('asset_access_control',(select count(*) from public.asset_access_control)),('semantic_embeddings',(select count(*) from public.semantic_embeddings)),('asset_search_concepts_v2',(select count(*) from public.asset_search_concepts_v2)),('semantic_assertions',(select count(*) from public.semantic_assertions)),('semantic_assertion_evidence',(select count(*) from public.semantic_assertion_evidence)),('asset_search_documents',(select count(*) from public.asset_search_documents)),('scene_search_documents',(select count(*) from public.scene_search_documents)),('app_users',(select count(*) from public.app_users)))x(name,row_count)`);
const migration=await sql(`select version,name,statements from supabase_migrations.schema_migrations where version in ('20260826034218','20260826043121') order by version`);
const acl=await sql(`select internal_usage_status,is_clinical,requires_clinical_permission,sensitivity_level,download_allowed,count(*) row_count from public.asset_access_control group by 1,2,3,4,5 order by row_count desc`);
const pilot=await sql(`select a.file_name,c.id,c.canonical_code,c.display_text,c.scene_id,c.event_id from public.asset_search_concepts_v2 c join public.assets a on a.id=c.asset_id where a.file_name in('DSC03753.JPG','DSC08097.JPG','IMG_0493.MP4','IMG_0531.MP4','IMG_1148.MP4','IMG_1160.MP4','IMG_1238.MP4','IMG_2963.MP4','IMG_3429.MP4','IMG_9871.MOV') order by a.file_name,c.canonical_code,c.scene_id nulls first`);
const pilotAssets=await sql(`select a.file_name,a.id,acl.internal_usage_status,acl.is_clinical,acl.requires_clinical_permission,acl.sensitivity_level,acl.download_allowed from public.assets a left join public.asset_access_control acl on acl.asset_id=a.id where a.file_name in('DSC03753.JPG','DSC08097.JPG','IMG_0493.MP4','IMG_0531.MP4','IMG_1148.MP4','IMG_1160.MP4','IMG_1238.MP4','IMG_2963.MP4','IMG_3429.MP4','IMG_9871.MOV') order by a.file_name`);
const temporary=await sql(`select
 (select count(*) from auth.users where email ilike 'phase19-%' or email ilike '%phase19%') temporary_auth_users,
 (select count(*) from public.app_users where email ilike 'phase19-%' or email ilike '%phase19%') temporary_app_users,
 (select count(*) from public.assets where file_name ilike 'phase19-%' or file_name ilike '%phase19%') temporary_assets,
 (select count(*) from public.asset_access_control acl join public.assets a on a.id=acl.asset_id where a.file_name ilike 'phase19-%' or a.file_name ilike '%phase19%') temporary_acl_rows`);
const columns=await sql(`select table_name,column_name,data_type from information_schema.columns where table_schema='public' and table_name in('semantic_assertions','semantic_assertion_evidence','asset_search_concepts_v2','asset_search_documents','scene_search_documents','asset_scenes','asset_events','scene_people','scene_anatomy','scene_actions','scene_treatments','ocr_observations','asset_transcript_chunks') order by table_name,ordinal_position`);
const report={generated_at:new Date().toISOString(),counts,acl,migration_history:migration,pilot_assets:pilotAssets,temporary,pilot_concepts:pilot,columns};const out=path.join(root,"reports","semantic-search","phase19");mkdirSync(out,{recursive:true});writeFileSync(path.join(out,"live_preflight.json"),JSON.stringify(report,null,2)+"\n");console.log(JSON.stringify({counts,acl,migration_history:migration,pilot_assets:pilotAssets,temporary,pilot_concept_rows:(pilot as any[]).length,tables:[...new Set((columns as any[]).map(x=>x.table_name))]},null,2));
