import { readFileSync } from "node:fs";
import path from "node:path";
import type { Facts } from "./phase18-protected-oracle";
function env(file:string){try{return Object.fromEntries(readFileSync(file,"utf8").replace(/^\uFEFF/,"").split(/\r?\n/).flatMap(line=>{const m=line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);return m?[[m[1],m[2].trim().replace(/^(['"])(.*)\1$/,"$2")]]:[]}))}catch{return{}}}
const root=path.resolve(import.meta.dirname,"../.."),a:any=env(path.join(root,".env.local")),b:any=env(path.join(root,"dashboard",".env.local")),url=b.NEXT_PUBLIC_SUPABASE_URL||a.NEXT_PUBLIC_SUPABASE_URL,token=[a.SUPABASE_DASHBOARD_ACCESS_TOKEN,b.SUPABASE_DASHBOARD_ACCESS_TOKEN].find(x=>x?.startsWith("sbp_"));if(!url||!token)throw Error("configuration unavailable");
const ref=new URL(url).hostname.split(".")[0],input=JSON.parse(readFileSync(0,"utf8")) as Facts,q=(x:string)=>`'${x.replace(/'/g,"''")}'`,bool=(x:boolean)=>x?"true":"false",nullable=(x:boolean|null)=>x===null?"null":bool(x);
const sql=`begin;set local statement_timeout='30s';do $x$ declare a uuid;active_user uuid;inactive_user uuid;sf uuid;folder uuid;chosen uuid;begin
select id into strict a from public.assets where file_name='IMG_3429.MP4';select user_id into strict active_user from public.app_users where is_active order by user_id limit 1;select user_id into inactive_user from public.app_users where not is_active order by user_id limit 1;
select s.source_file_id,f.id into strict sf,folder from public.asset_sources s join public.source_files x on x.id=s.source_file_id join public.source_folders f on f.id=x.source_folder_id where s.asset_id=a limit 1;
chosen=case when not ${bool(input.authenticated&&input.valid_user)} then gen_random_uuid() when not ${bool(input.user_active)} then inactive_user else active_user end;
update public.app_users set can_view_clinical=${bool(input.user_clinical)},can_download=${bool(input.user_download)} where user_id=active_user;
update public.assets set upload_status=${input.asset_available?q("PENDING"):q("FAILED")} where id=a;update public.source_folders set active=${bool(input.source_available)} where id=folder;update public.source_files set is_missing=${bool(input.source_missing)},trashed=${bool(input.source_trashed)},sync_classification=${input.source_available?q("UNCHANGED"):q("REMOVED_FROM_SOURCE")} where id=sf;
delete from public.asset_access_control where asset_id=a;if ${bool(input.auth_row)} then insert into public.asset_access_control(asset_id,internal_usage_status,is_clinical,requires_clinical_permission,sensitivity_level,download_allowed)values(a,${q(input.internal)},${nullable(input.clinical)},${nullable(input.requires_clinical)},${q(input.sensitivity)},${nullable(input.download_allowed)});end if;
create temporary table phase18_result on commit drop as select * from public.phase18_authorize_candidates_for(chosen,array[a]);end$x$;select discover,view_metadata,preview,download from phase18_result;rollback;`;
const response=await fetch(`https://api.supabase.com/v1/projects/${ref}/database/query`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({query:sql})});if(!response.ok)throw Error(`runner failed ${response.status}: ${(await response.text()).slice(0,1000)}`);const rows=await response.json() as any[];process.stdout.write(JSON.stringify(rows.at(-1)));
