import {readFileSync,writeFileSync,mkdirSync} from "node:fs";import path from "node:path";
function env(file:string){try{return Object.fromEntries(readFileSync(file,"utf8").replace(/^\uFEFF/,"").split(/\r?\n/).flatMap(line=>{const m=line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);return m?[[m[1],m[2].trim().replace(/^(['"])(.*)\1$/,"$2")]]:[]}))}catch{return{}}}
const root=path.resolve(import.meta.dirname,"../.."),a:any=env(path.join(root,".env.local")),b:any=env(path.join(root,"dashboard",".env.local")),url=b.NEXT_PUBLIC_SUPABASE_URL||a.NEXT_PUBLIC_SUPABASE_URL,token=[a.SUPABASE_DASHBOARD_ACCESS_TOKEN,b.SUPABASE_DASHBOARD_ACCESS_TOKEN].find(x=>x?.startsWith("sbp_"));if(!url||!token)throw Error("configuration unavailable");const ref=new URL(url).hostname.split(".")[0];async function sql(query:string){const r=await fetch(`https://api.supabase.com/v1/projects/${ref}/database/query`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({query})});if(!r.ok)throw Error(`preflight failed ${r.status}`);return r.json()}
const names=['DSC03753.JPG','DSC08097.JPG','IMG_0493.MP4','IMG_0531.MP4','IMG_1148.MP4','IMG_1160.MP4','IMG_1238.MP4','IMG_2963.MP4','IMG_3429.MP4','IMG_9871.MOV'];
const [counts,acl,pilots,temporary,migrations]=await Promise.all([
 sql(`select * from(values('assets',(select count(*) from public.assets)),('asset_sources',(select count(*) from public.asset_sources)),('asset_access_control',(select count(*) from public.asset_access_control)),('semantic_embeddings',(select count(*) from public.semantic_embeddings)),('asset_search_concepts_v2',(select count(*) from public.asset_search_concepts_v2)),('semantic_assertions',(select count(*) from public.semantic_assertions)),('semantic_assertion_evidence',(select count(*) from public.semantic_assertion_evidence)),('asset_search_documents',(select count(*) from public.asset_search_documents)),('scene_search_documents',(select count(*) from public.scene_search_documents)),('app_users',(select count(*) from public.app_users)))x(name,row_count)`),
 sql(`select internal_usage_status,is_clinical,requires_clinical_permission,sensitivity_level,download_allowed,consent_status,marketing_usage_status,external_ai_status,count(*) row_count from public.asset_access_control group by 1,2,3,4,5,6,7,8 order by 9 desc`),
 sql(`select a.file_name,acl.internal_usage_status,acl.is_clinical,acl.requires_clinical_permission,acl.sensitivity_level,acl.download_allowed,acl.consent_status,acl.external_ai_status from public.assets a join public.asset_access_control acl on acl.asset_id=a.id where a.file_name in(${names.map(x=>`'${x}'`).join(",")}) order by a.file_name`),
 sql(`select (select count(*) from auth.users where email ilike '%phase20%') auth_users,(select count(*) from public.app_users where email ilike '%phase20%') app_users,(select count(*) from public.assets where file_name ilike '%phase20%') assets,(select count(*) from public.asset_access_control acl join public.assets a on a.id=acl.asset_id where a.file_name ilike '%phase20%') acl_rows`),
 sql(`select version from supabase_migrations.schema_migrations where version in('20260826034218','20260826043121') order by version`)
]);
const report={generated_at:new Date().toISOString(),counts,acl,pilots,temporary,migration_history:migrations,external_ai_processing:"NOT_USED",raw_media_sent:0,secrets_exposed:0};const out=path.join(root,"reports","semantic-search","phase20");mkdirSync(out,{recursive:true});writeFileSync(path.join(out,"live_preflight.json"),JSON.stringify(report,null,2)+"\n");console.log(JSON.stringify(report,null,2));
