// Phase 22 regression: the certified Phase 9 suite re-run unchanged against the expanded index.
// Results are written under phase-10 so the certified Phase 9 artifacts stay untouched.
import{readFileSync,mkdirSync,writeFileSync}from"node:fs";import path from"node:path";import{performance}from"node:perf_hooks";import{createClient}from"@supabase/supabase-js";
import{interpretQuery}from"../db/query-interpreter";import{classifyRequirements}from"../db/requirement-classifier";import{expandQuery}from"../db/query-expander";import{retrieveCandidates}from"../db/candidate-retriever";import{authorizeCandidates}from"../db/candidate-authorizer";import{loadRerankingEvidence,rerankAuthorizedCandidates}from"../db/deterministic-reranker";import{applyResultCount}from"../db/result-count-controller";import{encodePhase17Queries}from"../db/phase17-query-encoder";import{buildDatabaseGroundedResponse,SupabaseGroundedResponseRepository}from"../db/database-grounded-search-response";
const root=path.resolve(import.meta.dirname,"../.."),out=path.join(root,"reports/semantic-search/rollout/phase-10"),CANARY="a9c4cf6f-c86c-4d9d-8a6d-2a815fe211bd";mkdirSync(out,{recursive:true});
function env(p:string){try{return Object.fromEntries(readFileSync(p,"utf8").replace(/^\uFEFF/,"").split(/\r?\n/).flatMap(line=>{const m=line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);return m?[[m[1],m[2].trim().replace(/^(['"])(.*)\1$/,"$2")]]:[]}))}catch{return{}}}const e:any={...env(path.join(root,".env")),...env(path.join(root,".env.local")),...env(path.join(root,"dashboard/.env.local"))},url=e.SUPABASE_URL||e.NEXT_PUBLIC_SUPABASE_URL,key=e.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw Error("database config unavailable");const db=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});
type Case={id:string;category:string;query:string;expectCanary?:boolean;expectCount?:number;expectMedia?:string;clinical?:boolean;unsupported?:boolean};const cases:Case[]=[];const add=(category:string,items:Array<[string,string,Partial<Case>?]>)=>items.forEach(([id,query,x])=>cases.push({id,category,query,...x}));
add("exact",[["exact-stem","IMG_2951",{expectCanary:true}],["exact-full","IMG_2951.MP4",{expectCanary:true}]]);
add("grounded",[["g1","show me a video with a visible person",{expectCanary:true}],["g2","find a video showing gloved hands",{expectCanary:true}],["g3","show me a video with an exposed body region",{expectCanary:true}],["g4","find a video showing physical contact",{expectCanary:true}]]);
add("paraphrase",[["p1","hands wearing gloves",{expectCanary:true}],["p2","visible tool",{expectCanary:true}],["p3","object touching body region",{expectCanary:true}]]);
add("multi",[["m1","show me a video with a visible person and gloved hands",{expectCanary:true}],["m2","video with an exposed body region and physical contact",{expectCanary:true}]]);
for(const q of["surgery","show me surgery videos","procedure","show me a procedure","treatment","hair transplant","FUE","follicular unit extraction","implantation","graft extraction"])cases.push({id:`clinical-${cases.length}`,category:"clinical",query:q,expectCanary:false,clinical:true});
for(const n of[1,3,5,7,10])cases.push({id:`count-${n}`,category:"count",query:n===7?"give me 7 files":n===10?"show me 10 videos":`give me ${n} videos with gloved hands`,expectCount:n,expectCanary:n===7||n===10?undefined:true});
add("number",[["age1","man around 30",{expectCount:5}],["age2","person in his 30s",{expectCount:5}],["age3","30-year-old person",{expectCount:5}],["age4","give me 30 results",{expectCount:30}]]);
add("media",[["video","show me videos with gloved hands",{expectCanary:true,expectMedia:"VIDEO"}],["image","show me images with gloved hands",{expectCanary:false,expectMedia:"IMAGE"}],["mp4","IMG_2951.MP4",{expectCanary:true,expectMedia:"VIDEO"}],["document","show me documents",{expectCanary:false}]]);
add("negative",[["n1","show videos with a visible person but without gloved hands",{expectCanary:false}],["n2","show videos with an exposed body region but not physical contact",{expectCanary:false}],["n3","show videos with a visible instrument excluding a visible person",{expectCanary:false}]]);
for(const q of["food","car","landscape","animal","airplane"])cases.push({id:`unsupported-${q}`,category:"unsupported",query:q,expectCanary:false,unsupported:true});
const pilots=[["IMG_0531.MP4","7f72217d-3839-4920-86b4-ccc33e9e3d95"],["IMG_1238.MP4","babae120-9372-42ad-b535-02a3276ea2be"],["IMG_3429.MP4","c86344e9-5b32-4d86-9205-67952d508651"],["IMG_9871.MOV","444da390-0117-4380-8c87-d7c32f2903ff"],["DSC03753.JPG","37838d30-a0ce-4f90-8cc3-c986db0aaa65"],["DSC08097.JPG","6215ad8b-12be-4a8e-bc49-f6b3dcf55c21"],["IMG_0493.MP4","64712c6a-c02c-46e9-9f73-16786109468b"],["IMG_1148.MP4","47611c6d-7923-42a4-87b6-c2a416a90f5c"],["IMG_2963.MP4","bfae6c51-5d71-47ae-a3e1-6d07092b8896"],["IMG_1160.MP4","753eb5f3-82c7-4148-a226-d5b960fd8619"]];for(const[f,id]of pilots)cases.push({id:`pilot-${f}`,category:"pilot",query:f,expectCanary:false} as any);
const users=await db.from("app_users").select("user_id").eq("is_active",true).limit(1);if(users.error||!users.data?.[0])throw users.error??Error("active user unavailable");const userId=String(users.data[0].user_id);
const vectors=await encodePhase17Queries([...new Set(cases.map(x=>x.query))]);const vectorBy=new Map([...new Set(cases.map(x=>x.query))].map((q,i)=>[q,vectors[i]]));
async function run(c:Case){const started=performance.now(),p0=performance.now(),plan=await interpretQuery(c.query),parser_ms=performance.now()-p0,req=classifyRequirements(plan),expanded=expandQuery(plan,req),rv=vectorBy.get(c.query)!,r0=performance.now(),retrieved=await retrieveCandidates(db,{queryPlan:plan,requirementPlan:req,expandedQueryPlan:expanded,queryVectors:rv,requestedCount:plan.result_request.effective_count}),retrieval_ms=performance.now()-r0,a0=performance.now(),authorized=await authorizeCandidates(db,retrieved,userId),authorization_ms=performance.now()-a0,evidence=await loadRerankingEvidence(db,authorized as any),k0=performance.now(),ranked=rerankAuthorizedCandidates(authorized as any,req,expanded,evidence,plan.result_request.effective_count),ranking_ms=performance.now()-k0,controlled=applyResultCount(ranked.candidates,plan.result_request,{isAuthorized:(x:any)=>x.authorization?.discover===true,isEligible:(x:any)=>x.phase19.eligible===true}),response=await buildDatabaseGroundedResponse({query:c.query,userId,count:controlled.count,candidates:controlled.candidates.map((x:any)=>({asset_id:x.asset_id,score:x.phase19.normalizedScore}))},new SupabaseGroundedResponseRepository(db)),ids=controlled.candidates.map((x:any)=>x.asset_id),idx=ids.indexOf(CANARY),canary=controlled.candidates[idx] as any;const actualCount=controlled.count.effective_count,ageSafe=c.category!=="number"||c.id==="age4"?true:plan.result_request.requested_count===null,passCanary=c.expectCanary===undefined||c.expectCanary===(idx>=0),passCount=c.expectCount===undefined||actualCount===c.expectCount,passMedia=!c.expectMedia||controlled.candidates.every((x:any)=>String(evidence.metadata[x.asset_id]?.mimeType??"").toUpperCase().startsWith(c.expectMedia!));const unsafeReason=response.results?.find((x:any)=>x.asset_id===CANARY)?.match_reason?.match(/surgery|procedure|treatment|hair transplant|fue|implantation|extraction/i);return{...c,pass:passCanary&&passCount&&passMedia&&ageSafe&&!unsafeReason,parsed_intent:plan.intent,requested_count:plan.result_request.requested_count,effective_count:actualCount,requirements:req,expanded:expanded.requirements,candidate_count:retrieved.candidates.length,authorized_count:authorized.candidates.length,returned_count:controlled.candidates.length,canary_returned:idx>=0,canary_rank:idx>=0?idx+1:null,canary_score:canary?.phase19?.normalizedScore??null,canary_channels:canary?.channels??[],ranking:controlled.candidates.map((x:any,i:number)=>({rank:i+1,asset_id:x.asset_id,filename:x.filename,score:x.phase19.normalizedScore,eligible:x.phase19.eligible,components:x.phase19})),response,latency_ms:{parser:parser_ms,retrieval:retrieval_ms,authorization:authorization_ms,ranking:ranking_ms,total:performance.now()-started},diagnostics:retrieved.diagnostics}}
const results:any[]=[];for(const c of cases){results.push(await run(c));console.log(`${c.id} ${results.at(-1)!.pass?"PASS":"FAIL"}`)}
const repeatQueries=["IMG_2951.MP4","find a video showing gloved hands","show me a video with a visible person and gloved hands","surgery","give me 3 videos with gloved hands"],det:any[]=[];for(const q of repeatQueries){const rows:any[]=[];for(let i=0;i<3;i++)rows.push(await run({...cases.find(x=>x.query===q)!,id:`det-${i}`}));det.push({query:q,orders:rows.map(x=>x.ranking.map((y:any)=>y.asset_id)),scores:rows.map(x=>x.ranking.map((y:any)=>y.score)),pass:rows.every((x,i)=>i===0||JSON.stringify(x.ranking.map((y:any)=>[y.asset_id,y.score]))===JSON.stringify(rows[0].ranking.map((y:any)=>[y.asset_id,y.score])))})}
const report={generated_at:new Date().toISOString(),status:results.every(x=>x.pass)&&det.every(x=>x.pass)?"PASS":"FAIL",user_id_hash:"redacted-active-user",cases:results,determinism:det,external_inference:0,semantic_media_analysis:0};writeFileSync(path.join(out,"phase_10_phase_09_regression_benchmark.json"),JSON.stringify(report,null,2)+"\n");console.log(JSON.stringify({status:report.status,total:results.length,passed:results.filter(x=>x.pass).length,failed:results.filter(x=>!x.pass).map(x=>x.id),determinism:det.every(x=>x.pass)}));if(report.status!=="PASS")process.exitCode=1;
