import { mkdirSync,readFileSync,writeFileSync } from "node:fs";import path from "node:path";
import {buildDocuments,BUILDER_VERSION,CONFIGURATION_FINGERPRINT,CONFIGURATION_VERSION,ONTOLOGY_VERSION,SEARCH_DOCUMENT_VERSION,SEMANTIC_SPEC_VERSION,canonicalJson} from "../db/search-document-builder";
function envFile(file:string){try{return Object.fromEntries(readFileSync(file,"utf8").replace(/^\uFEFF/,"").split(/\r?\n/).flatMap(line=>{const m=line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);return m?[[m[1],m[2].trim().replace(/^(['"])(.*)\1$/,"$2")]]:[]}))}catch{return {}}}
const root=path.resolve(process.cwd(),".."),rootEnv=envFile(path.join(root,".env.local")),localEnv=envFile(path.join(process.cwd(),".env.local")),env={...rootEnv,...localEnv};const url=env.NEXT_PUBLIC_SUPABASE_URL,token=[rootEnv.SUPABASE_DASHBOARD_ACCESS_TOKEN,localEnv.SUPABASE_DASHBOARD_ACCESS_TOKEN].find(v=>v?.startsWith("sbp_"));if(!url||!token)throw new Error("configuration unavailable");const ref=new URL(url).hostname.split(".")[0];
async function sql<T=unknown>(query:string):Promise<T>{for(let attempt=0;attempt<8;attempt++){const r=await fetch(`https://api.supabase.com/v1/projects/${ref}/database/query`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({query})});if(r.ok)return r.json() as Promise<T>;const body=(await r.text()).slice(0,3000);if(r.status!==429||attempt===7)throw new Error(`query failed ${r.status}: ${body}`);await new Promise(resolve=>setTimeout(resolve,500*(attempt+1)))}throw new Error("query retry exhausted")}
const lit=(v:unknown)=>v==null?"null":`'${String(v).replaceAll("'","''")}'`;const json=(v:unknown)=>`${lit(canonicalJson(v))}::jsonb`;
const audit=JSON.parse(readFileSync(path.join(root,"reports","semantic-search","phase11","phase11_existing_search_document_audit.json"),"utf8"));
if(audit.pilot_found!==10)throw new Error(`pilot integrity failure: ${audit.pilot_found}/10`);
const built=audit.assets.map((a:any)=>({input:a,result:buildDocuments({asset_id:a.asset_id,filename:a.filename,mime_type:a.mime_type,source_fingerprint:a.source_fingerprint,scenes:a.scenes,events:a.events,assertions:a.effective_assertions,narratives:a.semantic_narratives,transcripts:a.transcripts,ocr:a.ocr})}));
const docs=built.flatMap((x:any)=>[x.result.asset,...x.result.scenes,...x.result.events]);if(built.length!==10)throw new Error("exact asset document gate failed");
const run=await sql<any[]>(`insert into public.search_document_build_runs(status,search_document_version,builder_version,configuration_version,configuration_fingerprint,semantic_spec_version,ontology_version,source_semantic_version,asset_count,asset_document_count,scene_document_count,event_document_count) values('RUNNING','${SEARCH_DOCUMENT_VERSION}','${BUILDER_VERSION}','${CONFIGURATION_VERSION}','${CONFIGURATION_FINGERPRINT}','${SEMANTIC_SPEC_VERSION}','${ONTOLOGY_VERSION}','${SEMANTIC_SPEC_VERSION}',10,10,${built.reduce((n:any,x:any)=>n+x.result.scenes.length,0)},${built.reduce((n:any,x:any)=>n+x.result.events.length,0)}) returning id`);const runId=run[0].id;
for(const d of docs){
 const old=await sql<any[]>(`select id,document_fingerprint from public.search_document_builds where asset_id=${lit(d.asset_id)}::uuid and document_type=${lit(d.document_type)} and scene_id is not distinct from ${lit((d as any).scene_id)}::uuid and event_id is not distinct from ${lit((d as any).event_id)}::uuid and search_document_version='${SEARCH_DOCUMENT_VERSION}' and active for update`);
 let documentId:string;
 if(old[0]?.document_fingerprint===d.document_fingerprint){await sql(`update public.search_document_builds set build_run_id='${runId}',generated_at=now(),status='READY',stale=false where id='${old[0].id}'`);documentId=old[0].id}else{
  if(old[0])await sql(`update public.search_document_builds set active=false,stale=true,status='STALE' where id='${old[0].id}'`);
  const inserted=await sql<any[]>(`insert into public.search_document_builds(build_run_id,asset_id,scene_id,event_id,document_type,filename,media_type,start_time,end_time,normalized_document,search_text,positive_concepts,negative_concepts,search_document_version,builder_version,configuration_version,configuration_fingerprint,semantic_spec_version,ontology_version,source_semantic_version,source_fingerprint,source_semantic_fingerprint,document_fingerprint,status,review_status,gold_standard_version,human_approved,review_required,active,stale,generated_at) values('${runId}',${lit(d.asset_id)}::uuid,${lit((d as any).scene_id)}::uuid,${lit((d as any).event_id)}::uuid,${lit(d.document_type)},${lit(d.filename)},${lit(d.media_type)},${lit((d as any).start_time)}::numeric,${lit((d as any).end_time)}::numeric,${json(d)},${lit(d.search_text)},${json(d.positive_concepts)},${json(d.negative_concepts)},'${SEARCH_DOCUMENT_VERSION}','${BUILDER_VERSION}','${CONFIGURATION_VERSION}','${CONFIGURATION_FINGERPRINT}','${SEMANTIC_SPEC_VERSION}','${ONTOLOGY_VERSION}','${SEMANTIC_SPEC_VERSION}',${lit(d.source_semantic_fingerprint)},${lit(d.source_semantic_fingerprint)},${lit(d.document_fingerprint)},'READY','AI_UNREVIEWED',null,false,${d.review_required},true,false,now()) returning id`);documentId=inserted[0].id;
  if(old[0])await sql(`update public.search_document_builds set superseded_by='${documentId}' where id='${old[0].id}'`);
 }
 for(const c of [...d.positive_concepts,...d.negative_concepts])if(c.assertion_id){const rows=await sql<any[]>(`insert into public.search_document_concepts(document_id,asset_id,scene_id,event_id,concept_type,canonical_code,display_text,semantic_state,confidence,origin,resolution_source,review_status,assertion_id,search_critical) select '${documentId}',${lit(d.asset_id)}::uuid,${lit((d as any).scene_id)}::uuid,${lit((d as any).event_id)}::uuid,${lit(c.concept_type)},${lit(c.canonical_code)},${lit(c.display_text)},${lit(c.semantic_state)},${lit(c.confidence)}::numeric,${lit(c.origin)},${lit(c.resolution_source)},'AI_UNREVIEWED',${lit(c.assertion_id)}::uuid,${c.search_critical} where not exists(select 1 from public.search_document_concepts x where x.document_id='${documentId}' and x.assertion_id=${lit(c.assertion_id)}::uuid) returning id`);const conceptId=rows[0]?.id;if(conceptId)for(const evidenceId of c.evidence_ids)await sql(`insert into public.search_document_evidence(document_id,concept_id,assertion_id,assertion_evidence_id,asset_id,scene_id,event_id,keyframe_id,transcript_chunk_id,ocr_observation_id,evidence_type) select '${documentId}','${conceptId}',e.assertion_id,e.id,e.asset_id,e.scene_id,e.event_id,e.keyframe_id,e.transcript_chunk_id,e.ocr_observation_id,e.evidence_type from public.semantic_assertion_evidence e where e.id=${lit(evidenceId)}::uuid and not exists(select 1 from public.search_document_evidence x where x.document_id='${documentId}' and x.assertion_evidence_id=e.id)`)}
 }
await sql(`update public.search_document_build_runs set status='COMPLETE',completed_at=now() where id='${runId}'`);
const dir=path.join(root,"reports","semantic-search","phase11"),assetDir=path.join(dir,"assets");mkdirSync(assetDir,{recursive:true});
for(const x of built)writeFileSync(path.join(assetDir,`${x.input.asset_id}_search_document.json`),JSON.stringify(x.result.asset,null,2)+"\n");
const assets=built.map((x:any)=>x.result.asset),scenes=built.flatMap((x:any)=>x.result.scenes),events=built.flatMap((x:any)=>x.result.events),concepts=built.flatMap((x:any)=>x.result.concepts);
const base={generated_at:new Date().toISOString(),build_run_id:runId,search_document_version:SEARCH_DOCUMENT_VERSION,builder_version:BUILDER_VERSION,configuration_version:CONFIGURATION_VERSION,configuration_fingerprint:CONFIGURATION_FINGERPRINT,review_status:"AI_UNREVIEWED",human_approved:false,gold_standard_version:null};
writeFileSync(path.join(dir,"phase11_asset_documents.json"),JSON.stringify({...base,count:assets.length,documents:assets},null,2)+"\n");writeFileSync(path.join(dir,"phase11_scene_documents.json"),JSON.stringify({...base,count:scenes.length,documents:scenes},null,2)+"\n");writeFileSync(path.join(dir,"phase11_event_documents.json"),JSON.stringify({...base,count:events.length,technical_only_skipped:audit.assets.reduce((n:number,a:any)=>n+a.events.filter((e:any)=>e.technical_only).length,0),documents:events},null,2)+"\n");writeFileSync(path.join(dir,"phase11_search_concepts.json"),JSON.stringify({...base,count:concepts.length,concepts},null,2)+"\n");writeFileSync(path.join(dir,"phase11_document_lineage.json"),JSON.stringify({...base,documents:docs.map((d:any)=>({asset_id:d.asset_id,document_type:d.document_type,scene_id:d.scene_id??null,event_id:d.event_id??null,source_semantic_fingerprint:d.source_semantic_fingerprint,document_fingerprint:d.document_fingerprint}))},null,2)+"\n");
console.log(JSON.stringify({run_id:runId,asset_documents:assets.length,scene_documents:scenes.length,event_documents:events.length,concepts:concepts.length},null,2));
