import { readFileSync } from "node:fs";import path from "node:path";
function envFile(file:string){try{return Object.fromEntries(readFileSync(file,"utf8").replace(/^\uFEFF/,"").split(/\r?\n/).flatMap(line=>{const m=line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);return m?[[m[1],m[2].trim().replace(/^(['"])(.*)\1$/,"$2")]]:[]}))}catch{return {}}}
const root=path.resolve(process.cwd(),'..'),l=envFile(path.join(process.cwd(),'.env.local')),p=envFile(path.join(root,'.env.local')),url=l.NEXT_PUBLIC_SUPABASE_URL||p.NEXT_PUBLIC_SUPABASE_URL,token=[p.SUPABASE_DASHBOARD_ACCESS_TOKEN,l.SUPABASE_DASHBOARD_ACCESS_TOKEN].find(v=>v?.startsWith('sbp_'));if(!url||!token)throw new Error('configuration unavailable');const ref=new URL(url).hostname.split('.')[0];
const query=`begin;set local statement_timeout='60s';
do $$ declare
 v_video uuid:=gen_random_uuid();v_image uuid:=gen_random_uuid();v_run uuid;v_image_run uuid;v_s1 uuid;v_s2 uuid;v_e1 uuid;v_e2 uuid;v_e3 uuid;v_k1 uuid;v_k2 uuid;v_k3 uuid;v_k4 uuid;v_k5 uuid;v_t bigint;v_o uuid;v_unknown uuid;v_false uuid;v_observed uuid;v_review uuid;v_decision uuid;v_gold_set uuid;v_gold_asset uuid;v_effect jsonb;v_code text;v_state text;
begin
 insert into public.assets(id,checksum_sha256,original_file_name,file_name,mime_type,migration_status,upload_status) values
 (v_video,encode(digest(v_video::text,'sha256'),'hex'),'phase10-synthetic-video.mp4','phase10-synthetic-video.mp4','video/mp4','PENDING','PENDING'),
 (v_image,encode(digest(v_image::text,'sha256'),'hex'),'phase10-synthetic-image.jpg','phase10-synthetic-image.jpg','image/jpeg','PENDING','PENDING');
 insert into public.asset_access_control(asset_id,is_clinical,sensitivity_level,internal_usage_status) values(v_video,false,'GENERAL','ALLOWED'),(v_image,false,'GENERAL','ALLOWED');
 insert into public.semantic_analysis_runs(asset_id,run_type,status,processor_version,configuration_fingerprint,source_fingerprint) values(v_video,'FULL','COMPLETED','phase10-test','cfg-video','src-video') returning id into v_run;
 insert into public.semantic_analysis_runs(asset_id,run_type,status,processor_version,configuration_fingerprint,source_fingerprint) values(v_image,'FULL','COMPLETED','phase10-test','cfg-image','src-image') returning id into v_image_run;
 insert into public.asset_semantic_layers(asset_id,layer_id,analysis_run_id,applicability,semantic_state,processing_status,completeness_status,ontology_version,semantic_spec_version)
 select v_video,layer_id,v_run,'APPLICABLE','UNKNOWN','COMPLETE','COMPLETE','KDI_SEMANTIC_V2','semantic_index_v1' from public.semantic_layer_definitions;
 if(select count(*) from public.asset_semantic_layers where asset_id=v_video)<>18 then raise exception '18 layer status test failed';end if;
 insert into public.asset_semantic_layers(asset_id,layer_id,analysis_run_id,applicability,semantic_state,processing_status,completeness_status,ontology_version,semantic_spec_version) values
 (v_image,'TEMPORAL_SCENE_STRUCTURE',v_image_run,'NOT_APPLICABLE','NOT_APPLICABLE','COMPLETE','NOT_APPLICABLE','KDI_SEMANTIC_V2','semantic_index_v1'),
 (v_image,'SPEECH_TRANSCRIPT_AUDIO',v_image_run,'NOT_APPLICABLE','NOT_APPLICABLE','COMPLETE','NOT_APPLICABLE','KDI_SEMANTIC_V2','semantic_index_v1'),
 (v_image,'OCR_VISIBLE_TEXT',v_image_run,'APPLICABLE','FALSE','COMPLETE','COMPLETE','KDI_SEMANTIC_V2','semantic_index_v1');
 insert into public.asset_scenes(asset_id,scene_index,start_seconds,end_seconds,source,processor_version,configuration_version,semantic_state,semantic_analysis_run_id) values(v_video,900001,0,10,'SYNTHETIC','phase10-test','v1','OBSERVED',v_run) returning id into v_s1;
 insert into public.asset_scenes(asset_id,scene_index,start_seconds,end_seconds,source,processor_version,configuration_version,semantic_state,semantic_analysis_run_id) values(v_video,900002,10,20,'SYNTHETIC','phase10-test','v1','OBSERVED',v_run) returning id into v_s2;
 insert into public.asset_events(asset_id,scene_id,start_time,end_time,event_type,canonical_action,semantic_state,confidence,analysis_run_id) values(v_video,v_s1,1,3,'ACTION','IMPLANTING_GRAFTS','OBSERVED',.95,v_run) returning id into v_e1;
 insert into public.asset_events(asset_id,scene_id,start_time,end_time,event_type,canonical_action,semantic_state,confidence,analysis_run_id) values(v_video,v_s1,4,7,'ACTION','HOLDING_SYRINGE','OBSERVED',.9,v_run) returning id into v_e2;
 insert into public.asset_events(asset_id,scene_id,start_time,end_time,event_type,canonical_action,semantic_state,confidence,analysis_run_id) values(v_video,v_s2,12,16,'ACTION','LOOKING_AT_CAMERA','OBSERVED',.9,v_run) returning id into v_e3;
 insert into public.asset_keyframes(asset_id,scene_id,event_id,timestamp_seconds,frame_index,selection_reason,source_fingerprint,processor_version,semantic_analysis_run_id) values(v_video,v_s1,v_e1,1.5,1,'EVENT','kf1','phase10-test',v_run) returning id into v_k1;
 insert into public.asset_keyframes(asset_id,scene_id,event_id,timestamp_seconds,frame_index,selection_reason,source_fingerprint,processor_version) values(v_video,v_s1,v_e1,2.5,2,'EVENT','kf2','phase10-test') returning id into v_k2;
 insert into public.asset_keyframes(asset_id,scene_id,event_id,timestamp_seconds,frame_index,selection_reason,source_fingerprint,processor_version) values(v_video,v_s1,v_e2,5,3,'EVENT','kf3','phase10-test') returning id into v_k3;
 insert into public.asset_keyframes(asset_id,scene_id,event_id,timestamp_seconds,frame_index,selection_reason,source_fingerprint,processor_version) values(v_video,v_s2,v_e3,13,4,'EVENT','kf4','phase10-test') returning id into v_k4;
 insert into public.asset_keyframes(asset_id,scene_id,event_id,timestamp_seconds,frame_index,selection_reason,source_fingerprint,processor_version) values(v_video,v_s2,v_e3,15,5,'EVENT','kf5','phase10-test') returning id into v_k5;
 insert into public.asset_transcript_chunks(asset_id,scene_id,event_id,start_seconds,end_seconds,transcript_text,raw_text,normalized_text,language,search_status,source_text_fingerprint,provider,model,version,semantic_analysis_run_id) values(v_video,v_s1,v_e1,1,2,'test transcript','test transcript','test transcript','en','UNREVIEWED','tx-fp','test','test','v1',v_run) returning id into v_t;
 insert into public.ocr_observations(asset_id,scene_id,event_id,keyframe_id,timestamp_seconds,raw_text,normalized_text,text_type,search_status,source_text_fingerprint,provider,model,version,semantic_analysis_run_id) values(v_video,v_s1,v_e1,v_k1,1.5,'KDI','kdi','OTHER','UNREVIEWED','ocr-fp','test','test','v1',v_run) returning id into v_o;
 insert into public.semantic_assertions(asset_id,layer_id,subject_type,predicate,semantic_state,search_critical,analysis_run_id,origin,ontology_version,semantic_spec_version,source_fingerprint,idempotency_key) values(v_video,'TREATMENT_PROCEDURE','ASSET','treatment','UNKNOWN',true,v_run,'AI_MODEL','KDI_SEMANTIC_V2','semantic_index_v1','src-video','unknown-treatment') returning id into v_unknown;
 insert into public.semantic_assertions(asset_id,scene_id,event_id,keyframe_id,layer_id,subject_type,predicate,canonical_concept_code,semantic_state,confidence,search_critical,analysis_run_id,origin,ontology_version,semantic_spec_version,source_fingerprint,idempotency_key) values(v_video,v_s1,v_e1,v_k1,'ACTIONS_EVENTS','EVENT','action','IMPLANTING_GRAFTS','OBSERVED',.95,true,v_run,'AI_MODEL','KDI_SEMANTIC_V2','semantic_index_v1','src-video','observed-action') returning id into v_observed;
 insert into public.semantic_assertion_evidence(assertion_id,evidence_type,asset_id,scene_id,event_id,keyframe_id,evidence_score,source_fingerprint,analysis_run_id) values(v_observed,'KEYFRAME_LEVEL',v_video,v_s1,v_e1,v_k1,.95,'kf1',v_run);
 insert into public.semantic_assertions(asset_id,layer_id,subject_type,predicate,canonical_concept_code,semantic_state,search_critical,analysis_run_id,origin,ontology_version,semantic_spec_version,source_fingerprint,idempotency_key) values(v_image,'ACTIONS_EVENTS','ASSET','action','POSING_FOR_CAMERA','OBSERVED',true,v_image_run,'AI_MODEL','KDI_SEMANTIC_V2','semantic_index_v1','src-image','image-pose') returning id into v_observed;
 insert into public.semantic_assertion_evidence(assertion_id,evidence_type,asset_id,polarity,completeness,source_fingerprint,analysis_run_id) values(v_observed,'ASSET_LEVEL',v_image,'POSITIVE','COMPLETE','src-image',v_image_run);
 insert into public.semantic_assertions(asset_id,layer_id,subject_type,predicate,semantic_state,search_critical,analysis_run_id,origin,ontology_version,semantic_spec_version,source_fingerprint,idempotency_key) values(v_image,'OCR_VISIBLE_TEXT','ASSET','visible_text','FALSE',true,v_image_run,'DETERMINISTIC_PROCESSOR','KDI_SEMANTIC_V2','semantic_index_v1','src-image','image-no-ocr') returning id into v_false;
 insert into public.semantic_assertion_evidence(assertion_id,evidence_type,asset_id,polarity,completeness,source_fingerprint,analysis_run_id) values(v_false,'OCR',v_image,'NEGATIVE','COMPLETE','ocr-complete',v_image_run);
 insert into public.semantic_narratives(asset_id,narrative_type,text,input_evidence_fingerprint,generator_version,analysis_run_id) values(v_video,'ASSET_NARRATIVE','Synthetic asset narrative','narrative-fp','test-v1',v_run),(v_video,'SCENE_NARRATIVE','Synthetic scene narrative','scene-narrative-fp','test-v1',v_run),(v_video,'EVENT_NARRATIVE','Synthetic event narrative','event-narrative-fp','test-v1',v_run);
 insert into public.semantic_review_sessions(reviewer_label,semantic_spec_version) values('SYNTHETIC_TEST','semantic_index_v1') returning id into v_review;
 insert into public.semantic_review_decisions(session_id,asset_id,layer_id,assertion_id,original_value,decision,human_value,reason,reviewer_label) values(v_review,v_video,'TREATMENT_PROCEDURE',v_unknown,'{"semantic_state":"UNKNOWN"}','CORRECT','{"canonical_concept_code":"HAIR_TRANSPLANT","semantic_state":"OBSERVED"}','synthetic precedence test','SYNTHETIC_TEST') returning id into v_decision;
 select canonical_concept_code,effective_value into v_code,v_effect from public.effective_semantic_assertions where asset_id=v_video and predicate='treatment';if v_code<>'HAIR_TRANSPLANT' or v_effect->>'canonical_concept_code'<>'HAIR_TRANSPLANT' then raise exception 'human override precedence failed';end if;
 begin update public.semantic_review_decisions set reason='mutated' where id=v_decision;raise exception 'review immutability failed';exception when raise_exception then if sqlerrm='review immutability failed' then raise;end if;end;
 insert into public.gold_standard_sets(code,revision,status,semantic_spec_version,source_fingerprint,gold_fingerprint) values('synthetic-gold',1,'DRAFT','semantic_index_v1','src-video','gold-fp') returning id into v_gold_set;
 insert into public.gold_standard_assets(gold_set_id,asset_id,revision,source_fingerprint,gold_fingerprint,status) values(v_gold_set,v_video,1,'src-video','gold-asset-fp','SIGNED_OFF') returning id into v_gold_asset;
 insert into public.gold_standard_assertions(gold_asset_id,source_assertion_id,layer_id,predicate,semantic_state,canonical_concept_code,value_json,human_decision_id,human_reason,revision,source_fingerprint,gold_fingerprint) values(v_gold_asset,v_unknown,'TREATMENT_PROCEDURE','treatment','OBSERVED','HAIR_TRANSPLANT','{"canonical_concept_code":"HAIR_TRANSPLANT"}',v_decision,'synthetic',1,'src-video','gold-assertion-fp');
 update public.gold_standard_sets set status='SIGNED_OFF',signed_off_at=now() where id=v_gold_set;
 insert into public.semantic_analysis_runs(asset_id,run_type,status,processor_version,configuration_fingerprint,source_fingerprint) values(v_video,'RERUN','COMPLETED','phase10-test-v2','cfg-video-v2','src-video');
 select resolution_source,canonical_concept_code into v_state,v_code from public.effective_semantic_assertions where asset_id=v_video and predicate='treatment';if v_state<>'HUMAN_GOLD' or v_code<>'HAIR_TRANSPLANT' then raise exception 'gold precedence failed';end if;
 begin update public.gold_standard_assertions set canonical_concept_code='UNKNOWN' where gold_asset_id=v_gold_asset;raise exception 'gold immutability failed';exception when raise_exception then if sqlerrm='gold immutability failed' then raise;end if;end;
 insert into public.asset_search_documents(asset_id,searchable_text,source_hash,document_version) values(v_image,'legacy treatment FUE','legacy-fp','legacy-v1');
 select semantic_state into v_state from public.effective_semantic_assertions where asset_id=v_video and predicate='treatment';if v_state<>'OBSERVED' then raise exception 'legacy/gold precedence failed';end if;
 set constraints all immediate;
 if(select count(*) from public.asset_scenes where asset_id=v_video)<>2 or (select count(*) from public.asset_events where asset_id=v_video)<>3 or (select count(*) from public.asset_keyframes where asset_id=v_video)<>5 then raise exception 'video relationship counts failed';end if;
 if not exists(select 1 from public.semantic_assertion_evidence where transcript_chunk_id=v_t) then insert into public.semantic_assertion_evidence(assertion_id,evidence_type,asset_id,scene_id,event_id,transcript_chunk_id,source_fingerprint,analysis_run_id) values(v_unknown,'TRANSCRIPT',v_video,v_s1,v_e1,v_t,'tx-fp',v_run);end if;
end $$;rollback;`;
const response=await fetch(`https://api.supabase.com/v1/projects/${ref}/database/query`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({query})});if(!response.ok)throw new Error(`live contract test failed ${response.status}: ${(await response.text()).slice(0,3000)}`);console.log(JSON.stringify({live_storage_contract:'PASS',video_relational:'PASS',image_relational:'PASS',false_negative_evidence:'PASS',human_override:'PASS',gold_precedence:'PASS',gold_immutability:'PASS',legacy_precedence:'PASS',rolled_back:true},null,2));
