import { createHash } from "node:crypto";
import { SEMANTIC_SPEC_FINGERPRINT, SEMANTIC_SPEC_VERSION, SCALE_PIPELINE_VERSION, type AssetState, idempotencyKey } from "./scale-readiness";
export { SEMANTIC_SPEC_FINGERPRINT, SEMANTIC_SPEC_VERSION, SCALE_PIPELINE_VERSION } from "./scale-readiness";

export const AUTOMATIC_PIPELINE_VERSION = "kdi_automatic_indexing_pipeline_v1";
export const EXTERNAL_AI_ENABLED = false;
export const LAYER_IDS = Array.from({ length: 18 }, (_, i) => `LAYER_${String(i + 1).padStart(2, "0")}`);
export type StageName = "PREPROCESSING" | "SEMANTIC_ANALYSIS" | "VALIDATION" | "SEMANTIC_STORAGE" | "DESCRIPTION" | "NARRATIVE" | "SEARCH_DOCUMENT" | "EMBEDDING" | "FINAL_VALIDATION";
export type StageStatus = "COMPLETED" | "FAILED_RETRYABLE" | "FAILED_PERMANENT";
export interface StageResult { stage: StageName; status: StageStatus; inputVersion: string; outputVersion?: string; startedAt: number; completedAt: number; durationMs: number; warnings: string[]; errors: string[]; lineage: string[]; retryable: boolean; }
export interface DiscoveryEvent { sourceId: string; sourcePath: string; filename: string; contentHash: string; mediaType: string; fileSize: number; discoveredAt: number; }
export interface LayerEvaluation { layerId: string; semanticState: "OBSERVED" | "FALSE" | "UNKNOWN" | "NOT_APPLICABLE"; evidence: { source: string }[]; }
export interface StructuredSemanticResult { specVersion: string; specFingerprint: string; pipelineVersion: string; layers: LayerEvaluation[]; }
export interface AssetRecord { assetId: string; sourceId: string; contentHash: string; state: AssetState; activeVersion?: string; sourcePath: string; }
export interface IndexJob { jobId: string; assetId: string; contentHash: string; status: "QUEUED" | "RUNNING" | "COMPLETED" | "FAILED_RETRYABLE" | "FAILED_PERMANENT"; attempt: number; stage?: StageName; stages: Partial<Record<StageName, StageResult>>; checkpoint: StageName[]; }

export interface SemanticAnalysisProvider { readonly providerName: string; analyze(input: { asset: DiscoveryEvent; modalities: string[]; specVersion: string; specFingerprint: string }): Promise<StructuredSemanticResult>; }
export class SyntheticSemanticProvider implements SemanticAnalysisProvider { readonly providerName = "SYNTHETIC_FIXTURE"; async analyze(input: { asset: DiscoveryEvent; modalities: string[]; specVersion: string; specFingerprint: string }): Promise<StructuredSemanticResult> { return { specVersion: input.specVersion, specFingerprint: input.specFingerprint, pipelineVersion: AUTOMATIC_PIPELINE_VERSION, layers: LAYER_IDS.map((layerId, i) => ({ layerId, semanticState: i % 7 === 0 ? "UNKNOWN" : i % 11 === 0 ? "NOT_APPLICABLE" : "OBSERVED", evidence: [{ source: `fixture:${input.asset.sourceId}` }] })) }; } }
export class ExternalAIProviderBlocked implements SemanticAnalysisProvider { readonly providerName = "EXTERNAL_AI"; async analyze(): Promise<StructuredSemanticResult> { throw new Error("EXTERNAL_AI_DISABLED"); } }

export function validateStructuredResult(result: StructuredSemanticResult, expectedFingerprint = SEMANTIC_SPEC_FINGERPRINT): void { if (result.specVersion !== SEMANTIC_SPEC_VERSION || result.specFingerprint !== expectedFingerprint) throw new Error("SPEC_MISMATCH"); if (result.pipelineVersion !== AUTOMATIC_PIPELINE_VERSION) throw new Error("PIPELINE_VERSION_MISMATCH"); if (result.layers.length !== 18 || new Set(result.layers.map(x => x.layerId)).size !== 18 || result.layers.some(x => !LAYER_IDS.includes(x.layerId))) throw new Error("INVALID_LAYER_SET"); const states = new Set(["OBSERVED", "FALSE", "UNKNOWN", "NOT_APPLICABLE"]); if (result.layers.some(x => !states.has(x.semanticState) || !x.evidence.length)) throw new Error("INVALID_LAYER_OUTPUT"); }
export function discoveryIdempotencyKey(e: DiscoveryEvent): string { return idempotencyKey({ assetId: e.sourceId, contentHash: e.contentHash, jobType: "DISCOVERY", specFingerprint: SEMANTIC_SPEC_FINGERPRINT, pipelineVersion: AUTOMATIC_PIPELINE_VERSION }); }

export class AutomaticIndexingPipeline {
  readonly assets = new Map<string, AssetRecord>(); readonly jobs = new Map<string, IndexJob>(); readonly stages = new Map<string, StageResult[]>(); readonly semanticWrites = new Map<string, StructuredSemanticResult>(); readonly activeVersions = new Map<string, string>(); readonly metrics: { networkCalls: number; productionWrites: number } = { networkCalls: 0, productionWrites: 0 };
  private readonly discovery = new Map<string, string>(); private sequence = 0;
  constructor(private readonly provider: SemanticAnalysisProvider = new SyntheticSemanticProvider()) {}
  discover(event: DiscoveryEvent): AssetRecord { const existing = this.discovery.get(discoveryIdempotencyKey(event)); if (existing) return this.assets.get(existing)!; const assetId = `fixture-asset-${++this.sequence}`; const record: AssetRecord = { assetId, sourceId: event.sourceId, contentHash: event.contentHash, sourcePath: event.sourcePath, state: "DISCOVERED" }; this.discovery.set(discoveryIdempotencyKey(event), assetId); this.assets.set(assetId, record); return record; }
  enqueue(asset: AssetRecord, force = false): IndexJob { const key = `${asset.assetId}:${asset.contentHash}:${SCALE_PIPELINE_VERSION}`; const prior = force ? undefined : [...this.jobs.values()].find(j => `${j.assetId}:${j.contentHash}:${SCALE_PIPELINE_VERSION}` === key && j.status !== "FAILED_PERMANENT"); if (prior) return prior; const job: IndexJob = { jobId: `fixture-job-${++this.sequence}`, assetId: asset.assetId, contentHash: asset.contentHash, status: "QUEUED", attempt: 0, stages: {}, checkpoint: [], }; this.jobs.set(job.jobId, job); asset.state = "QUEUED"; return job; }
  async run(jobId: string, options: { failStage?: StageName; invalidSemantic?: boolean; source?: DiscoveryEvent } = {}): Promise<IndexJob> { const job = this.jobs.get(jobId)!; const asset = this.assets.get(job.assetId)!; job.status = "RUNNING"; job.attempt++; const stages: StageName[] = ["PREPROCESSING", "SEMANTIC_ANALYSIS", "VALIDATION", "SEMANTIC_STORAGE", "DESCRIPTION", "NARRATIVE", "SEARCH_DOCUMENT", "EMBEDDING", "FINAL_VALIDATION"]; for (const stage of stages) { if (job.checkpoint.includes(stage)) continue; job.stage = stage; if (options.failStage === stage) { const result = this.result(stage, "FAILED_RETRYABLE", job); this.record(job, result); job.status = "FAILED_RETRYABLE"; asset.state = "FAILED_RETRYABLE"; return job; } try { if (stage === "SEMANTIC_ANALYSIS") { const event = options.source ?? { sourceId: asset.sourceId, sourcePath: asset.sourcePath, filename: asset.sourceId, contentHash: asset.contentHash, mediaType: "application/octet-stream", fileSize: 0, discoveredAt: 0 }; const result = await this.provider.analyze({ asset: event, modalities: this.modalities(event.mediaType), specVersion: SEMANTIC_SPEC_VERSION, specFingerprint: options.invalidSemantic ? "bad" : SEMANTIC_SPEC_FINGERPRINT }); validateStructuredResult(result); this.semanticWrites.set(asset.assetId, result); } else if (stage === "VALIDATION") { const semantic = this.semanticWrites.get(asset.assetId); if (!semantic) throw new Error("SEMANTIC_OUTPUT_MISSING"); validateStructuredResult(semantic); } else if (["SEMANTIC_STORAGE", "DESCRIPTION", "NARRATIVE", "SEARCH_DOCUMENT", "EMBEDDING"].includes(stage) && !this.semanticWrites.has(asset.assetId)) throw new Error("DEPENDENCY_NOT_READY"); const result = this.result(stage, "COMPLETED", job); this.record(job, result); job.checkpoint.push(stage); } catch (error) { const result = this.result(stage, "FAILED_PERMANENT", job, error instanceof Error ? error.message : "STAGE_FAILURE"); this.record(job, result); job.status = "FAILED_PERMANENT"; asset.state = "FAILED_PERMANENT"; this.semanticWrites.delete(asset.assetId); return job; } } job.status = "COMPLETED"; asset.state = "READY"; const version = `semantic-${asset.contentHash.slice(0, 12)}`; asset.activeVersion = version; this.activeVersions.set(asset.assetId, version); return job; }
  retry(jobId: string): Promise<IndexJob> { const job = this.jobs.get(jobId)!; if (job.status !== "FAILED_RETRYABLE") throw new Error("JOB_NOT_RETRYABLE"); job.status = "QUEUED"; return this.run(jobId); }
  reindex(asset: AssetRecord, reason: string, requestedStages: StageName[]): IndexJob { const job = this.enqueue(asset); job.stage = requestedStages[0]; return job; }
  partialRebuild(asset: AssetRecord, changed: "SEARCH_DOCUMENT" | "EMBEDDING"): IndexJob { const job = this.enqueue(asset, true); job.checkpoint = ["PREPROCESSING", "SEMANTIC_ANALYSIS", "VALIDATION", "SEMANTIC_STORAGE", "DESCRIPTION", "NARRATIVE"]; job.stage = changed; return job; }
  private modalities(mediaType: string): string[] { return mediaType.startsWith("video/") ? ["visual", "audio", "ocr"] : mediaType.startsWith("image/") ? ["visual", "ocr"] : ["text", "ocr"]; }
  private result(stage: StageName, status: StageStatus, job: IndexJob, error?: string): StageResult { const t = Date.now(); return { stage, status, inputVersion: SCALE_PIPELINE_VERSION, outputVersion: status === "COMPLETED" ? `${stage.toLowerCase()}_v1` : undefined, startedAt: t, completedAt: t + 1, durationMs: 1, warnings: [], errors: error ? [error] : [], lineage: [job.assetId, SEMANTIC_SPEC_VERSION, SEMANTIC_SPEC_FINGERPRINT], retryable: status === "FAILED_RETRYABLE" }; }
  private record(job: IndexJob, result: StageResult): void { const list = this.stages.get(job.jobId) ?? []; list.push(result); this.stages.set(job.jobId, list); }
}

export function systemManifestFingerprint(): string { return createHash("sha256").update(JSON.stringify({ systemVersion: "kdi_semantic_system_v1", specVersion: SEMANTIC_SPEC_VERSION, specFingerprint: SEMANTIC_SPEC_FINGERPRINT, pipelineVersion: AUTOMATIC_PIPELINE_VERSION, scaleReadinessVersion: "kdi_scale_readiness_v1", benchmarkVersion: "kdi_semantic_benchmark_v1", goldVersion: "kdi_gold_answers_v1", goldFingerprint: "979389e6b045a4913f9e82b96687e46a65e789753e2598be601cb3a6d5663763", phase28: "PASS", phase29: "PASS", phase30: "kdi_automatic_indexing_pipeline_v1" })).digest("hex"); }
