import {createHash} from "node:crypto";
import type {SupabaseClient} from "@supabase/supabase-js";
import policy from "../../config/semantic-search/kdi_candidate_retrieval_policy_v1.json";

export const CANDIDATE_RETRIEVER_VERSION="kdi_candidate_retriever_v1";
export const RETRIEVAL_POLICY_VERSION="kdi_candidate_retrieval_policy_v1";
export const CANDIDATE_SCHEMA_VERSION="kdi_candidate_set_v1";
export const RETRIEVAL_CHANNEL_VERSION="kdi_retrieval_channels_v1";
export const RETRIEVAL_POLICY_FINGERPRINT=createHash("sha256").update(JSON.stringify(policy)).digest("hex");
export type EmbeddingCompatibility={representation:string;provider:string;model:string;modelVersion:string;dimension:number;normalization:string};
export function assertEmbeddingCompatibility(identity:EmbeddingCompatibility,vector:number[]){
  const text=identity.representation.startsWith("TEXT_"),visual=identity.representation.startsWith("VISUAL_");
  const valid=text
    ?identity.provider==="sentence_transformers"&&identity.model==="intfloat/multilingual-e5-small"&&identity.modelVersion==="hf-main-pinned-runtime-v1"&&identity.dimension===384&&identity.normalization==="L2"
    :visual&&identity.provider==="open_clip"&&identity.model==="ViT-B-32"&&identity.modelVersion==="laion2b_s34b_b79k"&&identity.dimension===512&&identity.normalization==="L2";
  if(!valid)throw Object.assign(new Error(`INCOMPATIBLE_EMBEDDING_IDENTITY:${identity.representation}`),{code:"EMBEDDING_COMPATIBILITY_MISMATCH"});
  if(vector.length!==identity.dimension||vector.some(x=>!Number.isFinite(x)))throw Object.assign(new Error(`QUERY_VECTOR_DIMENSION_MISMATCH:${identity.representation}:${vector.length}:${identity.dimension}`),{code:"VECTOR_DIMENSION_MISMATCH"});
}
const stable=(x:any):string=>Array.isArray(x)?`[${x.map(stable).join(",")}]`:x&&typeof x==="object"?`{${Object.keys(x).sort().map(k=>JSON.stringify(k)+":"+stable(x[k])).join(",")}}`:JSON.stringify(x);
const freeze=(x:any):any=>{if(x&&typeof x==="object"&&!Object.isFrozen(x)){Object.freeze(x);Object.values(x).forEach(freeze)}return x};
const finger=(x:any)=>createHash("sha256").update(stable(x)).digest("hex");
const reqs=(x:any)=>Array.isArray(x)?x:Object.values(x??{}).flatMap((v:any)=>Array.isArray(v)?v:[]);
const term=(r:any,e:any)=>String(e?.term??r.raw_text??r.value??r.canonical_code??"");

export async function retrieveCandidates(db:SupabaseClient,input:{queryPlan:any;requirementPlan:any;expandedQueryPlan:any;queryVectors?:{text?:number[];visual?:number[]};requestedCount?:number}){
  const {queryPlan,requirementPlan,expandedQueryPlan}=input;
  const diag:any={channels:{},unavailable_channels:[],errors:[],corpus_scope:"CURRENT_CANONICAL_INDEX",human_gold:"DEFERRED",final_ranking:false};
  const by=new Map<string,any>();
  const target=Math.min(Number(policy.max_union_candidates),Math.max(Number(policy.base_candidate_k),Number(input.requestedCount??queryPlan?.result_request?.effective_count??0)*Number(policy.requested_count_multiplier)));
  const expanded=reqs(expandedQueryPlan?.requirements).filter((r:any)=>!["RESPONSE_CONTROL","CONTEXT","UNRESOLVED"].includes(r.classification));
  const add=(row:any,channel:string,extra:any={})=>{const id=String(row.asset_id??row.assetId??row.id??"");if(!id)return;let c=by.get(id);if(!c){c={asset_id:id,filename:row.filename??row.file_name??null,channels:[],channel_count:0,best_channel_score:0,matched_hard_constraints:[],matched_strong_requirements:[],matched_preferences:[],unresolved_requirements:[],retrieval_provenance:{retriever_version:CANDIDATE_RETRIEVER_VERSION}};by.set(id,c)}else if(!c.filename&&(row.filename||row.file_name))c.filename=row.filename??row.file_name;const score=Number(extra.raw_score??row.raw_similarity??row.score??0),hit={channel,retrieval_channel:channel,channel_rank:extra.channel_rank??null,representation_type:extra.representation_type??row.representation_type??channel,source_id:row.embedding_id??row.id??null,source_document_id:row.source_document_id??null,source_scope:"CANONICAL",raw_score:score,raw_similarity:score,normalized_channel_score:Math.max(0,Math.min(1,score)),matched_canonical_concepts:extra.matched_concepts??[],matched_concepts:extra.matched_concepts??[],matched_expansions:extra.expansion_provenance?[extra.expansion_provenance]:[],matched_terms:extra.matched_terms??[],matched_literal:extra.matched_literal??null,expansion_provenance:extra.expansion_provenance??null,semantic_evidence_refs:[],scene_id:row.scene_id??null,event_id:row.event_id??null,keyframe_id:row.keyframe_id??null,transcript_chunk_id:row.transcript_chunk_id??null,ocr_observation_id:row.ocr_observation_id??null,time_start:row.time_start??row.start_seconds??row.timestamp_seconds??null,time_end:row.time_end??row.end_seconds??null,evidence_source:row.evidence_source??extra.evidence_source??"canonical_search_index",embedding_family:row.embedding_family??extra.embedding_family??null,embedding_dimension:row.embedding_dimension??extra.embedding_dimension??null};if(c.channels.filter((h:any)=>h.channel===channel).length<Number(policy.max_supporting_hits_per_channel))c.channels.push(hit);c.channel_count=c.channels.length;c.best_channel_score=Math.max(c.best_channel_score,score);const cls=extra.requirement_classification;if(cls==="HARD_CONSTRAINT")c.matched_hard_constraints.push(...(extra.matched_concepts??[]));if(cls==="STRONG_REQUIREMENT")c.matched_strong_requirements.push(...(extra.matched_concepts??[]));if(cls==="PREFERENCE")c.matched_preferences.push(...(extra.matched_concepts??[]))};
  const run=async(name:string,fn:()=>Promise<number>)=>{const started=performance.now();try{const hits=await fn();diag.channels[name]={status:hits>0?"AVAILABLE_WITH_HITS":"AVAILABLE_NO_HITS",hits,elapsed_ms:performance.now()-started};}catch(e:any){diag.channels[name]={status:"UNAVAILABLE",elapsed_ms:performance.now()-started,error:{code:e?.code??null,message:e?.message??String(e)}};if(!diag.unavailable_channels.includes(name))diag.unavailable_channels.push(name)}};
  await run("FILENAME_LITERAL",async()=>{const original=String(queryPlan?.original_query??"").trim(),token=original.match(/\b[A-Za-z][A-Za-z0-9_-]*\d[A-Za-z0-9_-]*(?:\.[A-Za-z0-9]{2,5})?\b/)?.[0];
  // The token pattern only recognises letter-initial names, and on a name like
  // "3631150497-preview.mp4" it latches onto the "mp4" fragment. Library filenames may also begin
  // with a digit and carry dots, spaces and parentheses ("25.01 (18).jpeg"). Probe the whole query
  // as a filename literal too, and let exact/stem scoring decide between the two.
  const whole=/^[A-Za-z0-9][A-Za-z0-9 ._()&'#+-]{0,119}$/.test(original)&&/\d/.test(original)?original:null;let matched=0;
  // A bare media extension is not a filename literal. "3631150497-preview.mp4" makes the token
  // pattern latch onto its "mp4" fragment, which then ilike-matches every mp4 in the library and
  // pushes the genuine exact match off rank 1. Extensions are already handled as EXTENSION and
  // MEDIA_TYPE hard constraints by the parser, so matching them here is both redundant and harmful.
  const BARE_EXTENSION=/^(mp4|m4v|mov|avi|mkv|webm|jpe?g|png|gif|heic|heif|webp|tiff?|bmp|mp3|wav|m4a|aac)$/i;
  for(const literal of ([...new Set([token,whole].filter(Boolean))] as string[]).filter(x=>!BARE_EXTENSION.test(x))){const q=await db.from("assets").select("id,file_name,mime_type,file_extension").ilike("file_name",`%${literal}%`).limit(Number(policy.per_channel_k));if(q.error)throw q.error;for(const row of q.data??[]){const exact=String(row.file_name).toLowerCase()===literal.toLowerCase(),stem=String(row.file_name).replace(/\.[^.]+$/,"").toLowerCase()===literal.replace(/\.[^.]+$/,"").toLowerCase();add(row,"FILENAME_LITERAL",{matched_literal:literal,raw_score:exact?1:stem?.98:.9,evidence_source:"canonical_asset_filename"})}matched+=(q.data??[]).length}return matched});
  // Structured semantic facts come from both stores. asset_search_concepts_v2 holds the normalized
  // search concepts, but the authoritative 18-layer observations live in semantic_assertions, and a
  // concept asserted there (an OCR or audio observation, say) would otherwise never enter the
  // candidate set - it would only ever be a reranking signal for candidates found some other way.
  await run("STRUCTURED_CANONICAL",async()=>{let n=0;for(const r of expanded.filter((x:any)=>x.canonical_code)){
    const q=await db.from("asset_search_concepts_v2").select("asset_id,scene_id,event_id,canonical_code,display_text,id").eq("canonical_code",r.canonical_code).limit(Number(policy.per_channel_k));
    if(q.error)throw q.error;
    for(const row of q.data??[]){n++;add(row,"STRUCTURED_CANONICAL",{matched_concepts:[r.canonical_code],requirement_classification:r.classification,raw_score:1})}
    const observed=await db.from("semantic_assertions").select("id,asset_id,scene_id,event_id,keyframe_id,canonical_concept_code").eq("canonical_concept_code",r.canonical_code).eq("semantic_state","OBSERVED").eq("active",true).limit(Number(policy.per_channel_k));
    if(observed.error&&observed.error.code!=="42501")throw observed.error;
    for(const row of observed.error?[]:observed.data??[]){n++;add(row,"STRUCTURED_CANONICAL",{matched_concepts:[r.canonical_code],requirement_classification:r.classification,raw_score:1,evidence_source:"canonical_semantic_assertion"})}
  }return n});
  await run("EXPANDED_STRUCTURED",async()=>{let n=0;for(const r of expanded)for(const e of r.expansions??[]){if(!e.term||e.expansion_type==="CANONICAL")continue;const q=await db.from("asset_search_concepts_v2").select("asset_id,scene_id,event_id,canonical_code,display_text,id").eq("canonical_code",e.canonical_target??r.canonical_code).limit(5);if(q.error)continue;for(const row of q.data??[]){n++;add(row,"EXPANDED_STRUCTURED",{matched_concepts:[e.canonical_target??r.canonical_code],matched_terms:[e.term],expansion_provenance:e,requirement_classification:r.classification,raw_score:e.weight})}}return n});
  await run("FULL_TEXT",async()=>{let n=0;const original=String(queryPlan?.original_query??"");const lexical=[...new Set([...expanded.flatMap((r:any)=>(r.expansions??[]).map((e:any)=>term(r,e))),...original.toLowerCase().match(/[a-z][a-z-]{3,}/g)??[]])].filter((t:any)=>t&&!/^(find|show|give|videos?|footage|clips?|with|similar|material|please)$/.test(t)).slice(0,20);for(const t of lexical){const q=await db.from("search_document_builds").select("id,asset_id,scene_id,event_id,search_text,status").eq("status","READY").eq("active",true).eq("stale",false).ilike("search_text",`%${t}%`).limit(10);if(q.error)continue;for(const row of q.data??[]){n++;add(row,"FULL_TEXT",{matched_terms:[t],raw_score:.75,evidence_source:"canonical_search_document"})}}return n});
  await run("READY_BROWSE",async()=>{const original=String(queryPlan?.original_query??"").trim();if(!/^(?:(?:give|show|find|return)(?:\s+me)?\s+)?\d+\s+(?:files|results|items|assets|media|videos?|images?|photos?|documents?)$/i.test(original))return 0;const q=await db.from("search_document_builds").select("id,asset_id,status").eq("document_type","ASSET").eq("status","READY").eq("active",true).eq("stale",false).limit(target);if(q.error)throw q.error;for(const row of q.data??[])add(row,"READY_BROWSE",{raw_score:.1,evidence_source:"canonical_search_ready_browse"});return(q.data??[]).length});
  await run("OCR_LITERAL",async()=>{let n=0;for(const r of expanded.filter((x:any)=>x.field==="OCR_LITERAL")){const t=String(r.value).replaceAll("*","");const q=await db.from("ocr_observations").select("id,asset_id,scene_id,event_id,keyframe_id,timestamp_seconds,end_time,raw_text,normalized_text,search_status,confidence,provenance").eq("search_status","ACCEPTED_FOR_SEARCH").ilike("raw_text",`%${t}%`).limit(10);if(q.error)throw q.error;for(const row of q.data??[]){n++;add(row,"OCR_LITERAL",{matched_literal:r.value,requirement_classification:r.classification,raw_score:1,evidence_source:"trusted_ocr_observation"})}}return n});
  await run("TRANSCRIPT_LITERAL",async()=>{let n=0;for(const r of expanded.filter((x:any)=>x.field==="TRANSCRIPT_LITERAL")){const t=String(r.value).replaceAll("*","");const q=await db.from("asset_transcript_chunks").select("id,asset_id,scene_id,event_id,start_seconds,end_seconds,transcript_text,raw_text,normalized_text,search_status,confidence,provenance").eq("search_status","ACCEPTED_FOR_SEARCH").ilike("transcript_text",`%${t}%`).limit(10);if(q.error)throw q.error;for(const row of q.data??[]){n++;add(row,"TRANSCRIPT_LITERAL",{matched_literal:r.value,requirement_classification:r.classification,raw_score:1,evidence_source:"trusted_transcript_chunk"})}}return n});
  await run("METADATA",async()=>{const media=expanded.find((r:any)=>r.field==="MEDIA_TYPE"),ext=expanded.find((r:any)=>r.field==="EXTENSION");if(!media&&!ext)return 0;let q:any=db.from("assets").select("id,file_name,mime_type,file_extension").limit(Number(policy.per_channel_k));if(media)q=q.ilike("mime_type",`${String(media.value).toLowerCase()==="video"?"video":"image"}/%`);if(ext)q=q.ilike("file_extension",String(ext.value));const result=await q;if(result.error)throw result.error;for(const row of result.data??[])add(row,"METADATA",{requirement_classification:"HARD_CONSTRAINT",raw_score:1});return (result.data??[]).length});
  const vectorChannel=async(channel:string,identity:EmbeddingCompatibility,vector:number[],minimum:number)=>run(channel,async()=>{assertEmbeddingCompatibility(identity,vector);const q=await db.rpc("match_kdi_semantic_search_embeddings",{query_embedding:vector,requested_representation:identity.representation,requested_provider:identity.provider,requested_model:identity.model,requested_model_version:identity.modelVersion,requested_dimension:identity.dimension,result_limit:Number(policy.per_channel_k),minimum_similarity:minimum});if(q.error)throw q.error;for(const [rank,row]of(q.data??[]).entries())add(row,channel,{raw_score:Number(row.raw_similarity),channel_rank:rank+1,representation_type:identity.representation,matched_terms:[queryPlan?.original_query??""]});return(q.data??[]).length});
  if(input.queryVectors?.text)for(const r of ["TEXT_ASSET","TEXT_SCENE","TEXT_EVENT","TEXT_TRANSCRIPT","TEXT_OCR"])await vectorChannel(r,{representation:r,provider:"sentence_transformers",model:"intfloat/multilingual-e5-small",modelVersion:"hf-main-pinned-runtime-v1",dimension:384,normalization:"L2"},input.queryVectors.text,Number(policy.thresholds.text_vector));
  if(input.queryVectors?.visual)for(const r of ["VISUAL_ASSET","VISUAL_SCENE","VISUAL_KEYFRAME"])await vectorChannel(r,{representation:r,provider:"open_clip",model:"ViT-B-32",modelVersion:"laion2b_s34b_b79k",dimension:512,normalization:"L2"},input.queryVectors.visual,Number(policy.thresholds.visual_vector));
  const vectorNames=["TEXT_ASSET","TEXT_SCENE","TEXT_EVENT","TEXT_TRANSCRIPT","TEXT_OCR","VISUAL_ASSET","VISUAL_SCENE","VISUAL_KEYFRAME"];
  for(const name of vectorNames)if(!diag.channels[name]){diag.channels[name]={status:"UNAVAILABLE",reason:"QUERY_VECTOR_NOT_PROVIDED_OR_CHANNEL_RPC_NOT_CONFIGURED"};if(!diag.unavailable_channels.includes(name))diag.unavailable_channels.push(name)}
  // E5 cosine values are not globally calibrated across arbitrary domains.
  // When Phases 14-16 preserve the whole semantic request as unresolved, an
  // E5-only nearest neighbour is not meaningful evidence. Keep candidates if
  // another trusted channel grounds the request; otherwise return no match.
  if(expanded.length===0){for(const[id,c]of by)if(c.channels.every((h:any)=>String(h.channel).startsWith("TEXT_")))by.delete(id)}
  const hard=reqs(requirementPlan?.hard_constraints),exclusions=reqs(requirementPlan?.hard_exclusions);const media=hard.find((r:any)=>r.field==="MEDIA_TYPE"),extension=hard.find((r:any)=>r.field==="EXTENSION");
  if(by.size&&(media||extension)){const ids=[...by.keys()],q=await db.from("assets").select("id,file_name,mime_type,file_extension").in("id",ids);if(q.error)diag.errors.push({channel:"HARD_CONSTRAINT",message:q.error.message});else{const allowed=new Set((q.data??[]).filter((a:any)=>(!media||String(a.mime_type).toLowerCase().startsWith(`${String(media.value).toLowerCase()}/`))&&(!extension||String(a.file_extension).toLowerCase()===String(extension.value).toLowerCase())).map((a:any)=>String(a.id)));for(const id of ids)if(!allowed.has(id))by.delete(id);for(const a of q.data??[]){const c=by.get(String(a.id));if(c&&!c.filename)c.filename=a.file_name}}}
  const explicitFalseObservation=/\bexplicitly\s+(?:does\s+)?not\s+(?:showing|containing|with|depicting)\b/i.test(String(queryPlan?.original_query??""));
  if(explicitFalseObservation&&exclusions.some((r:any)=>r.canonical_code)){by.clear();for(const x of exclusions.filter((r:any)=>r.canonical_code)){const q=await db.from("semantic_assertions").select("id,asset_id,scene_id,event_id,canonical_concept_code").eq("canonical_concept_code",x.canonical_code).eq("semantic_state","FALSE").eq("active",true).is("superseded_by",null).limit(Number(policy.per_channel_k));if(q.error)diag.errors.push({channel:"STRUCTURED_FALSE",message:q.error.message});else for(const row of q.data??[])add(row,"STRUCTURED_FALSE",{matched_concepts:[x.canonical_code],requirement_classification:"STRONG_REQUIREMENT",raw_score:1,evidence_source:"explicit_false_semantic_assertion"})}}
  else for(const x of exclusions.filter((r:any)=>r.canonical_code)){const q=await db.from("asset_search_concepts_v2").select("asset_id").eq("canonical_code",x.canonical_code).limit(500);if(q.error)diag.errors.push({channel:"HARD_EXCLUSION",message:q.error.message});else for(const row of q.data??[])by.delete(String(row.asset_id))}
  const missingNames=[...by.values()].filter(c=>!c.filename).map(c=>c.asset_id);if(missingNames.length){const q=await db.from("assets").select("id,file_name").in("id",missingNames);if(q.error)diag.errors.push({channel:"FILENAME_ROLLUP",message:q.error.message});else for(const a of q.data??[]){const c=by.get(String(a.id));if(c)c.filename=a.file_name}}
  // Production semantic retrieval is restricted to the current READY corpus.
  // This is applied after channel union and before ranking/count control.
  if(by.size){const ids=[...by.keys()],q=await db.from("kdi_search_ready_assets_v1").select("asset_id").in("asset_id",ids).eq("search_ready",true);if(q.error)throw q.error;const ready=new Set((q.data??[]).map((x:any)=>String(x.asset_id)));for(const id of ids)if(!ready.has(id))by.delete(id);diag.search_ready_filter={authority:"kdi_search_ready_assets_v1",input:ids.length,ready:by.size,excluded:ids.length-by.size}}
  const core={query_fingerprint:queryPlan?.parser_metadata?.query_fingerprint??null,requirement_plan_fingerprint:requirementPlan?.classifier_fingerprint??null,expanded_query_fingerprint:expandedQueryPlan?.expansion_fingerprint??null,retriever_version:CANDIDATE_RETRIEVER_VERSION,retrieval_policy_version:RETRIEVAL_POLICY_VERSION,requested_result_count:queryPlan?.result_request?.effective_count??null,retrieval_target_k:target,candidates:[...by.values()].sort((a,b)=>b.channel_count-a.channel_count||b.best_channel_score-a.best_channel_score||a.asset_id.localeCompare(b.asset_id)).slice(0,target).map(c=>({...c,matched_hard_constraints:[...new Set(c.matched_hard_constraints)],matched_strong_requirements:[...new Set(c.matched_strong_requirements)],matched_preferences:[...new Set(c.matched_preferences)]})),diagnostics:diag};
  return freeze({...core,candidate_set_fingerprint:finger(core)});
}
