import { createHash } from "node:crypto";
import type { SupabaseClient } from "@supabase/supabase-js";
import config from "../../config/semantic-search/kdi_deterministic_reranker_v1.json";

export const DETERMINISTIC_RERANKER_VERSION=config.version;
export const RANKED_AUTHORIZED_CANDIDATE_SCHEMA_VERSION=config.schema_version;
const canonical=(x:unknown):string=>Array.isArray(x)?`[${x.map(canonical).join(",")}]`:x&&typeof x==="object"?`{${Object.keys(x).sort().map(k=>JSON.stringify(k)+":"+canonical((x as any)[k])).join(",")}}`:JSON.stringify(x);
export const RERANKER_CONFIGURATION_FINGERPRINT=createHash("sha256").update(canonical(config)).digest("hex");
const freeze=<T>(x:T):T=>{if(x&&typeof x==="object"&&!Object.isFrozen(x)){Object.freeze(x);for(const v of Object.values(x as any))freeze(v)}return x};
const round=(n:number)=>Math.round(n*1e6)/1e6,clamp=(n:number,min=0,max=100)=>Math.max(min,Math.min(max,n));
const AUTHORIZATION_FINGERPRINT=/^[0-9a-f]{64}$/i;

export type SemanticState="OBSERVED"|"FALSE"|"UNKNOWN"|"NOT_APPLICABLE";
export type MatchType="EXACT_CANONICAL"|"EXACT_ALIAS"|"SAFE_EXPANSION"|"PARENT_CHILD_ONTOLOGY"|"LITERAL"|"FULL_TEXT"|"SEMANTIC_TEXT"|"VISUAL_SIMILARITY"|"UNRESOLVED_GROUNDED";
export type EvidenceFact={assetId:string;concept:string;state:SemanticState;sourceLayer:string;evidenceId:string;sceneId?:string|null;eventId?:string|null;confidence?:number;provenanceGroup?:string};
export type EvidenceContribution={requirementId:string;requirementClass:string;matchedConcept:string|null;matchType:MatchType|null;sourceLayer:string|null;evidenceIds:string[];state:SemanticState;confidence:number;baseContribution:number;weight:number;penalty:number;finalContribution:number};
export type CandidateScore={assetId:string;eligible:boolean;hardConstraintStatus:"SATISFIED"|"UNKNOWN"|"VIOLATED";hardExclusionStatus:"CLEAR"|"VIOLATED";strongRequirementCoverage:number;preferenceScore:number;negativePreferencePenalty:number;evidenceScore:number;literalScore:number;semanticTextScore:number;visualScore:number;specificityScore:number;contradictionPenalty:number;rawScore:number;normalizedScore:number;strongRequirementsSatisfied:number;exactCanonicalMatches:number;meanEvidenceConfidence:number;coherentRequirementGroups:number;evidenceContributions:EvidenceContribution[]};
export type AuthorizedCandidate={asset_id:string;filename?:string|null;channels?:any[];authorization:{discover:true;view_metadata:true;preview:true;download:boolean;[key:string]:unknown};[key:string]:unknown};
export type AuthorizedCandidateSet={schema_version:"kdi_authorized_candidate_set_v1";authorization_fingerprint:string;candidates:AuthorizedCandidate[];[key:string]:unknown};
export type RankedAuthorizedCandidateSet={schema_version:string;reranker_version:string;configuration_fingerprint:string;source_authorization_fingerprint:string|null;requested_result_count:number|null;candidates:Array<AuthorizedCandidate&{phase19:CandidateScore}>;ranking_fingerprint:string;diagnostics:{input_candidates:number;ranked_candidates:number;ineligible_candidates:number;database_query_count:number;authorization_boundary_valid:boolean}};
export type EvidenceBundle={facts:EvidenceFact[];metadata:Record<string,{mimeType?:string|null;extension?:string|null}>};

const buckets=(plan:any)=>({hard:plan?.hard_constraints??[],exclude:plan?.hard_exclusions??[],strong:plan?.strong_requirements??[],preference:plan?.preferences??[],negative:plan?.negative_preferences??[],context:plan?.context??[],unresolved:plan?.unresolved??[],conflicts:plan?.conflicts??[]});
const requirementConcept=(r:any)=>String(r.canonical_code??r.value??"").toUpperCase();
function matchType(requirement:any,fact:EvidenceFact,expanded:any):MatchType|null{const expected=requirementConcept(requirement);if(fact.concept===expected)return"EXACT_CANONICAL";const e=(expanded?.requirements??[]).find((x:any)=>x.id===requirement.id)?.expansions?.find((x:any)=>String(x.canonical_target??"").toUpperCase()===fact.concept);if(!e)return null;if(e.expansion_type==="EXACT_ALIAS")return"EXACT_ALIAS";if(["SAFE_SYNONYM","MORPHOLOGICAL_VARIANT"].includes(e.expansion_type))return"SAFE_EXPANSION";if(["ONTOLOGY_PARENT","ONTOLOGY_CHILD"].includes(e.expansion_type))return"PARENT_CHILD_ONTOLOGY";return e.expansion_type==="CANONICAL"?"EXACT_CANONICAL":null}
function distinctFacts(facts:EvidenceFact[]){const seen=new Set<string>();return facts.filter(f=>{const key=f.provenanceGroup??`${f.sourceLayer}:${f.evidenceId}`;if(seen.has(key))return false;seen.add(key);return true})}
function requirementEvidence(requirement:any,facts:EvidenceFact[],expanded:any){return distinctFacts(facts.filter(f=>matchType(requirement,f,expanded)!==null)).sort((a,b)=>a.evidenceId.localeCompare(b.evidenceId))}
function contribution(requirement:any,evidence:EvidenceFact[],expanded:any,weight:number):EvidenceContribution{const observed=evidence.filter(x=>x.state==="OBSERVED"),negative=evidence.filter(x=>x.state==="FALSE"),notApplicable=evidence.filter(x=>x.state==="NOT_APPLICABLE"),state:SemanticState=observed.length?"OBSERVED":negative.length?"FALSE":notApplicable.length?"NOT_APPLICABLE":"UNKNOWN",best=observed[0]??negative[0]??notApplicable[0],type=best?matchType(requirement,best,expanded):null,quality=type?Number((config.match_quality as any)[type]):0,confidence=best?clamp(Number(best.confidence??1),0,1):0,independent=Math.min(Number(config.weights.independent_support_cap),Math.max(0,observed.length-1)),base=state==="OBSERVED"?quality*confidence:0,final=base*weight+(state==="OBSERVED"?independent:0);return{requirementId:requirement.id,requirementClass:requirement.classification,matchedConcept:best?.concept??null,matchType:type,sourceLayer:best?.sourceLayer??null,evidenceIds:evidence.map(x=>x.evidenceId),state,confidence,baseContribution:round(base),weight,penalty:0,finalContribution:round(final)}}
function mediaState(r:any,meta:any):SemanticState{if(r.field==="MEDIA_TYPE"){if(!meta?.mimeType)return"UNKNOWN";return String(meta.mimeType).toLowerCase().startsWith(`${String(r.value).toLowerCase()}/`)?"OBSERVED":"FALSE"}if(r.field==="EXTENSION"){if(!meta?.extension)return"UNKNOWN";return String(meta.extension).toLowerCase()===String(r.value).toLowerCase()?"OBSERVED":"FALSE"}return"UNKNOWN"}
function score(candidate:AuthorizedCandidate,facts:EvidenceFact[],meta:any,plan:any,expanded:any):CandidateScore{const b=buckets(plan),out:EvidenceContribution[]=[];let eligible=true,hardUnknown=false,hardViolation=false,exclusion=false,strongSatisfied=0,exact=0,pref=0,negativePenalty=0,evidenceScore=0,literal=0,semantic=0,visual=0,specificity=0,contradiction=0;
  for(const r of b.hard){const ev=requirementEvidence(r,facts,expanded),state=["MEDIA_TYPE","EXTENSION"].includes(r.field)?mediaState(r,meta):(ev.some(x=>x.state==="OBSERVED")?"OBSERVED":ev.some(x=>x.state==="FALSE")?"FALSE":"UNKNOWN");if(state==="FALSE"){eligible=false;hardViolation=true}if(state==="UNKNOWN")hardUnknown=true;const c=contribution(r,ev,expanded,Number(config.weights.hard_constraint_satisfied));if(state==="UNKNOWN")c.finalContribution=Number(config.weights.hard_constraint_unknown);if(state==="FALSE")c.penalty=100;out.push(c);evidenceScore+=c.finalContribution}
  for(const r of b.exclude){const ev=requirementEvidence(r,facts,expanded),observed=ev.some(x=>x.state==="OBSERVED");if(observed){eligible=false;exclusion=true;out.push({...contribution(r,ev,expanded,0),penalty:100,finalContribution:-100})}else out.push(contribution(r,ev,expanded,0))}
  for(const r of b.strong){const c=contribution(r,requirementEvidence(r,facts,expanded),expanded,Number(config.weights.strong_requirement));out.push(c);evidenceScore+=c.finalContribution;if(c.state==="OBSERVED"){strongSatisfied++;if(c.matchType==="EXACT_CANONICAL")exact++;specificity+=Number(config.weights.specificity)*c.baseContribution}}
  for(const r of b.preference){const c=contribution(r,requirementEvidence(r,facts,expanded),expanded,Number(config.weights.preference));out.push(c);pref+=c.finalContribution}
  for(const r of b.context){const c=contribution(r,requirementEvidence(r,facts,expanded),expanded,Number(config.weights.context));out.push(c);pref+=c.finalContribution}
  for(const r of b.negative){const c=contribution(r,requirementEvidence(r,facts,expanded),expanded,0);if(c.state==="OBSERVED"){c.penalty=-Number(config.weights.negative_preference_violation);c.finalContribution=c.penalty;negativePenalty+=-c.penalty}else if(c.state==="FALSE")c.finalContribution=Number(config.weights.negative_preference_explicit_false);out.push(c)}
  const observedStrong=out.filter(x=>x.requirementClass==="STRONG_REQUIREMENT"&&x.state==="OBSERVED"),sceneCounts=new Map<string,Set<string>>(),eventCounts=new Map<string,Set<string>>();for(const c of observedStrong)for(const f of facts.filter(x=>c.evidenceIds.includes(x.evidenceId))){if(f.sceneId){const s=sceneCounts.get(f.sceneId)??new Set();s.add(c.requirementId);sceneCounts.set(f.sceneId,s)}if(f.eventId){const s=eventCounts.get(f.eventId)??new Set();s.add(c.requirementId);eventCounts.set(f.eventId,s)}}const sceneCoherent=[...sceneCounts.values()].some(s=>s.size>=Math.min(2,b.strong.length)),eventCoherent=[...eventCounts.values()].some(s=>s.size>=Math.min(2,b.strong.length)),coherent=Number(sceneCoherent)+Number(eventCoherent),coherence=(sceneCoherent?Number(config.weights.same_scene_coherence):0)+(eventCoherent?Number(config.weights.same_event_coherence):0);
  const channels=distinctFacts((candidate.channels??[]).map((h:any)=>({assetId:candidate.asset_id,concept:"",state:"OBSERVED" as const,sourceLayer:h.channel,evidenceId:String(h.source_id??`${h.channel}:${h.channel_rank}`),confidence:Number(h.normalized_channel_score??0),provenanceGroup:String(h.source_document_id??h.source_id??`${h.channel}:${h.channel_rank}`)})));for(const h of channels){const confidence=Number(h.confidence??0);if(h.sourceLayer.startsWith("TEXT_")){semantic=Math.max(semantic,Number(config.weights.text_similarity_cap)*confidence)}else if(h.sourceLayer.startsWith("VISUAL_")){visual=Math.max(visual,Number(config.weights.visual_similarity_cap)*confidence)}else if(["OCR_LITERAL","TRANSCRIPT_LITERAL","FILENAME_LITERAL"].includes(h.sourceLayer)){literal=Math.max(literal,Number(config.weights.literal_exact)*confidence)}else if(h.sourceLayer==="FULL_TEXT"){literal=Math.max(literal,Number(config.weights.literal_exact)*Number(config.match_quality.FULL_TEXT)*confidence)}}
  // Unresolved natural-language terms may use vector channels for discovery, but
  // vector proximity alone is not evidence. Only explicit filename identity or a
  // count/type-only READY browse request may pass without grounded requirements.
  const channelNames=new Set((candidate.channels??[]).map((h:any)=>String(h.channel)));
  // Vector proximity (TEXT_*/VISUAL_*) alone is not evidence. But lexical grounding - a full-text
  // hit on the search document, or an OCR/transcript/filename literal - is real textual evidence, so
  // it keeps the candidate eligible (it will rank below structurally-grounded matches via literal/
  // semantic scoring). Only when nothing resolves AND there is no lexical grounding do we drop it;
  // otherwise a query whose terms miss the ontology returns zero instead of degraded recall.
  const GROUNDING_CHANNELS=["FILENAME_LITERAL","READY_BROWSE","FULL_TEXT","OCR_LITERAL","TRANSCRIPT_LITERAL"];
  if(b.unresolved.length>0&&b.strong.length===0&&b.preference.length===0&&b.context.length===0&&!GROUNDING_CHANNELS.some(c=>channelNames.has(c)))eligible=false;
  contradiction=b.conflicts.length*Number(config.weights.conflict);const raw=eligible?evidenceScore+pref-negativePenalty+specificity+coherence+literal+semantic+visual-contradiction:-100,confident=out.filter(x=>x.state==="OBSERVED").map(x=>x.confidence),coverage=b.strong.length?strongSatisfied/b.strong.length:1;return{assetId:candidate.asset_id,eligible,hardConstraintStatus:hardViolation?"VIOLATED":hardUnknown?"UNKNOWN":"SATISFIED",hardExclusionStatus:exclusion?"VIOLATED":"CLEAR",strongRequirementCoverage:round(coverage),preferenceScore:round(pref),negativePreferencePenalty:round(negativePenalty),evidenceScore:round(evidenceScore),literalScore:round(literal),semanticTextScore:round(semantic),visualScore:round(visual),specificityScore:round(specificity),contradictionPenalty:round(contradiction),rawScore:round(raw),normalizedScore:round(eligible?clamp(raw):0),strongRequirementsSatisfied:strongSatisfied,exactCanonicalMatches:exact,meanEvidenceConfidence:round(confident.length?confident.reduce((a,n)=>a+n,0)/confident.length:0),coherentRequirementGroups:coherent,evidenceContributions:out}}
export function rerankAuthorizedCandidates(input:AuthorizedCandidateSet,requirementPlan:any,expandedQueryPlan:any,evidence:EvidenceBundle,requestedResultCount:number|null=null):RankedAuthorizedCandidateSet{const boundary=input?.schema_version==="kdi_authorized_candidate_set_v1"&&AUTHORIZATION_FINGERPRINT.test(input.authorization_fingerprint)&&Array.isArray(input.candidates)&&input.candidates.every(c=>c.authorization?.discover===true&&c.authorization?.view_metadata===true&&c.authorization?.preview===true);const candidates=boundary?input.candidates:[],factsBy=new Map<string,EvidenceFact[]>();for(const f of evidence.facts){const x=factsBy.get(f.assetId)??[];x.push({...f,concept:f.concept.toUpperCase()});factsBy.set(f.assetId,x)}const ranked=candidates.map(c=>({...c,phase19:score(c,factsBy.get(c.asset_id)??[],evidence.metadata[c.asset_id],requirementPlan,expandedQueryPlan)})).sort((a,b)=>Number(b.phase19.eligible)-Number(a.phase19.eligible)||b.phase19.normalizedScore-a.phase19.normalizedScore||b.phase19.strongRequirementsSatisfied-a.phase19.strongRequirementsSatisfied||b.phase19.exactCanonicalMatches-a.phase19.exactCanonicalMatches||b.phase19.meanEvidenceConfidence-a.phase19.meanEvidenceConfidence||b.phase19.coherentRequirementGroups-a.phase19.coherentRequirementGroups||a.asset_id.localeCompare(b.asset_id));const core={schema_version:RANKED_AUTHORIZED_CANDIDATE_SCHEMA_VERSION,reranker_version:DETERMINISTIC_RERANKER_VERSION,configuration_fingerprint:RERANKER_CONFIGURATION_FINGERPRINT,source_authorization_fingerprint:boundary?input.authorization_fingerprint:null,requested_result_count:requestedResultCount,candidates:ranked,diagnostics:{input_candidates:input?.candidates?.length??0,ranked_candidates:ranked.length,ineligible_candidates:ranked.filter(x=>!x.phase19.eligible).length,database_query_count:0,authorization_boundary_valid:boundary}};return freeze({...core,ranking_fingerprint:createHash("sha256").update(canonical(core)).digest("hex")})}
export async function loadRerankingEvidence(db:SupabaseClient,input:AuthorizedCandidateSet):Promise<EvidenceBundle&{databaseQueryCount:number}>{if(input.schema_version!=="kdi_authorized_candidate_set_v1"||!AUTHORIZATION_FINGERPRINT.test(input.authorization_fingerprint)||!input.candidates.every(c=>c.authorization?.discover===true&&c.authorization?.view_metadata===true&&c.authorization?.preview===true))return{facts:[],metadata:{},databaseQueryCount:0};const ids=input.candidates.map(c=>c.asset_id),[assertions,concepts,assets]=await Promise.all([db.from("semantic_assertions").select("id,asset_id,canonical_concept_code,semantic_state,scene_id,event_id,confidence").in("asset_id",ids).eq("active",true).is("superseded_by",null),db.from("asset_search_concepts_v2").select("id,asset_id,canonical_code,scene_id,event_id").in("asset_id",ids),db.from("assets").select("id,mime_type,file_extension").in("id",ids)]);if(concepts.error||assets.error)throw concepts.error??assets.error;if(assertions.error&&assertions.error.code!=="42501")throw assertions.error;const group=(x:any,concept:string)=>`fact:${x.asset_id}:${concept}:${x.scene_id??"asset"}:${x.event_id??"none"}`,direct=(assertions.error?[]:assertions.data??[]).filter((x:any)=>x.canonical_concept_code&&["OBSERVED","FALSE","UNKNOWN","NOT_APPLICABLE"].includes(x.semantic_state)).map((x:any)=>({assetId:String(x.asset_id),concept:String(x.canonical_concept_code),state:x.semantic_state as SemanticState,sourceLayer:"DIRECT_STRUCTURED_OBSERVATION",evidenceId:String(x.id),sceneId:x.scene_id,eventId:x.event_id,confidence:Number(x.confidence??0),provenanceGroup:group(x,String(x.canonical_concept_code))})),normalized=(concepts.data??[]).map((x:any)=>({assetId:String(x.asset_id),concept:String(x.canonical_code),state:"OBSERVED" as const,sourceLayer:"NORMALIZED_SEARCH_DOCUMENT",evidenceId:String(x.id),sceneId:x.scene_id,eventId:x.event_id,confidence:1,provenanceGroup:group(x,String(x.canonical_code))}));return{facts:[...direct,...normalized],metadata:Object.fromEntries((assets.data??[]).map((x:any)=>[String(x.id),{mimeType:x.mime_type,extension:x.file_extension}])),databaseQueryCount:3}}
