import { createHash } from "node:crypto";
import { KDISemanticDatabaseMaintainer, MAINTAINER_INSTRUCTION_CONTRACT, type MaintainerDataset, type MaintenanceActionRequest } from "./semantic-database-maintainer";
export const DATABASE_MAINTENANCE_AI_ENABLED = false;
export const DATABASE_MAINTENANCE_PROVIDER = "openai";
export const DATABASE_MAINTENANCE_MODEL = process.env.DATABASE_MAINTENANCE_MODEL ?? "gpt-5.6-sol";
export const TOOL_SCHEMA_VERSION = "kdi_maintenance_tools_v1";
export type ToolCall = { name: string; arguments: Record<string, unknown> };
export type DatabaseMaintenanceReasoningProvider = { readonly providerName: string; next(context: unknown, tools: unknown[]): Promise<ToolCall | null> };
export class MockDatabaseMaintenanceProvider implements DatabaseMaintenanceReasoningProvider { readonly providerName="MOCK_MAINTENANCE"; private index=0; constructor(private readonly calls:ToolCall[]){ } async next(){return this.calls[this.index++]??null;} }
// The disabled provider still has to satisfy the interface: a method that only throws is inferred
// as Promise<void>, which does not match Promise<ToolCall | null> and failed the production build.
export class OpenAIDatabaseMaintenanceProvider implements DatabaseMaintenanceReasoningProvider { readonly providerName="openai"; async next(_context:unknown,_tools:unknown[]):Promise<ToolCall|null>{throw new Error("DATABASE_MAINTENANCE_AI_DISABLED");} }
export type MaintenanceRun = { runId:string; mode:"READ_ONLY"|"CONTROLLED_REPAIR"; status:string; provider:string; model:string; instructionVersion:string; toolSchemaVersion:string; startedAt:string; completedAt:string; durationMs:number; toolCallsCount:number; findingsExamined:number; actionsRequested:number; actionsCompleted:number; actionsFailed:number; inputTokens:null; outputTokens:null; totalTokens:null; estimatedCost:null; requestIds:string[]; errorClass:null; loopGuardTriggered:boolean; toolAudit:Array<Record<string, unknown>>; summary:string };
const hash=(x:unknown)=>createHash("sha256").update(JSON.stringify(x)).digest("hex");
export class OpenAISemanticDatabaseMaintenanceOrchestrator {
  constructor(private readonly maintainer:KDISemanticDatabaseMaintainer, private readonly provider:DatabaseMaintenanceReasoningProvider, private readonly options={maxToolRounds:8,maxToolCalls:16,maxItemsPerListTool:20,maxRetries:0}){}
  async run():Promise<MaintenanceRun>{const start=Date.now(),runId=`maintenance-${start}`,calls:Array<Record<string,unknown>>=[],seen=new Map<string,number>();let findings=0,actionsRequested=0,actionsCompleted=0,actionsFailed=0,loopGuardTriggered=false;let summary="No verified maintenance action requested.";let context=this.maintainer.getDatabaseHealth();for(let round=0;round<this.options.maxToolRounds&&calls.length<this.options.maxToolCalls;round++){const call=await this.provider.next(context,this.maintainer.toolDefinitions());if(!call)break;const key=`${call.name}:${hash(call.arguments)}`,repeats=(seen.get(key)??0)+1;seen.set(key,repeats);if(repeats>2){loopGuardTriggered=true;summary="LOOP_GUARD_TRIGGERED";break}const at=Date.now();let result:any;try{result=this.execute(call);if(call.name.startsWith("queue_")||call.name.includes("rebuild")||call.name.includes("reindex")){actionsRequested++;if(result.status?.startsWith("REJECTED"))actionsFailed++;else actionsCompleted++}if(call.name.includes("finding"))findings++;context=result;summary=this.summarize(call,result)}catch(error){result={status:"REJECTED",error:error instanceof Error?error.message:"TOOL_ERROR"};actionsFailed++}calls.push({runId,toolName:call.name,argumentsHash:hash(call.arguments),safeArguments:call.arguments,requestedAt:new Date(at).toISOString(),completedAt:new Date().toISOString(),status:result.status??"COMPLETED",resultSummary:result});}const end=Date.now();return{runId,mode:this.maintainer.mode==="CONTROLLED_WRITE"?"CONTROLLED_REPAIR":"READ_ONLY",status:"COMPLETED",provider:this.provider.providerName,model:DATABASE_MAINTENANCE_MODEL,instructionVersion:"kdi_semantic_database_maintainer_v1",toolSchemaVersion:TOOL_SCHEMA_VERSION,startedAt:new Date(start).toISOString(),completedAt:new Date(end).toISOString(),durationMs:end-start,toolCallsCount:calls.length,findingsExamined:findings,actionsRequested,actionsCompleted,actionsFailed,inputTokens:null,outputTokens:null,totalTokens:null,estimatedCost:null,requestIds:[],errorClass:null,loopGuardTriggered,toolAudit:calls,summary};}
  private execute(call:ToolCall){const a=call.arguments;switch(call.name){case"get_database_health":return this.maintainer.getDatabaseHealth();case"get_asset_semantic_health":return this.maintainer.getAssetSemanticHealth(String(a.asset_id));case"list_maintenance_findings":return this.maintainer.listMaintenanceFindings().slice(0,this.options.maxItemsPerListTool);case"find_false_search_ready_assets":return this.maintainer.findFalseSearchReady().slice(0,this.options.maxItemsPerListTool);case"find_stale_search_documents":return this.maintainer.findStaleSearchDocuments().slice(0,this.options.maxItemsPerListTool);case"find_stale_embeddings":return this.maintainer.findStaleEmbeddings().slice(0,this.options.maxItemsPerListTool);case"find_failed_or_stuck_jobs":return this.maintainer.findFailedJobs().slice(0,this.options.maxItemsPerListTool);case"queue_embedding_rebuild":return this.maintainer.requestMaintenanceAction({actionType:"REBUILD_EMBEDDING",assetId:String(a.asset_id),findingId:a.finding_id?String(a.finding_id):undefined,requestedBy:String(a.requested_by??"model")});case"queue_asset_for_reindex":return this.maintainer.requestMaintenanceAction({actionType:"QUEUE_REINDEX",assetId:String(a.asset_id),requestedBy:String(a.requested_by??"model")});case"create_maintenance_finding":return this.maintainer.requestMaintenanceAction({actionType:"CREATE_REVIEW_FINDING",assetId:a.asset_id?String(a.asset_id):undefined,requestedBy:String(a.requested_by??"model")});default:throw new Error("UNAPPROVED_TOOL");}}
  private summarize(call:ToolCall,result:any){if(call.name.startsWith("queue_")&&result.status?.includes("ACCEPTED"))return"Action queued; pending backend verification.";if(call.name==="get_database_health"&&result.pendingIsHealthy)return"Healthy pending assets preserved as PENDING_ANALYSIS.";return"Verified tool result received.";}
}
export function maintenanceInstruction(){return MAINTAINER_INSTRUCTION_CONTRACT+" PostgreSQL is the source of truth; pgvector is retrieval storage. Begin with get_database_health and never use arbitrary SQL.";}
