import{createHash}from"node:crypto";import classifierConfig from"../../config/semantic-search/kdi_requirement_classifier_v1.json";import policy from"../../config/semantic-search/kdi_requirement_policy_v1.json";
export const REQUIREMENT_CLASSIFIER_VERSION=classifierConfig.requirement_classifier_version,REQUIREMENT_POLICY_VERSION=classifierConfig.requirement_policy_version,REQUIREMENT_SCHEMA_VERSION=classifierConfig.requirement_schema_version,REQUIREMENT_POLICY_FINGERPRINT=createHash("sha256").update(JSON.stringify(policy)).digest("hex");
export type RequirementClass="RESPONSE_CONTROL"|"HARD_CONSTRAINT"|"HARD_EXCLUSION"|"STRONG_REQUIREMENT"|"PREFERENCE"|"NEGATIVE_PREFERENCE"|"CONTEXT"|"UNRESOLVED"|"CONFLICT";
export type Requirement={id:string,field:string,value:any,canonical_code:string|null,source_field:string,source_span:{start_char:number|null,end_char:number|null},raw_text:string|null,polarity:"POSITIVE"|"NEGATIVE"|null,surface_marker:string|null,classification:RequirementClass,reason:string,clause_id:number|null,explicitness:"EXPLICIT_LITERAL"|"EXPLICIT_ALIAS"|"COMPOSITIONALLY_DERIVED"|"SEMANTICALLY_INFERRED"|"UNKNOWN",parser_provenance:any,classifier_provenance:any};
const canonical=(x:any):string=>Array.isArray(x)?`[${x.map(canonical).join(",")}]`:x&&typeof x==="object"?`{${Object.keys(x).sort().map(k=>JSON.stringify(k)+":"+canonical(x[k])).join(",")}}`:JSON.stringify(x),freeze=(x:any):any=>{if(x&&typeof x==="object"&&!Object.isFrozen(x)){Object.freeze(x);for(const v of Object.values(x))freeze(v)}return x};
const markerNear=(q:string,c:any,kind:"PREFERENCE"|"HARD")=>{const s=c.start_char??0,e=c.end_char??s,b=q.slice(Math.max(0,s-55),s).toLowerCase(),a=q.slice(e,Math.min(q.length,e+40)).toLowerCase();return kind==="PREFERENCE"?/\b(prefer|preferably|ideally|if possible|would prefer|nice to have|better if|priority to|favor)\b/.test(b)||/^\s*(?:if possible|preferably|ideally)\b/.test(a):/\b(must(?: show| include| contain)?|required|has to show|needs to show)\b/.test(b)||/^\s*(?:must|is required|has to|needs to)\b/.test(a)};
const negativePreference=(q:string,c:any)=>{const s=c.start_char??0,e=c.end_char??s,around=q.slice(Math.max(0,s-60),Math.min(q.length,e+45)).toLowerCase();return /\b(?:prefer(?:ably)?\s+(?:no|without|not)|prefer\s+to\s+avoid|if possible\s+(?:please\s+)?avoid|avoid\b[^,.!?;]{0,35}\bif possible|would rather not|ideally\s+(?:no|without))\b/.test(around)};
const onlyPromotes=(q:string,c:any,plan:any)=>{const s=c.start_char??0,b=q.slice(Math.max(0,s-60),s).toLowerCase();if(!/\bonly\b/.test(b))return false;const media=plan.media.media_type_extraction;if(media&&media.start_char<s&&/\bonly\s+(?:show\s+)?(?:videos?|images?|photos?|files?|media)\b/.test(q.slice(Math.max(0,media.start_char-12),media.end_char+2).toLowerCase()))return false;return /\bonly\s+(?:show|include|with|containing|featuring)\b/.test(b)};
function req(field:string,value:any,classification:RequirementClass,reason:string,src:any,plan:any,explicitness?:Requirement["explicitness"]):Requirement{const raw=src?.raw_text??null,start=src?.start_char??null,end=src?.end_char??null,code=src&&Object.prototype.hasOwnProperty.call(src,"canonical_code")?src.canonical_code:null,seed={field,value,classification,reason,raw,start,end,code,clause:src?.clause_id??null};return{id:createHash("sha256").update(canonical(seed)).digest("hex"),field,value,canonical_code:code,source_field:src?.source_field??field,source_span:{start_char:start,end_char:end},raw_text:raw,polarity:src?.polarity??null,surface_marker:src?.surface_strength??src?.marker??null,classification,reason,clause_id:src?.clause_id??null,explicitness:explicitness??"EXPLICIT_LITERAL",parser_provenance:{query_fingerprint:plan.parser_metadata.query_fingerprint,parser_version:plan.parser_metadata.query_parser_version,source:src?.source??"DETERMINISTIC_PARSER",normalization_status:src?.normalization_status??src?.status??"MATCHED"},classifier_provenance:{classifier_version:REQUIREMENT_CLASSIFIER_VERSION,policy_version:REQUIREMENT_POLICY_VERSION,policy_fingerprint:REQUIREMENT_POLICY_FINGERPRINT}}}
export function classifyRequirements(plan:any){const q=plan.original_query as string,all:Requirement[]=[];
 for(const x of plan.result_request.requested_count_occurrences??[])all.push(req("REQUESTED_RESULT_COUNT",x.value,"RESPONSE_CONTROL","RESPONSE_CONTROL_FIELD",{...x,source_field:"result_request.requested_count_occurrences"},plan));if(plan.ranking?.sort)all.push(req("SORT",plan.ranking.sort,"RESPONSE_CONTROL","RESPONSE_CONTROL_FIELD",{raw_text:plan.ranking.raw_text??null,source_field:"ranking.sort"},plan));if(plan.intent==="FIND_SIMILAR_MEDIA")all.push(req("SIMILARITY_INTENT",plan.intent,"RESPONSE_CONTROL","RESPONSE_CONTROL_FIELD",{raw_text:q,source_field:"intent"},plan));
 if(plan.media.media_type!=="ANY")all.push(req("MEDIA_TYPE",plan.media.media_type,"HARD_CONSTRAINT","EXPLICIT_MEDIA_TYPE",{...plan.media.media_type_extraction,source_field:"media.media_type"},plan));for(const x of plan.media.extension_extractions??[])all.push(req("EXTENSION",x.value,"HARD_CONSTRAINT","EXPLICIT_EXTENSION",{...x,source_field:"media.extensions"},plan));
 for(const [field,obj]of Object.entries(plan.temporal??{}))if(obj)all.push(req(field.toUpperCase(),obj,"HARD_CONSTRAINT","EXPLICIT_TEMPORAL_CONSTRAINT",{raw_text:(obj as any).raw_text??null,source_field:`temporal.${field}`},plan));
 const numeric=plan.numeric??{};for(const field of["age_exact","age_min","age_max","age_decade","graft_count_exact","graft_count_min","graft_count_max","treatment_session_count","session_ordinal","currency_amount"]){const value=numeric[field];if(value==null)continue;const range=/_min$|_max$/.test(field),occ=(numeric.occurrences??[]).find((x:any)=>x.value===value&&x.numeric_type!=="RESULT_COUNT");all.push(req(field.toUpperCase(),value,range?"HARD_CONSTRAINT":"STRONG_REQUIREMENT",range?"EXPLICIT_NUMERIC_RANGE":"DEFAULT_SEMANTIC_REQUIREMENT",{...occ,source_field:`numeric.${field}`},plan,range?"EXPLICIT_LITERAL":"SEMANTICALLY_INFERRED"))}
 for(const c of plan.semantic.positive_concepts??[]){const pref=markerNear(q,c,"PREFERENCE")||c.surface_strength==="PREFERENCE",hard=!pref&&(markerNear(q,c,"HARD")||c.surface_strength==="EXPLICIT_MUST"||c.surface_strength==="EXPLICIT_EXACT"||onlyPromotes(q,c,plan)),classification:RequirementClass=pref?"PREFERENCE":hard?"HARD_CONSTRAINT":"STRONG_REQUIREMENT",reason=pref?"SOFT_PREFERENCE_MARKER":hard?"EXPLICIT_HARD_MARKER":"DEFAULT_SEMANTIC_REQUIREMENT",explicitness=c.normalization_status==="PARTIAL"?"COMPOSITIONALLY_DERIVED":c.concept_type==="ACTION"?"COMPOSITIONALLY_DERIVED":"EXPLICIT_ALIAS";all.push(req(c.concept_type,c.canonical_code,classification,reason,{...c,source_field:"semantic.positive_concepts"},plan,explicitness))}
 for(const c of plan.semantic.negative_concepts??[]){const soft=negativePreference(q,c),classification:RequirementClass=soft?"NEGATIVE_PREFERENCE":"HARD_EXCLUSION";all.push(req(c.concept_type,c.canonical_code,classification,soft?"NEGATIVE_PREFERENCE_MARKER":"EXPLICIT_NEGATION",{...c,source_field:"semantic.negative_concepts"},plan,c.normalization_status==="PARTIAL"?"COMPOSITIONALLY_DERIVED":"EXPLICIT_ALIAS"))}
 for(const c of plan.semantic.unresolved_concepts??[])all.push(req("UNRESOLVED",c.raw_text,"UNRESOLVED","UNRESOLVED_SEMANTIC",{...c,source_field:"semantic.unresolved_concepts"},plan,"UNKNOWN"));
 const ocrIntent=/\b(?:text|words?|written|screen (?:says|reads)|[A-Za-z0-9-]+\s+(?:is\s+)?(?:visible|displayed|appears on screen)|M-CURE|iGraft)\b/i.test(q),transcriptIntent=/\b(?:says?|mentions?|speaks? about|talks? about|audio says)\b/i.test(q);for(const modality of plan.textual.modalities??[])if(modality!=="VISUAL"&&(modality!=="OCR"||ocrIntent)&&(modality!=="TRANSCRIPT"||transcriptIntent)){const hard=/\bmust|required|has to\b/i.test(q),pref=/\bprefer|preferably|ideally|if possible\b/i.test(q);all.push(req("SOURCE_MODALITY",modality,hard?"HARD_CONSTRAINT":pref?"PREFERENCE":"STRONG_REQUIREMENT",hard?"EXPLICIT_HARD_MARKER":pref?"SOFT_PREFERENCE_MARKER":"DEFAULT_SEMANTIC_REQUIREMENT",{raw_text:modality,source_field:"textual.modalities"},plan))}for(const[k,field]of[["ocr","OCR_LITERAL"],["transcript","TRANSCRIPT_LITERAL"]]as const)for(const term of plan.textual[k]?.required_terms??[]){if(k==="ocr"&&!ocrIntent||k==="transcript"&&!transcriptIntent)continue;const hard=/\bmust|required|has to\b/i.test(q),pref=/\bprefer|preferably|ideally|if possible\b/i.test(q);all.push(req(field,term,hard?"HARD_CONSTRAINT":pref?"PREFERENCE":"STRONG_REQUIREMENT",hard?"EXPLICIT_HARD_MARKER":pref?"SOFT_PREFERENCE_MARKER":"DEFAULT_SEMANTIC_REQUIREMENT",{raw_text:term,source_field:`textual.${k}.required_terms`},plan,"EXPLICIT_LITERAL"))}
 for(const c of plan.parser_metadata.conflicts??[])all.push(req("PARSER_CONFLICT",c,"CONFLICT","PARSER_CONFLICT",{raw_text:null,source_field:"parser_metadata.conflicts"},plan));for(const m of q.matchAll(/\bfor\s+((?:the\s+)?(?:archive|library|catalogue|collection|media|clinical|internal|quality)\s+(?:review|team|curation|assessment|selection)|social media|marketing)\b/gi))all.push(req("USAGE_CONTEXT",m[1].toUpperCase().replace(/\s+/g,"_"),"CONTEXT","CONTEXT_ONLY",{raw_text:m[0],start_char:m.index,end_char:m.index!+m[0].length,source_field:"original_query"},plan));
 const buckets:Record<string,Requirement[]>={response_controls:[],hard_constraints:[],hard_exclusions:[],strong_requirements:[],preferences:[],negative_preferences:[],context:[],unresolved:[],conflicts:[]},map:Record<RequirementClass,string>={RESPONSE_CONTROL:"response_controls",HARD_CONSTRAINT:"hard_constraints",HARD_EXCLUSION:"hard_exclusions",STRONG_REQUIREMENT:"strong_requirements",PREFERENCE:"preferences",NEGATIVE_PREFERENCE:"negative_preferences",CONTEXT:"context",UNRESOLVED:"unresolved",CONFLICT:"conflicts"};for(const r of all)buckets[map[r.classification]].push(r);const core={requirement_schema_version:REQUIREMENT_SCHEMA_VERSION,query_fingerprint:plan.parser_metadata.query_fingerprint,parser_version:plan.parser_metadata.query_parser_version,requirement_classifier_version:REQUIREMENT_CLASSIFIER_VERSION,requirement_policy_version:REQUIREMENT_POLICY_VERSION,requirement_policy_fingerprint:REQUIREMENT_POLICY_FINGERPRINT,...buckets,classification_summary:Object.fromEntries(Object.entries(buckets).map(([k,v])=>[k,v.length]))},classifier_fingerprint=createHash("sha256").update(canonical(core)).digest("hex");return freeze({...core,classifier_fingerprint,validation:{status:"VALID",errors:[]}})}
