import {createHash} from "node:crypto";
export const SEARCH_DOCUMENT_VERSION="kdi_search_document_v1",BUILDER_VERSION="kdi_search_document_builder_v1",CONFIGURATION_VERSION="kdi_search_document_config_v1",SEMANTIC_SPEC_VERSION="semantic_index_v1",ONTOLOGY_VERSION="KDI_SEMANTIC_V2";
export const BUILDER_CONFIGURATION=Object.freeze({canonicalSource:"effective_semantic_assertions",allowLegacyFallback:false,includeStates:["OBSERVED","FALSE"],positiveState:"OBSERVED",negativeState:"FALSE",omitStates:["UNKNOWN","NOT_APPLICABLE"],transcriptStatuses:["ACCEPTED_FOR_SEARCH"],ocrStatuses:["ACCEPTED_FOR_SEARCH"],excludeTechnicalEvents:true,excludeImageScenes:true});
export function canonicalJson(value:unknown):string{if(value===null||typeof value!=="object")return JSON.stringify(value);if(Array.isArray(value))return`[${value.map(canonicalJson).join(",")}]`;return`{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${JSON.stringify(k)}:${canonicalJson(v)}`).join(",")}}`}
export const sha256=(value:unknown)=>createHash("sha256").update(typeof value==="string"?value:canonicalJson(value)).digest("hex");export const CONFIGURATION_FINGERPRINT=sha256(BUILDER_CONFIGURATION);
export type SemanticAssertion={assertion_id?:string;asset_id:string;scene_id?:string|null;event_id?:string|null;layer_id?:string;predicate:string;canonical_concept_code?:string|null;semantic_state:"OBSERVED"|"FALSE"|"UNKNOWN"|"NOT_APPLICABLE";confidence?:number|null;search_critical?:boolean;resolution_source?:string;origin?:string;evidence_ids?:string[]};
export type BuildInput={asset_id:string;filename:string;mime_type:string;source_fingerprint:string;scenes:Array<{id:string;scene_index:number;start_seconds:number;end_seconds:number;scene_type?:string;semantic_state?:string}>;events:Array<{id:string;scene_id?:string|null;start_time:number;end_time:number;event_type:string;technical_only:boolean;semantic_state:string}>;assertions:SemanticAssertion[];narratives?:any[];transcripts?:any[];ocr?:any[]};
const typeMap:Record<string,string>={PEOPLE_ROLES:"ROLE",ANATOMY:"ANATOMY",TREATMENT_PROCEDURE:"TREATMENT",ACTIONS_EVENTS:"ACTION",RELATIONSHIPS:"RELATIONSHIP",CLINICAL_VISUAL_OBSERVATIONS:"CLINICAL_OBSERVATION",ENVIRONMENT:"ENVIRONMENT",MARKETING_CONTENT_USAGE:"CONTENT_TYPE",OCR_VISIBLE_TEXT:"OCR",SPEECH_TRANSCRIPT_AUDIO:"SPOKEN_CONCEPT"};
export function buildDocuments(input:BuildInput){const mediaType=input.mime_type.startsWith("video/")?"VIDEO":"IMAGE",supported=input.assertions.filter(a=>a.canonical_concept_code&&(a.semantic_state==="OBSERVED"||a.semantic_state==="FALSE"));const concepts=supported.map(a=>({concept_type:typeMap[a.layer_id??""]??"SEMANTIC_CONCEPT",canonical_code:a.canonical_concept_code!,display_text:a.canonical_concept_code!.replaceAll("_"," ").toLowerCase(),semantic_state:a.semantic_state,confidence:a.confidence??null,search_critical:Boolean(a.search_critical),assertion_id:a.assertion_id??null,evidence_ids:a.evidence_ids??[],resolution_source:a.resolution_source??"UNVERIFIED_AI",origin:a.origin??"AI_MODEL"}));
 const scoped=(scene?:string,event?:string)=>concepts.filter((_,i)=>{const a=supported[i];return(!scene||a.scene_id===scene)&&(!event||a.event_id===event)});
 const make=(document_type:"ASSET"|"SCENE"|"EVENT",scopeConcepts:typeof concepts,extra:Record<string,unknown>)=>{const positive=scopeConcepts.filter(c=>c.semantic_state==="OBSERVED"),negative=scopeConcepts.filter(c=>c.semantic_state==="FALSE"),scene=extra.scene_id as string|undefined,event=extra.event_id as string|undefined;const narratives=(input.narratives??[]).filter(n=>(document_type==="ASSET"?n.narrative_type==="ASSET_NARRATIVE":document_type==="SCENE"?n.scene_id===scene&&n.narrative_type==="SCENE_NARRATIVE":n.event_id===event&&n.narrative_type==="EVENT_NARRATIVE")&&n.search_status==="ACCEPTED_FOR_SEARCH"),transcripts=(input.transcripts??[]).filter(t=>t.search_status==="ACCEPTED_FOR_SEARCH"&&(!scene||t.scene_id===scene)&&(!event||t.event_id===event)),ocr=(input.ocr??[]).filter(o=>o.search_status==="ACCEPTED_FOR_SEARCH"&&(!scene||o.scene_id===scene)&&(!event||o.event_id===event));const search_text=[document_type==="ASSET"?`${mediaType.toLowerCase()} ${input.filename}`:`${mediaType.toLowerCase()} segment from ${input.filename}`,...narratives.map(n=>n.text),...positive.map(c=>c.display_text),...ocr.map(o=>o.normalized_text),...transcripts.map(t=>t.normalized_text)].filter(Boolean).join(". "),codes=(kind:string)=>positive.filter(c=>c.concept_type===kind).map(c=>c.canonical_code),sourceSemanticFingerprint=sha256({asset_id:input.asset_id,source_fingerprint:input.source_fingerprint,assertions:supported.map(a=>({id:a.assertion_id,state:a.semantic_state,code:a.canonical_concept_code,evidence:a.evidence_ids??[]})),narratives:narratives.map(n=>n.input_evidence_fingerprint),transcripts:transcripts.map(t=>t.source_text_fingerprint),ocr:ocr.map(o=>o.source_text_fingerprint),...extra});const body={document_type,asset_id:input.asset_id,filename:input.filename,media_type:mediaType,semantic_summary:narratives[0]?.text??null,roles:codes("ROLE"),people_attributes:[],anatomy:codes("ANATOMY"),treatments:codes("TREATMENT"),actions:codes("ACTION"),relationships:codes("RELATIONSHIP"),clinical_observations:codes("CLINICAL_OBSERVATION"),environments:codes("ENVIRONMENT"),procedure_stages:codes("PROCEDURE_STAGE"),marketing_content_types:codes("CONTENT_TYPE"),accepted_ocr:ocr.map(o=>({text:o.normalized_text,observation_id:o.id,origin:"OCR",review_status:"AI_UNREVIEWED"})),accepted_spoken_concepts:transcripts.map(t=>({text:t.normalized_text,transcript_chunk_id:t.id,origin:"TRANSCRIPT",review_status:"AI_UNREVIEWED"})),positive_concepts:positive,negative_concepts:negative,search_text,source_semantic_version:SEMANTIC_SPEC_VERSION,source_semantic_fingerprint:sourceSemanticFingerprint,source_gold_version:null,review_status:"AI_UNREVIEWED",human_approved:false,gold_standard_version:null,review_required:input.asset_id==="babae120-9372-42ad-b535-02a3276ea2be",under_segmentation_possible:input.asset_id==="babae120-9372-42ad-b535-02a3276ea2be",...extra};return{...body,document_fingerprint:sha256(body)}};
 const asset=make("ASSET",concepts,{}),scenes=mediaType==="VIDEO"?input.scenes.filter(s=>s.end_seconds>s.start_seconds&&s.scene_type!=="STILL_IMAGE").map(s=>make("SCENE",scoped(s.id),{scene_id:s.id,scene_index:s.scene_index,start_time:s.start_seconds,end_time:s.end_seconds,duration:s.end_seconds-s.start_seconds})):[],events=input.events.filter(e=>!e.technical_only&&e.semantic_state==="OBSERVED").map(e=>make("EVENT",scoped(e.scene_id??undefined,e.id),{scene_id:e.scene_id??null,event_id:e.id,start_time:e.start_time,end_time:e.end_time,event_label:e.event_type}));return{asset,scenes,events,concepts}}
export function markDownstreamStale(oldSourceFingerprint:string,newSourceFingerprint:string){return oldSourceFingerprint!==newSourceFingerprint}
