import { createHash } from "node:crypto";
import { KDISemanticDatabaseMaintainer, MAINTAINER_VERSION, type MaintainerDataset, type MaintenanceFinding, type MaintenanceActionType } from "./semantic-database-maintainer";
export const HEALTH_SCANNER_VERSION="kdi_semantic_health_scanner_v1";
export type ScannerMode="READ_ONLY"|"DRY_RUN"|"CONTROLLED_REPAIR";
export type ScanSnapshot={snapshotId:string;scannerVersion:string;startedAt:string;completedAt:string;durationMs:number;health:ReturnType<KDISemanticDatabaseMaintainer["getDatabaseHealth"]>;newFindings:string[];existingFindings:string[];resolvedSincePrevious:string[];reopenedFindings:string[];healthMetricChanges:Record<string,number>};
export type QueueItem={maintenanceJobId:string;findingId:string;assetId?:string;actionType:MaintenanceActionType;priority:string;status:"DRY_RUN"|"QUEUED"|"COMPLETED"|"FAILED";attempt:number;maxAttempts:number;idempotencyKey:string;verificationRequired:true};
export class SemanticMaintenanceQueue { private items=new Map<string,QueueItem>(); queue(input:Omit<QueueItem,"maintenanceJobId"|"status"|"attempt"|"idempotencyKey"|"verificationRequired">,mode:ScannerMode){const allowed=new Set<MaintenanceActionType>(["QUEUE_REINDEX","REBUILD_SEARCH_DOCUMENT","REBUILD_EMBEDDING","REVALIDATE_READINESS","MARK_REPRESENTATION_STALE","RETRY_FAILED_JOB"]);if(!allowed.has(input.actionType))throw Error("UNAPPROVED_MAINTENANCE_ACTION");const key=createHash("sha256").update(JSON.stringify({findingId:input.findingId,assetId:input.assetId,actionType:input.actionType})).digest("hex");const prior=this.items.get(key);if(prior)return prior;const item={...input,maintenanceJobId:`maintenance-job-${key.slice(0,16)}`,status:(mode==="DRY_RUN"?"DRY_RUN":"QUEUED") as QueueItem["status"],attempt:0,idempotencyKey:key,verificationRequired:true as const};if(mode==="CONTROLLED_REPAIR")this.items.set(key,item);return item;} list(){return [...this.items.values()]} verify(jobId:string,passed:boolean){const item=[...this.items.values()].find(x=>x.maintenanceJobId===jobId);if(!item)throw Error("MAINTENANCE_JOB_NOT_FOUND");item.status=passed?"COMPLETED":"FAILED";return item;}}
export class SemanticDatabaseHealthScanner { readonly maintainer:KDISemanticDatabaseMaintainer; readonly queue=new SemanticMaintenanceQueue(); private previous:ScanSnapshot|null=null; constructor(dataset:MaintainerDataset){this.maintainer=new KDISemanticDatabaseMaintainer(dataset,"READ_ONLY");}
  scan():ScanSnapshot{const started=Date.now(),health=this.maintainer.getDatabaseHealth(),findings=health.findings,priorIds=new Set(this.previous?.health.findings.map(x=>x.findingId)??[]),currentIds=new Set(findings.map(x=>x.findingId));const snap={snapshotId:`health-${started}`,scannerVersion:HEALTH_SCANNER_VERSION,startedAt:new Date(started).toISOString(),completedAt:new Date().toISOString(),durationMs:Date.now()-started,health,newFindings:findings.filter(x=>!priorIds.has(x.findingId)).map(x=>x.findingId),existingFindings:findings.filter(x=>priorIds.has(x.findingId)).map(x=>x.findingId),resolvedSincePrevious:[...(this.previous?.health.findings??[])].filter(x=>!currentIds.has(x.findingId)).map(x=>x.findingId),reopenedFindings:[],healthMetricChanges:{pendingAnalysis:health.pendingAnalysis-(this.previous?.health.pendingAnalysis??health.pendingAnalysis),falseSearchReady:health.falseSearchReady-(this.previous?.health.falseSearchReady??health.falseSearchReady)}};this.previous=snap;return snap;}
  handoff(){const s=this.previous??this.scan();return {scannerVersion:HEALTH_SCANNER_VERSION,health:{totalAssets:s.health.totalAssets,completeV1:s.health.completeV1,pendingAnalysis:s.health.pendingAnalysis,unsupported:s.health.unsupported,falseSearchReady:s.health.falseSearchReady,falseComplete:s.health.falseComplete},topFindings:s.health.findings.slice(0,20),activeMaintenanceJobs:this.queue.list().slice(0,20)};}
  resolveFinding(findingId:string,verified:boolean){const finding=this.maintainer.listMaintenanceFindings().find(x=>x.findingId===findingId);if(!finding)throw Error("FINDING_NOT_FOUND");if(!verified) return {...finding,status:"OPEN" as const};return {...finding,status:"RESOLVED" as const,resolvedAt:new Date().toISOString()};}
  reopenFinding(findingId:string){const finding=this.maintainer.listMaintenanceFindings().find(x=>x.findingId===findingId);if(!finding)throw Error("FINDING_NOT_FOUND");return {...finding,status:"REOPENED" as const};}
}
