export const GOLD_IMPLEMENTATION_VERSION="kdi_semantic_gold_answers_v1";
export const GOLD_VERSION="kdi_gold_answers_v1";
export const GOLD_LABELS=["EXACT_RELEVANT","RELEVANT","PARTIAL_RELEVANT","NOT_RELEVANT","EXCLUDED","UNRESOLVED"] as const;
export type GoldLabel=typeof GOLD_LABELS[number];
export type EvidenceRef={source_type:"SEMANTIC_ASSERTION"|"ASSERTION_EVIDENCE"|"SCENE"|"EVENT"|"NARRATIVE"|"TRANSCRIPT"|"OCR"|"GROUNDED_DESCRIPTION";source_id:string};
export type GoldJudgment={asset_id:string;filename:string;label:GoldLabel;ideal_group:number|null;reason:string;evidence:EvidenceRef[]};
export type GoldTurn={turn:number;query:string;resolved_semantic_target:string;inherited_context:string[];added_context:string[];requested_count:number|null;effective_count:number;maximum_valid_relevant:number;judgments:GoldJudgment[];acceptable_asset_ids:string[];expected_referenced_asset_id:string|null;expected_description_source:string|null};
export type EvaluationMode="RETRIEVAL_RELEVANCE"|"PARSER_CONTROL"|"RESULT_COUNT_CONTROL"|"FILTER_CONTROL"|"RESPONSE_STATE"|"CONVERSATION_CONTROL"|"AUTHORIZATION_CONTROL";
export type GoldCase={case_id:string;category:string;review_status:"UNREVIEWED"|"EVIDENCE_VERIFIED"|"APPROVED"|"DISPUTED";evaluation_modes?:EvaluationMode[];scored_for_retrieval_metrics?:boolean;determinacy?:"GOLD_DETERMINATE"|"GOLD_AMBIGUOUS";behavioral_expectations?:Record<string,unknown>;turns:GoldTurn[]};
export type GoldSet={implementation_version:string;gold_version:string;benchmark_version:string;suite_id:string;spec_version:string;spec_fingerprint:string;pilot_manifest_version:string;pilot_manifest:string[];status:"DRAFT"|"CERTIFIED";certification_status?:"EVIDENCE_VERIFIED";lock_status?:"LOCKED";gold_fingerprint?:string;human_review_required?:boolean;immutable:boolean;review_status:string;source_policy:string[];semantic_state_invariants:string[];created_at:string;cases:GoldCase[]};
export function validateGoldSet(g:GoldSet,benchmarkIds:string[]){const errors:string[]=[];if(g.cases.length!==40)errors.push("GOLD_CASE_COUNT");const ids=g.cases.map(x=>x.case_id);if(new Set(ids).size!==ids.length)errors.push("DUPLICATE_CASE");for(const id of benchmarkIds)if(!ids.includes(id))errors.push(`MISSING:${id}`);for(const c of g.cases)for(const t of c.turns)for(const j of t.judgments){if(!GOLD_LABELS.includes(j.label))errors.push(`LABEL:${c.case_id}`);if(["EXACT_RELEVANT","RELEVANT","PARTIAL_RELEVANT"].includes(j.label)&&!j.evidence.length)errors.push(`POSITIVE_WITHOUT_EVIDENCE:${c.case_id}:${j.filename}`)}return errors}
export function assertGoldMutable(g:GoldSet){if(g.immutable||g.status==="CERTIFIED")throw Error("CERTIFIED_GOLD_IMMUTABLE_CREATE_NEW_VERSION")}
export function deleteGold(g:GoldSet){assertGoldMutable(g);return true}
export function createNextGoldVersion(g:GoldSet,next:string){if(next===g.gold_version)throw Error("NEW_GOLD_VERSION_REQUIRED");return{...g,gold_version:next,status:"DRAFT" as const,immutable:false,certification_status:undefined,lock_status:undefined,gold_fingerprint:undefined}}
const stable=(x:any):string=>x===null||typeof x!=="object"?JSON.stringify(x):Array.isArray(x)?`[${x.map(stable).join(",")}]`:`{${Object.keys(x).sort().map(k=>`${JSON.stringify(k)}:${stable(x[k])}`).join(",")}}`;
export function canonicalGold(g:GoldSet){return{gold_version:g.gold_version,benchmark_version:g.benchmark_version,suite_id:g.suite_id,spec_version:g.spec_version,spec_fingerprint:g.spec_fingerprint,pilot_manifest_version:g.pilot_manifest_version,pilot_manifest:g.pilot_manifest,semantic_state_invariants:g.semantic_state_invariants,cases:g.cases.map(c=>({case_id:c.case_id,category:c.category,evaluation_modes:c.evaluation_modes,scored_for_retrieval_metrics:c.scored_for_retrieval_metrics,determinacy:c.determinacy,behavioral_expectations:c.behavioral_expectations,turns:c.turns}))}}
export const goldFingerprint=(g:GoldSet)=>createHash("sha256").update(stable(canonicalGold(g))).digest("hex");
import{createHash}from"node:crypto";
