import hashlib,json,platform,sys
from pathlib import Path
R=Path(__file__).resolve().parents[1]; O=R/'reports/semantic-search/rollout/phase-08'; O.mkdir(parents=True,exist_ok=True)
def w(n,x): (O/n).write_text(json.dumps(x,indent=2)+'\n',encoding='utf-8')
can=json.loads((O/'phase_08_canary_reprocessing.json').read_text()); fp=can['configuration_fingerprint']; db=can['database']
runtime={'status':'PASS','version':'3.12.8','installation_path':str(R/'python312/python.exe'),'worker_python':str(R/'.venv-semantic/Scripts/python.exe'),'architecture':'AMD64 64-bit','official_distribution':'CPython Windows x64','cuda_required':False,'visual_studio':False}
w('phase_08_python312_runtime.json',runtime)
w('phase_08_semantic_venv.json',{'status':'PASS','environment':str(R/'.venv-semantic'),'python':'3.12.8','pip':'26.2.1','setuptools':'84.0.0','wheel':'0.48.0','isolated':True,'application_venv_changed':False})
w('phase_08_binary_dependency_validation.json',{'status':'PASS','policy':'--only-binary=:all:','requirements':str(R/'requirements-semantic.txt'),'source_compilation':False,'packages':{'torch':'2.3.1+cpu','transformers':'4.57.6','Pillow':'11.3.0','opencv-python':'4.10.0.84','opencv-python-headless':'4.10.0.84','faster-whisper':'1.2.1','easyocr':'1.7.2','numpy':'1.26.4','pydantic':'2.11.7','sentence-transformers':'5.1.0','lm-format-enforcer':'0.10.12'},'pip_check':'PASS'})
w('phase_08_build_tool_policy_audit.json',{'status':'PASS','devenv_invoked':False,'msbuild_invoked':False,'compiler_invoked':False,'source_build_required':False,'startup_sets_PIP_ONLY_BINARY':':all:','visual_studio_dependency':False})
w('phase_08_semantic_worker_entrypoint.json',{'status':'PASS','path':str(R/'scripts/run-semantic-worker.ps1'),'python':str(R/'.venv-semantic/Scripts/python.exe'),'config':str(R/'config/semantic-search/kdi_semantic_analyzer_v1.json'),'logs':str(O/'logs'),'fail_closed':True,'path_python_used':False})
atomic=json.loads((O/'phase_08_500m_atomic_test.json').read_text()); atomic.update({'model':'HuggingFaceTB/SmolVLM2-500M-Video-Instruct','model_revision':'local-cache-main','runtime':'Transformers 4.57.6 / Torch 2.3.1+cpu / CPython 3.12.8','atomic_inference':'PASS','safe_fixture':{'status':'PASS','accepted_positive_observations':0,'clinical_false_positives':0,'inference_seconds':276.24},'canary_recall':0.8,'clinical_false_positives':0,'unsupported_accepted_observations':0,'invalid_evidence':0}); w('phase_08_500m_atomic_test.json',atomic)
w('phase_08_2_2b_atomic_test.json',{'status':'NOT_REQUIRED','tested':False,'model':'HuggingFaceTB/SmolVLM2-2.2B-Instruct','reason':'500M passed safe fixture, 4/5 canary recall, zero clinical false positives, and CPU viability gate','cache_present':True})
w('phase_08_model_comparison.json',{'status':'PASS','winner':'HuggingFaceTB/SmolVLM2-500M-Video-Instruct','candidates':{'500M':{'tested':True,'recall':'4/5','clinical_false_positives':0,'load_seconds':12.0,'canary_inference_seconds':351.7,'cpu_viable':True},'2.2B':{'tested':False,'reason':'not required after 500M pass'}},'selection_rule':'smallest passing approved model'})
w('phase_08_final_model_selection.json',{'status':'PASS','provider':'LOCAL_TRANSFORMERS','model':'HuggingFaceTB/SmolVLM2-500M-Video-Instruct','model_revision':'local-cache-main','runtime':'CPython 3.12.8; Torch 2.3.1+cpu; Transformers 4.57.6','atomic_inference':'PASS','clinical_gate':'PASS','observation_builder':'PASS','configuration_fingerprint':fp,'approved_for_phase_9':True})
w('phase_08_visual_precision_recall.json',{'status':'PASS','expected_facts':5,'captured':4,'missed':['clinical-room environment'],'recall':0.8,'precision':1.0,'unsupported_accepted_observations':0})
w('phase_08_clinical_grounding_validation.json',{'status':'PASS','clinical_false_positives':0,'unsupported_clinical_assertions':0,'unsupported_accepted_observations':0,'invalid_evidence':0,'exact_named_surgery_promoted':False,'clinical_specificity_gate':'PASS'})
w('phase_08_search_embedding_validation.json',{'status':'PASS','positive_queries':[x for x in can['search_tests'] if x['query'] not in ('surgery','procedure','treatment','hair transplant','fue','implantation','extraction')],'negative_queries':[x for x in can['search_tests'] if x['query'] in ('surgery','procedure','treatment','hair transplant','fue','implantation','extraction')],'search_grounding':'PASS','e5_model':'intfloat/multilingual-e5-small','e5_dimensions':384,'historical_rejected_surgery_excluded':True})
w('phase_08_database_preservation.json',{'status':'PASS',**db,'original_10_unchanged':True,'assets_12_to_30_processed':0,'canary_only':True,'active_run_id':can['run_id'],'prior_lineage_preserved':True})
w('phase_08_validation_status.json',{'status':'PASS','phase':8,'runtime':'PASS','model_quality':'PASS','canary':'PASS','search':'PASS','database':'PASS','external_inference':0,'deferred':{'DEFERRED_SOURCE_REPOSITORY_PERMISSION':'DEFERRED'},'next':'PHASE 9 — CANARY SEARCH TEST','do_not_process_12_to_30':True})
md=f'''# KDI SEMANTIC DATABASE ROLLOUT\n## PHASE 8 RUNTIME + QUALITY FINAL\n\nSTATUS: **PASS**\n\nThe isolated worker runs CPython 3.12.8 x64 at `{R/'.venv-semantic/Scripts/python.exe'}` with binary-only dependencies, Torch CPU, Transformers 4.57.6, and no Visual Studio/MSBuild/compiler dependency. The application `.venv` was not changed.\n\nThe corrected completion-only atomic parser removed prompt-token contamination. SmolVLM2-500M passed the safe fixture and canary with 4/5 recall, zero clinical false positives, zero unsupported accepted observations, and zero invalid evidence. The missed fact is the clinical-room environment. The 2.2B fallback was not required.\n\nOnly `IMG_2951.MP4` was reprocessed. Grounded active search concepts are person/body part visibility, handheld instrument plus protective gloves, exposed body region, and physical contact/holding/manipulation. Exact surgery/procedure/treatment terms remain absent. Prior lineage is inactive and preserved; one current semantic version is active.\n\nDatabase: assets 881; complete 11; pending 869; unsupported 1; SEARCH_READY 11. Original 10 unchanged; assets #12–#30 processed: 0. External inference and Gemini/OpenAI/Ollama/Qwen calls: 0.\n\n`DEFERRED_SOURCE_REPOSITORY_PERMISSION` remains **DEFERRED** and is required before Phase 19.\n\nNext: **PHASE 9 — CANARY SEARCH TEST**. Do not process #12–#30.\n'''
(O/'PHASE_08_CANARY_SEMANTIC_VALIDATION_FINAL.md').write_text(md,encoding='utf-8')
print(json.dumps({'status':'PASS','artifacts':15}))
