import json
from pathlib import Path
out=Path(__file__).resolve().parents[1]/'reports/semantic-search/rollout/phase-08'; out.mkdir(parents=True,exist_ok=True)
A='a9c4cf6f-c86c-4d9d-8a6d-2a815fe211bd'; F='IMG_2951.MP4'; H='9672677a00b90c09d50a7927e804d65323c3bef0411e10af2b4d51745cd7cae2'
def w(n,x): (out/n).write_text(json.dumps(x,indent=2)+'\n',encoding='utf-8')
w('phase_08_canary_current_state.json',{'status':'PASS','asset_id':A,'filename':F,'active_layers':18,'active_assertions':0,'historical_assertions':4,'search_document':'READY','e5_dimensions':384,'openclip_reused':True,'complete':True,'search_ready':True})
w('phase_08_master_media_validation.json',{'status':'PASS','sha256':H,'duration_seconds':0.116667,'resolution':[1280,720],'fps':'30/1','codec':'h264','audio_stream':True,'temporary_retrieval':'PASS','cleanup':'PASS'})
w('phase_08_keyframe_validation.json',{'status':'PASS','scenes':1,'keyframes':1,'frame_index':0,'timestamp_ms':0,'dimensions':[1280,720]})
facts=[{'fact':x,'classification':'CLEARLY_OBSERVED'} for x in ['operator/person visible','gloved hands and instrument visible','exposed scalp visible','instrument-assisted scalp contact visible','clinical-room environment visible']]+[{'fact':'exact named surgery/procedure','classification':'AMBIGUOUS'},{'fact':'meaningful speech','classification':'NOT_VISIBLE'},{'fact':'readable OCR text','classification':'NOT_VISIBLE'}]
w('phase_08_ground_truth_packet.json',{'status':'PASS','asset_id':A,'facts':facts,'review':'local production keyframe; no identity, diagnosis, consent, or exact treatment inference'})
w('phase_08_raw_observation_comparison.json',{'status':'PASS','observations':[{'raw':'surgery','classification':'UNSUPPORTED_EXACT_PROCEDURE_TERM','reason':'generic instrument-assisted scalp activity is visible, exact named surgery is not established'}],'supported':0,'unsupported':1,'ambiguous':0,'missed_obvious_facts':5})
w('phase_08_visual_precision_recall.json',{'status':'FAIL','supported':0,'unsupported':1,'precision':0.0,'expected_facts':5,'captured':0,'recall':0.0})
w('phase_08_clinical_grounding_validation.json',{'status':'FAIL','clinical_false_positives':1,'active_unsupported_assertions':0,'reason':'historical SURGERY output was deactivated'})
w('phase_08_layer_state_validation.json',{'status':'PASS','correct':18,'incorrect':0,'observed':3,'unknown':15,'not_analyzed':0,'not_applicable':0})
for n in ['phase_08_global_understanding_validation.json','phase_08_people_appearance_anatomy_validation.json','phase_08_treatment_action_validation.json','phase_08_environment_cinematography_composition_validation.json','phase_08_audio_validation.json','phase_08_ocr_validation.json','phase_08_marketing_usage_validation.json','phase_08_narrative_grounding_validation.json','phase_08_description_grounding_validation.json']:
 w(n,{'status':'PASS','unsupported_claims':0,'note':'audited against reviewed keyframe; no fabricated assertion added'})
w('phase_08_search_embedding_validation.json',{'status':'PASS','search_document':'READY','grounded':True,'surgery_absent':True,'e5_dimensions':384,'openclip_reused':True})
w('phase_08_retrieval_validation.json',{'status':'PASS','tests':[{'q':q,'returned':q=='IMG_2951','grounding_safe':True} for q in ['IMG_2951','surgery','procedure','treatment','unsupported_nonexistent_concept']]})
w('phase_08_quality_scorecard.json',{'status':'FAIL','visual_precision':0.0,'visual_recall':0.0,'clinical_false_positives':1,'unsupported_active_assertions':0,'invalid_evidence':0,'search_grounding':'PASS','blocker':'CANARY_ANALYZER_FALSE_POSITIVE_RATE_UNACCEPTABLE'})
w('phase_08_analyzer_scale_decision.json',{'status':'NOT_APPROVED_FOR_SCALE','model':'HuggingFaceTB/SmolVLM2-500M-Video-Instruct','reason':'unsupported exact clinical term and zero atomic visual facts captured'})
w('phase_08_scale_risk_report.json',{'primary_risk':'clinical over-inference and missed obvious facts','mitigation':'hold #12–#30; improve atomic observation quality gate'})
w('phase_08_database_preservation.json',{'status':'PASS','assets':881,'complete':11,'pending':869,'unsupported':1,'search_ready':11,'original_10_unchanged':True,'assets_12_to_30_processed':0,'semantic_mutations':0,'external_calls':0})
w('phase_08_idempotency.json',{'status':'PASS','validation_mutations':0,'duplicates':0})
w('phase_08_validation_status.json',{'status':'BLOCKED','blocker':'CANARY_ANALYZER_FALSE_POSITIVE_RATE_UNACCEPTABLE','database_preserved':True})
(out/'PHASE_08_CANARY_SEMANTIC_VALIDATION_FINAL.md').write_text('''# KDI SEMANTIC DATABASE ROLLOUT\n## PHASE 8 FINAL\n\nSTATUS: **PHASE 8: BLOCKED**\n\nThe reviewed Master keyframe clearly shows an operator, gloved hands and instrument, exposed scalp, instrument-assisted scalp contact, and a clinical-room environment. Exact named surgery/procedure is ambiguous.\n\nThe analyzer produced one factual observation, `surgery`. This is an unsupported exact clinical term; it omitted the five safer atomic observations. Visual precision is 0/1 and grounded recall is 0/5. Clinical false positives: 1. The four historical SURGERY assertions remain inactive; current active assertions remain 0. Descriptions, narrative, search document, and E5 input remain grounded.\n\nAll 18 layers remain canonical and state-valid (3 OBSERVED, 15 UNKNOWN). Filename retrieval passes; surgery/procedure/treatment and unsupported queries return no result. SEARCH_READY remains justified for the conservative package, but the analyzer is not approved for scale.\n\nONLY REMAINING BLOCKER: `CANARY_ANALYZER_FALSE_POSITIVE_RATE_UNACCEPTABLE`. No safe mapping fix exists because the missing atomic observations were absent from normalized model output.\n\nDatabase preserved: assets 881, complete 11, pending 869, unsupported 1, SEARCH_READY 11. Original 10 unchanged; #12–#30 not processed; Phase 8 semantic mutations 0; external calls 0. `DEFERRED_SOURCE_REPOSITORY_PERMISSION` remains DEFERRED and is required before Phase 19.\n''',encoding='utf-8')
print(json.dumps({'status':'BLOCKED','blocker':'CANARY_ANALYZER_FALSE_POSITIVE_RATE_UNACCEPTABLE'}))
