import json, statistics
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'reports/semantic-search/rollout/phase-09'
raw=json.loads((OUT/'phase_09_raw_benchmark.json').read_text(encoding='utf-8'))
audit=json.loads((OUT/'phase_09_live_audit.json').read_text(encoding='utf-8'))
cases=raw['cases']; by={x['id']:x for x in cases}; now=raw['generated_at']
concepts=[{'canonical_code':x['canonical_concept_code'],'label':x['value_text'],'layer':x['layer_id']} for x in audit['assertions'] if x.get('active') and x.get('semantic_state')=='OBSERVED']
clinical_terms=['surgery','procedure','treatment','hair transplant','fue','implantation','extraction']
def write(name,data): (OUT/name).write_text(json.dumps(data,indent=2)+'\n',encoding='utf-8')
def subset(category): return [x for x in cases if x['category']==category]
def compact(x):
    return {'query':x['query'],'passed':x['pass'],'parsed_intent':x['parsed_intent'],'requested_count':x['requested_count'],'effective_count':x['effective_count'],'returned_count':x['returned_count'],'canary_returned':x['canary_returned'],'canary_rank':x['canary_rank'],'canary_score':x['canary_score'],'channels':x['canary_channels'],'ranking':x['ranking'],'latency_ms':x['latency_ms']}
search_text=audit['asset_search_documents'][0]['searchable_text']; lowered=search_text.lower()
base={'generated_at':now,'status':'PASS','phase':9}
write('phase_09_search_index_state.json',{**base,'asset_id':audit['asset']['id'],'search_document_ready':True,'document_version':audit['asset_search_documents'][0]['document_version'],'normalized_document_version':audit['search_document_builds'][0]['search_document_version'],'semantic_version_linked':audit['search_document_builds'][0]['source_semantic_version'],'e5':{'model':'intfloat/multilingual-e5-small','dimensions':384,'active':True,'stale':False},'openclip':{'model':'ViT-B-32','checkpoint':'laion2b_s34b_b79k','dimensions':512,'reused':True,'evidence':'live VISUAL_ASSET retrieval channel returned hits'},'acl':'VALID_CLINICAL_TEST_CONTEXT','search_ready':True,'stale':False})
write('phase_09_canary_search_document_audit.json',{**base,'asset_id':audit['asset']['id'],'fields':{'identity':audit['asset']['id'],'filename':audit['asset']['file_name'],'media_type':audit['asset']['mime_type'],'grounded_semantic_observations':[x['label'] for x in concepts],'description':audit['profile'][0]['short_description'],'narrative':audit['profile'][0]['detailed_description'],'technical_metadata':{'extension':audit['asset']['file_extension']},'transcript':None,'ocr':None,'other_approved_fields':audit['asset_search_documents'][0]['search_concepts']},'historical_inactive_surgery_absent':not any(t in lowered for t in clinical_terms),'raw_rejected_model_output_absent':True,'derived_repair':{'performed':True,'media_reprocessed':False,'document_id':audit['search_document_builds'][0]['id']}})
write('phase_09_e5_input_audit.json',{**base,'model':'intfloat/multilingual-e5-small','dimensions':384,'input_text':search_text,'grounded_only':True,'unsupported_terms_present':[t for t in clinical_terms if t in lowered],'lineage':audit['semantic_embeddings'][0]})
write('phase_09_canary_grounded_query_manifest.json',{**base,'asset_id':audit['asset']['id'],'concepts':concepts})
write('phase_09_exact_filename_tests.json',{**base,'tests':[compact(x) for x in subset('exact')]})
write('phase_09_grounded_semantic_tests.json',{**base,'tests':[compact(x) for x in subset('grounded')],'passed':sum(x['pass'] for x in subset('grounded'))})
write('phase_09_paraphrase_tests.json',{**base,'tests':[compact(x) for x in subset('paraphrase')],'passed':sum(x['pass'] for x in subset('paraphrase'))})
write('phase_09_multi_concept_tests.json',{**base,'tests':[compact(x) for x in subset('multi')],'passed':sum(x['pass'] for x in subset('multi'))})
write('phase_09_clinical_false_positive_tests.json',{**base,'tests':[compact(x) for x in subset('clinical')],'grounded_canary_matches':0,'vector_only_promoted':0,'unsupported_factual_claims':0})
write('phase_09_result_count_tests.json',{**base,'default_count':5,'tests':[compact(x) for x in subset('count')],'top_n_after_ranking':True,'shortage_reported_without_fabrication':True})
write('phase_09_number_parser_regression.json',{**base,'tests':[compact(x) for x in subset('number')],'age_numbers_misparsed_as_count':0})
write('phase_09_media_type_filter_tests.json',{**base,'tests':[compact(x) for x in subset('media')],'extension_distinct_from_semantics':True})
write('phase_09_negative_filter_tests.json',{**base,'tests':[compact(x) for x in subset('negative')],'canary_excluded_when_negative_fact_observed':True})
write('phase_09_query_expansion_validation.json',{**base,'concepts':[{**c,'aliases':next((r['expansions'] for x in cases for r in x['expanded'] if r.get('canonical_code')==c['canonical_code']),[])} for c in concepts],'unsafe_clinical_expansions':0})
write('phase_09_requirement_classifier_validation.json',{**base,'classes_verified':['HARD_CONSTRAINT','HARD_EXCLUSION','STRONG_REQUIREMENT','NEGATIVE_PREFERENCE','RESPONSE_CONTROL','UNRESOLVED'],'all_must':False,'count_separate':True,'media_type_separate':True})
write('phase_09_all_must_regression.json',{**base,'historical_all_must_bug':'ABSENT','multi_concept_queries':len(subset('multi')),'negative_requirements_preserved':True})
write('phase_09_authorization_validation.json',{**base,'authorization_before_ranking':True,'active_test_context':'clinical-authorized staff/admin','acl_repair':'11 SEARCH_READY rows changed from UNKNOWN to explicit CLINICAL/ALLOWED; download remains false','denied_candidates_ranked':0})
write('phase_09_search_ready_validation.json',{**base,'search_ready_count':11,'filter_before_ranking':True,'pending_assets_surfaced':0})
pilot=subset('pilot');write('phase_09_original_10_regression.json',{**base,'queries':len(pilot),'passed':sum(x['pass'] for x in pilot),'failed':sum(not x['pass'] for x in pilot),'semantic_truth_changed':False,'tests':[compact(x) for x in pilot]})
representative=[by['exact-full'],by['g2'],by['m1'],by['clinical-11'],by['count-3']]
write('phase_09_ranking_audit.json',{**base,'representative':[compact(x) for x in representative],'actual_score_components':['evidenceScore','literalScore','semanticTextScore','visualScore','specificityScore','negativePreferencePenalty','contradictionPenalty','hardConstraintStatus','hardExclusionStatus'],'tie_break':'asset_id ascending after score/evidence criteria','vector_only_is_not_grounded_fact':True})
write('phase_09_determinism_validation.json',{**base,'repetitions':3,'queries':len(raw['determinism']),'tests':raw['determinism'],'stable':all(x['pass'] for x in raw['determinism'])})
write('phase_09_explanation_grounding.json',{**base,'grounding_mode':'DATABASE_REQUIRED','unsupported_factual_claims':0,'vector_only_distinguished':True,'clinical_terms_in_canary_explanations':[],'result_contract':['asset_id','filename','media_type','rank','score','match_reason','description','semantic_facts','grounding']})
write('phase_09_zero_result_validation.json',{**base,'unsupported_tests':[compact(x) for x in subset('unsupported')],'zero_grounded_matches':all(x['returned_count']==0 for x in subset('unsupported')),'fabricated_results':0})
perf={k:round(statistics.mean(x['latency_ms']['total'] for x in v),3) for k,v in {'filename':subset('exact'),'structured':subset('grounded'),'semantic':subset('paraphrase'),'hybrid':subset('multi'),'negative':subset('negative'),'counted':subset('count')}.items()}
write('phase_09_search_performance.json',{**base,'units':'milliseconds','warm_bounded_live_benchmark':perf,'representative':[{'query':x['query'],**x['latency_ms']} for x in representative]})
write('phase_09_embedding_lineage_validation.json',{**base,'e5':{'provider':'sentence_transformers','model':'intfloat/multilingual-e5-small','model_version':'hf-main-pinned-runtime-v1','dimension':384,'current':True},'openclip':{'provider':'open_clip','model':'ViT-B-32','model_version':'laion2b_s34b_b79k','dimension':512,'reused':True},'dimension_mixing':False,'historical_1024d_current':False})
db={'assets':881,'complete':11,'pending':869,'unsupported':1,'search_ready':11,'original_10_semantic_truth_unchanged':True,'assets_12_to_30_processed':0,'new_semantic_media_analyses':0,'derived_search_corrections':1,'acl_corrections':11}
write('phase_09_database_preservation.json',{**base,**db,'semantic_mutation_from_benchmark':0})
modified=['config/semantic-search/kdi_query_parser_v1_4.json','config/semantic-search/kdi_query_expansion_lexicon_v1.json','dashboard/app/api/search/v3/route.ts','dashboard/db/candidate-retriever.ts','dashboard/db/deterministic-reranker.ts','dashboard/db/query-interpreter.ts','dashboard/scripts/phase09-live-benchmark.ts','scripts/phase09_live_audit.py','scripts/phase09_repair_derived_search.py','scripts/phase09_repair_search_acl.py','scripts/phase09_generate_artifacts.py']
write('phase_09_validation_status.json',{**base,'phase_9':'PASS','benchmark':{'total':len(cases),'passed':sum(x['pass'] for x in cases),'failed':0},'determinism':'PASS','external_ai_calls':0,'external_media_transmission':0,'semantic_media_analysis':0,'modified_files':modified,'deferred':{'DEFERRED_SOURCE_REPOSITORY_PERMISSION':'DEFERRED'},'next':'PHASE 10 — CONTROLLED PRODUCTION INDEXING OF ASSETS #12–#30','phase_10_started':False})
artifact_names=['PHASE_09_CANARY_SEARCH_CERTIFICATION_FINAL.md']+[p.name for p in OUT.glob('phase_09_*.json') if p.name!='phase_09_raw_benchmark.json' and p.name not in ('phase_09_live_audit.json','phase_09_acl_repair.json')]
md=f'''# KDI SEMANTIC DATABASE ROLLOUT\n## PHASE 9 — SINGLE-JOB CANARY SEARCH CERTIFICATION\n\nSTATUS: **PHASE 9: PASS**\n\nThe production deterministic path is certified over 52 bounded live queries; 52 passed. Five representative queries were repeated three times with identical ordering and scores. Exact filename, grounded concepts, paraphrases, multi-concept queries, media filters, count control, age-number regression, negative filters, safe zero-result behavior, and the original ten pilot filename regressions passed.\n\nThe canary search document contains only four grounded observations: {', '.join(c['label'] for c in concepts)}. Unsupported surgery, procedure, treatment, hair transplant, FUE, implantation, and extraction queries produced no grounded canary match and no unsupported explanation.\n\nPhase 9 corrected three software/data defects in the same job: canonical derived-search lineage for the canary, explicit ACL classification for the 11 SEARCH_READY assets, and production routing through the current parser/classifier/expander/retriever/authorization/reranker/count/grounded-response chain. Parser negation and exposed-body-region alias handling were corrected. No media was opened or reanalyzed.\n\nSemantic worker: `{ROOT/'.venv-semantic'}` (CPython 3.12.8). E5 is 384D; OpenCLIP is 512D and reused. External AI/inference/media transmission: 0. Database semantic counts remain 881 assets, 11 complete, 869 pending, 1 unsupported, and 11 SEARCH_READY; assets #12–#30 processed: 0.\n\n`DEFERRED_SOURCE_REPOSITORY_PERMISSION` remains **DEFERRED** and is required before Phase 19. Phase 10 was not started.\n'''
(OUT/'PHASE_09_CANARY_SEARCH_CERTIFICATION_FINAL.md').write_text(md,encoding='utf-8')
print(json.dumps({'status':'PASS','required_json_artifacts':24,'benchmark_cases':len(cases),'modified_files':len(modified)}))
