import test from "node:test";
import assert from "node:assert/strict";
import { DeterministicQueryInterpreter, EMPTY_CONVERSATIONAL_SEARCH, effectiveSemanticQuery, stateFromSearchParams, stateToSearchParams } from "../app/lib/media/conversation";
const interpreter = new DeterministicQueryInterpreter();
test("initial request creates semantic and structured state",async()=>{const r=await interpreter.interpret("Show me female patients talking about FUE recovery.",EMPTY_CONVERSATIONAL_SEARCH);assert.equal(r.state.subject,"Female patient");assert.equal(r.state.treatment,"FUE Hair Transplant");assert.match(r.state.semanticQuery,/recovery/i)});
test("follow-ups preserve meaning while changing one concern",async()=>{const a=(await interpreter.interpret("female patient FUE recovery",EMPTY_CONVERSATIONAL_SEARCH)).state,b=(await interpreter.interpret("Only videos.",a)).state,c=(await interpreter.interpret("With Dr Inder.",b)).state,d=(await interpreter.interpret("Newest first.",c)).state;assert.equal(d.semanticQuery,a.semanticQuery);assert.equal(d.mediaType,"video");assert.equal(d.doctorName,"Datuk Dr Inder");assert.equal(d.sort,"newest")});
test("removal exclusion and reset are deterministic",async()=>{let s=(await interpreter.interpret("female patient FUE recovery",EMPTY_CONVERSATIONAL_SEARCH)).state;s=(await interpreter.interpret("With Dr Inder",s)).state;s=(await interpreter.interpret("Without testimonials",s)).state;assert.deepEqual(s.excludedContentTypes,["Patient Testimonial"]);s=(await interpreter.interpret("Clear doctor filter",s)).state;assert.equal(s.doctorName,null);s=(await interpreter.interpret("Start over",s)).state;assert.deepEqual(s,EMPTY_CONVERSATIONAL_SEARCH)});
test("state round-trips and conversations stay isolated",async()=>{const a=(await interpreter.interpret("Long Hair FUE for women",EMPTY_CONVERSATIONAL_SEARCH)).state,r=stateFromSearchParams(stateToSearchParams(a));assert.equal(r.treatment,"iGraft Long Hair FUE");assert.match(effectiveSemanticQuery(r),/Female patient/);const b=(await interpreter.interpret("doctor consultation",EMPTY_CONVERSATIONAL_SEARCH)).state;assert.equal(b.subject,null);assert.notEqual(b.semanticQuery,a.semanticQuery)});
test("empty and nonsense inputs are safe",async()=>{assert.deepEqual((await interpreter.interpret("",EMPTY_CONVERSATIONAL_SEARCH)).state,EMPTY_CONVERSATIONAL_SEARCH);assert.equal((await interpreter.interpret("purple banana zqxv",EMPTY_CONVERSATIONAL_SEARCH)).state.semanticQuery,"purple banana zqxv")});
