import test from "node:test";import assert from "node:assert/strict";
import {completion,duplicateTrace,fileKind,isException,isUuid,maskDestination,maskFilename,parseFileParams,parseParams,safePath,shortId,SORT_FIELDS} from "../app/lib";
const summary={sourceFiles:886,eligible:878,excluded:8,assets:878,verified:878,failed:0,retries:0,claims:0,leases:0,duplicateGroups:0,duplicateDestinations:0};
test("summary fixture reconciles",()=>{assert.equal(summary.sourceFiles,886);assert.equal(summary.excluded,8);assert.equal(summary.failed,0)});
test("completion",()=>assert.equal(completion(summary),100));
test("filename masking",()=>{assert.equal(maskFilename("private patient.jpeg"),"Restricted file.jpeg");assert.ok(!maskFilename("private patient.jpeg").includes("patient"))});
test("destination masking",()=>assert.equal(maskDestination("1234567890123456"),"12345678…3456"));
test("uuid shortening",()=>assert.equal(shortId("12345678-1234-1234-1234"),"12345678…1234"));
test("page size bounded",()=>assert.equal(parseParams({pageSize:"999"}).pageSize,100));
test("sort allowlist",()=>{assert.ok(SORT_FIELDS.includes("verified_at"));assert.equal(parseParams({sort:"raw_hash"}).sort,"verified_at")});
test("invalid params safe",()=>assert.deepEqual(parseParams({page:"x",direction:"sideways"}),{page:1,pageSize:25,sort:"verified_at",direction:"desc",search:""}));
test("exceptions",()=>assert.equal(isException("VERIFIED","SOURCE_CHANGED",false),true));
test("one source trace",()=>assert.equal(duplicateTrace([{assetId:"a",sourceId:"s",folderId:"f"}])[0].isDuplicate,false));
test("multiple source trace",()=>assert.equal(duplicateTrace([{assetId:"a",sourceId:"s1",folderId:"f"},{assetId:"a",sourceId:"s2",folderId:"g"}])[0].isDuplicate,true));
test("folder explorer defaults to 50 rows",()=>assert.equal(parseFileParams({}).pageSize,50));
test("folder explorer allows only supported page sizes",()=>assert.equal(parseFileParams({pageSize:"999"}).pageSize,50));
test("file sort is allowlisted",()=>assert.equal(parseFileParams({sort:"content_sha256"}).sort,"drive_modified_at"));
test("type filter is allowlisted",()=>assert.equal(parseFileParams({type:"secret"}).type,""));
test("file kinds cover media and unsupported files",()=>{assert.equal(fileKind("image/jpeg",null),"image");assert.equal(fileKind("video/mp4",null),"video");assert.equal(fileKind(null,"pptx"),"document");assert.equal(fileKind(null,"zip"),"other")});
test("invalid UUID is rejected",()=>assert.equal(isUuid("not-an-id"),false));
test("relative paths never expose source segments",()=>{const shown=safePath("Patient A/Aftercare");assert.equal(shown,"Nested folder · 2 levels");assert.ok(!shown.includes("Patient"))});
test("masked names retain only a safe extension",()=>{const shown=maskFilename("Jane Doe scan.JPEG");assert.equal(shown,"Restricted file.jpeg");assert.ok(!shown.includes("Jane"))});
