import test from"node:test";import assert from"node:assert/strict";import{readFileSync}from"node:fs";
const folderList=readFileSync("app/source-folders/page.tsx","utf8"),folder=readFileSync("app/source-folders/[sourceFolderId]/page.tsx","utf8"),detail=readFileSync("app/source-folders/[sourceFolderId]/files/[sourceFileId]/page.tsx","utf8"),queries=readFileSync("app/queries.ts","utf8"),session=readFileSync("app/reader-session.ts","utf8");
test("source folder rows are accessible links",()=>{assert.match(folderList,/className="folderRow" href=/);assert.match(folderList,/aria-label={`Open source folder/)});
test("folder route has search filters pagination and mobile-safe fields",()=>{for(const value of["query","type","extension","decision","status","migration","verified","duplicate","pageSize"])assert.match(folder,new RegExp(`name=\\"${value}\\"`));assert.match(folder,/Pagination/);assert.match(folder,/maskFilename/);assert.match(folder,/safePath/)});
test("file detail is folder scoped and read only",()=>{assert.match(queries,/id=eq\.\$\{fileId\}&source_folder_id=eq\.\$\{folderId\}/);assert.doesNotMatch(detail,/(delete|rename|upload|move) file/i)});
test("queries remain server only and select explicit fields",()=>{assert.match(queries,/import "server-only"/);assert.doesNotMatch(queries,/select=\*/);assert.match(queries,/DASHBOARD_MUTATIONS:readonly never\[\]=\[\]/)});
test("sensitive hashes and raw paths are absent from rendered pages",()=>{const pages=folder+detail;assert.doesNotMatch(pages,/(content_sha256|source_sha256|md5_checksum)/);assert.doesNotMatch(pages,/\.relativePath}/)});
test("managed reader rotation stays server only",()=>{assert.match(session,/import "server-only"/);assert.match(session,/grant_type=refresh_token/);assert.match(session,/MIN_TTL=300/);assert.match(session,/fs\.open\(lock,"wx"/);assert.doesNotMatch(folderList+folder+detail,/refresh_token|access_token/)});
test("expired managed access tokens reach refresh and lock contention retries",()=>{assert.match(session,/validate\(managed,url,true\)/);assert.match(session,/allowExpired=false/);assert.match(session,/attempt<40/);assert.doesNotMatch(session,/return current as T/)});
