import assert from "node:assert/strict";
import test from "node:test";
import { rerankAuthorizedCandidates,type AuthorizedCandidateSet,type EvidenceFact } from "../db/deterministic-reranker";
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`;
const req=(n:number,classification:string,concept:string,field="CONCEPT")=>({id:`r${n}`,classification,canonical_code:concept,value:concept,field});
const set=(ids:number[]):AuthorizedCandidateSet=>({schema_version:"kdi_authorized_candidate_set_v1",authorization_fingerprint:"a".repeat(64),candidates:ids.map(n=>({asset_id:id(n),authorization:{discover:true,view_metadata:true,preview:true,download:false}}))});
const fact=(n:number,concept:string,state:"OBSERVED"|"FALSE"|"UNKNOWN"="OBSERVED",sceneId:string|null="scene-1",evidenceId=`${n}-${concept}`):EvidenceFact=>({assetId:id(n),concept,state,sourceLayer:"DIRECT_STRUCTURED_OBSERVATION",evidenceId,sceneId,confidence:1});
const plan=(x:Record<string,any[]>)=>({hard_constraints:[],hard_exclusions:[],strong_requirements:[],preferences:[],negative_preferences:[],context:[],unresolved:[],conflicts:[],...x});
const rank=(p:any,facts:EvidenceFact[],ids=[1,2],metadata:any={})=>rerankAuthorizedCandidates(set(ids),p,{requirements:[]},{facts,metadata});

test("exact multi-evidence and same-scene evidence outrank partial/scattered evidence",()=>{const p=plan({strong_requirements:[req(1,"STRONG_REQUIREMENT","CLINICIAN"),req(2,"STRONG_REQUIREMENT","INJECTING"),req(3,"STRONG_REQUIREMENT","NECK")]});const out=rank(p,[fact(1,"CLINICIAN"),fact(1,"INJECTING"),fact(1,"NECK"),fact(2,"CLINICIAN","OBSERVED","s1"),fact(2,"INJECTING","OBSERVED","s2")]);assert.equal(out.candidates[0].asset_id,id(1));assert.equal(out.candidates[0].phase19.strongRequirementCoverage,1);assert.ok(out.candidates[0].phase19.normalizedScore>out.candidates[1].phase19.normalizedScore)});
test("hard constraints and observed exclusions determine eligibility while UNKNOWN is not FALSE",()=>{const p=plan({hard_constraints:[req(1,"HARD_CONSTRAINT","VIDEO","MEDIA_TYPE")],hard_exclusions:[req(2,"HARD_EXCLUSION","NEEDLE")],strong_requirements:[req(3,"STRONG_REQUIREMENT","CLINICIAN")]});const out=rank(p,[fact(1,"CLINICIAN"),fact(2,"CLINICIAN"),fact(2,"NEEDLE")],[1,2],{[id(1)]:{mimeType:"video/mp4"},[id(2)]:{mimeType:"image/jpeg"}});assert.equal(out.candidates[0].asset_id,id(1));assert.equal(out.candidates[0].phase19.eligible,true);assert.equal(out.candidates[1].phase19.eligible,false);assert.equal(out.candidates[0].phase19.evidenceContributions.find(x=>x.requirementId==="r2")?.state,"UNKNOWN")});
test("negative preference penalizes OBSERVED, explicitly FALSE receives only a small boost, UNKNOWN is neutral",()=>{const p=plan({strong_requirements:[req(1,"STRONG_REQUIREMENT","PROCEDURE")],negative_preferences:[req(2,"NEGATIVE_PREFERENCE","BLOOD")]});const out=rank(p,[fact(1,"PROCEDURE"),fact(1,"BLOOD"),fact(2,"PROCEDURE"),fact(2,"BLOOD","FALSE")],[1,2]);assert.equal(out.candidates[0].asset_id,id(2));assert.equal(out.candidates[1].phase19.negativePreferencePenalty,7)});
test("structured evidence cannot be drowned by visual similarity and duplicates are capped",()=>{const p=plan({strong_requirements:[req(1,"STRONG_REQUIREMENT","NECK"),req(2,"STRONG_REQUIREMENT","INJECTING")]});const candidates=set([1,2]);candidates.candidates[1].channels=[{channel:"VISUAL_ASSET",source_id:"v",normalized_channel_score:1}];const many=[fact(1,"NECK"),fact(1,"INJECTING"),...Array.from({length:20},(_,i)=>fact(1,"NECK","OBSERVED","scene-1",`dup-${i}`))];const out=rerankAuthorizedCandidates(candidates,p,{requirements:[]},{facts:many,metadata:{}});assert.equal(out.candidates[0].asset_id,id(1));assert.ok(out.candidates[0].phase19.evidenceScore<60)});
test("unauthorized/raw candidate sets fail closed before scoring",()=>{const raw:any={schema_version:"kdi_candidate_set_v1",authorization_fingerprint:"",candidates:[{asset_id:id(1),channels:[{channel:"VISUAL_ASSET",normalized_channel_score:1}]}]};const out=rerankAuthorizedCandidates(raw,plan({strong_requirements:[req(1,"STRONG_REQUIREMENT","NECK")]}),{requirements:[]},{facts:[fact(1,"NECK")],metadata:{}});assert.equal(out.candidates.length,0);assert.equal(out.diagnostics.authorization_boundary_valid,false)});
test("correct schema with malformed authorization fingerprint fails closed",()=>{const malformed:any=set([1]);malformed.authorization_fingerprint="not-a-sha256";const out=rerankAuthorizedCandidates(malformed,plan({strong_requirements:[req(1,"STRONG_REQUIREMENT","NECK")]}),{requirements:[]},{facts:[fact(1,"NECK")],metadata:{}});assert.equal(out.candidates.length,0);assert.equal(out.diagnostics.authorization_boundary_valid,false)});
test("ties and complete reranks are byte-reproducible",()=>{const p=plan({strong_requirements:[req(1,"STRONG_REQUIREMENT","CLINICIAN")]});const evidence={facts:[fact(1,"CLINICIAN"),fact(2,"CLINICIAN")],metadata:{}};const outputs=Array.from({length:20},()=>rank(p,evidence.facts));assert.equal(new Set(outputs.map(x=>x.ranking_fingerprint)).size,1);assert.deepEqual(outputs[0].candidates.map(x=>x.asset_id),[id(1),id(2)])});
test("NOT_APPLICABLE remains distinct and contributes neither reward nor penalty",()=>{const p=plan({strong_requirements:[req(1,"STRONG_REQUIREMENT","NECK")]});const f={...fact(1,"NECK"),state:"NOT_APPLICABLE" as const};const out=rank(p,[f],[1]);assert.equal(out.candidates[0].phase19.evidenceContributions[0].state,"NOT_APPLICABLE");assert.equal(out.candidates[0].phase19.evidenceContributions[0].finalContribution,0)});
