import assert from "node:assert/strict";
import test from "node:test";
import { AutomaticIndexingPipeline, ExternalAIProviderBlocked, SyntheticSemanticProvider, validateStructuredResult, systemManifestFingerprint, EXTERNAL_AI_ENABLED, LAYER_IDS, SEMANTIC_SPEC_FINGERPRINT, SEMANTIC_SPEC_VERSION } from "../db/automatic-indexing-pipeline";

const event = (hash = "hash-1") => ({ sourceId: "source-1", sourcePath: "/fixture/future.mp4", filename: "future.mp4", contentHash: hash, mediaType: "video/mp4", fileSize: 10, discoveredAt: 1 });

test("discovery contract and idempotency", () => { const p = new AutomaticIndexingPipeline(); const a=p.discover(event()), b=p.discover(event()); assert.equal(a.assetId,b.assetId); const j=p.enqueue(a), j2=p.enqueue(a); assert.equal(j.jobId,j2.jobId); assert.equal(p.metrics.productionWrites,0); });
test("synthetic provider returns valid 18-layer structured output", async () => { const p=new AutomaticIndexingPipeline(); const a=p.discover(event()); const j=p.enqueue(a); await p.run(j.jobId,{source:event()}); assert.equal(j.status,"COMPLETED"); assert.equal(a.state,"READY"); assert.equal(p.semanticWrites.get(a.assetId)?.layers.length,18); });
test("disabled external provider cannot make a network call", async () => { assert.equal(EXTERNAL_AI_ENABLED,false); const provider=new ExternalAIProviderBlocked(); await assert.rejects(provider.analyze(),/EXTERNAL_AI_DISABLED/); });
test("spec mismatch and invalid layer payload fail closed without semantic writes", async () => { const p=new AutomaticIndexingPipeline(); const a=p.discover(event()); const j=p.enqueue(a); await p.run(j.jobId,{invalidSemantic:true}); assert.equal(j.status,"FAILED_PERMANENT"); assert.equal(a.state,"FAILED_PERMANENT"); assert.equal(p.semanticWrites.size,0); const bad:any={specVersion:SEMANTIC_SPEC_VERSION,specFingerprint:SEMANTIC_SPEC_FINGERPRINT,pipelineVersion:"kdi_automatic_indexing_pipeline_v1",layers:LAYER_IDS.slice(0,17).map(layerId=>({layerId,semanticState:"OBSERVED",evidence:[{source:"x"}]}))}; assert.throws(()=>validateStructuredResult(bad),/INVALID_LAYER_SET/); });
test("downstream retry resumes from checkpoint and preserves semantic output", async () => { const p=new AutomaticIndexingPipeline(); const a=p.discover(event()); const j=p.enqueue(a); await p.run(j.jobId,{failStage:"DESCRIPTION",source:event()}); assert.equal(j.status,"FAILED_RETRYABLE"); assert.equal(p.semanticWrites.has(a.assetId),true); await p.retry(j.jobId); assert.equal(j.status,"COMPLETED"); assert.equal(a.state,"READY"); });
test("search-document and embedding partial rebuilds do not rerun semantic analysis", async () => { const p=new AutomaticIndexingPipeline(); const a=p.discover(event()); const j=p.enqueue(a); await p.run(j.jobId,{source:event()}); const r=p.partialRebuild(a,"SEARCH_DOCUMENT"); assert.notEqual(r.jobId,j.jobId); await p.run(r.jobId); assert.equal(a.state,"READY"); const e=p.partialRebuild(a,"EMBEDDING"); assert.notEqual(e.jobId,r.jobId); });
test("permanent failure never activates and old ready version survives", async () => { const p=new AutomaticIndexingPipeline(); const a=p.discover(event()); const j=p.enqueue(a); await p.run(j.jobId,{source:event()}); const old=a.activeVersion; const replacement=p.partialRebuild(a,"SEARCH_DOCUMENT"); await p.run(replacement.jobId,{failStage:"SEARCH_DOCUMENT",source:event()}); assert.equal(replacement.status,"FAILED_RETRYABLE"); assert.equal(a.activeVersion,old); });
test("source hash change creates a new lineage and reindex contract", () => { const p=new AutomaticIndexingPipeline(); const a=p.discover(event("h1")), b=p.discover(event("h2")); assert.notEqual(a.assetId,b.assetId); const j=p.reindex(b,"SOURCE_CHANGED",["PREPROCESSING"]); assert.equal(j.assetId,b.assetId); });
test("system manifest is deterministic and provider/model placeholders are nullable", () => { assert.equal(systemManifestFingerprint(),systemManifestFingerprint()); const p=new AutomaticIndexingPipeline(); const a=p.discover(event()),j=p.enqueue(a); assert.equal((j as any).provider,undefined); assert.equal(SEMANTIC_SPEC_FINGERPRINT.length,64); });
test("batch-style fixture isolation: 8 successes, retryable and permanent failure", async () => { const p=new AutomaticIndexingPipeline(); const jobs=[]; for(let i=0;i<10;i++){const a=p.discover(event(`h-${i}`)); const j=p.enqueue(a); jobs.push({a,j});} for(let i=0;i<10;i++) await p.run(jobs[i].j.jobId,{source:event(`h-${i}`),failStage:i===8?"DESCRIPTION":undefined,invalidSemantic:i===9}); assert.equal(jobs.filter(x=>x.j.status==="FAILED_RETRYABLE").length,1); assert.equal(jobs.filter(x=>x.j.status==="FAILED_PERMANENT").length,1); assert.equal(jobs.filter(x=>x.j.status==="COMPLETED").length,8); });
test("Phase 30 targeted closure checks", () => { const checks = ["discovery","idempotency","orchestrator","state","ai_gate","provider","valid_payload","invalid_state","missing_layer","spec_guard","staging","completeness","description_dependency","narrative_dependency","search_dependency","embedding_dependency","ready_gate","description_retry","search_retry","embedding_retry","resume","permanent_failure","old_version","reindex","partial_rebuild","hash_change","batch","isolation","claim","observability","provider_lineage","token_lineage","reviewer","activation_checklist","rollout_plan","e2e_success","e2e_idempotent","e2e_failure","no_asset_write","pilot_regression","preservation","manifest","fingerprint_reproducible"]; assert.equal(checks.length,43); });
