import assert from"node:assert/strict";import test from"node:test";
import{CONVERSATIONAL_SEARCH_MEMORY_VERSION,SEARCH_CONTEXT_TTL_MS,memoryRecord,resolveConversationalSearch,type PriorSearchContext}from"../db/conversational-search-memory";
const ids=["a","b","c"];
const prior=(x:Partial<PriorSearchContext>={}):PriorSearchContext=>({sessionId:"s1",userId:"u1",queryId:"q1",resolvedQuery:"show me injection videos",filters:{action:"INJECTING",media_type:"video"},requestedCount:5,resultAssetIds:ids,lastActivityAt:new Date().toISOString(),...x});
const r=(query:string,p:PriorSearchContext|undefined=prior(),extra:Record<string,unknown>={})=>resolveConversationalSearch({query,sessionId:"s1",userId:"u1",prior:p,...extra});

test("count continuation inherits intent",()=>{const x=r("give me 2");assert.equal(x.context_mode,"CONTINUE");assert.equal(x.resolved_query,prior().resolvedQuery);assert.equal(x.requested_count,2)});
test("media type narrowing",()=>assert.equal(r("only videos").filters.media_type,"video"));
test("anatomy narrowing",()=>{const x=r("only neck ones");assert.equal(x.filters.action,"INJECTING");assert.equal(x.filters.anatomy,"NECK")});
test("anatomy replacement",()=>{const x=r("actually lower face",prior({filters:{action:"INJECTING",anatomy:"NECK"}}));assert.equal(x.context_mode,"MODIFY");assert.equal(x.filters.anatomy,"LOWER_FACE")});
test("first ordinal resolves ranked first",()=>assert.equal(r("give me the first one").referenced_asset_id,"a"));
test("second ordinal resolves ranked second",()=>assert.equal(r("what about the second one?").referenced_asset_id,"b"));
test("last ordinal resolves ranked last",()=>assert.equal(r("show me the last one").referenced_asset_id,"c"));
test("detailed description follow-up is an asset reference, not a fact cache",()=>{const x=r("give me the detailed description of the first one");assert.equal(x.reference_kind,"DETAILED_DESCRIPTION");assert.equal(x.referenced_asset_id,"a");assert.equal((x as any).detailed_description,undefined)});
test("treatment follow-up retains DATABASE_REQUIRED boundary",()=>{const x=r("what treatment is happening in the first one?");assert.equal(x.reference_kind,"TREATMENT");assert.equal(memoryRecord(x).referenced_asset_id,"a")});
test("self-contained topic resets context",()=>{const x=r("show me frontal hairline thinning");assert.equal(x.context_mode,"NEW_QUERY");assert.deepEqual(x.filters,{})});
test("ordinal without context fails safely",()=>assert.equal(resolveConversationalSearch({query:"show me the second one",sessionId:"s1",userId:"u1"}).status,"CONTEXT_NOT_AVAILABLE"));
test("session isolation",()=>assert.equal(resolveConversationalSearch({query:"first one",sessionId:"s2",userId:"u1",prior:prior()}).status,"CONTEXT_NOT_AVAILABLE"));
test("user isolation",()=>assert.equal(resolveConversationalSearch({query:"first one",sessionId:"s1",userId:"u2",prior:prior()}).status,"CONTEXT_NOT_AVAILABLE"));
test("neck exclusion is negative",()=>{const x=r("exclude neck");assert.equal(x.filters.excluded_anatomy,"NECK");assert.equal(x.filters.anatomy,undefined)});
test("same search changes media type",()=>{const x=r("same search but only images");assert.equal(x.filters.action,"INJECTING");assert.equal(x.filters.media_type,"image")});
test("same search top count",()=>assert.equal(r("same search, top 3").requested_count,3));
test("zero-result context cannot resolve ordinal",()=>assert.equal(r("second one",prior({resultAssetIds:[]})).status,"ORDINAL_OUT_OF_RANGE"));
test("out-of-range ordinal fails",()=>assert.equal(r("third one",prior({resultAssetIds:["a","b"]})).status,"ORDINAL_OUT_OF_RANGE"));
test("result memory is deduplicated without reordering",()=>assert.deepEqual(r("from those, show me the best 2",prior({resultAssetIds:["a","b","a"]})).prior_result_scope,["a","b"]));
test("result-set reference preserves scope and count",()=>{const x=r("from those, show me the best 2");assert.equal(x.context_mode,"RESULT_SET_REFERENCE");assert.equal(x.requested_count,2);assert.deepEqual(x.prior_result_scope,ids)});
test("expired context fails safely",()=>assert.equal(r("first one",prior({lastActivityAt:new Date(Date.now()-SEARCH_CONTEXT_TTL_MS-1).toISOString()})).status,"CONTEXT_EXPIRED"));
test("memory records IDs and context only",()=>{const m:any=memoryRecord(r("only neck ones"));assert.equal(m.implementation_version,CONVERSATIONAL_SEARCH_MEMORY_VERSION);assert.equal(m.asset_facts,undefined);assert.equal(m.description,undefined)});
test("pilot neck sequence resolves IMG_3429 as first without storing facts",()=>{const x=r("only neck ones",prior({resultAssetIds:["IMG_3429.MP4","IMG_0531.MP4"]}));const y=r("detailed description of the first one",prior({resolvedQuery:x.resolved_query,filters:x.filters,resultAssetIds:["IMG_3429.MP4"]}));assert.equal(y.referenced_asset_id,"IMG_3429.MP4")});
test("pilot lower-face fragment preserves injection context",()=>{const x=r("lower-face ones",prior({resultAssetIds:["IMG_0531.MP4"]}));assert.equal(x.context_mode,"MODIFY");assert.equal(x.filters.anatomy,"LOWER_FACE");assert.equal(x.resolved_query,"show me injection videos")});
test("pilot hairline ordinal resolves DSC03753.JPG",()=>assert.equal(r("give me the first one",prior({resolvedQuery:"show me frontal hairline thinning",resultAssetIds:["DSC03753.JPG"]})).referenced_asset_id,"DSC03753.JPG"));
test("only top count is delegated as canonical count continuation",()=>assert.equal(r("give me only the top 2").requested_count,2));
