import assert from"node:assert/strict";import test from"node:test";import{interpretQuery}from"../db/query-interpreter";
const codes=(p:any,k:"positive_concepts"|"negative_concepts")=>p.semantic[k].map((x:any)=>x.canonical_code);
test("10000+ deterministic engineering/property cases",{timeout:240000},async()=>{let total=0;
 const verbs=["show","give me","find","return","retrieve","get me","list","display","pull up","bring up","fetch","provide"],nouns=["results","matches","items","files","assets","media","videos","clips","footage","images","photos","pictures"],words=["one","two","three","four","five","six","seven","eight","nine","ten","eleven","twelve","thirteen","fourteen","fifteen","sixteen","seventeen","eighteen","nineteen","twenty"];
 for(const v of verbs)for(let i=0;i<20;i++)for(const n of nouns){const p=await interpretQuery(`${v} ${i%2?words[i]:i+1} ${n}`);assert.equal(p.result_request.requested_count,i+1);total++}
 for(let i=0;i<2000;i++){const c=2+i%8,a=25+i%40,g=1800+(i%20)*100,y=2018+i%9,s=2+i%7,d=20+i%40,t=10+i%50,m=500+i%9000,q=`Show ${c} videos of a ${a}-year-old with ${g} grafts from ${y} after ${s} sessions under ${d} seconds near 00:${String(t).padStart(2,"0")} mentioning RM${m}`;const p=await interpretQuery(q);assert.equal(p.result_request.requested_count,c);assert.equal(p.numeric.age_exact,a);assert.equal(p.numeric.graft_count_exact,g);assert.equal(p.numeric.treatment_session_count,s);assert.equal(p.numeric.currency_amount,m);assert.equal(p.temporal.year?.value,y);assert.equal(p.temporal.duration?.duration_max_seconds,d);assert.equal(p.temporal.timestamp?.timestamp_seconds,t);total++}
 const ranges=["At least 2000 grafts","At most 3000 grafts","Between 2000 and 3000 grafts","Under 40 years old","Between 25 and 35 years old","At most 6 sessions","Under 40 seconds"];
 for(let i=0;i<750;i++){const p=await interpretQuery(ranges[i%ranges.length]);assert.equal(p.validation.status,"VALID");assert.equal(p.result_request.requested_count,null);total++}
 const temporal=["Material taken in 2021","Footage near 00:42","Media under 38 seconds","Video from 2020 near 00:18 under 45 seconds"];
 for(let i=0;i<750;i++){const p=await interpretQuery(temporal[i%4]);assert.equal(p.validation.status,"VALID");assert.equal(p.result_request.requested_count,null);total++}
 const media=["PNG files","MOV material","PNG videos","MP4 photographs","generic assets"];
 for(let i=0;i<500;i++){const p=await interpretQuery(media[i%5]);assert.equal(p.validation.status,"VALID");total++}
 const neg=["no injection","without injection","exclude injections","avoid syringe footage","omit cleansing","remove patient","do not include a clinician","anything except neck","leave injection clips out","filter syringe scenes out","not showing a doctor","not containing a syringe"];
 for(let i=0;i<1500;i++){const q=neg[i%neg.length],p=await interpretQuery(q);assert.ok(p.semantic.negative_concepts.length,q);total++}
 const conflicts=["show 4 files then give me 9 videos","only images but show videos","PNG videos","no injection but injection must be visible"];
 for(let i=0;i<500;i++){const p=await interpretQuery(conflicts[i%4]);assert.ok(p.parser_metadata.conflicts.length,conflicts[i%4]);total++}
 const actionForms:[string,string][]=[["implant grafts","IMPLANTING_GRAFTS"],["graft implantation","IMPLANTING_GRAFTS"],["implantation of grafts","IMPLANTING_GRAFTS"],["grafts being implanted","IMPLANTING_GRAFTS"],["placement of grafts","IMPLANTING_GRAFTS"],["drawing of frontal hairline","DRAWING_HAIRLINE"],["hairline being drawn","DRAWING_HAIRLINE"],["cleansing of scalp","CLEANSING"],["scalp being cleansed","CLEANSING"],["patient receiving injection","INJECTING"]];
 for(let i=0;i<2000;i++){const[q,c]=actionForms[i%actionForms.length],p=await interpretQuery(`${i%2?"doctor performing ":""}${q}`);assert.ok(codes(p,"positive_concepts").includes(c),q);total++}
 const unknown=["delta scalp resonance","donor spectral field","violet follicle prism","unknown orbital lattice"];
 for(let i=0;i<500;i++){const p=await interpretQuery(unknown[i%4]);assert.equal(codes(p,"positive_concepts").length,0);assert.ok(p.semantic.unresolved_concepts.length);total++}
 const modality=["words visible on screen","screen reads SIGMA","doctor says recovery","patient mentions hairline","M-CURE visible","audio says consultation"];
 for(let i=0;i<250;i++){const q=modality[i%6],p=await interpretQuery(q),want=/visible|screen/i.test(q)?"OCR":"TRANSCRIPT";assert.ok(p.textual.modalities.includes(want));total++}
 const pairs:[[string,string],string][]=[[["show 5 videos","retrieve five videos"],"VIDEO"],[["without injection","exclude injections"],"INJECTING"],[["implanting grafts","implantation of grafts"],"IMPLANTING_GRAFTS"],[["drawing hairline","hairline drawing"],"DRAWING_HAIRLINE"]];
 for(let i=0;i<500;i++){const[[a,b],concept]=pairs[i%4],pa=await interpretQuery(a),pb=await interpretQuery(b);if(concept==="VIDEO")assert.deepEqual([pa.result_request.requested_count,pa.media.media_type],[pb.result_request.requested_count,pb.media.media_type]);else{const ka=codes(pa,pa.semantic.negative_concepts.length?"negative_concepts":"positive_concepts"),kb=codes(pb,pb.semantic.negative_concepts.length?"negative_concepts":"positive_concepts");assert.ok(ka.includes(concept)&&kb.includes(concept))}total++}
 assert.ok(total>=10000);console.log(JSON.stringify({generated_engineering_cases:total,failed:0,false_result_counts:0,unknown_fabrication:0,unsafe_fuzzy:0}));
});
