import assert from"node:assert/strict";import test from"node:test";import{readFileSync}from"node:fs";import path from"node:path";import{GAIN,comparableEvaluation,evaluateAccuracy,evaluateCase,evaluateRetrieval}from"../db/semantic-accuracy-measurement";import{goldFingerprint,type GoldSet}from"../db/semantic-gold-answers";
const j=(id:string,label:string)=>({asset_id:id,label}),root=path.resolve(process.cwd(),"..");
test("EXACT_RELEVANT gain 3",()=>assert.equal(GAIN.EXACT_RELEVANT,3));
test("RELEVANT gain 2",()=>assert.equal(GAIN.RELEVANT,2));
test("PARTIAL_RELEVANT gain 1",()=>assert.equal(GAIN.PARTIAL_RELEVANT,1));
test("UNRESOLVED is unjudged",()=>{const r=evaluateRetrieval(["u"],[j("u","UNRESOLVED")]);assert.equal(r.at[1].judgment_coverage,0);assert.equal(r.at[1].unjudged_rate,1);assert.equal(r.at[1].strict_precision,0)});
test("acceptable relevant top1 passes",()=>assert.equal(evaluateRetrieval(["b"],[j("a","RELEVANT"),j("b","RELEVANT")]).pass,true));
test("excluded exposure captured",()=>{const r=evaluateRetrieval(["x"],[j("x","EXCLUDED"),j("a","RELEVANT")]);assert.equal(r.excluded_exposures.length,1);assert.ok(r.failures.includes("EXCLUDED_RESULT_RETURNED"))});
test("zero result correctness",()=>assert.equal(evaluateRetrieval([], [j("x","NOT_RELEVANT")]).zero_result_correct,true));
test("strict precision ignores unjudged denominator",()=>assert.equal(evaluateRetrieval(["u","r"],[j("u","UNRESOLVED"),j("r","RELEVANT")]).at[3].strict_precision,1));
test("lenient precision includes partial",()=>assert.equal(evaluateRetrieval(["p"],[j("p","PARTIAL_RELEVANT")]).at[1].lenient_precision,1));
test("partial-only retrieval can pass leniently",()=>assert.equal(evaluateRetrieval(["p"],[j("p","PARTIAL_RELEVANT")]).pass,true));
test("MRR uses first strict result",()=>assert.equal(evaluateRetrieval(["n","r"],[j("n","NOT_RELEVANT"),j("r","RELEVANT")]).mrr,.5));
test("nDCG perfect ranking is one",()=>assert.equal(evaluateRetrieval(["e","r"],[j("e","EXACT_RELEVANT"),j("r","RELEVANT")]).ndcg3,1));
test("judgment coverage works",()=>assert.equal(evaluateRetrieval(["r","u"],[j("r","RELEVANT"),j("u","UNRESOLVED")]).at[3].judgment_coverage,.5));
const base=(m:string,e:any)=>({case_id:"T",evaluation_modes:[m],scored_for_retrieval_metrics:false,behavioral_expectations:e,turns:[{requested_count:e.requested_count??null,effective_count:e.effective_count??5,judgments:[]}]});
test("parser control detects unavailable numeric capture",()=>assert.equal(evaluateCase(base("PARSER_CONTROL",{age:30}),{turns:[{parsed_intent:{positive:["PATIENT"]},requested_count:null}]}).pass,false));
test("count control exact scoring",()=>assert.equal(evaluateCase(base("RESULT_COUNT_CONTROL",{requested_count:3,effective_count:3}),{turns:[{requested_count:3,effective_count:3}]}).pass,true));
test("response state exact scoring",()=>assert.equal(evaluateCase(base("RESPONSE_STATE",{semantic_state:"UNKNOWN"}),{turns:[{parsed_intent:{status:"UNKNOWN"}}]}).pass,true));
test("conversation control scoring",()=>{const c:any={...base("CONVERSATION_CONTROL",{}),turns:[{expected_referenced_asset_id:null,resolved_semantic_target:"a",judgments:[]},{expected_referenced_asset_id:null,resolved_semantic_target:"b",judgments:[]}]};assert.equal(evaluateCase(c,{turns:[{conversation:{status:"RESOLVED"}},{conversation:{status:"RESOLVED"}}]}).pass,true)});
test("authorization fail closed scoring",()=>assert.equal(evaluateCase(base("AUTHORIZATION_CONTROL",{authorized_asset_ids:[]}),{turns:[{asset_ids:[]}]}).pass,true));
test("locked gold fingerprint unchanged",()=>{const g:GoldSet=JSON.parse(readFileSync(path.join(root,"reports","semantic-search","phase25","kdi_gold_answers_v1.certified.json"),"utf8"));assert.equal(g.gold_fingerprint,goldFingerprint(g))});
test("Run A B evaluation reproducibility and no DB mutation",()=>{const a=JSON.parse(readFileSync(path.join(root,"reports","semantic-search","phase26","phase26_accuracy_run_a.json"),"utf8")),b=JSON.parse(readFileSync(path.join(root,"reports","semantic-search","phase26","phase26_accuracy_run_b.json"),"utf8"));assert.deepEqual(comparableEvaluation(a),comparableEvaluation(b));const s=readFileSync(path.join(process.cwd(),"scripts","phase26-accuracy-measurement.ts"),"utf8");assert.doesNotMatch(s,/\.insert\(|\.update\(|\.upsert\(|\.delete\(/)});
