import assert from"node:assert/strict";import test from"node:test";import{readFileSync}from"node:fs";import path from"node:path";import{assertGoldMutable,GOLD_LABELS,validateGoldSet,type GoldSet}from"../db/semantic-gold-answers";
const root=path.resolve(process.cwd(),".."),benchmark:any=JSON.parse(readFileSync(path.join(root,"config","semantic-search","kdi_semantic_benchmark_v1.json"),"utf8")),gold:GoldSet=JSON.parse(readFileSync(path.join(root,"reports","semantic-search","phase25","kdi_gold_answers_v1.draft.json"),"utf8")),audit:any=JSON.parse(readFileSync(path.join(root,"reports","semantic-search","phase25","live_evidence_audit.json"),"utf8"));const flat=gold.cases.flatMap(c=>c.turns.flatMap(t=>t.judgments)),first=gold.cases.flatMap(c=>c.turns[0].judgments),caseOf=(id:string)=>gold.cases.find(c=>c.case_id===id)!;
test("exact 40 benchmark cases loaded",()=>assert.equal(benchmark.cases.length,40));
test("40 gold answers produced",()=>assert.equal(gold.cases.length,40));
test("missing cases zero",()=>assert.deepEqual(validateGoldSet(gold,benchmark.cases.map((x:any[])=>x[0])).filter(x=>x.startsWith("MISSING")),[]));
test("duplicate active cases zero",()=>assert.equal(new Set(gold.cases.map(c=>c.case_id)).size,40));
test("positive judgments have evidence",()=>assert.ok(flat.filter(j=>["EXACT_RELEVANT","RELEVANT","PARTIAL_RELEVANT"].includes(j.label)).every(j=>j.evidence.length>0)));
test("UNKNOWN remains explicit in live evidence",()=>assert.ok(audit.assets.some((a:any)=>a.assertions.some((x:any)=>x.semantic_state==="UNKNOWN"))));
test("FALSE remains explicit in live evidence",()=>assert.ok(audit.assets.some((a:any)=>a.assertions.some((x:any)=>x.semantic_state==="FALSE"))));
test("NOT_APPLICABLE is preserved without fabrication",()=>{assert.ok(gold.semantic_state_invariants.includes("NOT_APPLICABLE_IS_NOT_FALSE"));assert.equal(audit.assets.some((a:any)=>a.assertions.some((x:any)=>x.semantic_state==="NOT_APPLICABLE")),false)});
test("typo-equivalent gold compatible",()=>assert.deepEqual(caseOf("C01").turns[0].judgments.map(j=>j.label),caseOf("C19").turns[0].judgments.map(j=>j.label)));
test("zero-result gold works",()=>{for(const id of["C29","C30","C31"])assert.equal(caseOf(id).turns[0].maximum_valid_relevant,0)});
test("multiple acceptable answers supported",()=>assert.ok(caseOf("C12").turns[0].acceptable_asset_ids.length>1));
test("conversation gold state supported",()=>assert.equal(gold.cases.filter(c=>c.turns.length>1).length,5));
test("ordinal reference supported",()=>assert.ok(caseOf("C36").turns[2].expected_referenced_asset_id));
test("certified gold is immutable",()=>assert.throws(()=>assertGoldMutable({...gold,status:"CERTIFIED",immutable:true}),/IMMUTABLE/));
test("spec fingerprint stored",()=>assert.equal(gold.spec_fingerprint,"6da50e2153f6fcb6c9ef27c308ad44d0d2024e702e3faad47586b0068ba64fd7"));
test("pilot manifest stored",()=>assert.equal(gold.pilot_manifest.length,10));
test("no search output used",()=>{const src=readFileSync(path.join(process.cwd(),"scripts","phase25-build-gold-answers.ts"),"utf8");assert.doesNotMatch(src,/candidate-retriever|deterministic-reranker|phase24\/runs|run a|run b/i)});
test("no semantic or ACL mutation code",()=>{for(const f of["scripts/phase25-live-evidence-audit.ts","scripts/phase25-build-gold-answers.ts"]){const src=readFileSync(path.join(process.cwd(),f),"utf8");assert.doesNotMatch(src,/\.insert\(|\.update\(|\.upsert\(|\.delete\(/)}});
test("OpenAI calls zero",()=>{const src=readFileSync(path.join(process.cwd(),"scripts","phase25-build-gold-answers.ts"),"utf8");assert.doesNotMatch(src,/from\s*["']openai|new OpenAI|chat\.completions|responses\.create/)});
test("all labels valid and contradictions absent",()=>{assert.equal(first.length,400);assert.ok(first.every(j=>GOLD_LABELS.includes(j.label)));assert.equal(new Set(gold.cases.flatMap(c=>c.turns[0].judgments.map(j=>`${c.case_id}:${j.asset_id}`))).size,400)});
