import test from "node:test";import assert from "node:assert/strict";import {buildDocuments,CONFIGURATION_FINGERPRINT,markDownstreamStale} from "../db/search-document-builder";
const input=(mime="video/mp4")=>({asset_id:"00000000-0000-4000-8000-000000000001",filename:mime.startsWith("video")?"x.mp4":"x.jpg",mime_type:mime,source_fingerprint:"a".repeat(64),scenes:[{id:"00000000-0000-4000-8000-000000000002",scene_index:0,start_seconds:0,end_seconds:mime.startsWith("video")?5:0,scene_type:mime.startsWith("video")?"PROCEDURE":"STILL_IMAGE"}],events:[] as any[],assertions:[] as any[]});
test("configuration fingerprint is stable",()=>assert.match(CONFIGURATION_FINGERPRINT,/^[a-f0-9]{64}$/));
test("document fingerprint is deterministic",()=>assert.equal(buildDocuments(input()).asset.document_fingerprint,buildDocuments(input()).asset.document_fingerprint));
test("video gets a scene and image gets no pseudo-scene",()=>{assert.equal(buildDocuments(input()).scenes.length,1);assert.equal(buildDocuments(input("image/jpeg")).scenes.length,0)});
test("UNKNOWN and NOT_APPLICABLE never become positive concepts",()=>{for(const semantic_state of ["UNKNOWN","NOT_APPLICABLE"]){const i=input();i.assertions=[{asset_id:i.asset_id,predicate:"TREATMENT",canonical_concept_code:"HAIR_TRANSPLANT",semantic_state}];assert.equal(buildDocuments(i as any).asset.positive_concepts.length,0)}});
test("FALSE is negative only",()=>{const i=input("image/jpeg");i.assertions=[{asset_id:i.asset_id,predicate:"OCR",canonical_concept_code:"VISIBLE_TEXT",semantic_state:"FALSE",evidence_ids:["e"]}];const d=buildDocuments(i as any).asset;assert.equal(d.positive_concepts.length,0);assert.equal(d.negative_concepts.length,1)});
test("technical events are excluded",()=>{const i=input();i.events=[{id:"e",scene_id:i.scenes[0].id,start_time:0,end_time:1,event_type:"CUT",technical_only:true,semantic_state:"OBSERVED"} as any];assert.equal(buildDocuments(i as any).events.length,0)});
test("semantic source changes mark document stale",()=>assert.equal(markDownstreamStale("a","b"),true));
