import assert from "node:assert/strict";import test from "node:test";import {evaluatePlan,normalizeActual,BENCHMARK_EVALUATOR_VERSION}from"../lib/search/query-parser-benchmark-evaluator";
const plan=(over:any={})=>({result_request:{requested_count:null,requested_count_occurrences:[]},media:{media_type:"ANY",extensions:[]},numeric:{},temporal:{},semantic:{positive_concepts:[],negative_concepts:[],unresolved_concepts:[]},textual:{modalities:["VISUAL"]},parser_metadata:{conflicts:[]},validation:{status:"VALID"},...over});
test("evaluator is independently versioned",()=>assert.equal(BENCHMARK_EVALUATOR_VERSION,"kdi_query_parser_evaluator_v2"));
test("structured year equals canonical expectation",()=>assert.equal(evaluatePlan({temporal:{year:{value:2021}}},plan({temporal:{year:{value:2021,status:"MATCHED"}}})).passed,true));
test("structured timestamp equals canonical expectation",()=>assert.equal(evaluatePlan({temporal:{timestamp:{seconds:42,approximate:false}}},plan({temporal:{timestamp:{timestamp_seconds:42,approximate:false}}})).passed,true));
test("structured duration equals canonical expectation",()=>assert.equal(evaluatePlan({temporal:{duration:{max_seconds:38}}},plan({temporal:{duration:{duration_min_seconds:null,duration_max_seconds:38}}})).passed,true));
test("two explicit counts are conflict, not false count",()=>{const p=plan({result_request:{requested_count:null,requested_count_occurrences:[{value:4},{value:9}]},parser_metadata:{conflicts:[{conflict_type:"COUNT_CONFLICT"}]}}),r=evaluatePlan({result_count:{values:[4,9],conflict:true}},p);assert.equal(r.false_result_count,0);assert.equal(r.passed,true)});
test("age promoted to count is false count",()=>{const p=plan({result_request:{requested_count:30,requested_count_occurrences:[{value:30}]}});assert.equal(evaluatePlan({non_result_numbers:[30]},p).false_result_count,1)});
test("grafts promoted to count is false count",()=>{const p=plan({result_request:{requested_count:3000,requested_count_occurrences:[{value:3000}]}});assert.equal(evaluatePlan({non_result_numbers:[3000]},p).false_result_count,1)});
