import assert from "node:assert/strict";
import test from "node:test";
import { ScaleReadinessSimulator, SEMANTIC_SPEC_FINGERPRINT, SCALE_PIPELINE_VERSION, canTransition, dryRunScale, idempotencyKey, runScaleReadinessChecks, staleStages, transition } from "../db/scale-readiness";

test("canonical lifecycle and illegal transitions", () => { assert.equal(canTransition("DISCOVERED", "REGISTERED"), true); assert.throws(() => transition("READY", "SEMANTIC_ANALYSIS")); const s = new ScaleReadinessSimulator(); s.register("a", "h"); const j = s.enqueue("a", "h"); s.claim(j.jobId, "w"); assert.throws(() => s.activate(j.jobId)); });
test("idempotency and content hash dedupe", () => { const s = new ScaleReadinessSimulator(); const a=s.register("a", "same"); const b=s.register("b", "same"); assert.equal(a.duplicate,false); assert.equal(b.duplicate,true); const j=s.enqueue("a","same"), j2=s.enqueue("a","same"); assert.equal(j.jobId,j2.jobId); assert.equal(idempotencyKey({assetId:"a",contentHash:"same",jobType:"FULL"}),idempotencyKey({assetId:"a",contentHash:"same",jobType:"FULL"})); });
test("bounded retry, permanent failure and isolation", () => { const s=new ScaleReadinessSimulator(); s.register("a","a"); s.register("b","b"); const a=s.enqueue("a","a"), b=s.enqueue("b","b"); s.claim(a.jobId,"w"); s.fail(a.jobId,"NETWORK_TIMEOUT"); assert.equal(a.status,"FAILED_RETRYABLE"); s.retry(a.jobId); s.claim(a.jobId,"w"); s.complete(a.jobId); s.activate(a.jobId); s.claim(b.jobId,"w"); s.fail(b.jobId,"CORRUPT_INPUT"); assert.equal(b.status,"FAILED_PERMANENT"); assert.equal(s.assets.get("a")?.state,"READY"); });
test("lease recovery and single-worker claim protection", () => { const s=new ScaleReadinessSimulator(); s.register("a","a"); const j=s.enqueue("a","a"); s.claim(j.jobId,"w1"); assert.throws(()=>s.claim(j.jobId,"w2")); assert.equal(s.recoverStaleJobs(Number.MAX_SAFE_INTEGER),1); s.claim(j.jobId,"w2"); });
test("atomic activation and supersession preserve old ready version on failed replacement", () => { const s=new ScaleReadinessSimulator(); s.register("a","a"); const j=s.enqueue("a","a"); s.claim(j.jobId,"w"); s.complete(j.jobId); s.activate(j.jobId,"v1"); assert.equal(s.assets.get("a")?.state,"READY"); const replacement=s.enqueue("a","a","REINDEX"); s.claim(replacement.jobId,"w"); s.fail(replacement.jobId,"SCHEMA_INVALID"); assert.equal(s.assets.get("a")?.activeVersion,"v1"); });
test("stale dependency contract and immutable spec guard", () => { assert.deepEqual(staleStages({descriptionChanged:true}),["STALE"]); assert.deepEqual(staleStages({sourceChanged:true}),["STALE"]); assert.equal(SEMANTIC_SPEC_FINGERPRINT.length,64); assert.match(SCALE_PIPELINE_VERSION,/^kdi_semantic_indexing_pipeline_v1$/); });
test("dry-run simulations for 30, 100 and 881 never write production assets", () => { for (const n of [30,100,881]) { const r=dryRunScale(n); assert.equal(r.count,n); assert.equal(r.duplicatePrevented,true); assert.equal(r.retryIsolated,true); assert.equal(r.permanentFailureIsolated,true); assert.equal(r.resumed,true); assert.equal(r.accountingCorrect,true); assert.equal(r.productionWrites,0); } });
test("Phase 29 targeted readiness checks", () => { const checks = runScaleReadinessChecks(); assert.equal(checks.length, 40); assert.equal(checks.filter(x => x.passed).length, 40); });
