import assert from "node:assert/strict";
import test from "node:test";
import { KDISemanticDatabaseMaintainer } from "../db/semantic-database-maintainer";

const fp="6da50e2153f6fcb6c9ef27c308ad44d0d2024e702e3faad47586b0068ba64fd7", sfp="ba59fb115bd96b878971a74cd3ee1c6a4601930110b29b3505a586c69acf4751";
const pending=(id:string, visualEmbedding=false)=>({assetId:id,filename:`${id}.mp4`,contentHash:`hash-${id}`,status:"PENDING_ANALYSIS" as const,layers:0,searchReady:false,sourceResolvable:true,backlogPresent:true,visualEmbedding});
test("healthy pending state is not an anomaly",()=>{const m=new KDISemanticDatabaseMaintainer({assets:[pending("p1"),{assetId:"complete",status:"COMPLETE",contentHash:"h",layers:18,complete:true,searchReady:true,sourceResolvable:true}],expectedSpecFingerprint:fp,expectedSystemFingerprint:sfp,backlogIds:["p1"]});const h=m.getDatabaseHealth();assert.equal(h.pendingAnalysis,1);assert.equal(h.falseComplete,0);assert.equal(h.falseSearchReady,0);assert.equal(h.findings.length,0);});
test("detectors find synthetic integrity anomalies",()=>{const m=new KDISemanticDatabaseMaintainer({assets:[{assetId:"bad",status:"PENDING_ANALYSIS",contentHash:null,sourceResolvable:false,searchReady:true,staleEmbedding:true,staleSearchDocument:true,orphan:true,failedJob:true}],expectedSpecFingerprint:fp,expectedSystemFingerprint:sfp,backlogIds:[]});const h=m.getDatabaseHealth();assert.equal(h.falseSearchReady,1);assert.equal(h.missingHash,1);assert.equal(h.missingProvenance,1);assert.equal(h.staleEmbeddings,1);assert.equal(h.staleSearchDocuments,1);assert.ok(h.findings.length>=5);});
test("read-only mode rejects writes and unsafe controls are absent",()=>{const m=new KDISemanticDatabaseMaintainer({assets:[],expectedSpecFingerprint:fp,expectedSystemFingerprint:sfp,backlogIds:[]});assert.equal(m.requestMaintenanceAction({actionType:"QUEUE_REINDEX",assetId:"x",requestedBy:"test"}).status,"REJECTED_READ_ONLY");assert.equal(m.toolDefinitions().some((x)=>x.name.includes("sql")),false);assert.throws(()=>m.requestMaintenanceAction({actionType:"QUEUE_REINDEX",assetId:"x",requestedBy:""}));});
test("asset health preserves pending and visual-embedding distinction",()=>{const m=new KDISemanticDatabaseMaintainer({assets:[pending("p1",true)],expectedSpecFingerprint:fp,expectedSystemFingerprint:sfp,backlogIds:["p1"]});const h=m.getAssetSemanticHealth("p1");assert.equal(h.processingStatus,"PENDING_ANALYSIS");assert.equal(h.layers,0);assert.equal(h.complete,false);assert.equal(h.searchReady,false);assert.equal(h.visualEmbeddingPresent,true);});
