import test from"node:test";import assert from"node:assert/strict";import{readFileSync}from"node:fs";import{allowedInvitationRoles,canAccessAdministration,canInvite,canManage,canUpload}from"../app/lib/management-rbac";const read=(path:string)=>readFileSync(path,"utf8");
test("explicit invitation matrix prevents privilege escalation",()=>{assert.equal(canInvite("super_admin","admin"),true);assert.equal(canInvite("super_admin","user"),true);assert.equal(canInvite("admin","user"),true);assert.equal(canInvite("admin","admin"),false);assert.equal(canInvite("admin","super_admin"),false);assert.equal(canInvite("user","user"),false);assert.deepEqual(allowedInvitationRoles("admin"),["user"])});
test("management and upload matrix is explicit",()=>{assert.equal(canManage("super_admin","admin"),true);assert.equal(canManage("super_admin","user"),true);assert.equal(canManage("admin","user"),true);assert.equal(canManage("admin","admin"),false);assert.equal(canManage("admin","super_admin"),false);assert.equal(canManage("user","user"),false);assert.equal(canAccessAdministration("user"),false);assert.equal(canUpload("admin"),true);assert.equal(canUpload("user"),false)});
test("server routes reauthorize role and protected target",()=>{const invite=read("app/api/admin/users/route.ts"),status=read("app/api/admin/users/[id]/status/route.ts"),role=read("app/api/admin/users/[id]/role/route.ts");assert.match(invite,/requireAdmin/);assert.match(invite,/canInvite\(actor\.managementRole,role\)/);assert.match(status,/canManage\(actor\.managementRole,target\.management_role\)/);assert.match(role,/requireSuperAdmin/);assert.match(role,/target\.management_role==="super_admin"/)});
test("user-management API distinguishes unauthenticated and unauthorized callers",()=>{const route=read("app/api/admin/users/route.ts");assert.match(route,/AuthenticationRequired\?401/);assert.match(route,/AuthorizationDenied\?403/)});
test("database protects the Super Admin and browser roles remain untrusted",()=>{const sql=read("../supabase/migrations/202608170001_add_user_management_invitations.sql"),setup=read("app/auth/setup-password/setup-password-form.tsx");assert.match(sql,/create trigger protect_super_admin/);assert.match(sql,/protected super admin cannot be modified/);assert.match(sql,/app_users_single_super_admin/);assert.doesNotMatch(setup,/assigned_role|management_role|select.*role/i)});
test("invitation security includes duplicates rate limits and audit",()=>{const invite=read("app/api/admin/users/route.ts"),resend=read("app/api/admin/users/[id]/resend/route.ts"),sql=read("../supabase/migrations/202608170001_add_user_management_invitations.sql");assert.match(invite,/An invitation is already pending/);assert.match(invite,/An account already exists/);assert.match(resend,/60000/);assert.match(resend,/invitation_resent/);assert.match(sql,/user_management_audit/);assert.doesNotMatch(sql,/token_hash|invitation_token/)});
test("failed mail or profile creation compensates orphaned Auth identities",()=>{const invite=read("app/api/admin/users/route.ts");assert.match(invite,/email_provider_rejected/);assert.match(invite,/profile_creation_failed/);assert.match(invite,/auth\.admin\.deleteUser/);assert.match(invite,/status:"cancelled"/)});
test("password setup and recovery use provider sessions",()=>{const setup=read("app/auth/setup-password/setup-password-form.tsx"),forgot=read("app/forgot-password/forgot-password-form.tsx"),reset=read("app/reset-password/reset-password-form.tsx");assert.match(setup,/Passwords do not match/);assert.match(setup,/minLength=\{8\}/);assert.match(setup,/accept-invitation/);assert.match(forgot,/If an account exists/);assert.match(reset,/Password updated successfully/);assert.match(reset,/invalid or expired/)});
