import{getSourceFileDetails,getSourceFolderById}from"../../../../queries";
import{fileKind,formatBytes,maskFilename,safePath,shortId}from"../../../../lib";
import{AppShell,Badge,Breadcrumbs,PageError}from"../../../../shell";
export const dynamic="force-dynamic";
type Props={params:Promise<{sourceFolderId:string;sourceFileId:string}>};
const dt=(v:string|null)=>v?new Intl.DateTimeFormat("en-MY",{dateStyle:"long",timeStyle:"short",timeZone:"Asia/Singapore"}).format(new Date(v)):"—";
export default async function Page({params}:Props){
 const p=await params,[folder,file]=await Promise.all([getSourceFolderById(p.sourceFolderId),getSourceFileDetails(p.sourceFolderId,p.sourceFileId)]);
 if(folder.error||file.error)return <AppShell active="/source-folders"><PageError message="We could not load this file. Try refreshing the page."/></AppShell>;
 if(!folder.data||!file.data)return <AppShell active="/source-folders"><PageError message="File record not found."/></AppShell>;
 const f=file.data;
 const info:[string,string][]=[["Media type",fileKind(f.mime,f.extension)],["Extension",f.extension?.toUpperCase()||"—"],["MIME type",f.mime||"—"],["File size",formatBytes(f.size)],["Source folder",folder.data.name],["Relative path",safePath(f.relativePath)],["Created",dt(f.created)],["Modified",dt(f.modified)],["Source identity",shortId(f.googleFileId)]];
 const lifecycle:[string,string|number][]=[["Decision",f.decision],["Processing status",f.processing],["Skip reason",f.skipReason||"—"],["Canonical asset",f.assetId?shortId(f.assetId):"Not linked"],["Asset relationship",f.assetRelationship||"—"],["Exact duplicate sources",f.duplicateCount],["Migration status",f.migration],["Destination present",f.destinationId?"Yes":"No"],["Verification",f.verification],["Uploaded",dt(f.uploadedAt)],["Verified",dt(f.verifiedAt)],["Attempts",f.attempts],["Exception",f.error?"Restricted operational error":"None"]];
 return <AppShell active="/source-folders"><Breadcrumbs items={[{label:"Overview",href:"/"},{label:"Source Folders",href:"/source-folders"},{label:folder.data.name,href:`/source-folders/${p.sourceFolderId}`},{label:maskFilename(f.name)}]}/><div className="pageHead detailHead"><div><div className="eyebrow">{fileKind(f.mime,f.extension)} · {f.extension?.toUpperCase()||"FILE"}</div><h1>{maskFilename(f.name)}</h1><p>{safePath(f.relativePath)}</p></div><a className="backButton" href={`/source-folders/${p.sourceFolderId}`}>← Back to folder</a></div><div className="detailLayout"><section className="detailCard"><h2>File information</h2><dl>{info.map(([a,b])=><div key={a}><dt>{a}</dt><dd>{b}</dd></div>)}</dl></section><section className="detailCard"><h2>Processing & migration</h2><dl>{lifecycle.map(([a,b])=><div key={a}><dt>{a}</dt><dd>{String(a).includes("status")||a==="Decision"||a==="Verification"?<Badge tone={String(b).includes("VERIFIED")||b==="TAKE"?"green":"neutral"}>{b}</Badge>:b}</dd></div>)}</dl>{(f.sourceUrl||f.destinationUrl)&&<div className="externalLinks">{f.sourceUrl&&<a href={f.sourceUrl} target="_blank" rel="noopener noreferrer">Open original in Google Drive ↗</a>}{f.destinationUrl&&<a href={f.destinationUrl} target="_blank" rel="noopener noreferrer">Open migrated destination ↗</a>}</div>}</section></div></AppShell>
}
