import "server-only";
/* eslint-disable @typescript-eslint/no-explicit-any */
import { createHash, randomUUID } from "node:crypto";
import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import path from "node:path";

export const DECISIONS=["APPROVE_AS_IS","CORRECT","REJECT","CONFIRM_UNKNOWN","NOT_APPLICABLE"] as const;
export type Decision=typeof DECISIONS[number];
type Json=Record<string,any>;
const root=path.resolve(process.cwd(),"..","reports","semantic-search","phase10");
const reviewDir=path.join(root,"review"),goldDir=path.join(root,"gold");
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export function goldReviewEnabled(){return process.env.NODE_ENV!=="production"&&process.env.KDI_LOCAL_SEMANTIC_REVIEW==="true"}
async function readJson(file:string){return JSON.parse(await readFile(file,"utf8")) as Json}
async function atomicWrite(file:string,value:Json){await mkdir(path.dirname(file),{recursive:true});const temporary=`${file}.${process.pid}.${randomUUID()}.tmp`;await writeFile(temporary,`${JSON.stringify(value,null,2)}\n`,{flag:"wx"});await rename(temporary,file)}
function canonical(value:any):string{if(Array.isArray(value))return`[${value.map(canonical).join(",")}]`;if(value&&typeof value==="object")return`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${canonical(value[key])}`).join(",")}}`;return JSON.stringify(value)}
function hash(value:any){return createHash("sha256").update(canonical(value)).digest("hex")}
function packetPath(assetId:string){if(!uuid.test(assetId))throw new Error("Invalid asset ID");return path.join(reviewDir,`${assetId}_review_packet.json`)}
export async function listPackets(){const manifest=await readJson(path.resolve(process.cwd(),"..","config","semantic-search","kdi_semantic_pilot_v1.json"));return Promise.all(manifest.assets.map((asset:Json)=>readJson(packetPath(asset.asset_id))))}
export async function loadPacket(assetId:string){return readJson(packetPath(assetId))}
export async function saveLayerDecision(assetId:string,input:Json){const packet=await loadPacket(assetId),layer=packet.layer_decisions.find((value:Json)=>value.layer_number===input.layer_number);if(!layer||!DECISIONS.includes(input.human_decision))throw new Error("Invalid layer decision");if(["CORRECT","REJECT"].includes(input.human_decision)&&!String(input.reason||"").trim())throw new Error("Correction/rejection requires a reason");if(input.human_decision==="CORRECT"&&!String(input.human_value||"").trim())throw new Error("Correction requires a human value");const now=new Date().toISOString(),previous={...layer};layer.history=[...(layer.history||[]),{revision:layer.revision||0,recorded_at:now,value:previous}];Object.assign(layer,{human_decision:input.human_decision,human_semantic_state:input.human_semantic_state||null,human_value:input.human_value||null,reason:input.reason||null,evidence_viewed:Array.isArray(input.evidence_viewed)?input.evidence_viewed:[],reviewer_label:String(input.reviewer_label||packet.reviewer_label),review_started_at:layer.review_started_at||now,review_completed_at:now,revision:(layer.revision||0)+1});packet.review_status="IN_REVIEW";packet.revision=(packet.revision||0)+1;await atomicWrite(packetPath(assetId),packet);return packet}
export async function saveSectionDecision(assetId:string,input:Json){const allowed=new Set(["temporal_review","transcript_review","ocr_review","narrative_review"]);if(!allowed.has(input.section)||!DECISIONS.includes(input.human_decision))throw new Error("Invalid section decision");const packet=await loadPacket(assetId),section=packet[input.section],now=new Date().toISOString();section.history=[...(section.history||[]),{revision:packet.revision||0,recorded_at:now,value:{...section}}];section.human_decision=input.human_decision;section.reason=input.reason||null;section.reviewer_label=String(input.reviewer_label||packet.reviewer_label);section.reviewed_at=now;if(Array.isArray(input.overrides))section.overrides=input.overrides;packet.review_status="IN_REVIEW";packet.revision=(packet.revision||0)+1;await atomicWrite(packetPath(assetId),packet);return packet}
export async function resolveIssue(assetId:string,input:Json){const packet=await loadPacket(assetId),issue=packet.critical_issue_decisions.find((value:Json)=>value.issue_id===input.issue_id);if(!issue||!DECISIONS.includes(input.human_decision)||!String(input.reason||"").trim())throw new Error("Invalid issue resolution");const now=new Date().toISOString();issue.history=[...(issue.history||[]),{recorded_at:now,value:{...issue}}];Object.assign(issue,{human_decision:input.human_decision,human_value:input.human_value||null,reason:input.reason,reviewer_label:String(input.reviewer_label||packet.reviewer_label),reviewed_at:now});packet.review_status="IN_REVIEW";packet.revision=(packet.revision||0)+1;await atomicWrite(packetPath(assetId),packet);return packet}
function signoffErrors(packet:Json){const errors:string[]=[];if(packet.layer_decisions.length!==18)errors.push("Exactly 18 layer decisions required");for(const layer of packet.layer_decisions){if(!DECISIONS.includes(layer.human_decision))errors.push(`Layer ${layer.layer_number} is incomplete`);if(["CORRECT","REJECT"].includes(layer.human_decision)&&!layer.reason)errors.push(`Layer ${layer.layer_number} needs a reason`)}for(const issue of packet.critical_issue_decisions)if(["P0","P1"].includes(issue.priority)&&!issue.human_decision)errors.push(`Issue ${issue.issue_id} unresolved`);for(const section of ["ocr_review","narrative_review",...(packet.media_type==="video"?["temporal_review","transcript_review"]:[])])if(!packet[section].human_decision)errors.push(`${section} incomplete`);return errors}
export async function signOff(assetId:string,reviewerLabel:string){const packet=await loadPacket(assetId),errors=signoffErrors(packet);if(errors.length)return{ok:false,errors};const now=new Date().toISOString();packet.review_status="SIGNED_OFF";packet.explicit_signoff=true;packet.signed_off_at=now;packet.reviewer_label=reviewerLabel;packet.revision=(packet.revision||0)+1;await atomicWrite(packetPath(assetId),packet);const gold:Json={gold_standard_version:packet.gold_standard_version,semantic_spec_version:packet.semantic_spec_version,pilot_manifest_version:packet.pilot_manifest_version,asset_id:packet.asset_id,filename:packet.filename,media_type:packet.media_type,source_fingerprint:packet.source_fingerprint,review:{reviewer_label:reviewerLabel,status:"SIGNED_OFF",completed_at:now,revision:packet.revision},layers:packet.layer_decisions,scene_overrides:packet.temporal_review.scene_overrides||[],event_overrides:packet.temporal_review.event_overrides||[],transcript_overrides:packet.transcript_review.overrides||[],ocr_overrides:packet.ocr_review.overrides||[],narrative_overrides:packet.narrative_review.overrides||[],resolved_conflicts:packet.critical_issue_decisions,precedence:"HUMAN_GOLD_OVERRIDE",source_review_packet_fingerprint:hash(packet)};gold.gold_fingerprint=hash(gold);await atomicWrite(path.join(goldDir,`${assetId}_gold_standard.json`),gold);return{ok:true,gold_fingerprint:gold.gold_fingerprint}}
