"use client";
import Link from"next/link";
import{useEffect,useState,type ButtonHTMLAttributes,type ReactNode}from"react";
export type PreviewRole="STAFF"|"ADMIN";
export function PreviewShell({role,section,active,children}:{role:PreviewRole;section:"library"|"admin";active?:string;children:ReactNode}){const[open,setOpen]=useState(false);const admin=role==="ADMIN";return <div className="damShell"><div className="previewBanner" role="status"><strong>FRONTEND PREVIEW — MOCK DATA — NOT AUTHENTICATED</strong><span>{role} PREVIEW</span><nav aria-label="Preview role"><a href="/dev-preview?role=STAFF">STAFF</a><a href="/dev-preview?role=ADMIN">ADMIN</a></nav></div><aside className={open?"damSidebar open":"damSidebar"}><div className="damBrand"><span>KDI</span><div>Central Media Library<small>Digital asset management</small></div></div>{admin&&<div className="damPanelSwitch" aria-label="Application panels"><Link className={section==="library"?"active":""} href="/library" onClick={()=>setOpen(false)}>Library</Link><Link className={section==="admin"?"active":""} href="/admin" onClick={()=>setOpen(false)}>Admin</Link></div>}<nav className="damNav" aria-label={section==="admin"?"Admin navigation":"Library navigation"}>{section==="admin"?<><Nav href="/admin" label="Overview" current={active==="/admin"}/><Nav href="/admin/upload" label="Upload" current={active==="/admin/upload"}/><Nav href="/admin/sources" label="Sources" current={active==="/admin/sources"}/><Nav href="/admin/activity" label="Activity" current={active==="/admin/activity"}/></>:<Nav href="/library" label="Media Library" current/>}</nav><div className="damSidebarFoot">Frontend Preview User<br/><span>DEMO DATA only</span></div></aside><div className="damMain"><header className="damTopbar"><button className="mobileMenu" aria-label="Toggle navigation" aria-expanded={open} onClick={()=>setOpen(v=>!v)}>☰</button><strong>{section==="admin"?"Admin Panel":"Library Panel"}</strong><span className="damAvatar">FP</span></header><main>{children}</main></div>{open&&<button className="navScrim" aria-label="Close navigation" onClick={()=>setOpen(false)}/>}</div>}
function Nav({href,label,current=false}:{href:string;label:string;current?:boolean}){return <Link className={current?"active":""} href={href}>{label}</Link>}
export function Button({variant="primary",loading=false,children,...props}:ButtonHTMLAttributes<HTMLButtonElement>&{variant?:"primary"|"secondary"|"ghost"|"danger";loading?:boolean}){return <button {...props} disabled={props.disabled||loading} className={`damButton ${variant} ${props.className||""}`}>{loading&&<span className="buttonSpinner" aria-hidden/>}<span>{children}</span></button>}
export type ToastKind="success"|"info"|"warning"|"error";
export function useToast(){const[toast,setToast]=useState<{kind:ToastKind;message:string}|null>(null);useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(null),3200);return()=>clearTimeout(id)},[toast]);return{notify:(message:string,kind:ToastKind="info")=>setToast({message,kind}),toast:<div className="toastRegion" aria-live="polite">{toast&&<div className={`damToast ${toast.kind}`}>{toast.message}</div>}</div>}}
export function StatusBadge({children,tone="neutral"}:{children:ReactNode;tone?:"success"|"warning"|"danger"|"neutral"}){return <span className={`damStatus ${tone}`}>{children}</span>}
export function EmptyState({title,text,action}:{title:string;text:string;action?:ReactNode}){return <div className="damEmpty"><span aria-hidden>◇</span><h2>{title}</h2><p>{text}</p>{action}</div>}
