"use client";
import Link from"next/link";
import{useSyncExternalStore}from"react";
import{DEMO_SOURCES}from"./demo-data";
import{getDemoAssets,serverDemoAssets,subscribeDemoAssets}from"./preview-store";
import{PreviewShell,StatusBadge}from"./preview-ui";
export function PreviewOverview(){const assets=useSyncExternalStore(subscribeDemoAssets,getDemoAssets,serverDemoAssets);return <PreviewShell role="ADMIN" section="admin" active="/admin"><section className="damPage"><PageHead/><div className="overviewGrid"><Metric href="/library" label="Total assets" value={assets.length}/><Metric href="/library?type=image" label="Images" value={assets.filter(x=>x.kind==="image").length}/><Metric href="/library?type=video" label="Videos" value={assets.filter(x=>x.kind==="video").length}/><Metric href="/admin/sources" label="Source status" value="3 connected"/><Metric href="/admin/activity?tab=attention" label="Needs attention" value="1 item" tone/></div><div className="adminColumns"><section className="damPanel"><div className="panelHead"><h2>Recent uploads</h2><Link href="/library">View library</Link></div>{assets.slice(0,3).map(a=><Link className="compactRow" href={`/library?asset=${a.id}`} key={a.id}><span className={`miniKind ${a.kind}`}>{a.kind==="video"?"▶":"▧"}</span><div><strong>{a.name}</strong><small>{a.extension} · {new Date(a.date).toLocaleDateString("en-MY")}</small></div><span>›</span></Link>)}</section><section className="damPanel"><div className="panelHead"><h2>Source health</h2><Link href="/admin/sources">View sources</Link></div>{DEMO_SOURCES.map(source=><div className="compactRow" key={source}><span className="healthDot"/><div><strong>{source}</strong><small>Connected · synchronized today</small></div><StatusBadge tone="success">HEALTHY</StatusBadge></div>)}</section></div><section className="damPanel attentionPanel"><div><StatusBadge tone="warning">NEEDS ATTENTION</StatusBadge><h2>One demo item requires review</h2><p>Review the synthetic metadata exception in Activity.</p></div><Link className="damLinkButton" href="/admin/activity?tab=attention">Review exceptions</Link></section></section></PreviewShell>}
function PageHead(){return <header className="damPageHead"><div><span className="damEyebrow">ADMIN</span><h1>Overview</h1><p>A concise view of library health and recent activity.</p></div></header>}
function Metric({href,label,value,tone=false}:{href:string;label:string;value:string|number;tone?:boolean}){return <Link className={tone?"overviewMetric attention":"overviewMetric"} href={href}><small>{label}</small><strong>{value}</strong><span>Open →</span></Link>}
