import{createHash}from"node:crypto";import{validateExpectation,type BenchmarkExpectation}from"./query-parser-benchmark-evaluator";
export const QUERY_GOLD_VALIDATOR_VERSION="kdi_query_gold_validator_v1";
export const QUERY_GOLD_VALIDATOR_FINGERPRINT=createHash("sha256").update([QUERY_GOLD_VALIDATOR_VERSION,"explicit-contract-rules","no-production-parser-calls","media-count-numeric-temporal-polarity-modality-conflict-semantic-v1"].join("\n")).digest("hex");
export type GoldFinding={field:string;status:"SUPPORTED"|"AMBIGUOUS"|"UNSUPPORTED"|"CONTRADICTORY_GOLD";reason:string};
const video=/\b(videos?|clips?|footage)\b|\b(?:mp4|mov)\b/i,image=/\b(images?|photos?|photographs?|pictures?)\b|\b(?:jpe?g|png|webp)\b/i,generic=/\b(files?|items?|media|materials?|content|assets?)\b/i;
const numberWords="one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|eighteen|nineteen|twenty|\\d+";
const request=new RegExp(`(?:\\b(?:show|give(?: me)?|find|return|retrieve|get(?: me)?|list|display|pull(?: up)?|bring(?: up)?|fetch|provide|send|select)\\s+(?:the\\s+)?(?:best\\s+)?|\\b(?:top|best|exactly)\\s+)(?:${numberWords})\\s+(?:results?|matches?|items?|files?|media|videos?|clips?|footage|images?|photos?|photographs?|pictures?)\\b`,`gi`);
const neg=/\b(no|without|exclude|excluding|avoid|omit|remove|do not include|don't include|anything except|not containing|not showing|leave out|filter out|keep out)\b|\b(?:leave|filter|keep)\b[^,.!?;]{0,64}\bout\b/i;
const transcript=/\b(says?|mentions?|talking about|speaks? about|audio says)\b/i,ocr=/\b(visible text|text visible|written on screen|text on screen|screen says|screen reads|words visible|appears on screen)\b/i;
const aliases:Record<string,RegExp>={CLINICIAN:/\b(doctor|clinician|physician|medical practitioner)\b/i,PATIENT:/\bpatient\b/i,STAFF:/\bstaff\b/i,SUBJECT:/\bsubject\b/i,PRESENTER:/\bpresenter\b/i,FRONTAL_HAIRLINE:/\b(front(?:al)?\s+hair\s*line|hair\s*line|harline)\b/i,FRONTAL_SCALP:/\bfront(?:al)?\s+scalp\b|\bfrntal sclap\b/i,RECIPIENT_REGION:/\brecipient (?:region|area)\b/i,SCALP:/\bscalp\b/i,FACE:/\bface\b/i,CHEEK:/\bcheek\b/i,NECK:/\bneck\b/i,HAIR_TRANSPLANT:/\bhair transplant(?:ation)?\b/i,HAIR_TRANSPLANT_FUE:/\b(?:FUE|follicular unit extraction)\b/i,DRAWING_HAIRLINE:/\b(draw|drawing|design|designing|plan|planning|mark|marking)\b[^,.!?;]{0,30}\bhair\s*line\b|\bhair\s*line\s+(?:drawing|design|planning|marking)\b|\bharline desgin\b/i,IMPLANTING_GRAFTS:/\b(graft implantation|implanting grafts|implantation of grafts|graft implntation)\b/i,INJECTING:/\b(inject(?:ion|ions|ing)?|syringes?|injection needle)\b/i,CLEANSING:/\b(cleansing|cleaning|wiping)\b/i,LOOKING_AT_CAMERA:/\b(facing|looking at) (?:the )?camera\b/i,CONSULTATION:/\bconsultation\b/i,CLINIC:/\b(clinic|clinical room|clinic room)\b/i,TREATMENT_ROOM:/\b(treatment room|procedure room)\b/i,PRE_PROCEDURE:/\b(before (?:procedure|treatment)|pre[- ]?procedure)\b/i,DURING_PROCEDURE:/\b(during (?:procedure|treatment))\b/i,POST_PROCEDURE:/\b(after (?:procedure|treatment)|post[- ]?procedure)\b/i,FOLLOW_UP:/\b(follow up|aftercare)\b/i};
export function validateGold(query:string,expected:BenchmarkExpectation){const findings:GoldFinding[]=[],add=(field:string,status:GoldFinding["status"],reason:string)=>findings.push({field,status,reason});for(const e of validateExpectation(expected))add("shape","UNSUPPORTED",e);
 if(expected.media_type){const supported=expected.media_type==="VIDEO"?video.test(query):expected.media_type==="IMAGE"?image.test(query):generic.test(query)&&!video.test(query)&&!image.test(query);add("media_type",supported?"SUPPORTED":"AMBIGUOUS",supported?"Explicit canonical media cue":"Expected media family lacks an explicit supporting noun or extension")}
 const matches=[...query.matchAll(request)].map(m=>m[0]);if(expected.result_count){add("result_count",matches.length>=expected.result_count.values.length?"SUPPORTED":"UNSUPPORTED",matches.length?"Explicit request-quantity grammar":"No sufficient request-quantity occurrence")}
 for(const key of Object.keys(expected.numeric??{})){const rules:Record<string,RegExp>={age_exact:/\b(?:aged?\s+\d+|\d+[- ]year[- ]old)\b/i,age_min:/\b(?:aged?\s+)?\d+\s*(?:to|-|and)\s*\d+(?:\s+years? old)?\b|\b(?:at least|over|more than)\s+\d+\s+years? old\b/i,age_max:/\b(?:aged?\s+)?\d+\s*(?:to|-|and)\s*\d+(?:\s+years? old)?\b|\b(?:under|at most|less than)\s+\d+\s+years? old\b/i,graft_count_exact:/\b[\d,]+\s+grafts?\b/i,graft_count_min:/\b(?:at least|no less than|more than|over)\s+[\d,]+\s+grafts?\b|\b[\d,]+\s*(?:to|and|-)\s*[\d,]+\s+grafts?\b/i,graft_count_max:/\b(?:at most|no more than|no greater than|under)\s+[\d,]+(?:\s+grafts?)?\b|\b[\d,]+\s*(?:to|and|-)\s*[\d,]+\s+grafts?\b/i,treatment_session_count:new RegExp(`\\b(?:${numberWords})\\s+(?:treatment )?sessions?\\b|\\bsession\\s+(?:${numberWords})\\b`,`i`),session_ordinal:/\b(?:first|second|third|fourth|fifth|sixth|\d+(?:st|nd|rd|th))\s+(?:treatment )?session\b/i,currency_amount:/\bRM\s*[\d,]+/i};const ok=rules[key]?.test(query)??false;add(`numeric.${key}`,ok?"SUPPORTED":"UNSUPPORTED",ok?"Typed surrounding numeric grammar":"Numeric slot unsupported by surrounding language")}
 if(expected.temporal?.year)add("temporal.year",/\b(?:from|in|recorded in|taken in|captured in|after|before)\s+(?:19|20)\d{2}\b/i.test(query)?"SUPPORTED":"UNSUPPORTED","Temporal year grammar");if(expected.temporal?.timestamp)add("temporal.timestamp",/\b\d{1,2}:\d{2}\b|\b(?:near|around|at)(?: the)?(?: second| timestamp)?\s+\d+(?:-second| seconds?| second mark)?\b/i.test(query)?"SUPPORTED":"UNSUPPORTED","Timestamp grammar");if(expected.temporal?.duration)add("temporal.duration",/\b(?:under|less than|shorter than|no longer than|maximum|at most|over|longer than|more than|minimum|at least|between)\b[^,.!?;]{0,30}\bseconds?\b/i.test(query)?"SUPPORTED":"UNSUPPORTED","Duration-bound grammar");
 for(const code of expected.positive??[]){const rule=aliases[code],matches=rule?[...query.matchAll(new RegExp(rule.source,rule.flags.includes("g")?rule.flags:`${rule.flags}g`))]:[],first=matches[0],directlyNegated=!!first&&/\b(?:no|without|exclude|avoid|omit|remove|not showing|not containing)\s+(?:every\s+|all\s+|any\s+)?$/i.test(query.slice(Math.max(0,first.index!-48),first.index));const supported=matches.length>0&&(!directlyNegated||matches.length>1);add(`positive.${code}`,supported?"SUPPORTED":directlyNegated?"CONTRADICTORY_GOLD":"UNSUPPORTED",supported?"Approved ontology alias/composition":directlyNegated?"Only occurrence is explicitly negated":"No supporting ontology alias")};for(const code of expected.negative??[]){const matched=aliases[code]?.test(query)??false;add(`negative.${code}`,matched&&neg.test(query)?"SUPPORTED":"UNSUPPORTED",matched&&neg.test(query)?"Explicit exclusion plus ontology phrase":"Negative concept lacks exclusion or ontology support")}
 for(const m of expected.modalities??[])add(`modality.${m}`,m==="OCR"&&ocr.test(query)||m==="TRANSCRIPT"&&transcript.test(query)?"SUPPORTED":"CONTRADICTORY_GOLD",m==="OCR"?"Visible/written cue required":"Spoken cue required");if(expected.conflict){const ok=expected.conflict==="EXTENSION_MEDIA_CONFLICT"?video.test(query)&&/\b(jpe?g|png|webp)\b/i.test(query)||image.test(query)&&/\b(mp4|mov)\b/i.test(query):expected.conflict==="MEDIA_TYPE_CONFLICT"?video.test(query)&&image.test(query):expected.conflict==="CONCEPT_POLARITY_CONFLICT"?neg.test(query)&&/\b(but|although|however|yet|though)\b/i.test(query):true;add(`conflict.${expected.conflict}`,ok?"SUPPORTED":"UNSUPPORTED","Explicit contradiction grammar")};if(expected.unresolved)add("unresolved",/\b(delta|indigo|violet|quartz|amber|zeta|spectral|resonance|waveform|harmonic|lattice|prism|unknown)\b/i.test(query)?"SUPPORTED":"AMBIGUOUS","Explicit unsupported phrase marker");
 const invalid=findings.filter(x=>x.status!=="SUPPORTED");return{validator_version:QUERY_GOLD_VALIDATOR_VERSION,query,findings,valid:invalid.length===0,ambiguous:invalid.filter(x=>x.status==="AMBIGUOUS").length,unsupported:invalid.filter(x=>x.status==="UNSUPPORTED").length,contradictory:invalid.filter(x=>x.status==="CONTRADICTORY_GOLD").length}}
