import{createServerClient}from"@supabase/ssr";import{NextRequest,NextResponse}from"next/server";import{profileForFirebaseUid}from"../auth-profile";import{getFirebaseAdminAuth}from"../firebase/admin";import{FIREBASE_SESSION_COOKIE}from"../firebase/session";import{previewRoleForRequest}from"../dev-preview";import{getSupabasePublicConfig,safeReturnPath,secureCookieOptions}from"./config";import{requestHasAdminSession}from"../admin-auth/request";
const adminRoots=["/source-folders","/migration-results","/exceptions","/duplicates","/system-status"];
function protectedPath(p:string){return p.startsWith("/library")||p.startsWith("/admin")||p.startsWith("/api/media")||adminRoots.some(x=>p===x||p.startsWith(`${x}/`))}function adminPath(p:string){return p.startsWith("/admin")||adminRoots.some(x=>p===x||p.startsWith(`${x}/`))}function noStore(r:NextResponse){r.headers.set("Cache-Control","private, no-store");return r}
export async function updateSession(request:NextRequest){let response=NextResponse.next({request});const path=request.nextUrl.pathname,isProtected=protectedPath(path),cacheableThumbnail=path.endsWith("/thumbnail")&&(path.startsWith("/api/media/")||path.startsWith("/api/dev/library/media/")),cookie=request.cookies.get(FIREBASE_SESSION_COOKIE)?.value;let identity=null,profile:null|{is_active:boolean;role:string;management_role?:string}=null;
  const customAdmin=await requestHasAdminSession(request);if(customAdmin){if(path==="/login")return noStore(NextResponse.redirect(new URL("/library",request.url)));return cacheableThumbnail?response:noStore(response)}
  const preview=previewRoleForRequest(request);if(preview){if(path.startsWith("/admin")&&preview!=="ADMIN")return noStore(NextResponse.redirect(new URL("/library",request.url)));return noStore(response)}
  if(cookie){try{identity=await getFirebaseAdminAuth().verifySessionCookie(cookie,true)}catch{identity=null}}
  if(identity?.uid)profile=await profileForFirebaseUid(identity.uid);
  if(!identity){const{url,key}=getSupabasePublicConfig(),supabase=createServerClient(url,key,{cookieOptions:secureCookieOptions,cookies:{getAll:()=>request.cookies.getAll(),setAll:items=>{for(const{name,value}of items)request.cookies.set(name,value);response=NextResponse.next({request});for(const{name,value,options}of items)response.cookies.set(name,value,{...options,...secureCookieOptions})}}}),{data:{user}}=await supabase.auth.getUser();if(user){const{data}=await supabase.from("app_users").select("role,management_role,is_active").eq("user_id",user.id).maybeSingle();profile=data}}
  if(isProtected&&!identity&&!profile){if(path.startsWith("/api/"))return noStore(NextResponse.json({error:"Authentication required"},{status:401}));const login=request.nextUrl.clone();login.pathname="/login";login.search=`?next=${encodeURIComponent(safeReturnPath(`${path}${request.nextUrl.search}`,"/library"))}`;return noStore(NextResponse.redirect(login))}
  if(isProtected&&(!profile?.is_active||(identity&&identity.role!=="authenticated"))){if(path.startsWith("/api/"))return noStore(NextResponse.json({error:"Access denied"},{status:403}));return noStore(NextResponse.redirect(new URL("/access-denied",request.url)))}
  const managementAdmin=profile?.management_role==="admin"||profile?.management_role==="super_admin";if(profile&&adminPath(path)&&!managementAdmin)return noStore(NextResponse.redirect(new URL("/library",request.url)));if(profile&&path==="/login")return noStore(NextResponse.redirect(new URL(managementAdmin?"/admin":"/library",request.url)));return cacheableThumbnail?response:noStore(response)}
